const crypto=require('crypto');
const {validateKnowledgeSnapshot}=require('../dimension/validateKnowledgeSnapshot');
const {validateDimensionKnowledgeState}=require('../dimension/validateDimensionKnowledgeState');
const {validateDerivedDimensionKnowledgeState}=require('../dimension/validateDerivedDimensionKnowledgeState');
const {validatePersonKnowledgeMatrix}=require('./validatePersonKnowledgeMatrix');
function obj(v){return v!==null&&typeof v==='object'&&!Array.isArray(v)}
function clone(v){if(Array.isArray(v))return v.map(clone);if(obj(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clone(x)]));return v}
function str(v){return typeof v==='string'&&v.trim()?v.trim():null}
function stable(v){if(Array.isArray(v))return `[${v.map(stable).join(',')}]`;if(obj(v))return `{${Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')}}`;return JSON.stringify(v)}
function hash(v){return crypto.createHash('sha256').update(v).digest('hex')}
function fail(code,message,details){const e=new Error(message);e.code=code;if(details!==undefined)e.details=details;throw e}
function elementaryId(state){return `elementaryDimensionKnowledgeState_${hash(stable(state)).slice(0,32)}`}
function uniqueSorted(values){return [...new Set(values.filter(Boolean))].sort()}
function buildPersonKnowledgeMatrix(input={},options={}){
 const subjectRef=obj(input.subjectRef)?{type:str(input.subjectRef.type),id:str(input.subjectRef.id)}:null;
 if(!subjectRef||subjectRef.type!=='person'||!subjectRef.id)fail('INVALID_SUBJECT_REF','subjectRef must be { type: "person", id }.');
 const snapshot=input.knowledgeSnapshot;const sv=validateKnowledgeSnapshot(snapshot);if(!sv.valid)fail('INVALID_KNOWLEDGE_SNAPSHOT',sv.errors.join(' | '),sv);
 const derived=Array.isArray(input.derivedStates)?input.derivedStates:[];const seenDerived=new Set();derived.forEach((s,i)=>{const v=validateDerivedDimensionKnowledgeState(s);if(!v.valid)fail('INVALID_DERIVED_DIMENSION_STATE',`derivedStates[${i}] is invalid: ${v.errors.join(' | ')}`,v);if(seenDerived.has(s.id))fail('DUPLICATE_DERIVED_DIMENSION_STATE',`Duplicate derived state id: ${s.id}.`);seenDerived.add(s.id);if(s.snapshotRef!==`knowledgeSnapshot:${snapshot.id}`)fail('INCONSISTENT_DERIVED_STATE_SNAPSHOT',`Derived state ${s.id} belongs to a different snapshot.`)});
 const elementary=snapshot.dimensionStates.map((s,i)=>{const v=validateDimensionKnowledgeState(s);if(!v.valid)fail('INVALID_ELEMENTARY_DIMENSION_STATE',`dimensionStates[${i}] is invalid: ${v.errors.join(' | ')}`,v);return {stateId:elementaryId(s),state:clone(s)}}).sort((a,b)=>a.state.dimensionId.localeCompare(b.state.dimensionId));
 const derivedLayer=derived.map(s=>clone(s)).sort((a,b)=>a.dimensionId.localeCompare(b.dimensionId)||a.recipeRef.localeCompare(b.recipeRef)||a.id.localeCompare(b.id));
 const logicalKeys=new Set();for(const s of derivedLayer){const key=[s.dimensionId,s.capabilityId,s.recipeRef,s.recipeVersion,s.snapshotRef,...s.sourceResultRefs].join('|');if(logicalKeys.has(key))fail('DUPLICATE_DERIVED_DIMENSION_STATE',`Ambiguous derived state lineage for ${s.dimensionId}.`);logicalKeys.add(key)}
 const dimensions=uniqueSorted([...elementary.map(x=>x.state.dimensionId),...derivedLayer.map(x=>x.dimensionId)]);const byDimensionId={};for(const d of dimensions)byDimensionId[d]={elementary:elementary.filter(x=>x.state.dimensionId===d).map(x=>x.stateId),derived:derivedLayer.filter(x=>x.dimensionId===d).map(x=>x.id)};
 const byKnowledgeLayer={elementary:elementary.map(x=>x.stateId),derived:derivedLayer.map(x=>x.id)};
 const byCapabilityId={};for(const s of derivedLayer){(byCapabilityId[s.capabilityId]??=[]).push(s.id)}Object.keys(byCapabilityId).sort().forEach(k=>byCapabilityId[k]=uniqueSorted(byCapabilityId[k]));
 const byRecipeId={};for(const s of derivedLayer){(byRecipeId[`${s.recipeRef}@${s.recipeVersion}`]??=[]).push(s.id)}Object.keys(byRecipeId).sort().forEach(k=>byRecipeId[k]=uniqueSorted(byRecipeId[k]));
 const elementaryDims=new Set(elementary.map(x=>x.state.dimensionId)),derivedDims=new Set(derivedLayer.map(x=>x.dimensionId));const shared=[...elementaryDims].filter(x=>derivedDims.has(x));
 const dependencyRefs=uniqueSorted([`subject:${subjectRef.id}`,`knowledgeSnapshot:${snapshot.id}`,snapshot.ledgerRef,...elementary.map(x=>`elementaryDimensionKnowledgeState:${x.stateId}`),...derivedLayer.map(s=>`derivedDimensionKnowledgeState:${s.id}`),...derivedLayer.flatMap(s=>[s.recipeRef,...s.executionRefs])]);
 const recipes=uniqueSorted(derivedLayer.map(s=>`${s.capabilityId}|${s.recipeRef}|${s.recipeVersion}`)).map(x=>{const [capabilityId,recipeRef,recipeVersion]=x.split('|');return{capabilityId,recipeRef,recipeVersion}});
 const builtAt=str(options.now)||str(input.builtAt)||snapshot.metadata.createdAt;
 const logical={subjectRef,sourceSnapshotRef:`knowledgeSnapshot:${snapshot.id}`,elementaryStateIds:elementary.map(x=>x.stateId),derivedStateIds:derivedLayer.map(x=>x.id),contractVersion:'1.0',compositionStrategyVersion:'1.0'};
 const matrix={id:`personKnowledgeMatrix_${hash(stable(logical)).slice(0,32)}`,subjectRef, matrixVersion:'1.0',sourceSnapshotRef:`knowledgeSnapshot:${snapshot.id}`,knowledgeLayers:{elementary,derived:derivedLayer},indexes:{byDimensionId,byKnowledgeLayer,byCapabilityId,byRecipeId},summary:{elementaryStateCount:elementary.length,derivedStateCount:derivedLayer.length,totalStateCount:elementary.length+derivedLayer.length,dimensionCount:dimensions.length,elementaryDimensionCount:elementaryDims.size,derivedDimensionCount:derivedDims.size,sharedDimensionCount:shared.length,capabilityCount:Object.keys(byCapabilityId).length,recipeCount:Object.keys(byRecipeId).length,dependencyCount:dependencyRefs.length,status:elementary.length&&derivedLayer.length?'composed':elementary.length?'elementary_only':derivedLayer.length?'derived_only':'empty'},lineage:{ledgerRef:snapshot.ledgerRef,snapshotRef:`knowledgeSnapshot:${snapshot.id}`,elementaryStateRefs:uniqueSorted(elementary.map(x=>`elementaryDimensionKnowledgeState:${x.stateId}`)),derivedStateRefs:uniqueSorted(derivedLayer.map(s=>`derivedDimensionKnowledgeState:${s.id}`)),executionRefs:uniqueSorted(derivedLayer.flatMap(s=>s.executionRefs))},versionContext:{matrixContractVersion:'1.0',compositionStrategyVersion:'1.0',snapshotVersion:snapshot.metadata.version,elementaryStateContractVersions:uniqueSorted(elementary.map(x=>x.state.metadata.version)),derivedStateContractVersions:uniqueSorted(derivedLayer.map(s=>s.metadata.contractVersion)),capabilityRecipes:recipes},provenance:{type:'person_knowledge_matrix_composition',producerVersion:'1.0',reconstructable:true,authoritative:false},dependencyRefs,builtAt,metadata:{contractVersion:'1.0',...(obj(input.metadata)?clone(input.metadata):{})},extensions:obj(input.extensions)?clone(input.extensions):{}};
 const validation=validatePersonKnowledgeMatrix(matrix);if(!validation.valid)fail('INVALID_GENERATED_PERSON_KNOWLEDGE_MATRIX',validation.errors.join(' | '),validation);return matrix;
}
module.exports={buildPersonKnowledgeMatrix};
