module.exports = {
  extractEvidenceFromStructuredInputProviderResult:
    require('./extractEvidenceFromStructuredInputProviderResult').extractEvidenceFromStructuredInputProviderResult,
  validateStructuredInputProviderResultEvidencePayload:
    require('./validateStructuredInputProviderResultEvidencePayload').validateStructuredInputProviderResultEvidencePayload,
  validateStructuredInputProviderResultEvidenceContext:
    require('./validateStructuredInputProviderResultEvidenceContext').validateStructuredInputProviderResultEvidenceContext,
  calculateStructuredInputEvidenceIdentity:
    require('./structuredInputProviderResultEvidenceIdentity').calculateStructuredInputEvidenceIdentity,
  healthStructuredInputProviderResultEvidenceExtractor:
    require('./healthStructuredInputProviderResultEvidenceExtractor').healthStructuredInputProviderResultEvidenceExtractor,
  buildKnowledgeAcquisitionProviderResult:
    require('./buildKnowledgeAcquisitionProviderResult').buildKnowledgeAcquisitionProviderResult,
  validateKnowledgeAcquisitionProviderResult:
    require('./validateKnowledgeAcquisitionProviderResult').validateKnowledgeAcquisitionProviderResult,
  validateKnowledgeAcquisitionProviderResultContext:
    require('./validateKnowledgeAcquisitionProviderResultContext').validateKnowledgeAcquisitionProviderResultContext,
  healthKnowledgeAcquisitionProviderResult:
    require('./healthKnowledgeAcquisitionProviderResult').healthKnowledgeAcquisitionProviderResult,
  createStructuredInputKnowledgeAcquisitionInvocationAdapter:
    require('./createStructuredInputKnowledgeAcquisitionInvocationAdapter')
      .createStructuredInputKnowledgeAcquisitionInvocationAdapter,
  validateStructuredInputKnowledgeAcquisitionProvider:
    require('./validateStructuredInputKnowledgeAcquisitionProvider')
      .validateStructuredInputKnowledgeAcquisitionProvider,
  healthStructuredInputKnowledgeAcquisitionInvocationAdapter:
    require('./healthStructuredInputKnowledgeAcquisitionInvocationAdapter')
      .healthStructuredInputKnowledgeAcquisitionInvocationAdapter
};
