import knowledgeInfrastructureApi from './index.js';

export const buildKnowledgeAcquisitionProviderResult = knowledgeInfrastructureApi.buildKnowledgeAcquisitionProviderResult;
export const validateKnowledgeAcquisitionProviderResult = knowledgeInfrastructureApi.validateKnowledgeAcquisitionProviderResult;
export const validateKnowledgeAcquisitionProviderResultContext = knowledgeInfrastructureApi.validateKnowledgeAcquisitionProviderResultContext;
export const healthKnowledgeAcquisitionProviderResult = knowledgeInfrastructureApi.healthKnowledgeAcquisitionProviderResult;
export const createStructuredInputKnowledgeAcquisitionInvocationAdapter =
  knowledgeInfrastructureApi.createStructuredInputKnowledgeAcquisitionInvocationAdapter;
export const validateStructuredInputKnowledgeAcquisitionProvider =
  knowledgeInfrastructureApi.validateStructuredInputKnowledgeAcquisitionProvider;
export const healthStructuredInputKnowledgeAcquisitionInvocationAdapter =
  knowledgeInfrastructureApi.healthStructuredInputKnowledgeAcquisitionInvocationAdapter;
