import knowledgeInfrastructureApi from './index.js';

export const extractEvidenceFromStructuredInputProviderResult = knowledgeInfrastructureApi.extractEvidenceFromStructuredInputProviderResult;
export const validateStructuredInputProviderResultEvidencePayload = knowledgeInfrastructureApi.validateStructuredInputProviderResultEvidencePayload;
export const validateStructuredInputProviderResultEvidenceContext = knowledgeInfrastructureApi.validateStructuredInputProviderResultEvidenceContext;
export const calculateStructuredInputEvidenceIdentity = knowledgeInfrastructureApi.calculateStructuredInputEvidenceIdentity;
export const healthStructuredInputProviderResultEvidenceExtractor = knowledgeInfrastructureApi.healthStructuredInputProviderResultEvidenceExtractor;

export const buildKnowledgeAcquisitionProviderResult = knowledgeInfrastructureApi.buildKnowledgeAcquisitionProviderResult;
export const validateKnowledgeAcquisitionProviderResult = knowledgeInfrastructureApi.validateKnowledgeAcquisitionProviderResult;
export const validateKnowledgeAcquisitionProviderResultContext = knowledgeInfrastructureApi.validateKnowledgeAcquisitionProviderResultContext;
export const healthKnowledgeAcquisitionProviderResult = knowledgeInfrastructureApi.healthKnowledgeAcquisitionProviderResult;
export const createStructuredInputKnowledgeAcquisitionInvocationAdapter =
  knowledgeInfrastructureApi.createStructuredInputKnowledgeAcquisitionInvocationAdapter;
export const validateStructuredInputKnowledgeAcquisitionProvider =
  knowledgeInfrastructureApi.validateStructuredInputKnowledgeAcquisitionProvider;
export const healthStructuredInputKnowledgeAcquisitionInvocationAdapter =
  knowledgeInfrastructureApi.healthStructuredInputKnowledgeAcquisitionInvocationAdapter;
