const {isObject,cleanString,unknownKeys,validDate,validateRef,hasRawPayload}=require('./shared');
const TOP=["id","type","subjectRef","sourceRefs","scope","targetIds","method","status","context","createdAt","completedAt","metadata","extensions"];
function validateMeasurement(m={}){const errors=[],warnings=[];if(!isObject(m))return{valid:false,errors:["Measurement must be an object."],warnings};unknownKeys(m,TOP,"measurement",errors);
 if(!cleanString(m.id))errors.push("id is required.");if(!cleanString(m.type))errors.push("type is required.");
 if(m.subjectRef!==null)validateRef(m.subjectRef,"subjectRef",errors);if(!Array.isArray(m.sourceRefs)||m.sourceRefs.length<1)errors.push("sourceRefs must contain at least one reference.");else{const seen=new Set();m.sourceRefs.forEach((r,i)=>{validateRef(r,`sourceRefs[${i}]`,errors);const k=isObject(r)?`${r.type}:${r.id}`:"";if(seen.has(k))errors.push("sourceRefs must not contain duplicates.");seen.add(k)})}
 if(!isObject(m.scope)||!cleanString(m.scope.type))errors.push("scope.type is required.");if(hasRawPayload(m.scope))errors.push("scope must not contain raw source content.");
 if(!Array.isArray(m.targetIds)||m.targetIds.some(x=>!cleanString(x)))errors.push("targetIds must be an array of non-empty strings.");
 if(!isObject(m.method)||!cleanString(m.method.id)||!cleanString(m.method.version))errors.push("method.id and method.version are required.");
 if(!["planned","in_progress","completed","cancelled"].includes(m.status))errors.push("status is invalid.");if(!validDate(m.createdAt))errors.push("createdAt must be a valid timestamp.");if(m.completedAt!==null&&!validDate(m.completedAt))errors.push("completedAt must be null or a valid timestamp.");if(m.status==="completed"&&!m.completedAt)errors.push("completedAt is required when status is completed.");if(m.status!=="completed"&&m.completedAt)errors.push("completedAt is only allowed when status is completed.");if(m.completedAt&&validDate(m.createdAt)&&Date.parse(m.completedAt)<Date.parse(m.createdAt))errors.push("completedAt cannot precede createdAt.");
 for(const [n,v] of [["context",m.context],["metadata",m.metadata],["extensions",m.extensions]])if(!isObject(v))errors.push(`${n} must be an object.`);if(isObject(m.context)&&hasRawPayload(m.context))errors.push("context must not contain raw source content.");if(!isObject(m.metadata)||m.metadata.version!=="1.0"||!validDate(m.metadata.createdAt))errors.push("metadata.version 1.0 and valid metadata.createdAt are required.");return{valid:errors.length===0,errors,warnings}}
module.exports={validateMeasurement};
