import { createHash } from 'node:crypto';
import { performance } from 'node:perf_hooks';
import { runGroqOpportunityRequirementSupportProposalModel } from '../../infrastructure/groq/runGroqOpportunityRequirementSupportProposalModel.js';
import { buildOpportunityRequirementSupportContributorInventory,buildOpportunityRequirementSupportProjection } from './requirementSupportAuthority.js';
const arr=v=>Array.isArray(v)?v:[];const text=v=>typeof v==='string'?v.trim():'';const freeze=v=>Object.freeze(v);const cache=new Map();
function allRequirements(u){return [['requirements','required'],['preferredRequirements','preferred'],['responsibilities','responsibility'],['constraints','constraint'],['unclassified','contextual_unclassified']].flatMap(([k,c])=>arr(u?.[k]).map(r=>({opportunityRequirementRef:r.id,requirementClass:c,statement:r.statement})));}
export function buildOpportunityRequirementSupportProposalInput({professionalIdentity,opportunityUnderstanding}={}){const contributors=buildOpportunityRequirementSupportContributorInventory({professionalIdentity}).map(c=>({contributorType:c.contributorType,contributorRef:c.contributorRef,semanticCeiling:c.semanticCeiling,professionalBasisRefs:c.professionalBasisRefs,materialRefs:c.materialRefs,sourceRefs:c.sourceRefs,value:{professionalMeaning:text(c.value?.professionalMeaning),description:text(c.value?.description),relationshipWording:text(c.value?.relationshipWording),structureWording:text(c.value?.structureWording),kind:text(c.value?.kind),claimShape:c.value?.claimShape||null,authorisedSemanticPayload:c.value?.authorisedSemanticPayload||null}}));return freeze({task:'opportunity_requirement_support_relevance_proposal',opportunityRef:opportunityUnderstanding?.opportunityRef,contributors,requirements:allRequirements(opportunityUnderstanding)});}
const fp=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
function providerFailureDiagnostic(error,{started,modelCallCount=1}={}){
 const p=error?.providerDiagnostic||{},msg=text(error?.message),parse=/MALFORMED_STRUCTURED_OUTPUT|INVALID_STRUCTURED_OUTPUT/i.test(msg);
 const structured=/structured|schema/i.test(msg)||p?.structuredOutput===true;
 return freeze({boundary:'pd085_live_opportunity_requirement_support',stage:parse?'proposal_parse_failed':structured?'structured_output_failed':'provider_model_call_failed',task:'opportunityRequirementSupportProposal',failureKind:text(p?.failureKind)||(parse?'proposal_parse_failure':structured?'structured_output_failure':'provider_failure'),errorClass:'provider',providerFallbackUsed:true,modelCallCount,httpStatus:Number.isFinite(Number(error?.status))?Number(error.status):(Number.isFinite(Number(p?.status))?Number(p.status):null),providerCode:p?.providerCode||null,providerType:p?.providerType||null,providerMessage:p?.providerMessage||null,model:p?.model||error?.model||null,outputMode:p?.outputMode||null,attemptCount:Number.isFinite(Number(p?.httpAttemptsUsed))?Number(p.httpAttemptsUsed):null,elapsedMs:Math.round(performance.now()-started),rateLimitClassification:p?.failureKind||null,retryAfter:p?.rateLimitMetadata?.retryAfter||p?.retryAfter||null,rateLimitMetadata:p?.rateLimitMetadata||null});
}
export async function proposeLiveOpportunityRequirementSupport({professionalIdentity,opportunityUnderstanding,modelRunner=runGroqOpportunityRequirementSupportProposalModel,diagnosticSink,executionDiagnosticSink}={}){
 const input=buildOpportunityRequirementSupportProposalInput({professionalIdentity,opportunityUnderstanding}),key=fp(input);
 if(cache.has(key)){const cached=cache.get(key);diagnosticSink?.(freeze({...cached.diagnostic,stage:'cache_reused',task:'opportunityRequirementSupportProposal',modelCallCount:0,providerFallbackUsed:Boolean(cached.degraded)}));return cached;}
 if(!input.contributors.length||!input.requirements.length){const diagnostic=freeze({boundary:'pd085_live_opportunity_requirement_support',stage:'proposal_not_required',task:'opportunityRequirementSupportProposal',failureKind:null,errorClass:null,providerAttempted:false,providerFallbackUsed:false,modelCallCount:0,proposalCount:0});diagnosticSink?.(diagnostic);return freeze({proposals:[],diagnostic});}
 const systemPrompt=`You propose bounded support relations for an IMAGO concrete job opportunity. The concrete JD is primary authority. Use only supplied IDs. The model is proposal-only: deterministic application validation decides acceptance. Never infer fit, readiness, employability, capability strength, personality, motivation or Candidate ranking. Never strengthen participated->contributed->coordinated->owned->decided, shared->exclusive responsibility, or contribution->sole causality. Do not use lexical similarity alone. Empty output is valid. Do not infer broader budget/resource responsibility or direct production planning/scheduling when not explicitly established.`;
 const userPrompt=`Propose only direct, bounded requirement-to-contributor support relations. relationBasis must explain the semantic connection without evaluating the Candidate.\n${JSON.stringify(input)}`;
 const started=performance.now();diagnosticSink?.(freeze({boundary:'pd085_live_opportunity_requirement_support',stage:'proposal_request_started',task:'opportunityRequirementSupportProposal',failureKind:null,errorClass:null,providerAttempted:true,providerFallbackUsed:false,modelCallCount:0,proposalCount:0}));
 let result;
 try{result=await modelRunner({systemPrompt,userPrompt,executionDiagnosticSink});}
 catch(error){const diagnostic=providerFailureDiagnostic(error,{started});const out=freeze({proposals:[],degraded:true,diagnostic});diagnosticSink?.(diagnostic);return out;}
 const refs=new Map(input.contributors.map(c=>[c.contributorRef,c]));
 const proposals=arr(result?.structured?.proposals).map((p,i)=>({contributorType:text(p.contributorType)||refs.get(text(p.contributorRef))?.contributorType||'unknown',contributorRef:text(p.contributorRef),opportunityRef:input.opportunityRef,opportunityRequirementRef:text(p.opportunityRequirementRef),relationBasis:text(p.relationBasis),provenance:{providerRef:`groq:${text(result.model)||'configured_model'}`,proposalRef:`pd085:${key.slice(0,12)}:${i+1}`}}));
 let projection;
 try{projection=buildOpportunityRequirementSupportProjection({professionalIdentity,opportunityUnderstanding,proposals});}
 catch(error){diagnosticSink?.(freeze({boundary:'pd085_live_opportunity_requirement_support',stage:'deterministic_validation_failed',task:'opportunityRequirementSupportProposal',failureKind:'deterministic_validation_failure',errorClass:'application',providerFallbackUsed:false,modelCallCount:1,attemptCount:Number.isFinite(Number(result?.execution?.attemptCount))?Number(result.execution.attemptCount):null,elapsedMs:Math.round(performance.now()-started),model:result?.model||null,outputMode:result?.outputMode||null}));throw error;}
 const diagnostic=freeze({boundary:'pd085_live_opportunity_requirement_support',stage:'proposal_completed',task:'opportunityRequirementSupportProposal',failureKind:null,errorClass:null,providerAttempted:true,providerFallbackUsed:false,modelCallCount:1,attemptCount:Number.isFinite(Number(result?.execution?.attemptCount))?Number(result.execution.attemptCount):null,elapsedMs:Math.round(performance.now()-started),model:result?.model||null,outputMode:result?.outputMode||null,proposalCount:proposals.length,acceptedCount:projection.relations.length,rejectedCount:projection.rejections.length,rateLimitMetadata:result?.rateLimitMetadata||null});
 const out=freeze({proposals,projection,diagnostic});cache.set(key,out);diagnosticSink?.(diagnostic);return out;
}
export function clearOpportunityRequirementSupportProposalCache(){cache.clear();}
