function pdfEscapeLatin1(s){return String(s??"").replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)");}
function latin1Safe(s){const map=new Map([["€",0x80],["‘",0x91],["’",0x92],["“",0x93],["”",0x94],["•",0x95],["–",0x96],["—",0x97]]);let out="";for(const ch of String(s??"")){const cp=ch.charCodeAt(0);if(cp<=255)out+=String.fromCharCode(cp);else if(map.has(ch))out+=String.fromCharCode(map.get(ch));else throw new Error("PDF_UNSUPPORTED_ARTIFACT_CHARACTER");}return out;}
function wrap(line,n){const words=String(line??"").split(/\s+/);const out=[];let cur="";for(const w of words){if(!w)continue;if((cur+" "+w).trim().length>n){if(cur)out.push(cur);cur=w;}else cur=(cur+" "+w).trim();}if(cur)out.push(cur);return out.length?out:[""];}
const SPECS=Object.freeze({
 essential:Object.freeze({id:"essential",layout:"single_column",fontSize:10,lineHeight:14,left:54,right:54,top:54,bottom:48,nameSize:16,sectionSize:11,sectionGap:8,rule:false,sidebar:false}),
 professional:Object.freeze({id:"professional",layout:"hierarchical_single_column",fontSize:10,lineHeight:14,left:60,right:60,top:58,bottom:50,nameSize:20,sectionSize:12,sectionGap:13,rule:true,sidebar:false}),
 compact:Object.freeze({id:"compact",layout:"main_plus_secondary_column",fontSize:9,lineHeight:12,left:40,right:40,top:46,bottom:44,nameSize:17,sectionSize:10,sectionGap:6,rule:true,sidebar:true})
});
export function getApplicationPdfTemplateSpec(template="essential"){return SPECS[template]||SPECS.essential;}
const val=v=>typeof v==="string"?v.trim():""; const arr=v=>Array.isArray(v)?v:[];
function modelSections(model){const identity=model?.identity||{};const header=[`${val(identity.name)} ${val(identity.surname)}`.trim(),val(identity.professionalTitle),[val(identity.phone),val(identity.email),val(identity.linkedin),val(identity.location)].filter(Boolean).join(" · ")].filter(Boolean);return {header,summary:val(model?.professionalSummary),experience:arr(model?.professionalExperience).map(x=>({role:val(x?.role),organisation:val(x?.organisation),period:val(x?.period),details:arr(x?.details||x?.responsibilities).map(v=>typeof v==="string"?val(v):val(v?.text)).filter(Boolean).concat(val(x?.text)?[val(x.text)]:[])})).filter(x=>x.role||x.organisation||x.period||x.details.length),education:arr(model?.education).map(x=>val(x?.text)).filter(Boolean),skills:arr(model?.skills).map(x=>typeof x==="string"?x:val(x?.text||x?.label)).filter(Boolean),languages:arr(model?.languages).map(x=>typeof x==="string"?x:val(x?.text||x?.label)).filter(Boolean)};}
function buildTrace(model,spec,labels={}){const s=modelSections(model),trace=[];const add=(section,region,items,kind="body")=>items.forEach((text,index)=>trace.push({section,region,kind,index,text}));add("header","main",s.header,"header");if(s.summary)add("summary","main",[s.summary]);s.experience.forEach((x,index)=>{const label=[x.role,x.organisation,x.period].filter(Boolean).join(" · ");if(label)trace.push({section:"experience",region:"main",kind:"experience_heading",index,text:label});x.details.forEach((d,j)=>trace.push({section:"experience",region:"main",kind:"experience_detail",index:`${index}:${j}`,text:d}));});const secondary=spec.sidebar?"secondary":"main";add("education",secondary,s.education);add("skills",secondary,s.skills);add("languages",secondary,s.languages);return trace;}
export function getCvPdfLayoutTrace({cvContentModel,template="essential"}={}){const spec=getApplicationPdfTemplateSpec(template);return Object.freeze({template:spec.id,layout:spec.layout,contentVersion:cvContentModel?.version||"",sourceMaterialRefs:arr(cvContentModel?.sourceMaterialRefs),entries:Object.freeze(buildTrace(cvContentModel,spec))});}
function textCmd({x,y,text,size=10,font="F1"}){return `BT /${font} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${pdfEscapeLatin1(latin1Safe(text))}) Tj ET`;}
function ruleCmd(x1,y,x2){return `${x1} ${y} m ${x2} ${y} l S`;}
function paginateBlocks(blocks,{pageH=842,top=54,bottom=48}={}){const pages=[[]];let y=pageH-top;for(const b of blocks){const h=b.height;if(y-h<bottom){pages.push([]);y=pageH-top;}pages.at(-1).push({...b,y});y-=h;}return pages;}
function cvBlocks(model,spec,labels={}){const s=modelSections(model),width=595-spec.left-spec.right,mainWidth=spec.sidebar?Math.floor(width*.68):width,sideX=spec.left+mainWidth+22,sideWidth=width-mainWidth-22,blocks=[];const chars=w=>Math.max(30,Math.floor(w/(spec.fontSize*.52)));const addLines=(section,items,{region="main",size=spec.fontSize,font="F1",gap=0,prefix=""}={})=>{const w=region==="secondary"?sideWidth:mainWidth;for(const item of items){const lines=wrap(prefix+item,chars(w));blocks.push({section,region,lines,size,font,height:lines.length*spec.lineHeight+gap,x:region==="secondary"?sideX:spec.left,width:w});}};const heading=(section,label,region="main")=>{if(!label)return;blocks.push({section,region,heading:label,size:spec.sectionSize,font:"F2",height:spec.lineHeight+spec.sectionGap,x:region==="secondary"?sideX:spec.left,width:region==="secondary"?sideWidth:mainWidth,rule:spec.rule});};
 if(s.header.length){addLines("header",[s.header[0]],{size:spec.nameSize,font:"F2",gap:4});addLines("header",s.header.slice(1),{size:spec.fontSize,gap:3});}
 if(s.summary){heading("summary",labels.profile);addLines("summary",[s.summary],{gap:4});}
 if(s.experience.length){heading("experience",labels.experience);for(const x of s.experience){const h=[x.role,x.organisation,x.period].filter(Boolean).join(" · ");if(h)addLines("experience",[h],{font:"F2",gap:2});addLines("experience",x.details,{prefix:"• ",gap:4});}}
 const secondary=spec.sidebar?"secondary":"main";if(s.education.length){heading("education",labels.education,secondary);addLines("education",s.education,{region:secondary,prefix:"• ",gap:3});}if(s.skills.length){heading("skills",labels.skills,secondary);addLines("skills",s.skills,{region:secondary,prefix:"• ",gap:3});}if(s.languages.length){heading("languages",labels.languages,secondary);addLines("languages",s.languages,{region:secondary,prefix:"• ",gap:3});}
 return blocks;}
function renderPages(pages,spec){return pages.map(page=>{const cmds=["0 G 0.6 w"];for(const b of page){let y=b.y;if(b.heading){cmds.push(textCmd({x:b.x,y,text:b.heading,size:b.size,font:b.font}));if(b.rule)cmds.push(ruleCmd(b.x,y-3,b.x+b.width));continue;}for(const line of b.lines){cmds.push(textCmd({x:b.x,y,text:line,size:b.size,font:b.font}));y-=spec.lineHeight;}}return cmds.join("\n");});}
function buildPdf(streams,title){const pageCount=streams.length,font1=3+pageCount*2,font2=font1+1,objects=[];const kids=streams.map((_,i)=>`${3+i*2} 0 R`).join(" ");objects.push(`1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj`,`2 0 obj << /Type /Pages /Kids [${kids}] /Count ${pageCount} >> endobj`);streams.forEach((stream,i)=>{const po=3+i*2,so=po+1;objects.push(`${po} 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font1} 0 R /F2 ${font2} 0 R >> >> /Contents ${so} 0 R >> endobj`,`${so} 0 obj << /Length ${Buffer.byteLength(stream,"latin1")} >> stream\n${stream}\nendstream endobj`);});objects.push(`${font1} 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >> endobj`,`${font2} 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >> endobj`);let pdf="%PDF-1.4\n",offset=[0];for(const o of objects){offset.push(Buffer.byteLength(pdf,"latin1"));pdf+=o+"\n";}const xref=Buffer.byteLength(pdf,"latin1"),count=objects.length+1;pdf+=`xref\n0 ${count}\n0000000000 65535 f \n${offset.slice(1).map(x=>String(x).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer << /Size ${count} /Root 1 0 R /Info << /Title (${pdfEscapeLatin1(latin1Safe(title))}) >> >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf,"latin1");}
export function renderCvApplicationPdf({cvContentModel,title="IMAGO",template="essential",labels={}}={}){if(cvContentModel?.type!=="cv_content_model")throw new Error("CV_CONTENT_MODEL_REQUIRED");const spec=getApplicationPdfTemplateSpec(template),blocks=cvBlocks(cvContentModel,spec,labels);let pages;if(spec.sidebar){const main=blocks.filter(x=>x.region!=="secondary"),secondary=blocks.filter(x=>x.region==="secondary"),mainPages=paginateBlocks(main,{top:spec.top,bottom:spec.bottom}),sidePages=paginateBlocks(secondary,{top:spec.top,bottom:spec.bottom});const count=Math.max(mainPages.length,sidePages.length);pages=Array.from({length:count},(_,i)=>[...(mainPages[i]||[]),...(sidePages[i]||[])]);}else pages=paginateBlocks(blocks,{top:spec.top,bottom:spec.bottom});return buildPdf(renderPages(pages,spec),title);}
export function renderApplicationPdf({content,title="IMAGO",template="essential"}={}){const spec=getApplicationPdfTemplateSpec(template),width=595-spec.left-spec.right,lines=String(content||"").split(/\r?\n/).flatMap(x=>wrap(x,Math.max(38,Math.floor(width/(spec.fontSize*.53))))),blocks=lines.map(line=>({section:"document",region:"main",lines:[line],size:spec.fontSize,font:"F1",height:spec.lineHeight,x:spec.left,width})),pages=paginateBlocks(blocks,{top:spec.top,bottom:spec.bottom});return buildPdf(renderPages(pages,{...spec,sidebar:false}),title);}
