const text=v=>typeof v==="string"?v.trim():"";const arr=v=>Array.isArray(v)?v:[];
function esc(s){return String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function crc32(buf){let c=0xffffffff;for(const byte of buf){c^=byte;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function zipStore(files){const locals=[],centrals=[];let offset=0;for(const [name,dataValue] of files){const data=Buffer.isBuffer(dataValue)?dataValue:Buffer.from(String(dataValue),"utf8"),nameBuf=Buffer.from(name,"utf8"),crc=crc32(data),local=Buffer.alloc(30+nameBuf.length);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0,6);local.writeUInt16LE(0,8);local.writeUInt16LE(0,10);local.writeUInt16LE(0,12);local.writeUInt32LE(crc,14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(nameBuf.length,26);local.writeUInt16LE(0,28);nameBuf.copy(local,30);locals.push(local,data);const central=Buffer.alloc(46+nameBuf.length);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(0,8);central.writeUInt16LE(0,10);central.writeUInt16LE(0,12);central.writeUInt16LE(0,14);central.writeUInt32LE(crc,16);central.writeUInt32LE(data.length,20);central.writeUInt32LE(data.length,24);central.writeUInt16LE(nameBuf.length,28);central.writeUInt16LE(0,30);central.writeUInt16LE(0,32);central.writeUInt16LE(0,34);central.writeUInt16LE(0,36);central.writeUInt32LE(0,38);central.writeUInt32LE(offset,42);nameBuf.copy(central,46);centrals.push(central);offset+=local.length+data.length;}const centralStart=offset,centralSize=centrals.reduce((n,b)=>n+b.length,0),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(0,4);end.writeUInt16LE(0,6);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(centralSize,12);end.writeUInt32LE(centralStart,16);end.writeUInt16LE(0,20);return Buffer.concat([...locals,...centrals,end]);}
function run(value,{bold=false,italic=false,size=21}={}){return `<w:r><w:rPr>${bold?"<w:b/>":""}${italic?"<w:i/>":""}<w:sz w:val="${size}"/><w:szCs w:val="${size}"/><w:rFonts w:ascii="Arial" w:hAnsi="Arial" w:cs="Arial"/></w:rPr><w:t xml:space="preserve">${esc(value)}</w:t></w:r>`;}
function p(value,{style="Body",bold=false,italic=false,size,keepNext=false,spacingAfter=120,num=false,align="left"}={}){if(!text(value))return "";return `<w:p><w:pPr><w:pStyle w:val="${style}"/>${keepNext?"<w:keepNext/>":""}<w:keepLines/><w:spacing w:after="${spacingAfter}"/>${align!=="left"?`<w:jc w:val="${align}"/>`:""}${num?'<w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr>':""}</w:pPr>${run(value,{bold,italic,size:size||undefined})}</w:p>`;}
function experienceTable(e){const left=[text(e.role),text(e.organisation)].filter(Boolean),period=text(e.period),leftXml=left.map((x,i)=>p(x,{style:i===0?"Role":"Meta",bold:i===0,italic:i>0,keepNext:true,spacingAfter:20})).join("");const right=period?p(period,{style:"Meta",italic:true,align:"right",keepNext:true,spacingAfter:20}):"";return `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders><w:top w:val="nil"/><w:left w:val="nil"/><w:bottom w:val="nil"/><w:right w:val="nil"/><w:insideH w:val="nil"/><w:insideV w:val="nil"/></w:tblBorders><w:tblCellMar><w:left w:w="0" w:type="dxa"/><w:right w:w="0" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="7000"/><w:gridCol w:w="2300"/></w:tblGrid><w:tr><w:trPr><w:cantSplit/></w:trPr><w:tc><w:tcPr><w:tcW w:w="7000" w:type="dxa"/></w:tcPr>${leftXml}</w:tc><w:tc><w:tcPr><w:tcW w:w="2300" w:type="dxa"/></w:tcPr>${right}</w:tc></w:tr></w:tbl>`;}
function documentBody(model){const out=[];for(const section of arr(model.sections)){if(section.kind==="cv_header"){for(const b of arr(section.blocks)){if(b.kind==="candidate_name")out.push(p(b.text,{style:"CandidateName",bold:true,size:34,spacingAfter:40}));else if(b.kind==="candidate_contact")out.push(p(b.text,{style:"Contact",size:18,spacingAfter:15}));else if(b.kind==="document_title")out.push(p(b.text,{style:"DocTitle",bold:true,size:20,spacingAfter:20}));else if(b.kind==="target_reference")out.push(p(b.text,{style:"Target",bold:true,size:22,spacingAfter:160}));}}
 else if(section.kind==="summary"){out.push(p(section.title,{style:"SectionHeading",bold:true,size:22,keepNext:true,spacingAfter:70}));for(const b of arr(section.blocks))out.push(p(b.text,{style:"Body",spacingAfter:160}));}
 else if(section.kind==="experience"){out.push(p(section.title,{style:"SectionHeading",bold:true,size:22,keepNext:true,spacingAfter:80}));for(const e of arr(section.entries)){out.push(experienceTable(e));for(const d of arr(e.details))out.push(p(d,{style:"Bullet",num:true,spacingAfter:55}));out.push(p(" ",{style:"Body",spacingAfter:70}));}}
 else if(section.kind==="list"){out.push(p(section.title,{style:"SectionHeading",bold:true,size:22,keepNext:true,spacingAfter:70}));for(const item of arr(section.items))out.push(p(item,{style:"Bullet",num:true,spacingAfter:55}));}
 else if(section.kind==="letter_header"){for(const b of arr(section.blocks)){if(b.kind==="candidate_name")out.push(p(b.text,{style:"CandidateName",bold:true,size:30,spacingAfter:30}));else out.push(p(b.text,{style:"Contact",size:18,spacingAfter:10}));}out.push(p(" ",{spacingAfter:120}));}
 else if(section.kind==="letter_reference"){for(const b of arr(section.blocks)){if(b.kind==="generated_date")out.push(p(b.text,{style:"Meta",size:18,align:"right",spacingAfter:120}));else if(b.kind==="document_title")out.push(p(b.text,{style:"DocTitle",bold:true,size:24,spacingAfter:50}));else out.push(p(b.text,{style:"Target",bold:true,size:21,spacingAfter:170}));}}
 else if(section.kind==="letter_body"){for(const b of arr(section.blocks))out.push(p(b.text,{style:"Body",spacingAfter:170}));}
 else if(section.kind==="letter_close"){for(const b of arr(section.blocks)){if(b.kind==="closing")out.push(p(b.text,{style:"Body",spacingAfter:130}));else out.push(p(b.text,{style:"Signature",bold:true,spacingAfter:40}));}}
 }
 return out.join("");}
const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:sz w:val="21"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="120"/><w:jc w:val="left"/></w:pPr></w:pPrDefault></w:docDefaults>${["Normal","Body","CandidateName","Contact","DocTitle","Target","SectionHeading","Role","Meta","Bullet","Signature"].map(id=>`<w:style w:type="paragraph" w:styleId="${id}"><w:name w:val="${id}"/>${id!=="Normal"?'<w:basedOn w:val="Normal"/>':""}<w:qFormat/></w:style>`).join("")}</w:styles>`;
const numbering=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:abstractNum w:abstractNumId="0"><w:multiLevelType w:val="singleLevel"/><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="bullet"/><w:lvlText w:val="•"/><w:lvlJc w:val="left"/><w:pPr><w:tabs><w:tab w:val="num" w:pos="420"/></w:tabs><w:ind w:left="420" w:hanging="240"/></w:pPr><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/></w:rPr></w:lvl></w:abstractNum><w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num></w:numbering>`;
export function renderApplicationDocumentDocx({documentModel}={}){if(documentModel?.type!=="application_document_model")throw new Error("APPLICATION_DOCUMENT_MODEL_REQUIRED");const body=documentBody(documentModel),doc=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134" w:header="708" w:footer="708" w:gutter="0"/></w:sectPr></w:body></w:document>`;const created=(text(documentModel.generatedAt)||"2000-01-01T00:00:00Z").replace(/\.\d+Z$/,"Z"),title=documentModel.documentType==="cover_letter"?"Cover Letter":"Curriculum Vitae";const files=[
 ["[Content_Types].xml",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>`],
 ["_rels/.rels",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>`],
 ["word/document.xml",doc],["word/styles.xml",styles],["word/numbering.xml",numbering],["word/_rels/document.xml.rels",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/></Relationships>`],
 ["docProps/core.xml",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>${esc(title)}</dc:title><dc:creator>IMAGO</dc:creator><dcterms:created xsi:type="dcterms:W3CDTF">${esc(created)}</dcterms:created></cp:coreProperties>`],
 ["docProps/app.xml",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>IMAGO</Application></Properties>`]
 ];return zipStore(files);}
