const val=v=>typeof v==="string"?v.trim():"";const arr=v=>Array.isArray(v)?v:[];
function pdfEscapeLatin1(s){return String(s??"").replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)");}
function latin1Safe(s){const map=new Map([["€",0x80],["‘",0x91],["’",0x92],["“",0x93],["”",0x94],["•",0x95],["–",0x96],["—",0x97]]);let out="";for(const ch of String(s??"")){const cp=ch.charCodeAt(0);if(cp<=255)out+=String.fromCharCode(cp);else if(map.has(ch))out+=String.fromCharCode(map.get(ch));else throw new Error("PDF_UNSUPPORTED_ARTIFACT_CHARACTER");}return out;}
function wrap(line,n){const words=String(line??"").split(/\s+/),out=[];let cur="";for(const w of words){if(!w)continue;if((cur+" "+w).trim().length>n){if(cur)out.push(cur);cur=w;}else cur=(cur+" "+w).trim();}if(cur)out.push(cur);return out.length?out:[""];}
function textCmd({x,y,text,size=10,font="F1"}){return `BT /${font} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${pdfEscapeLatin1(latin1Safe(text))}) Tj ET`;}
function ruleCmd(x1,y,x2){return `${x1} ${y} m ${x2} ${y} l S`;}
function buildPdf(streams,title){const pageCount=streams.length,font1=3+pageCount*2,font2=font1+1,objects=[],kids=streams.map((_,i)=>`${3+i*2} 0 R`).join(" ");objects.push(`1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj`,`2 0 obj << /Type /Pages /Kids [${kids}] /Count ${pageCount} >> endobj`);streams.forEach((stream,i)=>{const po=3+i*2,so=po+1;objects.push(`${po} 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font1} 0 R /F2 ${font2} 0 R >> >> /Contents ${so} 0 R >> endobj`,`${so} 0 obj << /Length ${Buffer.byteLength(stream,"latin1")} >> stream\n${stream}\nendstream endobj`);});objects.push(`${font1} 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >> endobj`,`${font2} 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >> endobj`);let pdf="%PDF-1.4\n",offset=[0];for(const o of objects){offset.push(Buffer.byteLength(pdf,"latin1"));pdf+=o+"\n";}const xref=Buffer.byteLength(pdf,"latin1"),count=objects.length+1;pdf+=`xref\n0 ${count}\n0000000000 65535 f \n${offset.slice(1).map(x=>String(x).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer << /Size ${count} /Root 1 0 R /Info << /Title (${pdfEscapeLatin1(latin1Safe(title))}) >> >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf,"latin1");}
const spec=Object.freeze({left:58,right:58,top:56,bottom:52,fontSize:10,lineHeight:14,width:479});
function lineBlock(text,{size=10,font="F1",gap=0,indent=0,keepWithNext=false}={}){const width=spec.width-indent,chars=Math.max(34,Math.floor(width/(size*.52))),lines=wrap(text,chars);return {kind:"lines",lines,size,font,gap,height:lines.length*spec.lineHeight+gap,x:spec.left+indent,width,keepWithNext};}
function headingBlock(text){return {kind:"heading",text,size:11,font:"F2",height:24,x:spec.left,width:spec.width,keepWithNext:true};}
function roleBlock(entry){const left=[val(entry.role),val(entry.organisation)].filter(Boolean),period=val(entry.period);return {kind:"role",left,period,size:10,height:(left.length?left.length:1)*spec.lineHeight+5,x:spec.left,width:spec.width,keepWithNext:true};}
function cvBlocks(model){const blocks=[];for(const section of arr(model.sections)){if(section.kind==="cv_header"){for(const b of arr(section.blocks)){if(b.kind==="candidate_name")blocks.push(lineBlock(b.text,{size:18,font:"F2",gap:3}));else if(b.kind==="candidate_contact")blocks.push(lineBlock(b.text,{size:9,gap:1}));else if(b.kind==="document_title")blocks.push(lineBlock(b.text,{size:10,font:"F2",gap:1}));else if(b.kind==="target_reference")blocks.push(lineBlock(b.text,{size:11,font:"F2",gap:10}));}}
 else if(section.kind==="summary"){blocks.push(headingBlock(section.title));for(const b of arr(section.blocks))blocks.push(lineBlock(b.text,{gap:8}));}
 else if(section.kind==="experience"){blocks.push(headingBlock(section.title));for(const e of arr(section.entries)){blocks.push(roleBlock(e));for(const d of arr(e.details))blocks.push(lineBlock(`• ${d}`,{indent:10,gap:2}));blocks.push({kind:"space",height:5});}}
 else if(section.kind==="list"){blocks.push(headingBlock(section.title));for(const item of arr(section.items))blocks.push(lineBlock(`• ${item}`,{indent:10,gap:2}));}}
 return blocks;}
function letterBlocks(model){const blocks=[];for(const section of arr(model.sections)){if(section.kind==="letter_header"){for(const b of arr(section.blocks)){if(b.kind==="candidate_name")blocks.push(lineBlock(b.text,{size:16,font:"F2",gap:2}));else blocks.push(lineBlock(b.text,{size:9,gap:1}));}blocks.push({kind:"space",height:12});}
 else if(section.kind==="letter_reference"){for(const b of arr(section.blocks)){if(b.kind==="generated_date")blocks.push({kind:"date",text:b.text,size:9,height:20,x:spec.left,width:spec.width});else if(b.kind==="document_title")blocks.push(lineBlock(b.text,{size:12,font:"F2",gap:3}));else blocks.push(lineBlock(b.text,{size:10,font:"F2",gap:14}));}}
 else if(section.kind==="letter_body"){for(const b of arr(section.blocks))blocks.push(lineBlock(b.text,{gap:10}));}
 else if(section.kind==="letter_close"){blocks.push({kind:"space",height:6});for(const b of arr(section.blocks))blocks.push(lineBlock(b.text,{font:b.kind==="signature"?"F2":"F1",gap:4}));}}
 return blocks;}
function paginate(blocks){const pages=[[]];let y=842-spec.top;for(let i=0;i<blocks.length;i++){const b=blocks[i],next=blocks[i+1],needed=b.height+(b.keepWithNext&&next?Math.min(next.height,36):0);if(y-needed<spec.bottom&&pages.at(-1).length){pages.push([]);y=842-spec.top;}pages.at(-1).push({...b,y});y-=b.height;}return pages;}
function renderPages(pages){return pages.map(page=>{const cmds=["0 G 0.6 w"];for(const b of page){let y=b.y;if(b.kind==="space")continue;if(b.kind==="date"){const approx=b.text.length*b.size*.48;cmds.push(textCmd({x:b.x+b.width-approx,y,text:b.text,size:b.size,font:"F1"}));continue;}if(b.kind==="heading"){cmds.push(textCmd({x:b.x,y,text:b.text,size:b.size,font:b.font}),ruleCmd(b.x,y-4,b.x+b.width));continue;}if(b.kind==="role"){if(b.left[0])cmds.push(textCmd({x:b.x,y,text:b.left[0],size:b.size,font:"F2"}));if(b.period){const approx=b.period.length*b.size*.48;cmds.push(textCmd({x:b.x+b.width-approx,y,text:b.period,size:9,font:"F1"}));}if(b.left[1])cmds.push(textCmd({x:b.x,y:y-spec.lineHeight,text:b.left[1],size:9,font:"F1"}));continue;}for(const line of b.lines){cmds.push(textCmd({x:b.x,y,text:line,size:b.size,font:b.font}));y-=spec.lineHeight;}}return cmds.join("\n");});}
export function renderApplicationDocumentPdf({documentModel}={}){if(documentModel?.type!=="application_document_model")throw new Error("APPLICATION_DOCUMENT_MODEL_REQUIRED");const blocks=documentModel.documentType==="cover_letter"?letterBlocks(documentModel):cvBlocks(documentModel),pages=paginate(blocks),title=documentModel.documentType==="cover_letter"?"Cover Letter":"Curriculum Vitae";return buildPdf(renderPages(pages),title);}
