import { createHash } from 'node:crypto';
const arr=v=>Array.isArray(v)?v:[];const text=v=>typeof v==='string'?v.trim():'';const unique=v=>[...new Set(arr(v).map(text).filter(Boolean))];
const freeze=v=>{if(Array.isArray(v)){v.forEach(freeze);return Object.freeze(v)}if(v&&typeof v==='object'){Object.values(v).forEach(freeze);return Object.freeze(v)}return v};
const hash=v=>createHash('sha256').update(String(v)).digest('hex').slice(0,24);
const AGENCY=['not_established','participated','contributed','coordinated','owned','decided'];const rank=v=>Math.max(0,AGENCY.indexOf(text(v)));
const PENDING_RX=/\b(budget|resource allocation|resource responsibility|production planning|production scheduling|pianificazione(?: della)? produzione|programmazione(?: della)? produzione|responsabilit[aà].*(?:budget|risorse))\b/i;
function latestRepresentation(identity){const s=arr(identity?.representationSnapshots).filter(x=>x?.representation?.type==='target_independent_professional_representation');return s.length?s[s.length-1].representation:null;}
function refsFromSupport(v){return unique(arr(v?.support).flatMap(x=>[x?.evidenceRef,x?.sourceId]));}
function contributor(type,ref,value,{professionalBasisRefs=[],materialRefs=[],sourceRefs=[],semanticProtection=[],maxAgency='not_established',causality='not_established'}={}){return freeze({contributorType:type,contributorRef:ref,value,professionalBasisRefs:unique(professionalBasisRefs),materialRefs:unique(materialRefs),sourceRefs:unique(sourceRefs),semanticProtection:unique(semanticProtection),semanticCeiling:freeze({maxAgency,causality})});}
export function buildOpportunityRequirementSupportContributorInventory({professionalIdentity}={}){
 const rep=latestRepresentation(professionalIdentity),pm=rep?.professionalMeaning||{},out=[];const descriptors=new Map(arr(pm.groundedDescriptiveDescriptors).filter(x=>x?.status==='accepted').map(x=>[text(x.descriptorId),x]));const relationAgency=r=>{const levels=unique(r?.descriptorRefs).map(id=>text(descriptors.get(id)?.claimShape?.agencyLevel)).filter(Boolean);return levels.sort((a,b)=>rank(b)-rank(a))[0]||text(r?.claimShape?.agencyLevel)||'not_established';};const relationships=new Map(arr(pm.groundedDescriptiveRelationships).filter(x=>x?.status==='accepted').map(x=>[text(x.relationshipId),x]));
 arr(pm.knowledgeContribution).forEach((k,i)=>{const q=k?.authorisedSemanticPayload||{};const responsibilityAgency=(()=>{const strength=text(q?.responsibilityStrength);if(strength==='participated')return'participated';if(strength==='contributed')return'contributed';if(strength==='coordinated')return'coordinated';if(['direct_bounded_responsibility','broader_responsibility'].includes(strength))return'owned';if(strength==='exclusive_final_authority')return'decided';return'not_established';})();out.push(contributor('bounded_canonical_knowledge_meaning',text(k?.sourceRef)||`knowledge:${i}`,k,{professionalBasisRefs:[k?.sourceRef],materialRefs:[k?.sourceRef],sourceRefs:[k?.lineage?.sourceEvidenceRef,k?.sourceRef,...arr(q.evidenceIds)],semanticProtection:arr(k?.limitations),maxAgency:text(q?.contributionRelationship)||responsibilityAgency,causality:text(q?.causalityBoundary)||'not_established'}));});
 arr(pm.supportedPatterns).forEach((p,i)=>out.push(contributor('supported_pattern',`pattern:${text(p.kind)||i}`,p,{professionalBasisRefs:p.episodeRefs,materialRefs:p.sourceRefs,sourceRefs:p.sourceRefs,semanticProtection:['existing_pattern_authority'],maxAgency:text(p?.claimShape?.agencyLevel)||'not_established'})));
 arr(rep?.episodeMeanings).forEach((e,i)=>out.push(contributor('episode_meaning',text(e?.episodeMeaningId)||`episodeMeaning:${i}`,e,{professionalBasisRefs:[e?.episodeMeaningId],materialRefs:[e?.sourceId],sourceRefs:[e?.sourceId,...refsFromSupport(e)],semanticProtection:e?.limitations,maxAgency:text(e?.participation)||'not_established'})));
 arr(pm.groundedDescriptiveRelationships).filter(x=>x?.status==='accepted').forEach(r=>out.push(contributor('grounded_descriptive_professional_relationship',text(r.relationshipId),r,{professionalBasisRefs:r.professionalBasisRefs,materialRefs:r.materialRefs,sourceRefs:r.sourceRefs,semanticProtection:['pd069_representation_only','no_person_level_inference','no_semantic_strengthening'],maxAgency:relationAgency(r)})));
 arr(pm.higherOrderDescriptiveProfessionalStructures).filter(x=>x?.status==='accepted').forEach(h=>out.push(contributor('higher_order_descriptive_professional_structure',text(h.structureId),h,{professionalBasisRefs:h.professionalBasisRefs,materialRefs:h.materialRefs,sourceRefs:h.sourceRefs,semanticProtection:h.inheritedSemanticProtection,maxAgency:unique(h?.contributorRefs).map(id=>relationships.get(id)).filter(Boolean).map(relationAgency).sort((a,b)=>rank(b)-rank(a))[0]||text(h?.claimShape?.agencyLevel)||'not_established'})));
 return freeze(out.filter(x=>x.contributorRef));
}
export function classifyOpportunityRequirement(opportunityUnderstanding,requirementRef){for(const [key,cls] of [['requirements','required'],['preferredRequirements','preferred'],['responsibilities','responsibility'],['constraints','constraint'],['unclassified','contextual_unclassified']]){const r=arr(opportunityUnderstanding?.[key]).find(x=>x.id===requirementRef);if(r)return freeze({requirement:r,requirementClass:cls});}return null;}
function requiredAgency(statement){const s=text(statement);if(/\b(decide|decision authority|approv|autorizz)\b/i.test(s))return 'decided';if(/\b(own|ownership|accountable|responsabile unico|piena responsabilit[aà])\b/i.test(s))return 'owned';if(/\b(lead|manage|supervis|coordin|orchestrat|guidare|gestir|coordinare|supervision|allineament)\w*\b/i.test(s))return 'coordinated';if(/\b(contribut|support|collabor|partecip)\b/i.test(s))return /\bparticip/i.test(s)?'participated':'contributed';return 'not_established';}
function robustness(c){if(c.contributorType==='higher_order_descriptive_professional_structure'&&unique(c.professionalBasisRefs).length>=2)return 'COMPOSED_HIGHER_ORDER_BASIS';if(c.contributorType==='supported_pattern'&&unique(c.professionalBasisRefs).length>=2)return 'INDEPENDENT_RECURRENT_BASIS';return 'SINGLE_GROUNDED_BASIS';}
export function validateOpportunityRequirementSupportProposal(proposal,{professionalIdentity,opportunityUnderstanding}={}){
 const inventory=buildOpportunityRequirementSupportContributorInventory({professionalIdentity});const c=inventory.find(x=>x.contributorType===text(proposal?.contributorType)&&x.contributorRef===text(proposal?.contributorRef));const target=classifyOpportunityRequirement(opportunityUnderstanding,text(proposal?.opportunityRequirementRef));const errors=[];
 if(text(proposal?.opportunityRef)!==text(opportunityUnderstanding?.opportunityRef))errors.push('opportunity_identity_mismatch');if(!target)errors.push('unknown_requirement_identity');if(!c)errors.push('unknown_or_unauthorised_contributor');if(!text(proposal?.relationBasis))errors.push('missing_relation_basis');if(!text(proposal?.provenance?.providerRef)||!text(proposal?.provenance?.proposalRef))errors.push('insufficient_proposal_provenance');if(proposal?.acceptanceState==='accepted'||proposal?.providerAuthority===true)errors.push('provider_self_authorisation_prohibited');
 if(target&&PENDING_RX.test(target.requirement.statement)){const semanticType=text(c?.value?.semanticType||c?.value?.authorisedSemanticPayload?.semanticType);const authorisedPd086=(/budget|resource allocation|resource responsibility|responsabilit[aà].*(?:budget|risorse)/i.test(target.requirement.statement)&&semanticType==='resource_budget_responsibility_scope')||(/production planning|production scheduling|pianificazione(?: della)? produzione|programmazione(?: della)? produzione/i.test(target.requirement.statement)&&semanticType==='production_planning_scheduling_responsibility_scope');if(!authorisedPd086)errors.push('pending_bounded_acquisition_authority');}
 if(target&&c){const need=requiredAgency(target.requirement.statement),have=text(c.semanticCeiling?.maxAgency)||'not_established';if(rank(need)>rank(have))errors.push('claim_strength_exceeds_contributor_ceiling');if(proposal?.semanticEquivalence==='established')errors.push('fabricated_equivalence_prohibited');if(proposal?.exclusiveResponsibility===true)errors.push('exclusive_responsibility_strengthening_prohibited');if(proposal?.soleCausality===true&&text(c.semanticCeiling?.causality)!=='sole_causality_established')errors.push('causality_strengthening_prohibited');}
 if(errors.length)return freeze({status:'rejected',errors,proposalRef:text(proposal?.provenance?.proposalRef)});
 const r=target.requirement;return freeze({status:'accepted',relationId:`opportunityRequirementSupport:${hash([opportunityUnderstanding.opportunityRef,r.id,c.contributorType,c.contributorRef].join('|'))}`,opportunityRef:opportunityUnderstanding.opportunityRef,opportunityRequirementRef:r.id,requirementClass:target.requirementClass,requirementStatement:r.statement,contributorType:c.contributorType,contributorRef:c.contributorRef,professionalBasisRefs:c.professionalBasisRefs,materialRefs:c.materialRefs,sourceRefs:c.sourceRefs,semanticCeiling:c.semanticCeiling,semanticProtection:unique([...c.semanticProtection,'opportunity_specific_only','derived_recomputable','no_person_knowledge_writeback','no_semantic_strengthening']),relationBasis:text(proposal.relationBasis),acceptanceState:'accepted',supportRobustnessClass:robustness(c),persistentAsPersonKnowledge:false,provenance:freeze({proposal:freeze({...proposal.provenance}),requirementSourceRef:r.sourceRef,contributorRef:c.contributorRef})});
}
export function buildOpportunityRequirementSupportProjection({professionalIdentity,opportunityUnderstanding,proposals=[]}={}){
 const checked=arr(proposals).filter(p=>text(p?.opportunityRef)===text(opportunityUnderstanding?.opportunityRef)).map(p=>validateOpportunityRequirementSupportProposal(p,{professionalIdentity,opportunityUnderstanding}));const relations=checked.filter(x=>x.status==='accepted'),rejections=checked.filter(x=>x.status==='rejected');const by=new Map();for(const r of relations){const xs=by.get(r.opportunityRequirementRef)||[];xs.push(r);by.set(r.opportunityRequirementRef,xs)}
 const order={SINGLE_GROUNDED_BASIS:1,INDEPENDENT_RECURRENT_BASIS:2,COMPOSED_HIGHER_ORDER_BASIS:3};const aggregates=[...by.entries()].map(([requirementRef,rs])=>{const strongest=[...rs].sort((a,b)=>order[b.supportRobustnessClass]-order[a.supportRobustnessClass])[0];return freeze({requirementRef,requirementClass:strongest.requirementClass,supported:true,acceptedContributorRefs:unique(rs.map(x=>x.contributorRef)),acceptedContributorTypes:unique(rs.map(x=>x.contributorType)),professionalBasisRefs:unique(rs.flatMap(x=>x.professionalBasisRefs)),materialRefs:unique(rs.flatMap(x=>x.materialRefs)),sourceRefs:unique(rs.flatMap(x=>x.sourceRefs)),supportRobustnessClass:strongest.supportRobustnessClass,relations:freeze(rs)});});
 return freeze({type:'opportunity_requirement_support_projection',version:'1.0',opportunityRef:text(opportunityUnderstanding?.opportunityRef),relations:freeze(relations),rejections:freeze(rejections),aggregates:freeze(aggregates),lexicalOverlapRole:'proposal_aid_retrieval_preselection_fallback_diagnostic_only',personKnowledgeWriteback:false});
}
