const {validateCapabilityExecutionResult}=require('../capability/validateCapabilityExecutionResult');
const {validateDerivedDimensionMapping}=require('./validateDerivedDimensionMapping');
const {buildDerivedDimensionKnowledgeState}=require('./buildDerivedDimensionKnowledgeState');
const {validateDerivedDimensionKnowledgeState}=require('./validateDerivedDimensionKnowledgeState');
function fail(code,message,details){const e=new Error(message);e.code=code;if(details!==undefined)e.details=details;throw e}
function round(v){return Math.round(v*1e12)/1e12}
function targetKey(t){return `${t.knowledgeType}:${t.knowledgeId}`}
function buildDerivedDimensionKnowledgeStates(executionResults,mappings,options={}){
  if(!Array.isArray(executionResults))fail('INVALID_CAPABILITY_EXECUTION_RESULT','executionResults must be an array.');
  if(!Array.isArray(mappings))fail('INVALID_DERIVED_DIMENSION_MAPPING','mappings must be an array.');
  const executionIds=new Set(), resultIds=new Set(), mappingKeys=new Set(), mappingIndex=new Map();
  executionResults.forEach((execution,index)=>{const validation=validateCapabilityExecutionResult(execution);if(!validation.valid)fail('INVALID_CAPABILITY_EXECUTION_RESULT',`executionResults[${index}] is invalid: ${validation.errors.join(' | ')}`,validation);if(executionIds.has(execution.id))fail('DUPLICATE_CAPABILITY_EXECUTION_RESULT',`Duplicate CapabilityExecutionResult id: ${execution.id}.`);executionIds.add(execution.id);execution.derivedResults.forEach(result=>{if(resultIds.has(result.id))fail('DUPLICATE_DERIVED_KNOWLEDGE_RESULT',`Duplicate DerivedKnowledgeResult id: ${result.id}.`);resultIds.add(result.id);});});
  mappings.forEach((mapping,index)=>{const validation=validateDerivedDimensionMapping(mapping);if(!validation.valid)fail('INVALID_DERIVED_DIMENSION_MAPPING',`mappings[${index}] is invalid: ${validation.errors.join(' | ')}`,validation);const key=targetKey(mapping.resultTarget);if(mappingKeys.has(key))fail('DUPLICATE_DERIVED_DIMENSION_MAPPING',`Duplicate mapping target: ${key}.`);mappingKeys.add(key);mappingIndex.set(key,mapping);});
  const groups=new Map();
  for(const execution of executionResults){for(const result of execution.derivedResults){const mapping=mappingIndex.get(targetKey(result.target));if(!mapping)continue;if(result.target.knowledgeType!=='derived_dimension')continue;if(result.value.valueType!=='boolean'||result.value.value!==true)continue;const key=[mapping.dimensionId,execution.capabilityId,execution.recipeRef,execution.recipeVersion,execution.snapshotRef].join('|');if(!groups.has(key))groups.set(key,{execution,items:[]});groups.get(key).items.push({result,mapping});}}
  const states=[];
  for(const group of [...groups.values()].sort((a,b)=>`${a.items[0].mapping.dimensionId}|${a.execution.recipeRef}`.localeCompare(`${b.items[0].mapping.dimensionId}|${b.execution.recipeRef}`))){const items=[...group.items].sort((a,b)=>a.result.id.localeCompare(b.result.id));const weight=items.reduce((sum,item)=>sum+item.result.confidence,0);const estimate=round(items.reduce((sum,item)=>sum+item.mapping.estimate*item.result.confidence,0)/weight);const confidence=Math.min(...items.map(item=>item.result.confidence));const executionRef=`capabilityExecutionResult:${group.execution.id}`;const sourceResultRefs=items.map(item=>`derivedKnowledgeResult:${item.result.id}`).sort();const dependencyRefs=[group.execution.snapshotRef,group.execution.recipeRef,executionRef,...items.map(item=>item.result.ruleRef),...sourceResultRefs,...items.flatMap(item=>item.result.dependencyRefs)].filter((x,i,a)=>a.indexOf(x)===i).sort();const now=options.now||group.execution.executedAt;const state=buildDerivedDimensionKnowledgeState({dimensionId:group.items[0].mapping.dimensionId,estimate,confidence,capabilityId:group.execution.capabilityId,recipeRef:group.execution.recipeRef,recipeVersion:group.execution.recipeVersion,snapshotRef:group.execution.snapshotRef,executionRefs:[executionRef],sourceResultRefs,dependencyRefs,extensions:{aggregation:{strategy:'confidence_weighted_mean_v1',confidenceStrategy:'minimum',mappingRefs:items.map(item=>`derivedDimensionMapping:${item.mapping.id}`).sort(),resultCount:items.length}}},{now});const validation=validateDerivedDimensionKnowledgeState(state);if(!validation.valid)fail('INVALID_GENERATED_DERIVED_DIMENSION_STATE',validation.errors.join(' | '),validation);states.push(state)}
  return states.sort((a,b)=>a.id.localeCompare(b.id));
}
module.exports={buildDerivedDimensionKnowledgeStates};
