module.exports = {
  ...require("./buildDimensionKnowledgeState"),
  ...require("./validateDimensionKnowledgeState"),
  ...require("./healthBuildDimensionKnowledgeState"),
  buildDimensionContribution: require("./buildDimensionContribution").buildDimensionContribution,
  validateDimensionContribution: require("./validateDimensionContribution").validateDimensionContribution,
  buildMeasurementDimensionMapping: require("./buildMeasurementDimensionMapping").buildMeasurementDimensionMapping,
  validateMeasurementDimensionMapping: require("./validateMeasurementDimensionMapping").validateMeasurementDimensionMapping,
  evaluateMeasurementResultMappingApplicability: require("./evaluateMeasurementResultMappingApplicability").evaluateMeasurementResultMappingApplicability,
  validateMeasurementResultMappingApplicability: require("./validateMeasurementResultMappingApplicability").validateMeasurementResultMappingApplicability,
  validateMeasurementResultMappingApplicabilityContext: require("./validateMeasurementResultMappingApplicabilityContext").validateMeasurementResultMappingApplicabilityContext,
  healthMeasurementResultMappingApplicability: require("./healthMeasurementResultMappingApplicability").healthMeasurementResultMappingApplicability,
  mapMeasurementResultToDimensionContributions: require("./mapMeasurementResultToDimensionContributions").mapMeasurementResultToDimensionContributions,
  aggregateDimensionContributions: require("./aggregateDimensionContributions").aggregateDimensionContributions,
  buildKnowledgeLedger: require("./buildKnowledgeLedger").buildKnowledgeLedger,
  validateKnowledgeLedger: require("./validateKnowledgeLedger").validateKnowledgeLedger,
  appendDimensionContributions: require("./appendDimensionContributions").appendDimensionContributions,
  buildKnowledgeSnapshot: require("./buildKnowledgeSnapshot").buildKnowledgeSnapshot,
  validateKnowledgeSnapshot: require("./validateKnowledgeSnapshot").validateKnowledgeSnapshot,
  buildDerivedKnowledgeRule: require("./buildDerivedKnowledgeRule").buildDerivedKnowledgeRule,
  validateDerivedKnowledgeRule: require("./validateDerivedKnowledgeRule").validateDerivedKnowledgeRule,
  buildDerivedKnowledgeResult: require("./buildDerivedKnowledgeResult").buildDerivedKnowledgeResult,
  validateDerivedKnowledgeResult: require("./validateDerivedKnowledgeResult").validateDerivedKnowledgeResult,
  evaluateDerivedKnowledgeRules: require("./evaluateDerivedKnowledgeRules").evaluateDerivedKnowledgeRules,
  buildDerivedDimensionMapping: require("./buildDerivedDimensionMapping").buildDerivedDimensionMapping,
  validateDerivedDimensionMapping: require("./validateDerivedDimensionMapping").validateDerivedDimensionMapping,
  buildDerivedDimensionKnowledgeState: require("./buildDerivedDimensionKnowledgeState").buildDerivedDimensionKnowledgeState,
  validateDerivedDimensionKnowledgeState: require("./validateDerivedDimensionKnowledgeState").validateDerivedDimensionKnowledgeState,
  buildDerivedDimensionKnowledgeStates: require("./buildDerivedDimensionKnowledgeStates").buildDerivedDimensionKnowledgeStates,
};
