const { validateDimensionKnowledgeState }=require("./validateDimensionKnowledgeState"); const { collectIntegrityErrors }=require("./knowledgeLedgerIntegrity"); const { snapshotId }=require("./knowledgeSnapshotIntegrity");
const TOP=["id","ledgerRef","dimensionStates","statistics","metadata","extensions"];
function isObject(v){return v!==null&&typeof v==="object"&&!Array.isArray(v);} function validString(v){return typeof v==="string"&&v.trim().length>0;} function validIso(v){return typeof v==="string"&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString()===v;}
function validateKnowledgeSnapshot(snapshot={}){const errors=[],warnings=[];if(!isObject(snapshot))return{valid:false,errors:["KnowledgeSnapshot must be an object."],warnings};for(const k of Object.keys(snapshot))if(!TOP.includes(k))errors.push(`knowledgeSnapshot.${k} is not allowed.`);if(!validString(snapshot.ledgerRef)||!snapshot.ledgerRef.startsWith("knowledgeLedger:"))errors.push("ledgerRef must be a knowledgeLedger reference.");
 const integrityErrors=[];collectIntegrityErrors(snapshot,"knowledgeSnapshot",integrityErrors);errors.push(...integrityErrors);
 if(!Array.isArray(snapshot.dimensionStates))errors.push("dimensionStates must be an array.");const states=Array.isArray(snapshot.dimensionStates)?snapshot.dimensionStates:[];const ids=new Set();states.forEach((s,i)=>{const v=validateDimensionKnowledgeState(s);if(!v.valid)errors.push(`dimensionStates[${i}] is invalid: ${v.errors.join(" | ")}`);if(s&&validString(s.dimensionId)){if(ids.has(s.dimensionId))errors.push(`Duplicate dimensionId: ${s.dimensionId}.`);ids.add(s.dimensionId);}if(i>0&&validString(states[i-1]&&states[i-1].dimensionId)&&validString(s&&s.dimensionId)&&states[i-1].dimensionId.localeCompare(s.dimensionId)>0)errors.push("dimensionStates must be ordered by dimensionId.");});
 if(!isObject(snapshot.statistics))errors.push("statistics must be an object.");else{for(const k of Object.keys(snapshot.statistics))if(!["dimensionCount","contributionCount"].includes(k))errors.push(`statistics.${k} is not allowed.`);if(snapshot.statistics.dimensionCount!==states.length)errors.push(`statistics.dimensionCount must equal ${states.length}.`);if(!Number.isInteger(snapshot.statistics.contributionCount)||snapshot.statistics.contributionCount<0)errors.push("statistics.contributionCount must be a non-negative integer.");}
 if(!isObject(snapshot.metadata))errors.push("metadata must be an object.");else{for(const k of Object.keys(snapshot.metadata))if(!["version","createdAt"].includes(k))errors.push(`metadata.${k} is not allowed.`);if(snapshot.metadata.version!=="1.0")errors.push('metadata.version must be "1.0".');if(!validIso(snapshot.metadata.createdAt))errors.push("metadata.createdAt must be a valid ISO timestamp.");}if(!isObject(snapshot.extensions))errors.push("extensions must be an object.");
 if(integrityErrors.length===0&&validString(snapshot.ledgerRef)){const ledgerId=snapshot.ledgerRef.slice("knowledgeLedger:".length);const expected=snapshotId(ledgerId,states);if(snapshot.id!==expected)errors.push("id does not match canonical Snapshot identity.");}if(!validString(snapshot.id))errors.push("id must be a non-empty string.");return{valid:errors.length===0,errors,warnings};}
module.exports={validateKnowledgeSnapshot};
