const crypto=require('crypto');
const {validateKnowledgeAcquisitionDesign}=require('./validateKnowledgeAcquisitionDesign');
const {validateKnowledgeAcquisitionCapabilityMatch}=require('./validateKnowledgeAcquisitionCapabilityMatch');
const {calculateKnowledgeAcquisitionCapabilityMatchId}=require('./knowledgeAcquisitionDeclarativeIdentity');
const {deepFreezeKnowledgeAcquisitionArtifact}=require('./knowledgeAcquisitionImmutability');
function obj(v){return v&&typeof v==='object'&&!Array.isArray(v)}function stable(v){if(Array.isArray(v))return `[${v.map(stable).join(',')}]`;if(obj(v))return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;return JSON.stringify(v)}function hash(v){return crypto.createHash('sha256').update(stable(v)).digest('hex')}function fail(code,message,details){const e=new Error(message);e.code=code;if(details)e.details=details;throw e}function set(a){return [...new Set(a)].sort()}function strings(v,name,required=true){if(v===undefined&&!required)return null;if(!Array.isArray(v)||!v.every(x=>typeof x==='string'&&x.trim()))fail('INVALID_CAPABILITY_CANDIDATE',`${name} must be an array of non-empty strings.`);return set(v)}
const TYPES=['measurement','structured_input','document_ingestion','deterministic_extraction','human_mediated','llm_assisted','llm_native','external_retrieval','generic'];
const FORBIDDEN=['selected','selectedCapability','selection','rank','ranking','priority','score','cost','latency','availability','provider','credentials','configuration','plan','steps','sequence','recipe','execution','observation','result','satisfaction','knowledgeUpdate','fallback','retry','schedule','runtimeState'];
function forbidden(v){if(Array.isArray(v))return v.some(forbidden);if(!obj(v))return false;return Object.entries(v).some(([k,x])=>FORBIDDEN.includes(k)||forbidden(x))}
function candidate(c){if(!obj(c))fail('INVALID_CAPABILITY_CANDIDATE','capabilityCandidate must be an object.');if(forbidden(c))fail('INVALID_CAPABILITY_CANDIDATE','capabilityCandidate contains forbidden downstream fields.');if(typeof c.capabilityRef!=='string'||!c.capabilityRef.trim())fail('INVALID_CAPABILITY_CANDIDATE','capabilityRef is required.');if(!TYPES.includes(c.capabilityType))fail('INVALID_CAPABILITY_CANDIDATE','capabilityType is invalid.');if(!obj(c.constraints)||!obj(c.metadata)||c.metadata.version!=='1.0'||!obj(c.extensions))fail('INVALID_CAPABILITY_CANDIDATE','constraints, metadata.version and extensions are required.');return{capabilityRef:c.capabilityRef,capabilityType:c.capabilityType,supportedDesignTypes:strings(c.supportedDesignTypes,'supportedDesignTypes'),supportedKnowledgeLayers:strings(c.supportedKnowledgeLayers,'supportedKnowledgeLayers'),supportedOutputTopologies:strings(c.supportedOutputTopologies,'supportedOutputTopologies'),supportedPrerequisiteModes:strings(c.supportedPrerequisiteModes,'supportedPrerequisiteModes',false),supportedObligations:strings(c.supportedObligations,'supportedObligations'),constraints:{...c.constraints},metadata:{version:'1.0'},extensions:{...c.extensions}}}
function buildKnowledgeAcquisitionCapabilityMatch(input={}){if(!obj(input))fail('INVALID_KNOWLEDGE_ACQUISITION_CAPABILITY_MATCH_INPUT','Input must be an object.');const design=input.design;const dv=validateKnowledgeAcquisitionDesign(design);if(!dv.valid)fail('INVALID_KNOWLEDGE_ACQUISITION_DESIGN',dv.errors.join(' | '),dv);const c=candidate(input.capabilityCandidate);const reasons=[];const insufficient=[];const designTypeSupported=c.supportedDesignTypes.includes(design.designType);if(!designTypeSupported)reasons.push('unsupported_design_type');const knowledgeLayerSupported=c.supportedKnowledgeLayers.includes(design.targetKnowledge.knowledgeLayer);if(!knowledgeLayerSupported)reasons.push('unsupported_knowledge_layer');const required=set(design.capabilityObligations),satisfied=required.filter(x=>c.supportedObligations.includes(x)),unsatisfied=required.filter(x=>!c.supportedObligations.includes(x));for(const x of unsatisfied)reasons.push(`missing_required_obligation:${x}`);const outputTopologySupported=c.supportedOutputTopologies.includes(design.solutionShape.outputTopology);if(!outputTopologySupported)reasons.push('unsupported_output_topology');let prerequisiteTopologySupported=null;if(c.supportedPrerequisiteModes===null)insufficient.push('insufficient_candidate_information:supportedPrerequisiteModes');else{prerequisiteTopologySupported=c.supportedPrerequisiteModes.includes(design.solutionShape.prerequisiteTopology.mode);if(!prerequisiteTopologySupported)reasons.push('unsupported_prerequisite_mode')}const constraintReasons=[];const constraintCompatible=constraintReasons.length===0;const eligible=designTypeSupported&&knowledgeLayerSupported;const explicit=reasons.length>0;const compatibilityState=explicit?'incompatible':insufficient.length?'indeterminate':'compatible';const allReasons=set([...reasons,...insufficient,...constraintReasons]);const sourceDesignRef=`knowledgeAcquisitionDesign:${design.id}`;const semantic={sourceDesignRef,candidateCapabilityRef:c.capabilityRef,compatibilityState,candidateEligibility:{eligible,reasons:set(reasons.filter(x=>x==='unsupported_design_type'||x==='unsupported_knowledge_layer'))},obligationCompatibility:{satisfiedObligations:satisfied,unsatisfiedObligations:unsatisfied},topologyCompatibility:{outputTopologySupported,prerequisiteTopologySupported},constraintCompatibility:{compatible:constraintCompatible,reasons:constraintReasons},reasons:allReasons};const out={id:'',type:'knowledge_acquisition_capability_match',...semantic,traceability:{sourceRequirementRef:design.sourceRequirementRef,...design.traceability},metadata:{contractVersion:'1.0',matchingStrategyVersion:'1.0',readOnly:true},extensions:{}};out.id=calculateKnowledgeAcquisitionCapabilityMatchId(out);const v=validateKnowledgeAcquisitionCapabilityMatch(out);if(!v.valid)fail('INVALID_GENERATED_KNOWLEDGE_ACQUISITION_CAPABILITY_MATCH',v.errors.join(' | '),v);return deepFreezeKnowledgeAcquisitionArtifact(out)}
module.exports={buildKnowledgeAcquisitionCapabilityMatch};
