const crypto=require('crypto');
const {validateKnowledgeAcquisitionRequirement}=require('./validateKnowledgeAcquisitionRequirement');
const {validateKnowledgeAcquisitionStrategy}=require('./validateKnowledgeAcquisitionStrategy');
const {validateKnowledgeAcquisitionNeed}=require('./validateKnowledgeAcquisitionNeed');
const {validateKnowledgeOpportunity}=require('./validateKnowledgeOpportunity');
const {validateKnowledgeCoverage}=require('./validateKnowledgeCoverage');
const {validatePersonKnowledgeMatrix}=require('./validatePersonKnowledgeMatrix');
const {validateKnowledgeAcquisitionDesign}=require('./validateKnowledgeAcquisitionDesign');
const {calculateKnowledgeAcquisitionDesignId}=require('./knowledgeAcquisitionDeclarativeIdentity');
const {deepFreezeKnowledgeAcquisitionArtifact}=require('./knowledgeAcquisitionImmutability');
function obj(v){return v&&typeof v==='object'&&!Array.isArray(v)}function clone(v){if(Array.isArray(v))return v.map(clone);if(obj(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clone(x)]));return v}function stable(v){if(Array.isArray(v))return `[${v.map(stable).join(',')}]`;if(obj(v))return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;return JSON.stringify(v)}function hash(v){return crypto.createHash('sha256').update(stable(v)).digest('hex')}function fail(code,message,details){const e=new Error(message);e.code=code;if(details)e.details=details;throw e}function validate(label,value,fn,code){const v=fn(value);if(!v.valid)fail(code,`${label}: ${v.errors.join(' | ')}`,v)}
function buildKnowledgeAcquisitionDesign(input={}){if(!obj(input))fail('INVALID_KNOWLEDGE_ACQUISITION_DESIGN_INPUT','Input must be an object.');const requirement=input.requirement,context=input.resolvedContext;if(!obj(context))fail('INVALID_RESOLVED_CONTEXT','resolvedContext must be an object.');const {strategy,need,opportunity,coverage,personKnowledgeMatrix}=context;validate('requirement',requirement,validateKnowledgeAcquisitionRequirement,'INVALID_KNOWLEDGE_ACQUISITION_REQUIREMENT');validate('strategy',strategy,validateKnowledgeAcquisitionStrategy,'INVALID_KNOWLEDGE_ACQUISITION_STRATEGY');validate('need',need,validateKnowledgeAcquisitionNeed,'INVALID_KNOWLEDGE_ACQUISITION_NEED');validate('opportunity',opportunity,validateKnowledgeOpportunity,'INVALID_KNOWLEDGE_OPPORTUNITY');validate('coverage',coverage,validateKnowledgeCoverage,'INVALID_KNOWLEDGE_COVERAGE');validate('personKnowledgeMatrix',personKnowledgeMatrix,validatePersonKnowledgeMatrix,'INVALID_PERSON_KNOWLEDGE_MATRIX');
 const expected={sourceStrategyRef:`knowledgeAcquisitionStrategy:${strategy.id}`,sourceNeedRef:`knowledgeAcquisitionNeed:${need.id}`,sourceOpportunityRef:`knowledgeOpportunity:${opportunity.id}`,sourceCoverageRef:`knowledgeCoverage:${coverage.id}`,sourcePersonKnowledgeMatrixRef:`personKnowledgeMatrix:${personKnowledgeMatrix.id}`};const mismatches=[];if(requirement.sourceStrategyRef!==expected.sourceStrategyRef)mismatches.push('Requirement.sourceStrategyRef');if(strategy.sourceNeedRef!==expected.sourceNeedRef)mismatches.push('Strategy.sourceNeedRef');if(need.sourceOpportunityRef!==expected.sourceOpportunityRef)mismatches.push('Need.sourceOpportunityRef');if(opportunity.sourceCoverageRef!==expected.sourceCoverageRef)mismatches.push('Opportunity.sourceCoverageRef');if(coverage.sourceMatrixRef!==expected.sourcePersonKnowledgeMatrixRef)mismatches.push('Coverage.sourceMatrixRef');if(requirement.sourceNeedRef!==strategy.sourceNeedRef||requirement.sourceOpportunityRef!==strategy.sourceOpportunityRef||requirement.sourceCoverageRef!==strategy.sourceCoverageRef||strategy.sourceOpportunityRef!==need.sourceOpportunityRef||strategy.sourceCoverageRef!==need.sourceCoverageRef||need.sourceCoverageRef!==opportunity.sourceCoverageRef)mismatches.push('transitive traceability');if(mismatches.length)fail('KNOWLEDGE_ACQUISITION_DESIGN_CAUSAL_MISMATCH',`Causal context mismatch: ${mismatches.join(', ')}.`,{mismatches});
 const elementary=requirement.requirementType==='elementary_knowledge_availability_required';const designType=elementary?'elementary_acquisition_design':'derived_acquisition_design';const targetRef=`${requirement.scope}:${requirement.scopeRef}`;let prerequisites=[];if(!elementary){if(requirement.scope==='dimension'){const entry=coverage.dimensionCoverage.find(x=>x.dimensionId===requirement.scopeRef);prerequisites=entry?entry.elementaryCoverage.map(x=>x.stateRef):[]}else{const entry=coverage.capabilityCoverage.find(x=>x.capabilityId===requirement.scopeRef);prerequisites=entry?entry.stateRefs:[];}prerequisites=[...new Set(prerequisites)].sort();if(!prerequisites.length)fail('MISSING_DERIVED_DESIGN_PREREQUISITES','Derived design requires prerequisite knowledge references.');}
 const solutionShape=elementary?{outputTopology:'elementary_knowledge_contribution_set',contributionRequirements:[{requirementType:'primary_knowledge_contribution',minimumCount:1,distinctness:'not_required'}],prerequisiteTopology:{mode:'none',prerequisiteKnowledgeUnitRefs:[]}}:{outputTopology:'derived_knowledge_composition',contributionRequirements:[{requirementType:'derived_knowledge_output',minimumCount:1,distinctness:'not_required'}],prerequisiteTopology:{mode:'all_required',prerequisiteKnowledgeUnitRefs:prerequisites}};const capabilityObligations=(elementary?['must_preserve_source_traceability','must_produce_elementary_contribution']:['must_preserve_source_traceability','must_produce_derived_output','must_support_prerequisite_composition']).sort();const targetKnowledge={knowledgeLayer:requirement.requiredKnowledgeLayer,scope:requirement.scope,scopeRef:requirement.scopeRef,knowledgeUnitRefs:[targetRef]};const sourceRequirementRef=`knowledgeAcquisitionRequirement:${requirement.id}`;const traceability={sourceStrategyRef:requirement.sourceStrategyRef,sourceNeedRef:requirement.sourceNeedRef,sourceOpportunityRef:requirement.sourceOpportunityRef,sourceCoverageRef:requirement.sourceCoverageRef,sourcePersonKnowledgeMatrixRef:coverage.sourceMatrixRef};const out={id:'',designVersion:'1.0',type:'knowledge_acquisition_design',designType,sourceRequirementType:requirement.requirementType,sourceRequirementRef,targetKnowledge,solutionShape,capabilityObligations,traceability,provenance:{type:'knowledge_acquisition_design_derivation',producerVersion:'1.0',deterministic:true,interpretive:false},dependencyRefs:[...new Set([sourceRequirementRef,...Object.values(traceability)])].sort(),metadata:{contractVersion:'1.0',designStrategyVersion:'1.0',readOnly:true},extensions:obj(input.extensions)?clone(input.extensions):{}};out.id=calculateKnowledgeAcquisitionDesignId(out);const v=validateKnowledgeAcquisitionDesign(out);if(!v.valid)fail('INVALID_GENERATED_KNOWLEDGE_ACQUISITION_DESIGN',v.errors.join(' | '),v);return deepFreezeKnowledgeAcquisitionArtifact(out)}
module.exports={buildKnowledgeAcquisitionDesign};
