const crypto=require('crypto');
const {validateKnowledgeOpportunity}=require('./validateKnowledgeOpportunity');
const {validateKnowledgeAcquisitionNeed}=require('./validateKnowledgeAcquisitionNeed');
const {calculateKnowledgeAcquisitionNeedId}=require('./knowledgeAcquisitionDeclarativeIdentity');
const {deepFreezeKnowledgeAcquisitionArtifact}=require('./knowledgeAcquisitionImmutability');
function obj(v){return v&&typeof v==='object'&&!Array.isArray(v)}
function clone(v){if(Array.isArray(v))return v.map(clone);if(obj(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clone(x)]));return v}
function stable(v){if(Array.isArray(v))return `[${v.map(stable).join(',')}]`;if(obj(v))return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;return JSON.stringify(v)}
function hash(v){return crypto.createHash('sha256').update(stable(v)).digest('hex')}
function fail(code,v){const e=new Error(v.errors.join(' | '));e.code=code;e.details=v;throw e}
function buildKnowledgeAcquisitionNeed(opportunity,options={}){const ov=validateKnowledgeOpportunity(opportunity);if(!ov.valid)fail('INVALID_KNOWLEDGE_OPPORTUNITY',ov);const mapping=opportunity.opportunityType==='elementary_layer_only'?{needType:'derived_knowledge_required',layer:'derived',reason:'DERIVED_KNOWLEDGE_REQUIRED'}:{needType:'elementary_knowledge_required',layer:'elementary',reason:'ELEMENTARY_KNOWLEDGE_REQUIRED'};const out={id:'',needVersion:'1.0',needType:mapping.needType,sourceOpportunityType:opportunity.opportunityType,scope:opportunity.scope,scopeRef:opportunity.scopeRef,requiredKnowledgeLayer:mapping.layer,reasonCodes:[mapping.reason,'KNOWLEDGE_COMPOSITION_INCOMPLETE'].sort(),sourceOpportunityRef:`knowledgeOpportunity:${opportunity.id}`,sourceCoverageRef:opportunity.sourceCoverageRef,provenance:{type:'knowledge_acquisition_need_evaluation',producerVersion:'1.0',deterministic:true,interpretive:false},dependencyRefs:[...new Set([`knowledgeOpportunity:${opportunity.id}`,opportunity.sourceCoverageRef,...opportunity.dependencyRefs])].sort(),metadata:{contractVersion:'1.0',evaluationStrategyVersion:'1.0',readOnly:true},extensions:obj(options.extensions)?clone(options.extensions):{}};out.id=calculateKnowledgeAcquisitionNeedId(out);const v=validateKnowledgeAcquisitionNeed(out);if(!v.valid)fail('INVALID_GENERATED_KNOWLEDGE_ACQUISITION_NEED',v);return deepFreezeKnowledgeAcquisitionArtifact(out)}
module.exports={buildKnowledgeAcquisitionNeed};
