const crypto=require('crypto');
const {validateKnowledgeCoverage}=require('./validateKnowledgeCoverage');
const {buildKnowledgeCoverageQuery}=require('./buildKnowledgeCoverageQuery');
const {queryKnowledgeCoverage}=require('./queryKnowledgeCoverage');
const {validateKnowledgeCoverageQueryResult}=require('./validateKnowledgeCoverageQueryResult');
const {buildKnowledgeOpportunity}=require('./buildKnowledgeOpportunity');
const {validateKnowledgeOpportunityCollection}=require('./validateKnowledgeOpportunityCollection');
function obj(v){return v&&typeof v==='object'&&!Array.isArray(v)}function clone(v){if(Array.isArray(v))return v.map(clone);if(obj(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clone(x)]));return v}function stable(v){if(Array.isArray(v))return `[${v.map(stable).join(',')}]`;if(obj(v))return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;return JSON.stringify(v)}function hash(v){return crypto.createHash('sha256').update(stable(v)).digest('hex')}function fail(code,v){const e=new Error(v.errors.join(' | '));e.code=code;e.details=v;throw e}
function evaluateKnowledgeOpportunities(coverage,queryOrResult=null,options={}){const cv=validateKnowledgeCoverage(coverage);if(!cv.valid)fail('INVALID_KNOWLEDGE_COVERAGE',cv);let dimensions=coverage.dimensionCoverage.map(clone),capabilities=coverage.capabilityCoverage.map(clone),appliedQuery=null,dependencyRefs=[`knowledgeCoverage:${coverage.id}`];if(queryOrResult){const rv=validateKnowledgeCoverageQueryResult(queryOrResult);if(rv.valid){dimensions=queryOrResult.dimensionCoverage.map(clone);capabilities=queryOrResult.capabilityCoverage.map(clone);appliedQuery=clone(queryOrResult.filters);dependencyRefs.push(`knowledgeCoverageQueryResult:${queryOrResult.coverageRef}`)}else{appliedQuery=buildKnowledgeCoverageQuery(queryOrResult);const r=queryKnowledgeCoverage(coverage,appliedQuery);dimensions=r.dimensionCoverage;capabilities=r.capabilityCoverage;dependencyRefs.push(`knowledgeCoverageQuery:${hash(appliedQuery).slice(0,24)}`)}}
 const ops=[];for(const d of dimensions){if(d.coverageState==='elementary_only')ops.push(buildKnowledgeOpportunity({opportunityType:'elementary_layer_only',scope:'dimension',scopeRef:d.dimensionId,coverageState:d.coverageState,knowledgeLayers:['elementary'],reasonCodes:['NO_DERIVED_LAYER','SINGLE_LAYER_COVERAGE'],sourceCoverageRef:`knowledgeCoverage:${coverage.id}`,dependencyRefs}));else if(d.coverageState==='derived_only')ops.push(buildKnowledgeOpportunity({opportunityType:'derived_layer_only',scope:'dimension',scopeRef:d.dimensionId,coverageState:d.coverageState,knowledgeLayers:['derived'],reasonCodes:['NO_ELEMENTARY_LAYER','SINGLE_LAYER_COVERAGE'],sourceCoverageRef:`knowledgeCoverage:${coverage.id}`,dependencyRefs}))}
 for(const c of capabilities){if(c.coverageState==='available')ops.push(buildKnowledgeOpportunity({opportunityType:'derived_layer_only',scope:'capability',scopeRef:c.capabilityId,coverageState:c.coverageState,knowledgeLayers:['derived'],reasonCodes:['NO_ELEMENTARY_LAYER','SINGLE_LAYER_COVERAGE'],sourceCoverageRef:`knowledgeCoverage:${coverage.id}`,dependencyRefs}))}
 ops.sort((a,b)=>a.scope.localeCompare(b.scope)||a.scopeRef.localeCompare(b.scopeRef)||a.opportunityType.localeCompare(b.opportunityType)||a.id.localeCompare(b.id));const by={};for(const o of ops)by[o.opportunityType]=(by[o.opportunityType]||0)+1;const identity={sourceCoverageRef:`knowledgeCoverage:${coverage.id}`,appliedQuery,opportunityIds:ops.map(o=>o.id),collectionVersion:'1.0'};const collection={id:`knowledgeOpportunityCollection_${hash(identity).slice(0,32)}`,collectionVersion:'1.0',sourceCoverageRef:`knowledgeCoverage:${coverage.id}`,appliedQuery:clone(appliedQuery),opportunities:ops,summary:{totalOpportunities:ops.length,dimensionOpportunityCount:ops.filter(o=>o.scope==='dimension').length,capabilityOpportunityCount:ops.filter(o=>o.scope==='capability').length,byOpportunityType:by,empty:ops.length===0},provenance:{type:'knowledge_opportunity_collection_evaluation',producerVersion:'1.0',deterministic:true,interpretive:false},dependencyRefs:[...new Set(dependencyRefs)].sort(),metadata:{contractVersion:'1.0',evaluationStrategyVersion:'1.0',readOnly:true},extensions:obj(options.extensions)?clone(options.extensions):{}};const v=validateKnowledgeOpportunityCollection(collection);if(!v.valid)fail('INVALID_GENERATED_KNOWLEDGE_OPPORTUNITY_COLLECTION',v);return collection}
module.exports={evaluateKnowledgeOpportunities};
