const {buildKnowledgeAcquisitionStrategy}=require('./buildKnowledgeAcquisitionStrategy');
const {evaluateKnowledgeAcquisitionRequirements}=require('./evaluateKnowledgeAcquisitionRequirements');
const {buildKnowledgeAcquisitionRequirementQuery}=require('./buildKnowledgeAcquisitionRequirementQuery');
const {validateKnowledgeAcquisitionRequirementQuery}=require('./validateKnowledgeAcquisitionRequirementQuery');
const {queryKnowledgeAcquisitionRequirements}=require('./queryKnowledgeAcquisitionRequirements');
const {validateKnowledgeAcquisitionRequirementQueryResult}=require('./validateKnowledgeAcquisitionRequirementQueryResult');
function need(id,type,scope='dimension'){const e=type==='elementary_knowledge_required';return{id:`need_${id}`,needVersion:'1.0',needType:type,sourceOpportunityType:e?'derived_layer_only':'elementary_layer_only',scope,scopeRef:id,requiredKnowledgeLayer:e?'elementary':'derived',reasonCodes:[e?'ELEMENTARY_KNOWLEDGE_REQUIRED':'DERIVED_KNOWLEDGE_REQUIRED','KNOWLEDGE_COMPOSITION_INCOMPLETE'].sort(),sourceOpportunityRef:`knowledgeOpportunity:${id}`,sourceCoverageRef:'knowledgeCoverage:query-health',provenance:{type:'knowledge_acquisition_need_evaluation',producerVersion:'1.0',deterministic:true,interpretive:false},dependencyRefs:[`knowledgeOpportunity:${id}`,'knowledgeCoverage:query-health'].sort(),metadata:{contractVersion:'1.0',evaluationStrategyVersion:'1.0',readOnly:true},extensions:{deep:{v:1}}}}
function strategyCollection(strategies){const a=[...strategies].sort((x,y)=>x.scope.localeCompare(y.scope)||x.scopeRef.localeCompare(y.scopeRef)||x.strategyType.localeCompare(y.strategyType)||x.id.localeCompare(y.id)),by={};a.forEach(s=>by[s.strategyType]=(by[s.strategyType]||0)+1);return{id:'strategy_collection_query_health',collectionVersion:'1.0',sourceNeedCollectionRef:'knowledgeAcquisitionNeedCollection:query-health',strategies:a,summary:{totalStrategies:a.length,elementaryKnowledgeAcquisitionCount:a.filter(s=>s.strategyType==='elementary_knowledge_acquisition').length,derivedKnowledgeCompositionCount:a.filter(s=>s.strategyType==='derived_knowledge_composition').length,dimensionStrategyCount:a.filter(s=>s.scope==='dimension').length,capabilityStrategyCount:a.filter(s=>s.scope==='capability').length,byStrategyType:by,empty:a.length===0},provenance:{type:'knowledge_acquisition_strategy_collection_evaluation',producerVersion:'1.0',deterministic:true,interpretive:false},dependencyRefs:['knowledgeAcquisitionNeedCollection:query-health'],metadata:{contractVersion:'1.0',evaluationStrategyVersion:'1.0',readOnly:true},extensions:{}}}
function healthKnowledgeAcquisitionRequirementQuery(){const s1=buildKnowledgeAcquisitionStrategy(need('a','elementary_knowledge_required')),s2=buildKnowledgeAcquisitionStrategy(need('b','derived_knowledge_required','capability'));const c=evaluateKnowledgeAcquisitionRequirements(strategyCollection([s2,s1]));const before=JSON.stringify(c),q=buildKnowledgeAcquisitionRequirementQuery({scope:'dimension',requiredKnowledgeLayer:'elementary'}),qb=JSON.stringify(q),r=queryKnowledgeAcquisitionRequirements(c,q),empty=queryKnowledgeAcquisitionRequirements(c,{scopeRef:'missing'}),again=queryKnowledgeAcquisitionRequirements(c,q),ec=evaluateKnowledgeAcquisitionRequirements(strategyCollection([])),er=queryKnowledgeAcquisitionRequirements(ec,{scope:'dimension'});r.filters.scope='capability';r.requirements[0].extensions.changed=true;return{ok:validateKnowledgeAcquisitionRequirementQuery(q).valid&&validateKnowledgeAcquisitionRequirementQueryResult(queryKnowledgeAcquisitionRequirements(c,q)).valid&&r.summary.totalRequirements===1&&empty.summary.empty&&er.summary.empty&&JSON.stringify(c)===before&&JSON.stringify(q)===qb&&JSON.stringify(queryKnowledgeAcquisitionRequirements(c,q))===JSON.stringify(again),details:{matched:r.summary.totalRequirements,emptyValid:empty.summary.empty}}}
module.exports={healthKnowledgeAcquisitionRequirementQuery};
