const {buildKnowledgeAcquisitionStrategy}=require('./buildKnowledgeAcquisitionStrategy');
const {buildKnowledgeAcquisitionRequirement}=require('./buildKnowledgeAcquisitionRequirement');
const {validateKnowledgeAcquisitionRequirement}=require('./validateKnowledgeAcquisitionRequirement');
const {evaluateKnowledgeAcquisitionRequirements}=require('./evaluateKnowledgeAcquisitionRequirements');
const {validateKnowledgeAcquisitionRequirementCollection}=require('./validateKnowledgeAcquisitionRequirementCollection');
function need(id,type,scope='dimension'){const elementary=type==='elementary_knowledge_required';return{id:`need_${id}`,needVersion:'1.0',needType:type,sourceOpportunityType:elementary?'derived_layer_only':'elementary_layer_only',scope,scopeRef:id,requiredKnowledgeLayer:elementary?'elementary':'derived',reasonCodes:[elementary?'ELEMENTARY_KNOWLEDGE_REQUIRED':'DERIVED_KNOWLEDGE_REQUIRED','KNOWLEDGE_COMPOSITION_INCOMPLETE'].sort(),sourceOpportunityRef:`knowledgeOpportunity:${id}`,sourceCoverageRef:'knowledgeCoverage:health',provenance:{type:'knowledge_acquisition_need_evaluation',producerVersion:'1.0',deterministic:true,interpretive:false},dependencyRefs:[`knowledgeOpportunity:${id}`,'knowledgeCoverage:health'].sort(),metadata:{contractVersion:'1.0',evaluationStrategyVersion:'1.0',readOnly:true},extensions:{nested:{value:1}}}}
function collection(strategies){const ordered=[...strategies].sort((a,b)=>a.scope.localeCompare(b.scope)||a.scopeRef.localeCompare(b.scopeRef)||a.strategyType.localeCompare(b.strategyType)||a.id.localeCompare(b.id));const by={};for(const s of ordered)by[s.strategyType]=(by[s.strategyType]||0)+1;return{id:'health_strategy_collection',collectionVersion:'1.0',sourceNeedCollectionRef:'knowledgeAcquisitionNeedCollection:health',strategies:ordered,summary:{totalStrategies:ordered.length,elementaryKnowledgeAcquisitionCount:ordered.filter(s=>s.strategyType==='elementary_knowledge_acquisition').length,derivedKnowledgeCompositionCount:ordered.filter(s=>s.strategyType==='derived_knowledge_composition').length,dimensionStrategyCount:ordered.filter(s=>s.scope==='dimension').length,capabilityStrategyCount:ordered.filter(s=>s.scope==='capability').length,byStrategyType:by,empty:ordered.length===0},provenance:{type:'knowledge_acquisition_strategy_collection_evaluation',producerVersion:'1.0',deterministic:true,interpretive:false},dependencyRefs:['knowledgeAcquisitionNeedCollection:health'],metadata:{contractVersion:'1.0',evaluationStrategyVersion:'1.0',readOnly:true},extensions:{}}}
function healthKnowledgeAcquisitionRequirement(){const a=buildKnowledgeAcquisitionStrategy(need('a','elementary_knowledge_required'),{extensions:{nested:{v:1}}}),b=buildKnowledgeAcquisitionStrategy(need('b','derived_knowledge_required','capability'));const input=collection([b,a]),before=JSON.stringify(input),ra=buildKnowledgeAcquisitionRequirement(a,{extensions:{deep:{x:1}}}),rb=buildKnowledgeAcquisitionRequirement(b),result=evaluateKnowledgeAcquisitionRequirements(input),empty=evaluateKnowledgeAcquisitionRequirements(collection([])),again=evaluateKnowledgeAcquisitionRequirements(input);ra.extensions.deep.x=9;return{ok:validateKnowledgeAcquisitionRequirement(ra).valid&&validateKnowledgeAcquisitionRequirement(rb).valid&&validateKnowledgeAcquisitionRequirementCollection(result).valid&&result.requirements.length===2&&result.requirements[0].sourceStrategyRef!==result.requirements[1].sourceStrategyRef&&result.requirements.some(r=>r.requirementType==='elementary_knowledge_availability_required'&&r.requiredKnowledgeLayer==='elementary')&&result.requirements.some(r=>r.requirementType==='derived_knowledge_availability_required'&&r.requiredKnowledgeLayer==='derived')&&empty.summary.empty&&JSON.stringify(result)===JSON.stringify(again)&&JSON.stringify(input)===before&&a.extensions.nested.v===1&&!Object.keys(result).some(k=>['status','satisfied','plan','execution'].includes(k)),details:{totalRequirements:result.summary.totalRequirements,emptyValid:empty.summary.empty}}}
module.exports={healthKnowledgeAcquisitionRequirement};
