const {validateKnowledgeAcquisitionStrategy}=require('./validateKnowledgeAcquisitionStrategy');
const {validateKnowledgeAcquisitionStrategyQuery}=require('./validateKnowledgeAcquisitionStrategyQuery');
const TOP=['collectionRef','filters','strategies','summary','metadata','extensions','sourceNeedCollectionRef','sourceNeedQueryResultRef','sourceOpportunityCollectionRef'];
const FORBIDDEN=['score','scoring','rank','ranking','priority','prioritization','weight','weighting','importance','urgency','recommendation','recommendedAction','recommendedStrategy','nextBestAction','bestStrategy','selectedStrategy','preferredStrategy','alternativeStrategies','plan','execution','method','channel','sourceSelection','question','questions','prompt','sequence','schedule','runtimeAction','candidateAssessment','personAssessment','potentialScore','potentialClass','prediction','probability'];
function obj(v){return v&&typeof v==='object'&&!Array.isArray(v)}function str(v){return typeof v==='string'&&v.trim().length>0}
function matches(s,f){return(!f.strategyType||s.strategyType===f.strategyType)&&(!f.sourceNeedType||s.sourceNeedType===f.sourceNeedType)&&(!f.scope||s.scope===f.scope)&&(!f.scopeRef||s.scopeRef===f.scopeRef)&&(!f.targetKnowledgeLayer||s.targetKnowledgeLayer===f.targetKnowledgeLayer)&&(!f.reasonCode||s.reasonCodes.includes(f.reasonCode))&&(!f.sourceNeedRef||s.sourceNeedRef===f.sourceNeedRef)&&(!f.sourceOpportunityRef||s.sourceOpportunityRef===f.sourceOpportunityRef)&&(!f.sourceCoverageRef||s.sourceCoverageRef===f.sourceCoverageRef)}
function forbidden(v){if(Array.isArray(v))return v.some(forbidden);if(!obj(v))return false;return Object.entries(v).some(([k,x])=>FORBIDDEN.includes(k)||forbidden(x))}
function validateKnowledgeAcquisitionStrategyQueryResult(r){const errors=[],warnings=[];if(!obj(r))return{valid:false,errors:['KnowledgeAcquisitionStrategyQueryResult must be an object.'],warnings};for(const k of Object.keys(r))if(!TOP.includes(k))errors.push(`Unknown property: ${k}.`);for(const k of ['collectionRef','filters','strategies','summary','metadata','extensions'])if(!(k in r))errors.push(`Missing property: ${k}.`);if(!str(r.collectionRef)||!r.collectionRef.startsWith('knowledgeAcquisitionStrategyCollection:'))errors.push('collectionRef is invalid.');for(const k of ['sourceNeedCollectionRef','sourceNeedQueryResultRef','sourceOpportunityCollectionRef'])if(k in r&&!str(r[k]))errors.push(`${k} is invalid.`);const qv=validateKnowledgeAcquisitionStrategyQuery(r.filters);if(!qv.valid)errors.push(`filters are invalid: ${qv.errors.join(' | ')}`);if(!Array.isArray(r.strategies))errors.push('strategies must be an array.');else{r.strategies.forEach((s,i)=>{const v=validateKnowledgeAcquisitionStrategy(s);if(!v.valid)errors.push(...v.errors.map(e=>`strategies[${i}].${e}`));if(!matches(s,r.filters||{}))errors.push(`strategies[${i}] does not match all filters.`)});const sorted=[...r.strategies].sort((a,b)=>a.scope.localeCompare(b.scope)||a.scopeRef.localeCompare(b.scopeRef)||a.strategyType.localeCompare(b.strategyType)||a.id.localeCompare(b.id));if(JSON.stringify(sorted)!==JSON.stringify(r.strategies))errors.push('strategies are not canonically ordered.');}const ss=Array.isArray(r.strategies)?r.strategies:[];if(!obj(r.summary))errors.push('summary must be an object.');else{const expected={totalStrategies:ss.length,elementaryKnowledgeAcquisitionCount:ss.filter(s=>s.strategyType==='elementary_knowledge_acquisition').length,derivedKnowledgeCompositionCount:ss.filter(s=>s.strategyType==='derived_knowledge_composition').length,dimensionStrategyCount:ss.filter(s=>s.scope==='dimension').length,capabilityStrategyCount:ss.filter(s=>s.scope==='capability').length,empty:ss.length===0};for(const [k,v] of Object.entries(expected))if(r.summary[k]!==v)errors.push(`summary.${k} is inconsistent.`);if(!obj(r.summary.byStrategyType))errors.push('summary.byStrategyType is invalid.');else{const by={};for(const s of ss)by[s.strategyType]=(by[s.strategyType]||0)+1;if(JSON.stringify(by)!==JSON.stringify(r.summary.byStrategyType))errors.push('summary.byStrategyType is inconsistent.')}}if(!obj(r.metadata)||r.metadata.contractVersion!=='1.0'||r.metadata.queryStrategyVersion!=='1.0'||r.metadata.readOnly!==true)errors.push('metadata is invalid.');if(!obj(r.extensions))errors.push('extensions must be an object.');if(forbidden(r))errors.push('Query result contains forbidden evaluative or operational fields.');try{JSON.stringify(r)}catch{errors.push('KnowledgeAcquisitionStrategyQueryResult must be serializable.')}return{valid:errors.length===0,errors,warnings}}
module.exports={validateKnowledgeAcquisitionStrategyQueryResult};
