const {validateKnowledgeOpportunity}=require('./validateKnowledgeOpportunity');
const {validateKnowledgeOpportunityQuery}=require('./validateKnowledgeOpportunityQuery');
const TOP=['collectionRef','filters','opportunities','summary','metadata','extensions'];
function obj(v){return v&&typeof v==='object'&&!Array.isArray(v)}
function matches(o,f){return(!f.opportunityType||o.opportunityType===f.opportunityType)&&(!f.scope||o.scope===f.scope)&&(!f.scopeRef||o.scopeRef===f.scopeRef)&&(!f.coverageState||o.coverageState===f.coverageState)&&(!f.knowledgeLayer||o.knowledgeLayers.includes(f.knowledgeLayer))&&(!f.reasonCode||o.reasonCodes.includes(f.reasonCode))&&(!f.sourceCoverageRef||o.sourceCoverageRef===f.sourceCoverageRef)}
function forbidden(v){if(Array.isArray(v))return v.some(forbidden);if(!obj(v))return false;return Object.entries(v).some(([k,x])=>['score','scoring','rank','ranking','priority','prioritization','weight','weighting','importance','urgency','recommendation','recommendedAction','nextBestAction','bestOpportunity','selectedOpportunity','question','questions','prompt','strategy','acquisitionStrategy','candidateAssessment','personAssessment','prediction','probability'].includes(k)||forbidden(x))}
function validateKnowledgeOpportunityQueryResult(r){const errors=[],warnings=[];if(!obj(r))return{valid:false,errors:['KnowledgeOpportunityQueryResult must be an object.'],warnings};for(const k of Object.keys(r))if(!TOP.includes(k))errors.push(`Unknown property: ${k}.`);for(const k of TOP)if(!(k in r))errors.push(`Missing property: ${k}.`);if(typeof r.collectionRef!=='string'||!r.collectionRef.startsWith('knowledgeOpportunityCollection:'))errors.push('collectionRef is invalid.');const qv=validateKnowledgeOpportunityQuery(r.filters);if(!qv.valid)errors.push(`filters are invalid: ${qv.errors.join(' | ')}`);if(!Array.isArray(r.opportunities))errors.push('opportunities must be an array.');else{r.opportunities.forEach((o,i)=>{const v=validateKnowledgeOpportunity(o);if(!v.valid)errors.push(...v.errors.map(e=>`opportunities[${i}].${e}`));if(!matches(o,r.filters||{}))errors.push(`opportunities[${i}] does not match all filters.`)});const sorted=[...r.opportunities].sort((a,b)=>a.scope.localeCompare(b.scope)||a.scopeRef.localeCompare(b.scopeRef)||a.opportunityType.localeCompare(b.opportunityType)||a.id.localeCompare(b.id));if(JSON.stringify(sorted)!==JSON.stringify(r.opportunities))errors.push('opportunities are not canonically ordered.');}
 const ops=Array.isArray(r.opportunities)?r.opportunities:[];if(!obj(r.summary))errors.push('summary must be an object.');else{if(r.summary.totalOpportunities!==ops.length||r.summary.dimensionOpportunityCount!==ops.filter(o=>o.scope==='dimension').length||r.summary.capabilityOpportunityCount!==ops.filter(o=>o.scope==='capability').length||r.summary.empty!==(ops.length===0)||!obj(r.summary.byOpportunityType))errors.push('summary is invalid or inconsistent.');const by={};for(const o of ops)by[o.opportunityType]=(by[o.opportunityType]||0)+1;if(JSON.stringify(by)!==JSON.stringify(r.summary.byOpportunityType))errors.push('summary.byOpportunityType is inconsistent.');}
 if(!obj(r.metadata)||r.metadata.contractVersion!=='1.0'||r.metadata.queryStrategyVersion!=='1.0'||r.metadata.readOnly!==true)errors.push('metadata is invalid.');if(!obj(r.extensions))errors.push('extensions must be an object.');if(forbidden(r))errors.push('Query result contains forbidden evaluative or operational fields.');return{valid:errors.length===0,errors,warnings}}
module.exports={validateKnowledgeOpportunityQueryResult};
