const STRATEGY_TYPES=['elementary_knowledge_acquisition','derived_knowledge_composition'];
const NEED_TYPES=['elementary_knowledge_required','derived_knowledge_required'];
const SCOPES=['dimension','capability'];
const LAYERS=['elementary','derived'];
const REASONS=['ELEMENTARY_KNOWLEDGE_ACQUISITION_REQUIRED','DERIVED_KNOWLEDGE_COMPOSITION_REQUIRED'];
const FORBIDDEN=['score','scoring','rank','ranking','priority','prioritization','weight','weighting','importance','urgency','recommendation','recommendedAction','nextBestAction','bestStrategy','selectedStrategy','preferredStrategy','alternativeStrategies','question','questions','prompt','method','channel','sourceSelection','executionOrder','sequence','schedule','runtimeAction','candidateAssessment','personAssessment','potentialScore','potentialClass','prediction','probability','plan','execution'];
function obj(v){return v&&typeof v==='object'&&!Array.isArray(v)}function str(v){return typeof v==='string'&&v.trim().length>0}
function forbidden(v){if(Array.isArray(v))return v.some(forbidden);if(!obj(v))return false;return Object.entries(v).some(([k,x])=>FORBIDDEN.includes(k)||forbidden(x))}
function validateKnowledgeAcquisitionStrategy(s){const errors=[],warnings=[];const fields=['id','strategyVersion','strategyType','sourceNeedType','scope','scopeRef','targetKnowledgeLayer','reasonCodes','sourceNeedRef','sourceOpportunityRef','sourceCoverageRef','provenance','dependencyRefs','metadata','extensions'];if(!obj(s))return{valid:false,errors:['KnowledgeAcquisitionStrategy must be an object.'],warnings};for(const k of Object.keys(s))if(!fields.includes(k))errors.push(`${k} is not allowed.`);for(const k of fields)if(!(k in s))errors.push(`Missing property: ${k}.`);for(const k of ['id','scopeRef','sourceNeedRef','sourceOpportunityRef','sourceCoverageRef'])if(!str(s[k]))errors.push(`${k} is invalid.`);if(s.strategyVersion!=='1.0')errors.push('strategyVersion is invalid.');if(!STRATEGY_TYPES.includes(s.strategyType))errors.push('strategyType is invalid.');if(!NEED_TYPES.includes(s.sourceNeedType))errors.push('sourceNeedType is invalid.');if(!SCOPES.includes(s.scope))errors.push('scope is invalid.');if(!LAYERS.includes(s.targetKnowledgeLayer))errors.push('targetKnowledgeLayer is invalid.');if(!Array.isArray(s.reasonCodes)||!s.reasonCodes.length||!s.reasonCodes.every(x=>REASONS.includes(x))||new Set(s.reasonCodes).size!==s.reasonCodes.length)errors.push('reasonCodes are invalid.');if(s.sourceNeedType==='elementary_knowledge_required'&&(s.strategyType!=='elementary_knowledge_acquisition'||s.targetKnowledgeLayer!=='elementary'||!s.reasonCodes?.includes('ELEMENTARY_KNOWLEDGE_ACQUISITION_REQUIRED')))errors.push('elementary_knowledge_required mapping is inconsistent.');if(s.sourceNeedType==='derived_knowledge_required'&&(s.strategyType!=='derived_knowledge_composition'||s.targetKnowledgeLayer!=='derived'||!s.reasonCodes?.includes('DERIVED_KNOWLEDGE_COMPOSITION_REQUIRED')))errors.push('derived_knowledge_required mapping is inconsistent.');if(!obj(s.provenance)||s.provenance.type!=='knowledge_acquisition_strategy_evaluation'||s.provenance.deterministic!==true||s.provenance.interpretive!==false)errors.push('provenance is invalid.');if(!Array.isArray(s.dependencyRefs)||!s.dependencyRefs.every(str)||!s.dependencyRefs.includes(s.sourceNeedRef)||!s.dependencyRefs.includes(s.sourceOpportunityRef)||!s.dependencyRefs.includes(s.sourceCoverageRef))errors.push('dependencyRefs are invalid.');if(!obj(s.metadata)||s.metadata.contractVersion!=='1.0'||s.metadata.evaluationStrategyVersion!=='1.0'||s.metadata.readOnly!==true)errors.push('metadata is invalid.');if(!obj(s.extensions))errors.push('extensions must be an object.');if(forbidden(s))errors.push('KnowledgeAcquisitionStrategy contains forbidden evaluative or operational fields.');try{JSON.stringify(s)}catch{errors.push('KnowledgeAcquisitionStrategy must be serializable.')}return{valid:errors.length===0,errors,warnings}}
module.exports={validateKnowledgeAcquisitionStrategy,STRATEGY_TYPES,NEED_TYPES,SCOPES,LAYERS,REASONS};
