const {calculateKnowledgeAcquisitionDesignId}=require('./knowledgeAcquisitionDeclarativeIdentity');
const DESIGN_TYPES=['elementary_acquisition_design','derived_acquisition_design'];
const REQUIREMENT_TYPES=['elementary_knowledge_availability_required','derived_knowledge_availability_required'];
const LAYERS=['elementary','derived'];
const OUTPUT_TOPOLOGIES=['elementary_knowledge_contribution_set','derived_knowledge_composition'];
const CONTRIBUTION_TYPES=['primary_knowledge_contribution','derived_knowledge_output'];
const PREREQUISITE_MODES=['none','all_required'];
const CAPABILITY_OBLIGATIONS=['must_produce_elementary_contribution','must_preserve_source_traceability','must_support_prerequisite_composition','must_produce_derived_output'];
const AUTHORIZED_SEMANTIC_POLICIES=Object.freeze({
 'professional_semantic_policy:decision_accountability:v1':'decision_accountability',
 'professional_semantic_policy:quantified_outcome:v1':'quantified_outcome'
});
const AUTHORIZED_SEMANTIC_POLICY='professional_semantic_policy:decision_accountability:v1';
const TOP=['id','designVersion','type','designType','sourceRequirementType','sourceRequirementRef','semanticPolicyRef','targetKnowledge','solutionShape','capabilityObligations','traceability','provenance','dependencyRefs','metadata','extensions'];
const REQUIRED=TOP.filter(k=>k!=='semanticPolicyRef');
const TARGET=['knowledgeLayer','scope','scopeRef','knowledgeUnitRefs'];
const SHAPE=['outputTopology','contributionRequirements','prerequisiteTopology'];
const CONTRIBUTION=['requirementType','minimumCount','distinctness'];
const PREREQUISITE=['mode','prerequisiteKnowledgeUnitRefs'];
const TRACE=['sourceStrategyRef','sourceNeedRef','sourceOpportunityRef','sourceCoverageRef','sourcePersonKnowledgeMatrixRef'];
const FORBIDDEN=new Set(['plan','steps','sequence','priority','ranking','selectedCapability','capabilityId','selectedSource','sourceId','selectedMethod','method','channel','question','prompt','artifact','template','executionMode','runtimeState','status','progress','satisfaction','satisfied','fulfilled','resolved','result','observation','measurementResult','knowledgeUpdate','recipe','evaluator','algorithm','formula','execution','orchestration','completion']);
function obj(v){return v!==null&&typeof v==='object'&&!Array.isArray(v)}
function str(v){return typeof v==='string'&&v.trim().length>0}
function unknown(v,allowed,path,errors){if(obj(v))for(const k of Object.keys(v))if(!allowed.includes(k))errors.push(`${path}.${k} is not allowed.`)}
function sortedUnique(a){return Array.isArray(a)&&a.every(str)&&new Set(a).size===a.length&&JSON.stringify(a)===JSON.stringify([...a].sort())}
function forbidden(v){if(Array.isArray(v))return v.some(forbidden);if(!obj(v))return false;return Object.entries(v).some(([k,x])=>FORBIDDEN.has(k)||forbidden(x))}
function validateKnowledgeAcquisitionDesign(d){const errors=[],warnings=[];if(!obj(d))return{valid:false,errors:['KnowledgeAcquisitionDesign must be an object.'],warnings};unknown(d,TOP,'knowledgeAcquisitionDesign',errors);for(const k of REQUIRED)if(!(k in d))errors.push(`Missing property: ${k}.`);
 if(!str(d.id)||!d.id.startsWith('knowledgeAcquisitionDesign_'))errors.push('id is invalid.');if(d.designVersion!=='1.0')errors.push('designVersion is invalid.');if(d.type!=='knowledge_acquisition_design')errors.push('type is invalid.');if(!DESIGN_TYPES.includes(d.designType))errors.push('designType is invalid.');if(!REQUIREMENT_TYPES.includes(d.sourceRequirementType))errors.push('sourceRequirementType is invalid.');if(!str(d.sourceRequirementRef)||!d.sourceRequirementRef.startsWith('knowledgeAcquisitionRequirement:'))errors.push('sourceRequirementRef is invalid.');
 if(d.semanticPolicyRef!==undefined){const target=AUTHORIZED_SEMANTIC_POLICIES[d.semanticPolicyRef];if(!target)errors.push('semanticPolicyRef is not authorized.');if(target&&(d.designType!=='elementary_acquisition_design'||d.targetKnowledge?.knowledgeLayer!=='elementary'||d.targetKnowledge?.scope!=='dimension'||d.targetKnowledge?.scopeRef!==target))errors.push(`semanticPolicyRef is authorized only for elementary dimension:${target}.`);}
 if(!obj(d.targetKnowledge))errors.push('targetKnowledge must be an object.');else{unknown(d.targetKnowledge,TARGET,'targetKnowledge',errors);if(!LAYERS.includes(d.targetKnowledge.knowledgeLayer))errors.push('targetKnowledge.knowledgeLayer is invalid.');if(!['dimension','capability'].includes(d.targetKnowledge.scope))errors.push('targetKnowledge.scope is invalid.');if(!str(d.targetKnowledge.scopeRef))errors.push('targetKnowledge.scopeRef is invalid.');if(!sortedUnique(d.targetKnowledge.knowledgeUnitRefs)||d.targetKnowledge.knowledgeUnitRefs.length===0)errors.push('targetKnowledge.knowledgeUnitRefs are invalid.');}
 if(!obj(d.solutionShape))errors.push('solutionShape must be an object.');else{unknown(d.solutionShape,SHAPE,'solutionShape',errors);if(!OUTPUT_TOPOLOGIES.includes(d.solutionShape.outputTopology))errors.push('solutionShape.outputTopology is invalid.');if(!Array.isArray(d.solutionShape.contributionRequirements)||d.solutionShape.contributionRequirements.length===0)errors.push('solutionShape.contributionRequirements are invalid.');else d.solutionShape.contributionRequirements.forEach((x,i)=>{if(!obj(x)){errors.push(`contributionRequirements[${i}] must be an object.`);return}unknown(x,CONTRIBUTION,`contributionRequirements[${i}]`,errors);if(!CONTRIBUTION_TYPES.includes(x.requirementType)||!Number.isInteger(x.minimumCount)||x.minimumCount<1||x.distinctness!=='not_required')errors.push(`contributionRequirements[${i}] is invalid.`)});const p=d.solutionShape.prerequisiteTopology;if(!obj(p))errors.push('solutionShape.prerequisiteTopology must be an object.');else{unknown(p,PREREQUISITE,'prerequisiteTopology',errors);if(!PREREQUISITE_MODES.includes(p.mode)||!sortedUnique(p.prerequisiteKnowledgeUnitRefs))errors.push('solutionShape.prerequisiteTopology is invalid.');}}
 if(!sortedUnique(d.capabilityObligations)||!d.capabilityObligations.every(x=>CAPABILITY_OBLIGATIONS.includes(x))||d.capabilityObligations.length===0)errors.push('capabilityObligations are invalid.');
 if(!obj(d.traceability))errors.push('traceability must be an object.');else{unknown(d.traceability,TRACE,'traceability',errors);for(const k of TRACE)if(!str(d.traceability[k]))errors.push(`traceability.${k} is invalid.`);if(str(d.traceability.sourceStrategyRef)&&!d.traceability.sourceStrategyRef.startsWith('knowledgeAcquisitionStrategy:'))errors.push('traceability.sourceStrategyRef is invalid.');if(str(d.traceability.sourceNeedRef)&&!d.traceability.sourceNeedRef.startsWith('knowledgeAcquisitionNeed:'))errors.push('traceability.sourceNeedRef is invalid.');if(str(d.traceability.sourceOpportunityRef)&&!d.traceability.sourceOpportunityRef.startsWith('knowledgeOpportunity:'))errors.push('traceability.sourceOpportunityRef is invalid.');if(str(d.traceability.sourceCoverageRef)&&!d.traceability.sourceCoverageRef.startsWith('knowledgeCoverage:'))errors.push('traceability.sourceCoverageRef is invalid.');if(str(d.traceability.sourcePersonKnowledgeMatrixRef)&&!d.traceability.sourcePersonKnowledgeMatrixRef.startsWith('personKnowledgeMatrix:'))errors.push('traceability.sourcePersonKnowledgeMatrixRef is invalid.');}
 const elementary=d.designType==='elementary_acquisition_design';if(elementary&&(d.sourceRequirementType!=='elementary_knowledge_availability_required'||d.targetKnowledge?.knowledgeLayer!=='elementary'||d.solutionShape?.outputTopology!=='elementary_knowledge_contribution_set'||d.solutionShape?.contributionRequirements?.[0]?.requirementType!=='primary_knowledge_contribution'||d.solutionShape?.prerequisiteTopology?.mode!=='none'||d.solutionShape?.prerequisiteTopology?.prerequisiteKnowledgeUnitRefs?.length!==0||JSON.stringify(d.capabilityObligations)!==JSON.stringify(['must_preserve_source_traceability','must_produce_elementary_contribution'].sort())))errors.push('elementary design mapping is inconsistent.');if(!elementary&&DESIGN_TYPES.includes(d.designType)&&(d.sourceRequirementType!=='derived_knowledge_availability_required'||d.targetKnowledge?.knowledgeLayer!=='derived'||d.solutionShape?.outputTopology!=='derived_knowledge_composition'||d.solutionShape?.contributionRequirements?.[0]?.requirementType!=='derived_knowledge_output'||d.solutionShape?.prerequisiteTopology?.mode!=='all_required'||!d.solutionShape?.prerequisiteTopology?.prerequisiteKnowledgeUnitRefs?.length||JSON.stringify(d.capabilityObligations)!==JSON.stringify(['must_preserve_source_traceability','must_produce_derived_output','must_support_prerequisite_composition'].sort())))errors.push('derived design mapping is inconsistent.');
 if(!obj(d.provenance)||d.provenance.type!=='knowledge_acquisition_design_derivation'||d.provenance.producerVersion!=='1.0'||d.provenance.deterministic!==true||d.provenance.interpretive!==false)errors.push('provenance is invalid.');if(!sortedUnique(d.dependencyRefs)||![d.sourceRequirementRef,...Object.values(d.traceability||{})].every(x=>d.dependencyRefs.includes(x)))errors.push('dependencyRefs are invalid.');if(!obj(d.metadata)||d.metadata.contractVersion!=='1.0'||d.metadata.designStrategyVersion!=='1.0'||d.metadata.readOnly!==true)errors.push('metadata is invalid.');if(!obj(d.extensions))errors.push('extensions must be an object.');if(forbidden(d))errors.push('KnowledgeAcquisitionDesign contains forbidden planning, selection, execution, result, or satisfaction fields.');try{JSON.stringify(d)}catch{errors.push('KnowledgeAcquisitionDesign must be serializable.')}if(REQUIRED.every(k=>k in d)&&str(d.id))try{if(d.id!==calculateKnowledgeAcquisitionDesignId(d))errors.push('id does not match the deterministic content fingerprint.')}catch{errors.push('id fingerprint cannot be calculated.')}return{valid:errors.length===0,errors,warnings}}
module.exports={validateKnowledgeAcquisitionDesign,DESIGN_TYPES,CAPABILITY_OBLIGATIONS,AUTHORIZED_SEMANTIC_POLICY,AUTHORIZED_SEMANTIC_POLICIES};
