const {calculateKnowledgeAcquisitionNeedId}=require('./knowledgeAcquisitionDeclarativeIdentity');
const NEED_TYPES=['elementary_knowledge_required','derived_knowledge_required'];
const OPPORTUNITY_TYPES=['elementary_layer_only','derived_layer_only'];
const SCOPES=['dimension','capability'];
const LAYERS=['elementary','derived'];
const REASONS=['ELEMENTARY_KNOWLEDGE_REQUIRED','DERIVED_KNOWLEDGE_REQUIRED','KNOWLEDGE_COMPOSITION_INCOMPLETE'];
const FORBIDDEN=['score','scoring','rank','ranking','priority','prioritization','weight','weighting','importance','urgency','recommendation','recommendedAction','nextBestAction','bestNeed','selectedNeed','acquisitionMethod','acquisitionStrategy','question','questions','prompt','candidateAssessment','personAssessment','prediction','probability','strategy','plan','timing','owner','runtimeInstruction'];
function obj(v){return v&&typeof v==='object'&&!Array.isArray(v)}function str(v){return typeof v==='string'&&v.trim().length>0}
function forbidden(v){if(Array.isArray(v))return v.some(forbidden);if(!obj(v))return false;return Object.entries(v).some(([k,x])=>FORBIDDEN.includes(k)||forbidden(x))}
function validateKnowledgeAcquisitionNeed(n){const errors=[],warnings=[];const fields=['id','needVersion','needType','sourceOpportunityType','scope','scopeRef','requiredKnowledgeLayer','reasonCodes','sourceOpportunityRef','sourceCoverageRef','provenance','dependencyRefs','metadata','extensions'];if(!obj(n))return{valid:false,errors:['KnowledgeAcquisitionNeed must be an object.'],warnings};for(const k of Object.keys(n))if(!fields.includes(k))errors.push(`${k} is not allowed.`);for(const k of fields)if(!(k in n))errors.push(`Missing property: ${k}.`);for(const k of ['id','scopeRef','sourceOpportunityRef','sourceCoverageRef'])if(!str(n[k]))errors.push(`${k} is invalid.`);if(n.needVersion!=='1.0')errors.push('needVersion is invalid.');if(!NEED_TYPES.includes(n.needType))errors.push('needType is invalid.');if(!OPPORTUNITY_TYPES.includes(n.sourceOpportunityType))errors.push('sourceOpportunityType is invalid.');if(!SCOPES.includes(n.scope))errors.push('scope is invalid.');if(!LAYERS.includes(n.requiredKnowledgeLayer))errors.push('requiredKnowledgeLayer is invalid.');if(!Array.isArray(n.reasonCodes)||!n.reasonCodes.length||!n.reasonCodes.every(x=>REASONS.includes(x))||new Set(n.reasonCodes).size!==n.reasonCodes.length)errors.push('reasonCodes are invalid.');if(n.sourceOpportunityType==='elementary_layer_only'&&(n.needType!=='derived_knowledge_required'||n.requiredKnowledgeLayer!=='derived'||!n.reasonCodes?.includes('DERIVED_KNOWLEDGE_REQUIRED')))errors.push('elementary_layer_only mapping is inconsistent.');if(n.sourceOpportunityType==='derived_layer_only'&&(n.needType!=='elementary_knowledge_required'||n.requiredKnowledgeLayer!=='elementary'||!n.reasonCodes?.includes('ELEMENTARY_KNOWLEDGE_REQUIRED')))errors.push('derived_layer_only mapping is inconsistent.');if(!n.reasonCodes?.includes('KNOWLEDGE_COMPOSITION_INCOMPLETE'))errors.push('KNOWLEDGE_COMPOSITION_INCOMPLETE reason is required.');if(!obj(n.provenance)||n.provenance.type!=='knowledge_acquisition_need_evaluation'||n.provenance.deterministic!==true||n.provenance.interpretive!==false)errors.push('provenance is invalid.');if(!Array.isArray(n.dependencyRefs)||!n.dependencyRefs.every(str)||!n.dependencyRefs.includes(n.sourceOpportunityRef)||!n.dependencyRefs.includes(n.sourceCoverageRef))errors.push('dependencyRefs are invalid.');if(!obj(n.metadata)||n.metadata.contractVersion!=='1.0'||n.metadata.evaluationStrategyVersion!=='1.0'||n.metadata.readOnly!==true)errors.push('metadata is invalid.');if(!obj(n.extensions))errors.push('extensions must be an object.');if(forbidden(n))errors.push('KnowledgeAcquisitionNeed contains forbidden evaluative or operational fields.');if(fields.every(k=>k in n)&&str(n.id))try{if(n.id!==calculateKnowledgeAcquisitionNeedId(n))errors.push('id does not match the deterministic content fingerprint.')}catch{errors.push('id fingerprint cannot be calculated.')}return{valid:errors.length===0,errors,warnings}}
module.exports={validateKnowledgeAcquisitionNeed,NEED_TYPES,OPPORTUNITY_TYPES,SCOPES,LAYERS,REASONS};
