import { runGroqChatCompletion } from './runGroqChatCompletion.js';

const claimShapeProperties={subjectScope:{type:'string',enum:['documented_material_structure','person_property']},structureClaim:{type:'string',enum:['descriptive_combination','recurrence']},personPropertyAssertion:{type:'string',enum:['none','capability','trait','personality','leadership','seniority','strength','weakness']},continuityAssertion:{type:'string',enum:['none','professional_continuity']},leadershipAssertion:{type:'string',enum:['none','authorised']},ownershipAssertion:{type:'string',enum:['none','authorised']},responsibilityAssertion:{type:'string',enum:['none','authorised']},generalAutonomyAssertion:{type:'string',enum:['none','authorised']},resultCausalityAssertion:{type:'string',enum:['none','authorised']},targetRelationAssertion:{type:'string',enum:['none','authorised']}};
export const HIGHER_ORDER_PROFESSIONAL_SYNTHESIS_SCHEMA={type:'object',properties:{structureProposals:{type:'array',maxItems:3,items:{type:'object',properties:{proposalRef:{type:'string'},contributorRefs:{type:'array',minItems:2,items:{type:'string'}},structureWording:{type:'string'},compositionBasis:{type:'string'},compositionSemanticClass:{type:'string',enum:['generic_descriptive_combination','cross_functional_coordination','people_responsibility','decision_accountability','quantified_outcome','production_planning','budget_resource','process_performance_improvement','decision_accountability_quantified_outcome']},claimShape:{type:'object',properties:claimShapeProperties,required:Object.keys(claimShapeProperties)}},required:['proposalRef','contributorRefs','structureWording','compositionBasis','compositionSemanticClass','claimShape']}}},required:['structureProposals']};
export async function runGroqHigherOrderProfessionalSynthesisModel({systemPrompt,userPrompt,runner=runGroqChatCompletion,executionDiagnosticSink}={}){
 const result=await runner({task:'higherOrderProfessionalSynthesis',systemText:systemPrompt,userText:userPrompt,temperature:0.1,maxRetries:1,retryDelayMs:500,jsonSchema:HIGHER_ORDER_PROFESSIONAL_SYNTHESIS_SCHEMA,strictSchemaCompatible:true,executionDiagnosticSink});
 let parsed;try{parsed=JSON.parse(result.content);}catch{const e=new Error('PD070L_MALFORMED_STRUCTURED_OUTPUT');e.task='higherOrderProfessionalSynthesis';throw e;}
 if(!parsed||!Array.isArray(parsed.structureProposals)){const e=new Error('PD070L_INVALID_STRUCTURED_OUTPUT');e.task='higherOrderProfessionalSynthesis';throw e;}
 return {model:result.model,outputMode:result.outputMode,attemptsUsed:result.attemptsUsed,execution:result.execution,rateLimitMetadata:result.rateLimitMetadata,structured:parsed};
}
export default runGroqHigherOrderProfessionalSynthesisModel;
