import { runGroqChatCompletion } from './runGroqChatCompletion.js';

const descriptorClaimProperties={subjectScope:{type:'string',enum:['source_material','episode','activity']},descriptiveRole:{type:'string',enum:['situation_context','activity','involved_function','work_phase','problem_object','contribution_participation']},agencyLevel:{type:'string',enum:['not_established','participated','contributed','coordinated','owned']},responsibilityScope:{type:'string',enum:['not_established','shared_non_exclusive','exclusive_sole']},ownershipAssertion:{type:'string',enum:['none','authorised']},decisionAuthorityAssertion:{type:'string',enum:['none','authorised']},resultCausalityAssertion:{type:'string',enum:['none','authorised']},personPropertyAssertion:{type:'string',enum:['none','capability','trait','personality','leadership','seniority','strength','weakness','fit_readiness']}};
const relationshipClaimProperties={subjectScope:{type:'string',enum:['material_relationship']},relationshipClaim:{type:'string',enum:['descriptive_relationship','recurrence']},personPropertyAssertion:{type:'string',enum:['none','capability','trait','personality','leadership','seniority','strength','weakness']},capabilityAssertion:{type:'string',enum:['none','authorised']},ownershipAssertion:{type:'string',enum:['none','authorised']},responsibilityAssertion:{type:'string',enum:['none','authorised']},causalityAssertion:{type:'string',enum:['none','authorised']},fitReadinessAssertion:{type:'string',enum:['none','authorised']},sameEpisodeAssertion:{type:'string',enum:['none','same_episode']},continuityAssertion:{type:'string',enum:['none','professional_continuity']}};
export const GROUNDED_RELATIONSHIP_PROPOSAL_SCHEMA={type:'object',properties:{descriptorProposals:{type:'array',maxItems:18,items:{type:'object',properties:{proposalRef:{type:'string'},descriptorRole:{type:'string',enum:['situation_context','activity','involved_function','work_phase','problem_object','contribution_participation']},descriptiveValue:{type:'string'},materialRef:{type:'string'},grounding:{type:'object',properties:{exactText:{type:'string'},supportRef:{type:'string'}},required:['exactText','supportRef']},claimShape:{type:'object',properties:descriptorClaimProperties,required:Object.keys(descriptorClaimProperties)}},required:['proposalRef','descriptorRole','descriptiveValue','materialRef','grounding','claimShape']}},relationshipHypotheses:{type:'array',maxItems:6,items:{type:'object',properties:{proposalRef:{type:'string'},descriptorProposalRefs:{type:'array',minItems:2,items:{type:'string'}},relationshipWording:{type:'string'},relationshipBasis:{type:'string'},claimShape:{type:'object',properties:relationshipClaimProperties,required:Object.keys(relationshipClaimProperties)}},required:['proposalRef','descriptorProposalRefs','relationshipWording','relationshipBasis','claimShape']} }},required:['descriptorProposals','relationshipHypotheses']};

export async function runGroqGroundedRelationshipProposalModel({systemPrompt,userPrompt,runner=runGroqChatCompletion,executionDiagnosticSink}={}){
 const result=await runner({task:'groundedRelationshipProposal',systemText:systemPrompt,userText:userPrompt,temperature:0.1,maxRetries:1,retryDelayMs:500,jsonSchema:GROUNDED_RELATIONSHIP_PROPOSAL_SCHEMA,strictSchemaCompatible:true,executionDiagnosticSink});
 let parsed;try{parsed=JSON.parse(result.content);}catch{const e=new Error('PD069L_MALFORMED_STRUCTURED_OUTPUT');e.task='groundedRelationshipProposal';throw e;}
 if(!parsed||!Array.isArray(parsed.descriptorProposals)||!Array.isArray(parsed.relationshipHypotheses)){const e=new Error('PD069L_INVALID_STRUCTURED_OUTPUT');e.task='groundedRelationshipProposal';throw e;}
 return {model:result.model,outputMode:result.outputMode,attemptsUsed:result.attemptsUsed,execution:result.execution,rateLimitMetadata:result.rateLimitMetadata,structured:parsed};
}
export default runGroqGroundedRelationshipProposalModel;
