'use strict';
const assert=require('assert'),K=require('../src/core/knowledge'),A=require('../src/app/knowledge');
const DF=require('./knowledge_acquisition_design_fixture'),SF=require('./knowledge_acquisition_solution_decision_fixture'),CF=require('./knowledge_acquisition_capability_configuration_fixture'),PF=require('./knowledge_acquisition_plan_fixture'),RF=require('./knowledge_acquisition_runtime_session_fixture');
const clone=value=>JSON.parse(JSON.stringify(value));
function deep(value,path='artifact'){if(!value||typeof value!=='object')return;assert(Object.isFrozen(value),`${path} is not frozen`);for(const [key,child]of Object.entries(value))deep(child,`${path}.${key}`)}
const di=DF.buildChain('elementary'),dib=JSON.stringify(di),need=di.resolvedContext.need,strategy=di.resolvedContext.strategy,requirement=di.requirement,design=K.buildKnowledgeAcquisitionDesign(di);assert.equal(JSON.stringify(di),dib);
const sf=SF.buildFixture(),sib=JSON.stringify(sf.inputs.single),decision=A.buildKnowledgeAcquisitionSolutionDecision(sf.inputs.single);assert.equal(JSON.stringify(sf.inputs.single),sib);
const cf=CF.buildFixture(),cib=JSON.stringify(cf.single.input),configuration=A.buildKnowledgeAcquisitionCapabilityConfiguration(cf.single.input);assert.equal(JSON.stringify(cf.single.input),cib);
const pf=PF.buildFixture(),pib=JSON.stringify(pf.single.input),plan=A.buildKnowledgeAcquisitionPlan(pf.single.input);assert.equal(JSON.stringify(pf.single.input),pib);
const rf=RF.buildFixture(),rib=JSON.stringify(rf.created.input),session=A.buildKnowledgeAcquisitionRuntimeSession(rf.created.input,{now:rf.now});assert.equal(JSON.stringify(rf.created.input),rib);
for(const [name,artifact]of Object.entries({need,strategy,requirement,design,decision,configuration,plan,session})){deep(artifact,name);const before=JSON.stringify(artifact);Reflect.set(artifact,'reviewMutation',true);assert.equal(JSON.stringify(artifact),before);const array=Object.values(artifact).find(Array.isArray);if(array){Reflect.set(array,'0','reviewMutation');assert.equal(JSON.stringify(artifact),before)}}
for(const [artifact,mutate,validate]of [[need,x=>x.scopeRef='stale',K.validateKnowledgeAcquisitionNeed],[strategy,x=>x.scopeRef='stale',K.validateKnowledgeAcquisitionStrategy],[requirement,x=>x.scopeRef='stale',K.validateKnowledgeAcquisitionRequirement],[design,x=>x.targetKnowledge.scopeRef='stale',K.validateKnowledgeAcquisitionDesign],[decision,x=>x.decisionContextSummary.approvalState='stale',A.validateKnowledgeAcquisitionSolutionDecision],[configuration,x=>x.configurationItems[0].value='stale',A.validateKnowledgeAcquisitionCapabilityConfiguration],[plan,x=>x.planScope.capabilityRefs[0]='stale',A.validateKnowledgeAcquisitionPlan]]){const stale=clone(artifact);mutate(stale);const validation=validate(stale);assert(!validation.valid);assert(validation.errors.some(error=>error.includes('id does not match')),validation.errors.join(' | '))}
assert(A.validateKnowledgeAcquisitionCapabilityConfigurationContext({capabilityConfiguration:configuration,knowledgeAcquisitionSolutionDecision:cf.single.solutionDecision,selectedCapabilitySnapshots:cf.single.selectedCapabilitySnapshots,configurationDefinition:cf.single.configurationDefinition,applicationConfigurationInput:cf.single.applicationConfigurationInput}).valid);
assert(A.validateKnowledgeAcquisitionPlanContext({knowledgeAcquisitionPlan:plan,capabilityConfiguration:pf.single.capabilityConfiguration}).valid);
assert(A.validateKnowledgeAcquisitionRuntimeSessionContext({knowledgeAcquisitionRuntimeSession:session,knowledgeAcquisitionPlan:rf.plan}).valid);
const active=A.buildKnowledgeAcquisitionRuntimeSession(rf.active.input,{now:rf.later});assert.equal(session.id,active.id);assert(A.validateKnowledgeAcquisitionRuntimeSession(active).valid);
console.log('Knowledge Acquisition declarative immutability and identity integrity tests PASSED');
