import assert from 'node:assert/strict';
import { createRoleRequirement } from '../src/app/careerDirection/contracts.js';
import { CURATED_ROLE_REPRESENTATIONS } from '../src/app/careerDirection/roleFixtures.js';
import { evaluateCareerDirections } from '../src/app/careerDirection/evaluateCareerDirections.js';
const src={sourceRef:'roleSource:test',sourceClass:'reference_authority',sourcePropositionRef:'curated proposition',observedAt:'2026-09-25',supportRole:'test',scope:'bounded'};
const generic=createRoleRequirement({id:'req:generic',type:'responsibility',statement:'Coordinate work.',strength:'context_dependent',material:true,semanticKey:'people_responsibility',sourceSupport:[src],requirementAuthority:{requirementRef:'req:generic',roleRequirementSemanticKey:'people_responsibility',requirementClass:'generic_people_coordination',responsibilityFormality:'informal_or_operational',continuityRequirement:'unspecified',responsibilityScope:'bounded_operational_coordination',authorityRef:'test:authority',sourceBasisRefs:['roleSource:test'],limitations:[]}});
assert.equal(generic.requirementAuthority.requirementClass,'generic_people_coordination');assert.notEqual(generic.requirementAuthority.responsibilityFormality,'formal');
const unspecified=createRoleRequirement({id:'req:unspecified',type:'responsibility',statement:'Work with people.',strength:'context_dependent',material:true,semanticKey:'people_responsibility',sourceSupport:[src]});assert.equal(unspecified.requirementAuthority,null);
for(const role of CURATED_ROLE_REPRESENTATIONS){const req=role.requirements.find(r=>r.semanticKey==='people_responsibility');assert(req);assert.equal(req.requirementAuthority.requirementClass,'formal_continuing_people_responsibility');assert.equal(req.requirementAuthority.responsibilityFormality,'formal');assert.equal(req.requirementAuthority.continuityRequirement,'continuing');assert(req.requirementAuthority.sourceBasisRefs.length);assert.match(req.requirementAuthority.authorityRef,/pd072d/);}
const rep={professionalMeaning:{supportedPatterns:[{kind:'documented_cross_functional_coordination_recurrence'}],professionalSynthesis:{hasDocumentedRoleContinuity:true,currentRole:'Production Supervisor',previousRoles:['Engineer'],domains:['manufacturing']},knowledgeContribution:[]}};
const ev=evaluateCareerDirections({professionalRepresentation:rep,professionalRepresentationRef:'rep:test'});assert(ev.hypotheses.length);for(const h of ev.hypotheses){const authorities=h.metadata.roleRequirementAuthorities;assert(authorities);for(const [ref,a] of Object.entries(authorities)){assert.equal(a.requirementRef,ref);if(a.requirementClass==='formal_continuing_people_responsibility')assert.equal(a.responsibilityFormality,'formal');else assert.equal(a.responsibilityFormality,'unspecified');}}
assert(!JSON.stringify(ev).match(/fitScore|readinessScore|recommendedRank/));
console.log('PD-072D bounded formal people responsibility target requirement authority PASSED');
