import assert from 'node:assert/strict';
import {buildGroundedApplicationPackage,buildOpportunityUnderstanding,buildProtectedApplicationArtifacts,candidateArtifactRequiresLanguageTransformation} from '../src/app/opportunityApplication/groundedApplicationPackage.js';
import {loadPrivateBetaUiMessages} from '../src/i18n/loadPrivateBetaUiMessages.js';
import {establishApplicationMaterialPresentationLanguage} from '../src/app/opportunityApplication/presentationLanguageBasis.js';
const valid=async({input})=>({materialRef:input.materialRef,verdict:'VALID',violations:[]});
function identity(role,description){return {revision:1,professionalSources:[{id:'cv1',sourceRole:'current_cv',content:`${role}. Fonte legacy.`}],representationSnapshots:[{representation:{type:'target_independent_professional_representation',roleHistory:[{sourceId:'cv1',role,status:'current'}],episodeMeanings:[{episodeMeaningId:'e1',sourceId:'cv1',description,participation:'participated',activity:'bounded activity',object:'work',professionalContext:'professional',limitations:['participation_not_ownership_or_management'],support:[{evidenceRef:'ev1'}]}],professionalMeaning:{knowledgeContribution:[]}}}]};}
function setup(role,description,artifactLanguage='it'){const professionalIdentity=identity(role,description),u=buildOpportunityUnderstanding({opportunityText:'Role requirement.',opportunityLabel:'Role'}),pkg=buildGroundedApplicationPackage({professionalIdentity,opportunityUnderstanding:u,documentData:{artifactLanguage}});return {professionalIdentity,u,pkg};}
async function build({role,description,from='it',to='en',translations,validationRunner=valid}){const {professionalIdentity,u,pkg}=setup(role,description,from);let calls=0;const arts=await buildProtectedApplicationArtifacts({applicationPackage:pkg,opportunityUnderstanding:u,documentLanguage:to,messages:loadPrivateBetaUiMessages(to),maxAttempts:1,transformRunner:async({input})=>{calls++;const out=translations(input);if(out instanceof Error)throw out;return {materialRef:input.materialRef,transformedText:out};},validationRunner});return {arts,calls,pkg,professionalIdentity};}
// Old heuristic false-negative must no longer authorize bypass.
{const {arts,calls}=await build({role:'Tecnico Qualità',description:'Supervisione impianti industriali.',translations:i=>i.materialKind==='professional_role'?'Quality Technician':'Industrial plant supervision.'});assert(calls>=2);assert(arts.targetedCv.content.includes('Quality Technician'));assert(arts.targetedCv.content.includes('Industrial plant supervision.'));assert(!arts.targetedCv.content.includes('Tecnico Qualità'));assert(!arts.targetedCv.content.includes('Supervisione impianti industriali.'));}
// Symmetric EN -> IT, deliberately outside prior heuristic vocabulary.
{const {arts,calls}=await build({role:'Quality Technician',description:'Oversaw laboratory instrumentation.',from:'en',to:'it',translations:i=>i.materialKind==='professional_role'?'Tecnico Qualità':'Supervisione della strumentazione di laboratorio.'});assert(calls>=2);assert(arts.targetedCv.content.includes('Tecnico Qualità'));assert(!arts.targetedCv.content.includes('Quality Technician'));}
// Heuristic may still report false, but it is no longer safety authority.
{const {pkg}=setup('Tecnico Qualità','Supervisione impianti industriali.');assert.equal(candidateArtifactRequiresLanguageTransformation({applicationPackage:pkg,documentLanguage:'en'}),false);}
// Partial/rejected materialization fails closed; no source fallback can produce an artifact.
{const {u,pkg}=setup('Tecnico Qualità','Supervisione impianti industriali.');let n=0;await assert.rejects(()=>buildProtectedApplicationArtifacts({applicationPackage:pkg,opportunityUnderstanding:u,documentLanguage:'en',messages:loadPrivateBetaUiMessages('en'),maxAttempts:1,transformRunner:async({input})=>({materialRef:input.materialRef,transformedText:input.materialKind==='professional_role'?'Quality Technician':'Industrial plant supervision.'}),validationRunner:async({input})=>{n++;return {materialRef:input.materialRef,verdict:n===1?'VALID':'REJECTED',violations:n===1?[]:['reject']};}}),/CQ05_LANGUAGE_MATERIALIZATION_REJECTED/);}
// Same-language stays deterministic and never invokes provider.
{const {u,pkg}=setup('Tecnico Qualità','Supervisione impianti industriali.');const established=pkg.candidateApplicationMaterials.map(m=>m.languageTransformationEligibility==='eligible'?establishApplicationMaterialPresentationLanguage(m,{language:'it',authority:'test_explicit_application_realization'}):m);const directPkg=Object.freeze({...pkg,candidateApplicationMaterials:Object.freeze(established)});const arts=await buildProtectedApplicationArtifacts({applicationPackage:directPkg,opportunityUnderstanding:u,documentLanguage:'it',messages:loadPrivateBetaUiMessages('it'),transformRunner:async()=>{throw new Error('provider must not run');},validationRunner:valid});assert(arts.targetedCv.content.includes('Tecnico Qualità'));}
// PI immutability and language proficiency separation.
{const {professionalIdentity,u,pkg}=setup('Tecnico Qualità','Supervisione impianti industriali.');const before=JSON.stringify(professionalIdentity);const arts=await buildProtectedApplicationArtifacts({applicationPackage:pkg,opportunityUnderstanding:u,documentLanguage:'en',messages:loadPrivateBetaUiMessages('en'),transformRunner:async({input})=>({materialRef:input.materialRef,transformedText:input.materialKind==='professional_role'?'Quality Technician':'Industrial plant supervision.'}),validationRunner:valid});assert.equal(JSON.stringify(professionalIdentity),before);assert.deepEqual(arts.cvContentModel.languages,[]);}
// Unrelated non-manufacturing fixture.
{const {arts}=await build({role:'Biomedical Systems Specialist',description:'Verifica strumentazione diagnostica.',translations:i=>i.materialKind==='professional_role'?'Biomedical Systems Specialist':'Diagnostic instrumentation verification.'});assert(arts.targetedCv.content.includes('Diagnostic instrumentation verification.'));}
console.log('CQ-05I-R1 cross-language materialization gate completion tests passed.');
