import assert from 'node:assert/strict';
import {renderPrivateBetaUiJourneyHtml} from '../src/app/renderPrivateBetaUiJourneyHtml.js';
import {buildPrivateBetaSourceGroundedProjection} from '../src/app/buildPrivateBetaSourceGroundedProjection.js';
import {runGroqContinuingPeopleResponsibilitySemanticExecutor} from '../src/infrastructure/groq/runGroqContinuingPeopleResponsibilitySemanticExecutor.js';

const answer='Da circa tre anni, in officina, gestisco direttamente circa 5 persone: assegno le attività e definisco le priorità di lavoro.';
const invalid={interpretationStatus:'SUPPORTED',responsibilityPresence:'supported',continuity:'continuing',responsibilityMode:'formal_line_management_NOT_AUTHORIZED',responsibilityKinds:['work_assignment_or_priority_setting'],peopleScope:{kind:'exact',value:'5',min:null,max:null},professionalContext:{description:'in officina',current:true},eventTime:{description:'Da circa tre anni'},support:{presence:'gestisco direttamente circa 5 persone',continuity:'Da circa tre anni',mode:'gestisco direttamente',peopleScope:'5',professionalContext:'in officina',responsibilityKinds:['assegno le attività e definisco le priorità di lavoro']},limitations:[]};
const valid={interpretationStatus:'SUPPORTED',responsibilityPresence:'supported',continuity:'continuing',responsibilityMode:'informal_operational',responsibilityKinds:['work_assignment_or_priority_setting'],peopleScope:{kind:'category',value:'circa 5 persone',min:null,max:null},professionalContext:{description:'in officina',current:true},eventTime:{description:'Da circa tre anni'},support:{presence:'gestisco direttamente circa 5 persone',continuity:'Da circa tre anni',mode:'gestisco direttamente',peopleScope:'circa 5 persone',professionalContext:'in officina',responsibilityKinds:['assegno le attività e definisco le priorità di lavoro']},limitations:['formal reporting authority not established']};
let calls=0;const semantic=await runGroqContinuingPeopleResponsibilitySemanticExecutor({evidence:{content:{answerText:answer}},completionRunner:async args=>({content:JSON.stringify(++calls===1?invalid:valid),model:'mock',outputMode:args.strictSchemaCompatible?'json_schema':'json_object'})});
assert.equal(semantic.supported,true);assert.equal(calls,2);assert.equal(semantic.provider.pd073Recovery.attempted,true);assert.equal(semantic.provider.pd073Recovery.succeeded,true);

const projection=buildPrivateBetaSourceGroundedProjection({professionalSources:[{id:'d1',sourceRole:'professional_declaration',content:'Ho coordinato un team interfunzionale per ridurre i costi del 15%.',provenance:{origin:'user_declaration',collectedAt:'2026-10-02T10:30:00Z'}}],candidateSourceProfiles:[{sourceId:'d1',sourceRole:'professional_declaration',candidateProfile:{summary:'Coordinamento di un team interfunzionale per riduzione costi',experienceSignals:{highlights:['Riduzione costi del 15%'],supportExcerpts:['Ho coordinato un team interfunzionale per ridurre i costi del 15%.']}}}]});
assert.equal(projection[0].provenance.collectedAt,'2026-10-02T10:30:00Z');
const enrich=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'purpose_build_enrich',productPurpose:'professional_identity_build_enrich',enrichmentOutcome:{acceptedMaterial:true,changed:true,acceptedSourceRefs:['d1']},preInterview:{sourceGroundedProjection:projection,professionalIdentityContinuity:{reusedKnowledgeCount:0}}},identityAvailable:true,identitySummary:{professionalSources:[],reusableKnowledgeResults:[]}});
assert.match(enrich,/candidate-material-row-new/);assert.match(enrich,/Aggiunta in IMAGO/);assert.match(enrich,/02\/10\/2026/);assert.equal((enrich.match(/Aggiunta in IMAGO/g)||[]).length,1);assert.doesNotMatch(enrich,/class="contextual-feedback"/);

const interview=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'understanding',sessionRef:'s1',preInterview:{targetRole:'Operations Manager',cvReviewReport:{profileRead:{summary:'Profilo operativo'},visibleSignals:{professionalTraits:['coordinamento']},missingForCvOptimization:{items:['dato quantitativo']}},sourceGroundedProjection:projection}},identityAvailable:true,identitySummary:{professionalSources:[],reusableKnowledgeResults:[]}});
assert.match(interview,/Inizia il colloquio/);assert.match(interview,/Approfondisci la preparazione/);assert(interview.indexOf('Inizia il colloquio')<interview.indexOf('Approfondisci la preparazione'));assert.doesNotMatch(interview,/class="contextual-feedback"/);
const feedback=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'feedback',sessionRef:'s1',report:{available:false}},identityAvailable:true,identitySummary:{professionalSources:[],reusableKnowledgeResults:[]}});
assert.doesNotMatch(feedback,/class="contextual-feedback"/);assert.doesNotMatch(feedback,/name="feedbackReaction"/);assert.match(feedback,/id="imago-beta-feedback-open"/);assert.match(feedback,/--imago-color-beta-feedback/);
console.log('PD-096 Second Corrective Rework: PASS');
