const assert=require('assert');const dim=require('../src/core/dimension');const cap=require('../src/core/capability');const know=require('../src/core/knowledge');const now='2026-07-27T10:00:00.000Z';
function contribution(id,d,v,c=.8){return dim.buildDimensionContribution({id,measurementId:`m_${id}`,dimensionId:d,contributionType:'supporting',contributionValue:v,confidence:c,provenance:{measurementResultRef:`measurementResult:${id}`,sourceRefs:['mapping:x']},metadata:{version:'1.0',createdAt:now,updatedAt:now},extensions:{}},{now})}
function fixture(){let ledger=dim.buildKnowledgeLedger({metadata:{createdAt:now,updatedAt:now}},{now});ledger=dim.appendDimensionContributions(ledger,[contribution('a','adaptability',.8),contribution('b','analysis',.7)],{now});const snapshot=dim.buildKnowledgeSnapshot(ledger,{now});function derived(capabilityId,version,target,dimensionId,estimate){const rule=dim.buildDerivedKnowledgeRule({target:{knowledgeType:'derived_dimension',knowledgeId:target},conditions:[{dimensionId:'adaptability',field:'estimate',operator:'gte',value:.7,minimumConfidence:.5,minimumCoverage:.5,extensions:{}}],conditionStrategy:'all',confidenceStrategy:'minimum',output:{valueType:'boolean',value:true},metadata:{createdAt:now,updatedAt:now},extensions:{}},{now});const recipe=cap.buildCapabilityRecipe({capabilityId,version,rules:[rule],extensions:{}},{now});const execution=cap.executeCapabilityRecipe(snapshot,recipe,{now});const mapping=dim.buildDerivedDimensionMapping({resultTarget:rule.target,dimensionId,estimate,extensions:{}},{now});return dim.buildDerivedDimensionKnowledgeStates([execution],[mapping],{now})[0]}
 const d1=derived('cap:adaptability','1.0.0','adapt_signal','adaptability',.9);const d2=derived('cap:analysis','2.0.0','analysis_signal','analysis',.85);const matrix=know.buildPersonKnowledgeMatrix({subjectRef:{type:'person',id:'subject-q'},knowledgeSnapshot:snapshot,derivedStates:[d2,d1]},{now});return{matrix,d1,d2}}
const {matrix,d1,d2}=fixture();const before=JSON.stringify(matrix);
const q=know.buildPersonKnowledgeQuery({dimensionId:' adaptability ',knowledgeLayer:'derived'});assert.deepStrictEqual(q,{dimensionId:'adaptability',knowledgeLayer:'derived'});assert(know.validatePersonKnowledgeQuery(q).valid);assert(!know.validatePersonKnowledgeQuery({}).valid);assert(!know.validatePersonKnowledgeQuery({unknown:'x'}).valid);assert(!know.validatePersonKnowledgeQuery({knowledgeLayer:'other'}).valid);assert(!know.validatePersonKnowledgeQuery({recipeVersion:'1.0'}).valid);
let r=know.queryPersonKnowledgeMatrix(matrix,{dimensionId:'adaptability'});assert.strictEqual(r.summary.elementaryCount,1);assert.strictEqual(r.summary.derivedCount,1);assert(know.validatePersonKnowledgeQueryResult(r).valid);
r=know.queryPersonKnowledgeMatrix(matrix,{knowledgeLayer:'elementary'});assert.strictEqual(r.summary.elementaryCount,2);assert.strictEqual(r.summary.derivedCount,0);
r=know.queryPersonKnowledgeMatrix(matrix,{knowledgeLayer:'derived'});assert.strictEqual(r.summary.elementaryCount,0);assert.strictEqual(r.summary.derivedCount,2);
r=know.queryPersonKnowledgeMatrix(matrix,{capabilityId:d1.capabilityId});assert.deepStrictEqual(r.knowledgeLayers.derived.map(x=>x.id),[d1.id]);assert.strictEqual(r.summary.elementaryCount,0);
r=know.queryPersonKnowledgeMatrix(matrix,{recipeId:d2.recipeRef});assert.deepStrictEqual(r.knowledgeLayers.derived.map(x=>x.id),[d2.id]);
r=know.queryPersonKnowledgeMatrix(matrix,{recipeVersion:'1.0.0'});assert.deepStrictEqual(r.knowledgeLayers.derived.map(x=>x.id),[d1.id]);
r=know.queryPersonKnowledgeMatrix(matrix,{knowledgeLayer:'derived',dimensionId:'analysis',capabilityId:d2.capabilityId,recipeId:d2.recipeRef,recipeVersion:'2.0.0'});assert.deepStrictEqual(r.knowledgeLayers.derived.map(x=>x.id),[d2.id]);
r=know.queryPersonKnowledgeMatrix(matrix,{dimensionId:'missing'});assert.strictEqual(r.summary.empty,true);assert.deepStrictEqual(r.knowledgeLayers,{elementary:[],derived:[]});
assert.throws(()=>know.queryPersonKnowledgeMatrix(matrix,{knowledgeLayer:'elementary',capabilityId:'cap:x'}),e=>e.code==='INVALID_PERSON_KNOWLEDGE_QUERY');assert.strictEqual(JSON.stringify(matrix),before);const input={dimensionId:'analysis'};const ib=JSON.stringify(input);r=know.queryPersonKnowledgeMatrix(matrix,input);assert.strictEqual(JSON.stringify(input),ib);r.knowledgeLayers.derived[0].estimate=0;assert.notStrictEqual(matrix.knowledgeLayers.derived.find(x=>x.id===d2.id).estimate,0);
for(const key of ['score','ranking','recommendation','overallScore'])assert(!Object.prototype.hasOwnProperty.call(r,key));console.log('PersonKnowledgeMatrix query tests PASSED');
