import assert from 'node:assert/strict';
import {createPrivateBetaUiServer} from '../src/app/privateBetaUiServer.js';
import {startPd086ProfessionalResponsibilityAcquisition,PD086_RESOURCE_BUDGET_ACTION} from '../src/app/careerDirection/pendingProfessionalResponsibilityAcquisition.js';
import {PD086_AUTHORITIES,PD086_SEMANTIC_CANDIDATE_SCHEMA,validatePd086SemanticCandidate,runPd086ProductionSemanticExecutor,describePd086CandidateShape} from '../src/app/knowledge/pd086ProfessionalResponsibility.js';

const authority=PD086_AUTHORITIES.resource_budget_responsibility_scope;
const answer='Nel progetto controllavo il budget del reparto ogni mese.';
const evidence={content:{answerText:answer}};
const canonical={interpretationStatus:'SUPPORTED',semanticType:'resource_budget_responsibility_scope',responsibilityStrength:'direct_bounded_responsibility',directness:'direct',scope:'reparto',continuity:'recurring',allocationAuthority:false,approvalAuthority:false,monitoringControl:true,amountRange:null,participationType:null,directScheduleCreationChange:null,prioritisationAuthority:null,productionScope:null,timeHorizon:null,affectedScope:null,professionalContext:{description:'reparto',current:true},eventTime:{description:null},support:{primary:'controllavo il budget del reparto',scope:'reparto',continuity:null,amount:null},limitations:[]};
assert.equal(validatePd086SemanticCandidate(canonical,{authority,evidence}).valid,true);
for(const [field,bad,error] of [['interpretationStatus','supported','interpretation_status_invalid'],['responsibilityStrength','owner','responsibility_strength_invalid'],['continuity','ongoing','continuity_invalid'],['directness','indirect','directness_invalid']]){const x=structuredClone(canonical);x[field]=bad;const v=validatePd086SemanticCandidate(x,{authority,evidence});assert.equal(v.valid,false);assert(v.errors.includes(error));}
const wrongSemantic={...canonical,semanticType:'continuing_people_responsibility'};assert(validatePd086SemanticCandidate(wrongSemantic,{authority,evidence}).errors.includes('semantic_type_mismatch'));
const badStructure={...canonical,limitations:null};assert(validatePd086SemanticCandidate(badStructure,{authority,evidence}).errors.includes('candidate_structure_invalid'));
assert.deepEqual(new Set(PD086_SEMANTIC_CANDIDATE_SCHEMA.required),new Set(Object.keys(PD086_SEMANTIC_CANDIDATE_SCHEMA.properties)));

const legacy={semantic_type:'resource_budget_responsibility_scope',interpretationStatus:'supported',responsibilityStrength:'owner',continuity:'ongoing',directness:'indirect',professional_context:{description:'reparto'},supportingEvidence:'controllavo il budget del reparto'};
const shape=describePd086CandidateShape(legacy);assert(shape.presentFields.includes('semantic_type'));assert(shape.missingFields.includes('semanticType'));assert(shape.unexpectedFields.includes('semantic_type'));assert.equal(shape.interpretationStatus,'supported');assert(!JSON.stringify(shape).includes(answer));

let calls=[];
const exec=await runPd086ProductionSemanticExecutor({authority,evidence,completionRunner:async opts=>{calls.push(opts);return calls.length===1?{structured:legacy,model:'controlled'}:{structured:canonical,model:'controlled'};}});
assert.equal(exec.supported,true);assert.equal(exec.diagnostic.pd073Recovery.attempted,true);assert.equal(exec.diagnostic.pd073Recovery.succeeded,true);assert.equal(calls.length,2);assert.equal(calls[0].strictSchemaCompatible,true);assert.equal(calls[1].strictSchemaCompatible,false);assert.deepEqual(calls[0].jsonSchema,PD086_SEMANTIC_CANDIDATE_SCHEMA);for(const token of ['interpretationStatus enum: SUPPORTED | UNSUPPORTED','responsibilityStrength enum: contextual_no_direct_responsibility | participated | contributed | coordinated | direct_bounded_responsibility | broader_responsibility | exclusive_final_authority | insufficient','continuity enum: episode | recurring | continuing | insufficient','directness enum: none | contribution | direct | exclusive_final | insufficient','No additional top-level fields.'])assert(calls[1].systemText.includes(token));assert(calls[1].systemText.includes('single bounded recovery attempt'));

let failCalls=0;const failed=await runPd086ProductionSemanticExecutor({authority,evidence,completionRunner:async()=>{failCalls++;return {structured:legacy,model:'controlled'};}});assert.equal(failed.supported,false);assert.equal(failed.reason,'invalid_provider_output');assert.equal(failed.diagnostic.pd073Recovery.attempted,true);assert.equal(failed.diagnostic.pd073Recovery.succeeded,false);assert.equal(failCalls,2);assert(failed.diagnostic.candidateShape.missingFields.includes('semanticType'));

const now='2026-10-02T14:07:07.000Z',personRef={type:'person',id:'pd096-fifth'};
const evaluation={type:'career_direction_evaluation',professionalRepresentationRef:'rep:pd096-fifth',hypotheses:[{id:'ops',directionRef:'operations_manager',metadata:{roleLabel:'Operations Manager'},conditionsToVerify:[{id:'budget-condition',reason:'broader_resource_budget_scope',roleRequirementRef:'budget-role-requirement'}]}]};
const identity={type:'private_beta_professional_identity_continuity',professionalIdentityRef:'professionalIdentity:pd096-fifth',personRef,professionalSources:[],reusableKnowledgeResults:[],authorizedMaterials:{},applicationState:{}};
const acquisition=startPd086ProfessionalResponsibilityAcquisition({careerDirectionEvaluation:evaluation,selectedDirectionRef:'ops',conditionRef:'budget-condition',actionIdentity:PD086_RESOURCE_BUDGET_ACTION,professionalIdentity:identity,subjectRef:personRef,professionalRepresentationRef:'rep:pd096-fifth',now});
const sessionRef='pd096-fifth-route',sessionStore=new Map([[sessionRef,{type:'direction_explore_state',personRef,careerDirectionEvaluation:evaluation,directionAcquisition:acquisition,reusableProfessionalIdentity:identity}]]);
let routeCalls=0;const semanticExecutor=({authority,evidence})=>runPd086ProductionSemanticExecutor({authority,evidence,completionRunner:async()=>{routeCalls++;return routeCalls===1?{structured:legacy,model:'controlled-route'}:{structured:canonical,model:'controlled-route'};}});
const server=createPrivateBetaUiServer({operatorDiagnosticsEnabled:true,sessionStore,locale:'it',journeyOptions:{pd086ProfessionalResponsibilitySemanticExecutor:semanticExecutor}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
try{const port=server.address().port;const response=await fetch(`http://127.0.0.1:${port}/private-beta/direction/answer`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({sessionRef,answer})});const html=await response.text();assert.equal(response.status,200);assert.doesNotMatch(html,/Non sono riuscito a interpretare la risposta per un problema tecnico/);const state=sessionStore.get(sessionRef);assert.equal(state.directionAcquisition.status,'resolved');assert(state.directionAcquisition.knowledgeResult?.knowledgeSnapshot);assert.equal(state.directionAcquisition.knowledgeResult.semanticExecutionTrace.pd073Recovery.attempted,true);assert.equal(state.directionAcquisition.knowledgeResult.semanticExecutionTrace.pd073Recovery.succeeded,true);assert.equal(routeCalls,2);}finally{await new Promise(r=>server.close(r));}
console.log('PD-096 Fifth Corrective PD-086 semantic candidate contract alignment: PASS');
