import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {buildAcceptedRuntimeAnswerEvidenceStore} from '../src/app/registerAcceptedRuntimeAnswerEvidence.js';
const require=createRequire(import.meta.url);
const K=require('../src/core/knowledge');const A=require('../src/app/knowledge');const D=require('../src/core/dimension');const M=require('../src/core/measurement/decisionAccountability');const {resolveDecisionAccountabilitySemanticAuthority}=require('../src/app/knowledge/resolveDecisionAccountabilitySemanticAuthority');const {constructAuthorizedDecisionAccountabilityObservation}=require('../src/app/knowledge/constructAuthorizedDecisionAccountabilityObservation');const {projectDecisionAccountabilityMeasureResult}=require('../src/core/measurement/decisionAccountability/projectDecisionAccountabilityMeasureResult');const {buildDecisionAccountabilityMeasurementDimensionMapping}=require('../src/core/dimension/buildDecisionAccountabilityMeasurementDimensionMapping');const {runDecisionAccountabilitySemanticKnowledgePath}=require('../src/app/knowledge/runDecisionAccountabilitySemanticKnowledgePath');
const DF=require('./knowledge_acquisition_design_fixture');const I=require('../src/core/knowledge/knowledgeAcquisitionDeclarativeIdentity');
const now='2026-09-01T09:00:00.000Z', later='2026-09-01T09:01:00.000Z';
function canonicalDesign(){const c=DF.buildChain('elementary');const requirement=JSON.parse(JSON.stringify(c.requirement));requirement.scope='dimension';requirement.scopeRef='decision_accountability';requirement.id=I.calculateKnowledgeAcquisitionRequirementId(requirement);return K.buildKnowledgeAcquisitionDesign({requirement,resolvedContext:c.resolvedContext,semanticPolicyRef:'professional_semantic_policy:decision_accountability:v1'});}
function chain(){const design=canonicalDesign();const capability={capabilityRef:'capability:structured-input-v1',capabilityType:'structured_input',supportedDesignTypes:['elementary_acquisition_design'],supportedKnowledgeLayers:['elementary'],supportedOutputTopologies:['elementary_knowledge_contribution_set'],supportedPrerequisiteModes:['none'],supportedObligations:['must_preserve_source_traceability','must_produce_elementary_contribution'],constraints:{},metadata:{version:'1.0'},extensions:{}};const match=K.buildKnowledgeAcquisitionCapabilityMatch({design,capabilityCandidate:capability});const decision=A.buildKnowledgeAcquisitionSolutionDecision({design,matches:[match],candidateSnapshots:[{capabilityRef:capability.capabilityRef,capabilityType:'structured_input',metadata:{version:'1.0'},extensions:{}}],decisionContext:{contextRef:'applicationDecisionContext:ar02b',approvalState:'approved',decisionTimestamp:now},decisionPolicy:{policyRef:'applicationDecisionPolicy:ar02b',allowedModes:['single'],allowComposition:false,criteria:['explicit_request']},decisionRequest:{mode:'single',selectedCapabilityRefs:[capability.capabilityRef],reasons:[{code:'canonical_slice',category:'adoption',blocking:false}]}});const configuration=A.buildKnowledgeAcquisitionCapabilityConfiguration({solutionDecision:decision,selectedCapabilitySnapshots:[{capabilityRef:capability.capabilityRef,capabilityType:'structured_input',metadata:{version:'1.0'},extensions:{}}],configurationDefinition:{configurationDefinitionRef:'knowledgeAcquisitionConfigurationDefinition:ar02b',capabilityDefinitions:[{capabilityRef:capability.capabilityRef,parameters:[]}]},applicationConfigurationInput:{applicationConfigurationInputRef:'applicationConfigurationInput:ar02b',configurationItems:[]}});const plan=A.buildKnowledgeAcquisitionPlan({capabilityConfiguration:configuration});const item=plan.planItems[0].planItemRef;const session=A.buildKnowledgeAcquisitionRuntimeSession({knowledgeAcquisitionPlan:plan,sessionKey:'ar02b-session',status:'active',activePlanItemRef:item,itemStates:[{sourcePlanItemRef:item,status:'active',activatedAt:now,suspendedAt:null,completedAt:null,abandonedAt:null}],lifecycle:{createdAt:now,updatedAt:now,activatedAt:now,suspendedAt:null,completedAt:null,abandonedAt:null}},{now});const execution=A.buildKnowledgeAcquisitionExecution({knowledgeAcquisitionRuntimeSession:session,knowledgeAcquisitionPlan:plan,executionKey:'ar02b-execution'},{now});return{design,decision,configuration,plan,session,execution};}
function evidenceFor(c,text='Ho preso la decisione finale sul rilascio e ne ho risposto al team.'){const store=buildAcceptedRuntimeAnswerEvidenceStore({betaSessionId:'beta-ar02b',interviewSessionId:'interview-ar02b',answers:[{answerText:text,questionContext:{questionKey:'irrelevant-question-key',expectedSignals:['must-not-select-authority']},stepType:'answer',phaseName:'interview',timestamp:now}],knowledgeAcquisitionExecutionRef:`knowledgeAcquisitionExecution:${c.execution.id}`});return store.evidence[0];}
const c=chain(), evidence=evidenceFor(c);const authority=resolveDecisionAccountabilitySemanticAuthority({evidence,knowledgeAcquisitionExecution:c.execution,knowledgeAcquisitionPlan:c.plan,capabilityConfiguration:c.configuration,solutionDecision:c.decision,knowledgeAcquisitionDesign:c.design});assert.equal(authority.resolved,true);assert.equal(authority.semanticPolicyRef,c.design.semanticPolicyRef);assert.equal(evidence.semanticPolicyRef,undefined);assert.equal(evidence.content.provenance.semanticPolicyRef,undefined);
const authorityOtherText=resolveDecisionAccountabilitySemanticAuthority({evidence:evidenceFor(c,'Testo completamente diverso senza keyword pertinenti.'),knowledgeAcquisitionExecution:c.execution,knowledgeAcquisitionPlan:c.plan,capabilityConfiguration:c.configuration,solutionDecision:c.decision,knowledgeAcquisitionDesign:c.design});assert.equal(authorityOtherText.resolved,true,'resolver must not inspect answer/question semantics');
const executor=()=>({supported:true,observation:{observationId:'decision_accountability:ar02b:1',decisionAuthority:'final',consequenceScope:'team',accountabilityEvidence:'explicit_with_outcomes',responsibilityContinuityMonths:24,context:{episode:'release'},inferenceSupportInputs:{evidenceQuality:.9,sourceConvergence:.8,consistency:.9,coverage:.8},limitations:[],metadata:{createdAt:now}}});const observation=constructAuthorizedDecisionAccountabilityObservation({evidence,semanticAuthority:authority,executor});assert(observation);assert.deepEqual(observation.evidenceIds,[evidence.id]);assert.equal(observation.extensions.semanticProvenance.semanticPolicyRef,c.design.semanticPolicyRef);assert.equal(observation.extensions.semanticProvenance.knowledgeAcquisitionDesignRef,`knowledgeAcquisitionDesign:${c.design.id}`);assert.equal(observation.extensions.semanticProvenance.knowledgeAcquisitionExecutionRef,`knowledgeAcquisitionExecution:${c.execution.id}`);
const specialized=M.buildDecisionAccountabilityMeasureResult({observation});assert.equal(specialized.resultStatus,'draft');const generic=projectDecisionAccountabilityMeasureResult(specialized,{calculatedAt:now});assert.equal(generic.measurementId,'decision_accountability');assert.equal(generic.characteristicId,'decision_accountability');assert.equal(generic.normalizedValue,specialized.score);assert.deepEqual(generic.extensions.projection.specializedResult,specialized);
const mapping=buildDecisionAccountabilityMeasurementDimensionMapping({now});assert.equal(mapping.targets[0].dimensionId,'decision_accountability');assert.equal(mapping.targets[0].weight,1);assert.equal(mapping.targets[0].confidenceFactor,1);const contributions=D.mapMeasurementResultToDimensionContributions(generic,mapping);assert.equal(contributions.length,1);assert.equal(contributions[0].dimensionId,'decision_accountability');assert(!JSON.stringify({observation,specialized,generic,mapping,contributions}).includes('ownership'));
let ledger=D.buildKnowledgeLedger({contributions:[],metadata:{createdAt:now,updatedAt:now}},{now});ledger=D.appendDimensionContributions(ledger,contributions,{now});const snapshot=D.buildKnowledgeSnapshot(ledger,{now});const pkm=K.buildPersonKnowledgeMatrix({subjectRef:{type:'person',id:'person-ar02b'},knowledgeSnapshot:snapshot,derivedStates:[]},{now});const coverage=K.buildKnowledgeCoverage({personKnowledgeMatrix:pkm});assert.equal(coverage.dimensionCoverage[0].dimensionId,'decision_accountability');
const full=runDecisionAccountabilitySemanticKnowledgePath({evidence,knowledgeAcquisitionExecution:c.execution,knowledgeAcquisitionPlan:c.plan,capabilityConfiguration:c.configuration,solutionDecision:c.decision,knowledgeAcquisitionDesign:c.design,observationExecutor:executor,subjectRef:{type:'person',id:'person-ar02b-full'},now});assert.equal(full.knowledgeCoverage.dimensionCoverage[0].dimensionId,'decision_accountability');const noEffect=runDecisionAccountabilitySemanticKnowledgePath({evidence,knowledgeAcquisitionExecution:c.execution,knowledgeAcquisitionPlan:c.plan,capabilityConfiguration:c.configuration,solutionDecision:c.decision,knowledgeAcquisitionDesign:c.design,observationExecutor:()=>({supported:false}),subjectRef:{type:'person',id:'person-ar02b-none'},now});assert.equal(noEffect.observation,null);assert.equal(noEffect.measurementResult,null);assert.equal(noEffect.dimensionContributions.length,0);assert.equal(noEffect.knowledgeLedger,null);assert.equal(noEffect.personKnowledgeMatrix,null);assert.equal(noEffect.knowledgeCoverage,null);

const missing=JSON.parse(JSON.stringify(evidence));delete missing.content.provenance.knowledgeAcquisitionExecutionRef;assert.equal(resolveDecisionAccountabilitySemanticAuthority({evidence:missing,knowledgeAcquisitionExecution:c.execution,knowledgeAcquisitionPlan:c.plan,capabilityConfiguration:c.configuration,solutionDecision:c.decision,knowledgeAcquisitionDesign:c.design}).resolved,false);
const brokenExecution={...c.execution,id:'knowledgeAcquisitionExecution_broken'};assert.equal(resolveDecisionAccountabilitySemanticAuthority({evidence,knowledgeAcquisitionExecution:brokenExecution,knowledgeAcquisitionPlan:c.plan,capabilityConfiguration:c.configuration,solutionDecision:c.decision,knowledgeAcquisitionDesign:c.design}).resolved,false);
const badTarget=JSON.parse(JSON.stringify(c.design));badTarget.targetKnowledge.scopeRef='ownership';assert.equal(resolveDecisionAccountabilitySemanticAuthority({evidence,knowledgeAcquisitionExecution:c.execution,knowledgeAcquisitionPlan:c.plan,capabilityConfiguration:c.configuration,solutionDecision:c.decision,knowledgeAcquisitionDesign:badTarget}).resolved,false);
const badPolicy=JSON.parse(JSON.stringify(c.design));badPolicy.semanticPolicyRef='professional_semantic_policy:other:v1';assert.equal(resolveDecisionAccountabilitySemanticAuthority({evidence,knowledgeAcquisitionExecution:c.execution,knowledgeAcquisitionPlan:c.plan,capabilityConfiguration:c.configuration,solutionDecision:c.decision,knowledgeAcquisitionDesign:badPolicy}).resolved,false);
assert.equal(constructAuthorizedDecisionAccountabilityObservation({evidence,semanticAuthority:authority,executor:()=>({supported:false})}),null);assert.equal(constructAuthorizedDecisionAccountabilityObservation({evidence,semanticAuthority:authority,executor:()=>({supported:true,observation:{}})}),null);assert.equal(projectDecisionAccountabilityMeasureResult(M.buildDecisionAccountabilityMeasureResult({observation:M.buildDecisionAccountabilityObservation({observationId:'not-observed'})}),{calculatedAt:now}),null);
console.log('AR-02C decision accountability semantic integration tests passed.');
