import assert from 'assert';
import { buildRepresentationValueProofProjection } from '../src/app/buildRepresentationValueProofProjection.js';
const source={professionalPerception:{authorizedSemanticMaterial:[{semanticType:'quantified_outcome',sourceRef:'runtimeKnowledgeResults[0]',evidenceIds:['e1'],measurableOutcome:'scrap reduction',quantitativeValue:{value:20,unit:'percent',approximate:true},causalityBoundary:'contribution_only',limitations:['sole causality not established']}],visibleSignals:[{label:'legacy ownership'}],underVisibleSignals:[{label:'capacity planning'}]}};
const before=JSON.stringify(source);const out=buildRepresentationValueProofProjection({professionalPerceptionReport:source,targetRole:'Engineering Manager',roleProfile:{requirements:{mustHave:['capacity planning'],preferred:[],bonus:[]}}});
assert(out.claims.length>=2&&out.claims.length<=4);assert.equal(out.persistent,false);assert.equal(out.sourceOfTruth,false);assert.equal(out.hasPrimaryScore,false);assert(out.claims.every(c=>c.traceability.length>0));assert(out.claims.some(c=>c.epistemicStatus==='insufficiently_observed'));assert(out.claims.some(c=>c.targetRelation?.target==='Engineering Manager'));assert(!JSON.stringify(out).includes('legacy ownership'));assert.equal(JSON.stringify(source),before);assert(Object.isFrozen(out));
const sparse=buildRepresentationValueProofProjection({professionalPerceptionReport:{professionalPerception:{visibleSignals:[{label:'legacy only'}]}}});assert.equal(sparse.claims.length,0);
console.log('Representation Value Proof Projection tests PASSED');
import { renderPrivateBetaUiJourneyHtml } from '../src/app/renderPrivateBetaUiJourneyHtml.js';
const html=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'feedback',report:{available:true,representationValueProof:out}}});
assert(html.includes('Perché IMAGO vede questo?'));assert(html.includes('scrap reduction'));assert(!html.includes('runtimeKnowledgeResults[0]'));assert(html.includes('<details>'));
const rendererSource=(await import('fs')).readFileSync('src/app/renderPrivateBetaUiJourneyHtml.js','utf8');assert(!rendererSource.includes('Perché IMAGO vede questo?'));
