import assert from 'node:assert/strict';
import {buildTargetIndependentProfessionalRepresentation} from '../src/app/buildTargetIndependentProfessionalRepresentation.js';
import {TARGET_INDEPENDENT_REPRESENTATION_RECIPE,buildTargetIndependentRepresentationSnapshotState,materializeTargetIndependentRepresentationSnapshot,attachRepresentationSnapshotToProfessionalIdentity,findReusableTargetIndependentRepresentationSnapshot} from '../src/app/privateBetaProfessionalRepresentationSnapshots.js';
import {renderPrivateBetaUiJourneyHtml} from '../src/app/renderPrivateBetaUiJourneyHtml.js';
const now='2026-09-14T12:00:00Z';
const sources=[{id:'current',type:'text',sourceRole:'current_cv',content:'Production Supervisor',provenance:{label:'CV attuale'}},{id:'previous',type:'text',sourceRole:'previous_cv',content:'Industrialization Engineer',provenance:{label:'CV precedente'}}];
const projection=[{sourceId:'current',facts:['Production Supervisor'],domainSignals:['manufacturing'],activitySemantics:[],sourceFaithfulExperienceExcerpts:[]},{sourceId:'previous',facts:['Industrialization Engineer'],domainSignals:['manufacturing'],activitySemantics:[],sourceFaithfulExperienceExcerpts:[]}];
function pd({continuity='continuing',scope={kind:'exact',value:10},kinds=['work_assignment_or_priority_setting','workload_shift_or_schedule_coordination','performance_follow_up_or_feedback'],context={description:'reparto produttivo'},status='observed',policy='professional_semantic_policy:continuing_people_responsibility:v1'}={}){return {semanticType:'continuing_people_responsibility',semanticPolicyRef:policy,knowledgeRef:'knowledgeSnapshot:pd056',knowledgeSnapshot:{id:'pd056'},observation:{observationId:'obs:pd056',observationType:'observed_continuing_people_responsibility_context',observationStatus:status,evidenceIds:['evidence:answer'],professionalContext:context,limitations:[]},specializedMeasurementResult:{semanticDetail:{responsibilityPresence:'supported',continuity,responsibilityMode:'informal_operational',responsibilityKinds:kinds,peopleScope:scope},context}};}
const supported=pd();
const r=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,reusableKnowledgeResults:[supported],locale:'it',useModel:false});
const people=r.professionalMeaning.knowledgeContribution.find(x=>x.semanticType==='continuing_people_responsibility');assert.ok(people);assert.equal(people.primaryProfessionalMeaning.continuity,'continuing');assert.match(people.primaryProfessionalMeaning.peopleScope,/10/);assert.equal(people.primaryProfessionalMeaning.professionalContext,'reparto produttivo');assert.equal(people.primaryProfessionalMeaning.responsibilityKinds.length,3);assert.equal(r.professionalMeaning.supportedPatterns.some(x=>/people|leadership/.test(x.kind)),false);
const html=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'purpose_understand',preInterview:{targetIndependentProfessionalRepresentation:r}}});assert.match(html,/coordini il lavoro di circa 10 persone/i);assert.match(html,/circa 10 persone/i);assert.match(html,/reparto produttivo/i);assert.doesNotMatch(html,/leader|leadership|capacità manageriali|pronto per|idoneità per Operations Manager/i);assert.equal((html.match(/circa 10 persone/gi)||[]).length>=1,true);
const noPd=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,reusableKnowledgeResults:[],locale:'it',useModel:false});assert.equal(noPd.professionalMeaning.knowledgeContribution.some(x=>x.semanticType==='continuing_people_responsibility'),false);
for(const bad of [pd({continuity:'temporary'}),pd({status:'insufficient'}),{...supported,semanticPolicyRef:'professional_semantic_policy:decision_accountability:v1'}, {...supported,semanticType:'decision_accountability'}]){const x=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,reusableKnowledgeResults:[bad],locale:'it',useModel:false});assert.equal(x.professionalMeaning.knowledgeContribution.some(k=>k.semanticType==='continuing_people_responsibility'),false);}
const titleOnly=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,reusableKnowledgeResults:[],locale:'it',useModel:false});assert.doesNotMatch(renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'purpose_understand',preInterview:{targetIndependentProfessionalRepresentation:titleOnly}}}),/circa 10 persone/i);
assert.equal(TARGET_INDEPENDENT_REPRESENTATION_RECIPE.version,'2.0');
const pi={personRef:{type:'person',id:'bv03'},professionalIdentityRef:'pi:bv03',representationSnapshots:[]};
const before=buildTargetIndependentRepresentationSnapshotState({professionalIdentity:pi,professionalSources:sources,reusableKnowledgeResults:[]});const snap0=materializeTargetIndependentRepresentationSnapshot({professionalIdentity:pi,state:before,representation:noPd,now});const with0=attachRepresentationSnapshotToProfessionalIdentity({professionalIdentity:pi,snapshot:snap0});
const after=buildTargetIndependentRepresentationSnapshotState({professionalIdentity:with0,professionalSources:sources,reusableKnowledgeResults:[supported]});assert.notEqual(after.knowledgeStateFingerprint,before.knowledgeStateFingerprint);assert.equal(findReusableTargetIndependentRepresentationSnapshot({professionalIdentity:with0,state:after}),null);const snap1=materializeTargetIndependentRepresentationSnapshot({professionalIdentity:with0,state:after,representation:r,now:'2026-09-14T12:01:00Z'});assert.equal(snap1.changeCause,'knowledge_observability_change');const with1=attachRepresentationSnapshotToProfessionalIdentity({professionalIdentity:with0,snapshot:snap1});assert.equal(findReusableTargetIndependentRepresentationSnapshot({professionalIdentity:with1,state:after}).snapshotId,snap1.snapshotId);
const same=buildTargetIndependentRepresentationSnapshotState({professionalIdentity:with1,professionalSources:sources,reusableKnowledgeResults:[JSON.parse(JSON.stringify(supported))]});assert.equal(same.relevantStateFingerprint,after.relevantStateFingerprint);
const changed=buildTargetIndependentRepresentationSnapshotState({professionalIdentity:with1,professionalSources:sources,reusableKnowledgeResults:[pd({scope:{kind:'exact',value:12}})]});assert.notEqual(changed.relevantStateFingerprint,after.relevantStateFingerprint);
const revoked=buildTargetIndependentRepresentationSnapshotState({professionalIdentity:with1,professionalSources:sources,reusableKnowledgeResults:[]});assert.notEqual(revoked.relevantStateFingerprint,after.relevantStateFingerprint);assert.equal(findReusableTargetIndependentRepresentationSnapshot({professionalIdentity:with1,state:revoked})?.snapshotId,snap0.snapshotId,'historical pre-PD snapshot may remain historical/reusable only for the matching current material state');
console.log('BETA-VALUE-03 PD-056 Professional Representation reuse: PASS');
