import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createPrivateBetaUiServer } from '../src/app/privateBetaUiServer.js';
import { createMemoryPrivateBetaProfessionalIdentityStore, privateBetaPersonRefFromContext } from '../src/app/privateBetaProfessionalIdentityContinuity.js';

const fixture=JSON.parse(await readFile(new URL('../fixtures/expected_candidate_profile_01.json',import.meta.url),'utf8'));
function candidate(summary){const x=structuredClone(fixture);(x.candidateProfile||x).summary=summary;return x;}
const personRef=privateBetaPersonRefFromContext('pa01-understand-human');
const mk=(id,role,content)=>({id,type:'text',label:role,content,language:null,sourceRole:role,quality:null,provenance:{origin:role,providedBy:'user',collectedAt:'2026-09-09T09:00:00.000Z'},metadata:{createdAt:'2026-09-09T09:00:00.000Z',updatedAt:'2026-09-09T09:00:00.000Z'}});
const sources=[mk('current_cv','current_cv','Production Supervisor'),mk('previous_cv','previous_cv','Industrialization Engineer Germany'),mk('professional_declaration','professional_declaration','Project Atlas supplier ramp-up')];
const record={version:'1.0',type:'private_beta_professional_identity_continuity',professionalIdentityRef:`professionalIdentity:${personRef.id}`,personRef,owner:'person',authorizedMaterials:{cvText:'Production Supervisor',userNotes:''},professionalSources:sources,reusableKnowledgeResults:[],knowledgeRefs:[],revision:1,createdAt:'2026-09-09T09:00:00.000Z',updatedAt:'2026-09-09T09:00:00.000Z',lastEnrichedBySessionRef:null};
async function run(adapter,{diagnostics=false}={}){const store=createMemoryPrivateBetaProfessionalIdentityStore();await store.save({record});const diagnosticStore=[];const server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:store,contextIdFactory:()=> 'pa01-understand-human',journeyOptions:{modelAdapter:adapter},operatorDiagnosticsEnabled:diagnostics,preparationDiagnosticStore:diagnosticStore});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;const cookie='imago_beta_repeat_context=pa01-understand-human';const body=new URLSearchParams({identityAction:'recover',workingMode:'independent',productPurpose:'professional_representation_understand',consentDecision:'accept',targetRole:'',cvText:'',previousCvText:'',professionalDeclaration:'',userNotes:'',jdText:'',uiLocale:'it',sessionLocale:'it'});const response=await fetch(base+'/private-beta/journey',{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body});const html=await response.text();await new Promise(r=>server.close(r));return {status:response.status,html,diagnosticStore};}
const adapter=async({task,user})=>{assert.equal(task,'candidateProfile','Understand must not invoke RoleProfile/JobFit/interview preparation');if(user.includes('Germany'))return JSON.stringify(candidate('Industrialization Engineer; Germany launch'));if(user.includes('Project Atlas'))return JSON.stringify(candidate('Project Atlas supplier ramp-up'));return JSON.stringify(candidate('Production Supervisor'));};
const ok=await run(adapter);assert.equal(ok.status,200,ok.html);assert.match(ok.html,/purpose-no-interview/);assert.match(ok.html,/Production Supervisor/);assert.match(ok.html,/Industrialization Engineer/);assert.match(ok.html,/Project Atlas/);assert.doesNotMatch(ok.html,/understanding\/continue/);assert.doesNotMatch(ok.html,/runtime-question/);
const failed=await run(async({task})=>{const e=new Error('controlled projection failure');e.task=task;throw e;},{diagnostics:true});assert.equal(failed.status,422);assert.match(failed.html,/professional_representation_understand/,'failure render must preserve returning purpose state');assert.match(failed.html,/CV attuale/,'failure render must re-expose recoverable identity sources');assert(failed.diagnosticStore.some(x=>x.boundary==='professional_representation_materialization'&&x.task==='candidateProfile'));
console.log('PA-01 Understand live-routing corrective: PASS');
