import assert from 'node:assert/strict';
import {runGroqContinuingPeopleResponsibilitySemanticExecutor} from '../src/infrastructure/groq/runGroqContinuingPeopleResponsibilitySemanticExecutor.js';
import {buildContinuingPeopleResponsibilityProductionSemanticPrompt} from '../src/app/knowledge/buildContinuingPeopleResponsibilityProductionSemanticPrompt.js';

const evidenceText='Ho gestito continuativamente circa 5 persone di officina, assegnando le attività e definendo le priorità di lavoro.';
const base={interpretationStatus:'SUPPORTED',responsibilityPresence:'supported',continuity:'continuing',responsibilityMode:'insufficient',responsibilityKinds:['work_assignment_or_priority_setting'],peopleScope:{kind:'category',value:'circa 5 persone',min:null,max:null},professionalContext:{description:'officina',current:true},eventTime:{description:null},support:{presence:'Ho gestito',continuity:'continuativamente',mode:null,peopleScope:'circa 5 persone',professionalContext:null,responsibilityKinds:['assegnando le attività']},limitations:[]};
let calls=[];
const runner=async args=>{calls.push(args);if(calls.length===1)return{content:JSON.stringify(base),model:'openai/gpt-oss-120b',outputMode:'json_schema',execution:{elapsedMs:10,httpAttemptsUsed:1}};assert.equal(args.task,'continuingPeopleResponsibilitySemanticSupportRepair');const map=JSON.parse(args.userText.split('\n')[1]).unresolvedSelectionMap;return{content:JSON.stringify({selections:map.map(x=>({field:x.field,candidateId:x.candidates[0]?.candidateId||''}))}),model:'openai/gpt-oss-120b',outputMode:'json_object'};};
const accepted=await runGroqContinuingPeopleResponsibilitySemanticExecutor({evidence:{content:{answerText:evidenceText}},completionRunner:runner});
assert.equal(accepted.supported,true);assert.equal(accepted.candidate.professionalContext.description,'officina');assert(evidenceText.includes(accepted.candidate.support.professionalContext));assert(accepted.candidate.support.professionalContext.includes('officina'));assert.equal(calls.length,2);assert.equal(accepted.provider.supportRepairAttempted,true);

// Context invented by provider cannot be accepted when application-owned Evidence candidates cannot ground it safely.
const invented={...base,professionalContext:{description:'reparto verniciatura',current:true}};calls=[];const rejected=await runGroqContinuingPeopleResponsibilitySemanticExecutor({evidence:{content:{answerText:evidenceText}},completionRunner:async args=>{calls.push(args);if(calls.length===1)return{content:JSON.stringify(invented),model:'m',outputMode:'json_schema'};const map=JSON.parse(args.userText.split('\n')[1]).unresolvedSelectionMap;return{content:JSON.stringify({selections:map.map(x=>({field:x.field,candidateId:''}))}),model:'m',outputMode:'json_object'};}});assert.equal(rejected.supported,false);assert.equal(rejected.reason,'unsupported_candidate_support');

// Non-grounding semantic-candidate errors receive the accepted PD-073 bounded json_object recovery, then still fail closed if invalid.
const invalid={...base,responsibilityMode:'formal_line_NOT_AUTHORIZED'};calls=[];const invalidResult=await runGroqContinuingPeopleResponsibilitySemanticExecutor({evidence:{content:{answerText:evidenceText}},completionRunner:async args=>{calls.push(args);return{content:JSON.stringify(invalid),model:'m',outputMode:'json_schema'};}});assert.equal(invalidResult.supported,false);assert.equal(invalidResult.diagnostic.category,'candidate_rejected');assert.equal(calls.length,2);assert.equal(invalidResult.diagnostic.pd073Recovery?.attempted,true);assert.equal(invalidResult.diagnostic.pd073Recovery?.succeeded,false);

const prompt=buildContinuingPeopleResponsibilityProductionSemanticPrompt({evidence:{content:{answerText:evidenceText}}});assert(prompt.systemText.includes('if professionalContext.description is non-null, support.professionalContext MUST contain an exact contiguous Evidence excerpt'));
console.log('PD-073 fourth corrective CPR semantic candidate grounding alignment tests passed.');
