import fs from 'node:fs';
import assert from 'node:assert/strict';
const ui=fs.readFileSync('src/app/renderPrivateBetaUiJourneyHtml.js','utf8');
const it=JSON.parse(fs.readFileSync('config/private_beta_ui.it.json','utf8'));
const en=JSON.parse(fs.readFileSync('config/private_beta_ui.en.json','utf8'));
assert.match(ui,/directionOverviewClarificationCount/);
assert.match(ui,/directionOverviewBuildCount/);
assert.match(ui,/overviewStateSummary/);
assert.doesNotMatch(it.directionOverviewClarificationCount,/svilupp|costru/i);
assert.match(it.directionOverviewBuildCount,/costruire/);
assert.match(it.directionConditionPeopleQuestion,/\?$/);
assert.match(it.directionConditionBudgetQuestion,/\?$/);
assert.doesNotMatch(it.directionConditionPeopleQuestion,/Da verificare:/);
assert.doesNotMatch(it.directionConditionBudgetQuestion,/Da verificare:/);
assert.match(ui,/const unknownHtml=unresolved\.length/);
assert.match(ui,/nextStepText\(c\)/);
assert.match(ui,/absences\.length\?m\.directionNextBridge/);
assert.match(ui,/item\.actionability==='actionable_now'/);
assert.match(ui,/directionClarificationActionableStatus/);
assert.ok(it.directionNextClarifyPeople && it.directionNextClarifyBudget && it.directionNextClarifyProductionPlanning && it.directionNextClarifyResourceBudget);
assert.ok(en.directionNextClarifyPeople && en.directionConditionPeopleQuestion);
assert.doesNotMatch(ui,/fillMessage\(m\.directionOverviewOpenItems/);
console.log('PD-072F career direction Candidate actionability tests passed.');
