import assert from 'node:assert/strict';
import {buildCareerDirectionClarificationQueue} from '../src/app/careerDirection/buildCareerDirectionClarificationQueue.js';
import {startPd086ProfessionalResponsibilityAcquisition,answerPd086ProfessionalResponsibilityAcquisition,resolveCurrentPd086Conditions,PD086_RESOURCE_BUDGET_ACTION,PD086_PRODUCTION_PLANNING_ACTION} from '../src/app/careerDirection/pendingProfessionalResponsibilityAcquisition.js';
import {PD086_AUTHORITIES,validatePd086SemanticCandidate} from '../src/app/knowledge/pd086ProfessionalResponsibility.js';
import {buildPrivateBetaProfessionalIdentityContinuityRecord,createMemoryPrivateBetaProfessionalIdentityStore} from '../src/app/privateBetaProfessionalIdentityContinuity.js';
import {buildTargetIndependentProfessionalRepresentation} from '../src/app/buildTargetIndependentProfessionalRepresentation.js';
import {evaluateCareerDirections} from '../src/app/careerDirection/evaluateCareerDirections.js';
import {buildOpportunityUnderstanding,buildGroundedApplicationPackage} from '../src/app/opportunityApplication/groundedApplicationPackage.js';
import {validateOpportunityRequirementSupportProposal} from '../src/app/opportunityApplication/requirementSupportAuthority.js';

const now='2026-09-30T10:30:00.000Z';
const subjectRef={type:'person',id:'person:pd086'};
const evaluation={type:'career_direction_evaluation',professionalRepresentationRef:'rep:pd086',hypotheses:[
 {id:'ops',directionRef:'operations_manager',recipeVersion:'1.4',metadata:{roleLabel:'Operations Manager',roleRequirementSemanticKeys:{rb:'budget_resource_scope'}},conditionsToVerify:[{id:'cb',reason:'broader_resource_budget_scope',roleRequirementRef:'rb'}]},
 {id:'ops2',directionRef:'operations_manager_alt',recipeVersion:'1.4',metadata:{roleLabel:'Operations Manager 2',roleRequirementSemanticKeys:{rb2:'budget_resource_scope'}},conditionsToVerify:[{id:'cb2',reason:'broader_resource_budget_scope',roleRequirementRef:'rb2'}]},
 {id:'prod',directionRef:'industrial_production_manager',recipeVersion:'1.4',metadata:{roleLabel:'Industrial Production Manager',roleRequirementSemanticKeys:{rp:'production_planning_resource_scope'}},conditionsToVerify:[{id:'cp',reason:'production_planning_scope',roleRequirementRef:'rp'}]}
]};
const emptyIdentity={type:'private_beta_professional_identity_continuity',professionalIdentityRef:'professionalIdentity:pd086',personRef:subjectRef,professionalSources:[],reusableKnowledgeResults:[],authorizedMaterials:{cvText:'',userNotes:''},revision:1,representationSnapshots:[],currentRepresentationSnapshotRefs:{},applicationState:{}};
const q=buildCareerDirectionClarificationQueue({careerDirectionEvaluation:evaluation,directionResolutions:[],pd086Enabled:true});
assert.equal(q.length,2);const qb=q.find(x=>x.semanticType==='resource_budget_responsibility_scope'),qp=q.find(x=>x.semanticType==='production_planning_scheduling_responsibility_scope');assert.equal(qb.actionability,'actionable_now');assert.equal(qb.acquisitionActionRef,PD086_RESOURCE_BUDGET_ACTION);assert.equal(qb.affectedDirections.length,2);assert.equal(qp.acquisitionActionRef,PD086_PRODUCTION_PLANNING_ACTION);

function baseCandidate(semanticType){return {interpretationStatus:'SUPPORTED',semanticType,responsibilityStrength:'insufficient',directness:'insufficient',scope:null,continuity:'insufficient',allocationAuthority:null,approvalAuthority:null,monitoringControl:null,amountRange:null,participationType:null,directScheduleCreationChange:null,prioritisationAuthority:null,productionScope:null,timeHorizon:null,affectedScope:null,professionalContext:{description:null,current:null},eventTime:{description:null},support:{primary:null,scope:null,continuity:null,amount:null},limitations:[]};}
function budgetCandidate(answer){return {...baseCandidate('resource_budget_responsibility_scope'),responsibilityStrength:'direct_bounded_responsibility',directness:'direct',scope:'reparto industrializzazione',continuity:'continuing',allocationAuthority:true,approvalAuthority:true,monitoringControl:false,amountRange:'500.000 euro',professionalContext:{description:'reparto industrializzazione',current:true},support:{primary:answer,scope:'reparto industrializzazione',continuity:'continuativamente',amount:'500.000 euro'}};}
function planningCandidate(answer){return {...baseCandidate('production_planning_scheduling_responsibility_scope'),responsibilityStrength:'direct_bounded_responsibility',directness:'direct',scope:'due linee',continuity:'recurring',participationType:'direct_schedule_preparation_change',directScheduleCreationChange:true,prioritisationAuthority:true,productionScope:'due linee',professionalContext:{description:'due linee',current:true},support:{primary:answer,scope:'due linee',continuity:'Ogni settimana',amount:null}};}
const budgetAnswer='Continuativamente, nel reparto industrializzazione allocavo direttamente un budget di 500.000 euro per attrezzature e approvavo spese.';
const planningAnswer='Ogni settimana preparavo e modificavo direttamente il programma di produzione per due linee, decidendo le priorità.';
const semanticExecutor=async({authority,evidence})=>({supported:true,candidate:authority.semanticType==='resource_budget_responsibility_scope'?budgetCandidate(evidence.content.answerText):planningCandidate(evidence.content.answerText),provider:{model:'controlled:pd086'}});

let bstate=startPd086ProfessionalResponsibilityAcquisition({careerDirectionEvaluation:evaluation,selectedDirectionRef:'ops',conditionRef:'cb',actionIdentity:PD086_RESOURCE_BUDGET_ACTION,professionalIdentity:emptyIdentity,subjectRef,professionalRepresentationRef:'rep:pd086',now});assert.equal(bstate.status,'awaiting_answer');
const bdone=await answerPd086ProfessionalResponsibilityAcquisition({state:bstate,answer:budgetAnswer,careerDirectionEvaluation:evaluation,professionalIdentity:emptyIdentity,subjectRef,now,semanticExecutor});assert.equal(bdone.status,'resolved');assert.equal(bdone.knowledgeResult.specializedMeasurementResult.semanticDetail.responsibilityStrength,'direct_bounded_responsibility');assert.equal(bdone.knowledgeResult.specializedMeasurementResult.semanticDetail.budgetResources.allocationAuthority,true);

// A/D/H: contribution or negative context never becomes direct ownership/global weakness.
const contributionAnswer='Partecipavo alle discussioni sui costi e fornivo dati economici al responsabile di budget.';
const contribution={...baseCandidate('resource_budget_responsibility_scope'),responsibilityStrength:'contributed',directness:'contribution',scope:'discussioni sui costi',continuity:'episode',professionalContext:{description:'discussioni sui costi',current:false},support:{primary:contributionAnswer,scope:'discussioni sui costi',continuity:null,amount:null}};
assert.equal(validatePd086SemanticCandidate(contribution,{authority:PD086_AUTHORITIES.resource_budget_responsibility_scope,evidence:{content:{answerText:contributionAnswer}}}).valid,true);assert.notEqual(contribution.responsibilityStrength,'direct_bounded_responsibility');
const negativeAnswer='Non gestivo direttamente il budget; fornivo solo dati sui costi nel reparto qualità.';
const negative={...baseCandidate('resource_budget_responsibility_scope'),responsibilityStrength:'contextual_no_direct_responsibility',directness:'none',scope:'reparto qualità',continuity:'episode',professionalContext:{description:'reparto qualità',current:false},support:{primary:negativeAnswer,scope:'reparto qualità',continuity:null,amount:null}};
assert.equal(validatePd086SemanticCandidate(negative,{authority:PD086_AUTHORITIES.resource_budget_responsibility_scope,evidence:{content:{answerText:negativeAnswer}}}).valid,true);

let pstate=startPd086ProfessionalResponsibilityAcquisition({careerDirectionEvaluation:evaluation,selectedDirectionRef:'prod',conditionRef:'cp',actionIdentity:PD086_PRODUCTION_PLANNING_ACTION,professionalIdentity:emptyIdentity,subjectRef,professionalRepresentationRef:'rep:pd086',now});const pdone=await answerPd086ProfessionalResponsibilityAcquisition({state:pstate,answer:planningAnswer,careerDirectionEvaluation:evaluation,professionalIdentity:emptyIdentity,subjectRef,now,semanticExecutor});assert.equal(pdone.status,'resolved');assert.equal(pdone.knowledgeResult.specializedMeasurementResult.semanticDetail.productionPlanning.directScheduleCreationChange,true);
// E/G: own-team priority input cannot be upgraded to production-schedule ownership.
const priorityOnly='Fornivo priorità per il mio team, ma non preparavo né modificavo il piano di produzione.';
const invalidStrengthening={...baseCandidate('production_planning_scheduling_responsibility_scope'),responsibilityStrength:'direct_bounded_responsibility',directness:'direct',scope:'mio team',continuity:'episode',directScheduleCreationChange:false,prioritisationAuthority:true,productionScope:'mio team',professionalContext:{description:'mio team',current:false},support:{primary:priorityOnly,scope:'mio team',continuity:null,amount:null}};
const iv=validatePd086SemanticCandidate(invalidStrengthening,{authority:PD086_AUTHORITIES.production_planning_scheduling_responsibility_scope,evidence:{content:{answerText:priorityOnly}}});assert.equal(iv.valid,false);assert(iv.errors.includes('schedule_ownership_not_explicit'));

// Persistence/restart and shared Person-side truth.
const first=buildPrivateBetaProfessionalIdentityContinuityRecord({personRef:subjectRef,priorRecord:emptyIdentity,session:{runtimeKnowledgeResults:[{...bdone.knowledgeResult,semanticType:'resource_budget_responsibility_scope',semanticPolicyRef:PD086_AUTHORITIES.resource_budget_responsibility_scope.semanticPolicyRef,knowledgeRef:`knowledgeSnapshot:${bdone.knowledgeResult.knowledgeSnapshot.id}`}],professionalSources:[],rawInput:{},betaSession:{sessionId:'pd086-1'}},now});
const persisted=buildPrivateBetaProfessionalIdentityContinuityRecord({personRef:subjectRef,priorRecord:first,session:{runtimeKnowledgeResults:[{...pdone.knowledgeResult,semanticType:'production_planning_scheduling_responsibility_scope',semanticPolicyRef:PD086_AUTHORITIES.production_planning_scheduling_responsibility_scope.semanticPolicyRef,knowledgeRef:`knowledgeSnapshot:${pdone.knowledgeResult.knowledgeSnapshot.id}`}],professionalSources:[],rawInput:{},betaSession:{sessionId:'pd086-2'}},now:'2026-09-30T10:31:00.000Z'});
const store=createMemoryPrivateBetaProfessionalIdentityStore();await store.save({record:persisted});const reloaded=await store.load({personRef:subjectRef});assert.equal(reloaded.reusableKnowledgeResults.filter(x=>x.semanticType.includes('responsibility_scope')||x.semanticType.includes('planning_scheduling')).length,2);
const resolutions=resolveCurrentPd086Conditions({careerDirectionEvaluation:evaluation,professionalIdentity:reloaded,now});assert.equal(resolutions.length,3);assert(resolutions.every(x=>x.resolutionState==='resolved_by_current_authorised_state'));const qAfter=buildCareerDirectionClarificationQueue({careerDirectionEvaluation:evaluation,directionResolutions:resolutions,pd086Enabled:true});assert.equal(qAfter.length,0);

// Career Direction recomputation consumes the new Person Knowledge once representation is rematerialized.
const representation=await buildTargetIndependentProfessionalRepresentation({professionalSources:[],sourceGroundedProjection:[],reusableKnowledgeResults:reloaded.reusableKnowledgeResults,useModel:false,locale:'it'});assert(representation.professionalMeaning.knowledgeContribution.some(x=>x.semanticType==='resource_budget_responsibility_scope'));assert(representation.professionalMeaning.knowledgeContribution.some(x=>x.semanticType==='production_planning_scheduling_responsibility_scope'));
const career=evaluateCareerDirections({professionalRepresentation:representation,professionalRepresentationRef:'rep:pd086-rebuilt',explorationContext:{preferenceState:'declared',explicitDirectionRequests:['operations_manager','industrial_production_manager']},now});const allConditions=career.hypotheses.flatMap(x=>x.conditionsToVerify||[]);assert.equal(allConditions.some(x=>x.reason==='broader_resource_budget_scope'),false);assert.equal(allConditions.some(x=>x.reason==='production_planning_scope'),false);

// Application recomputation: PD-085 may now consume exactly the newly authorised semantic contributor.
const identityForApplication={...reloaded,representationSnapshots:[{representation}]};
const opportunity=buildOpportunityUnderstanding({opportunityText:'Operations Lead\nRequirements\nManage resource allocation and budget control.\nOwn production scheduling for the plant.',opportunityLabel:'Operations Lead',now});
const budgetReq=[...opportunity.requirements,...opportunity.responsibilities,...opportunity.unclassified].find(x=>/budget/i.test(x.statement));const planReq=[...opportunity.requirements,...opportunity.responsibilities,...opportunity.unclassified].find(x=>/production scheduling/i.test(x.statement));assert(budgetReq&&planReq);
const kBudget=representation.professionalMeaning.knowledgeContribution.find(x=>x.semanticType==='resource_budget_responsibility_scope');const kPlan=representation.professionalMeaning.knowledgeContribution.find(x=>x.semanticType==='production_planning_scheduling_responsibility_scope');
const proposal=(k,req,id)=>({contributorType:'bounded_canonical_knowledge_meaning',contributorRef:k.sourceRef,opportunityRef:opportunity.opportunityRef,opportunityRequirementRef:req.id,relationBasis:'PD-086 bounded responsibility Knowledge supports this exact opportunity requirement.',provenance:{providerRef:'controlled:pd086',proposalRef:id}});
const pb=proposal(kBudget,budgetReq,'pd086-budget'),pp=proposal(kPlan,planReq,'pd086-plan');assert.equal(validateOpportunityRequirementSupportProposal(pb,{professionalIdentity:identityForApplication,opportunityUnderstanding:opportunity}).status,'accepted');assert.equal(validateOpportunityRequirementSupportProposal(pp,{professionalIdentity:identityForApplication,opportunityUnderstanding:opportunity}).status,'accepted');const pkg=buildGroundedApplicationPackage({professionalIdentity:identityForApplication,opportunityUnderstanding:opportunity,requirementSupportProposals:[pb,pp]});assert.equal(pkg.targetRelativeInformationMap.find(x=>x.requirementRef===budgetReq.id).state,'sufficiently_documented');assert.equal(pkg.targetRelativeInformationMap.find(x=>x.requirementRef===planReq.id).state,'sufficiently_documented');assert.equal(pkg.opportunityRequirementSupportProjection.personKnowledgeWriteback,false);

// Candidate-facing wiring/localization remains factual, bounded and semantic-identity carrying.
const fs=await import('node:fs');
const rendererSource=fs.readFileSync('src/app/renderPrivateBetaUiJourneyHtml.js','utf8');
assert.match(rendererSource,/pd086Enabled:true/);assert.match(rendererSource,/acquisitionActionRef/);assert.match(rendererSource,/conditionRef/);
for(const locale of ['it','en']){const ui=JSON.parse(fs.readFileSync(`config/private_beta_ui.${locale}.json`,'utf8'));for(const key of ['directionAcquisitionResourceBudgetQuestion','directionAcquisitionResourceBudgetClarification','directionAcquisitionProductionPlanningQuestion','directionAcquisitionProductionPlanningClarification'])assert.equal(typeof ui[key],'string');}
const it=JSON.parse(fs.readFileSync('config/private_beta_ui.it.json','utf8'));assert.match(it.directionAcquisitionResourceBudgetQuestion,/responsabilità diretta/i);assert.match(it.directionAcquisitionProductionPlanningQuestion,/Preparavi o modificavi direttamente/i);
console.log('PD-086 Pending Professional Responsibility Acquisition Authority: PASS');

