import assert from 'node:assert/strict';
import { validateHigherOrderStructureProposal,runHigherOrderDescriptiveProfessionalStructureVerticalSlice } from '../src/app/higherOrderDescriptiveProfessionalStructureVerticalSlice.js';
import { buildTargetIndependentProfessionalRepresentation } from '../src/app/buildTargetIndependentProfessionalRepresentation.js';
import { renderPrivateBetaUiJourneyHtml } from '../src/app/renderPrivateBetaUiJourneyHtml.js';
import { composeProfessionalThreads,selectLevel1ProfessionalThreads } from '../src/app/professionalThreadComposition.js';
const claim=(o={})=>({subjectScope:'documented_material_structure',structureClaim:'recurrence',personPropertyAssertion:'none',continuityAssertion:'none',leadershipAssertion:'none',ownershipAssertion:'none',responsibilityAssertion:'none',generalAutonomyAssertion:'none',resultCausalityAssertion:'none',targetRelationAssertion:'none',...o});
const rel=(id,mats,sources,bases=[])=>({status:'accepted',relationshipId:id,kind:'grounded_descriptive_professional_relationship',relationshipWording:`relationship ${id}`,relationshipBasis:'accepted bounded material relation',materialRefs:mats,sourceRefs:sources,professionalBasisRefs:bases,persistent:false});
const contributors=[rel('r1',['m1','m2'],['s1','s2'],['episode:e1']),rel('r2',['m2','m3'],['s2','s3'],['episode:e2'])];
const good={proposalRef:'h1',contributorRefs:['r1','r2'],structureWording:'Tre situazioni documentate mostrano fasi operative correlate in configurazioni professionali distinte.',compositionBasis:'Due relazioni già accettate collegano tre basi professionali indipendenti senza attribuire una proprietà stabile alla persona.',independenceBasis:{professionalBasisRefs:['episode:e1','episode:e2']},claimShape:claim(),persistence:'representation_only'};
const ok=validateHigherOrderStructureProposal(good,{contributors});assert.equal(ok.status,'accepted');assert.equal(ok.persistent,false);assert.equal(ok.personPropertyAssertion,'none');assert.deepEqual(ok.contributorRefs,['r1','r2']);assert.equal(ok.materialRefs.length,3);assert.deepEqual(ok.professionalBasisRefs,['episode:e1','episode:e2']);
const bad=[
 {...good,claimShape:claim({personPropertyAssertion:'capability'})},
 {...good,claimShape:claim({continuityAssertion:'professional_continuity'})},
 {...good,claimShape:claim({leadershipAssertion:'authorised'})},
 {...good,claimShape:claim({ownershipAssertion:'authorised'})},
 {...good,claimShape:claim({responsibilityAssertion:'exclusive'})},
 {...good,claimShape:claim({generalAutonomyAssertion:'authorised'})},
 {...good,claimShape:claim({resultCausalityAssertion:'authorised'})},
 {...good,targetInputs:['jd:x']},
 {...good,contributorRefs:['r1','missing']},
 {...good,persistence:'person_knowledge'},
 {...good,providerAuthority:true},
 {...good,requiredContributorFacts:['invented-fact']}
];for(const x of bad)assert.equal(validateHigherOrderStructureProposal(x,{contributors}).status,'rejected');
const sameEpisodeDistinctMaterials=[rel('a',['mA'],['s1'],['episode:same']),rel('b',['mB'],['s2'],['episode:same'])];const sameEpisodeResult=validateHigherOrderStructureProposal({...good,contributorRefs:['a','b'],independenceBasis:{professionalBasisRefs:['episode:same']}},{contributors:sameEpisodeDistinctMaterials});assert.equal(sameEpisodeResult.status,'rejected');assert(sameEpisodeResult.errors.includes('recurrence_requires_independent_professional_bases'));
const distinctMaterialsWithoutCanonicalBases=[rel('na',['mA'],['s1']),rel('nb',['mB'],['s2'])];assert.equal(validateHigherOrderStructureProposal({...good,contributorRefs:['na','nb'],independenceBasis:{professionalBasisRefs:[]}},{contributors:distinctMaterialsWithoutCanonicalBases}).status,'rejected');
const independentBases=[rel('ia',['mA'],['s1'],['episode:e1']),rel('ib',['mB'],['s2'],['episode:e2'])];assert.equal(validateHigherOrderStructureProposal({...good,contributorRefs:['ia','ib'],independenceBasis:{professionalBasisRefs:['episode:e1','episode:e2']}},{contributors:independentBases}).status,'accepted');
const duplicate=await runHigherOrderDescriptiveProfessionalStructureVerticalSlice({contributors,proposalProvider:async()=>[good,{...good}]});assert.equal(duplicate.structures.length,0);assert(duplicate.rejections.every(x=>x.errors.includes('duplicate_proposal_ref')));
// End-to-end controlled slice: accepted PD-069 relationships -> PD-070 structure -> thread -> Level 1 -> renderer.
const sources=['Avvio controllato della linea con funzioni operative.','Stabilizzazione del processo con funzioni tecniche.','Riconfigurazione operativa con funzioni di supporto.'].map((content,i)=>({id:`s${i+1}`,sourceRole:'professional_declaration',content}));
const projection=sources.map(s=>({sourceId:s.id,sourceRole:s.sourceRole,facts:[s.content],roleDescriptionFacts:[],domainSignals:[],experienceHighlights:[s.content],sourceFaithfulExperienceExcerpts:[s.content],activitySemantics:[]}));
const dclaim=(role)=>({subjectScope:'source_material',descriptiveRole:role,agencyLevel:'not_established',responsibilityScope:'not_established',ownershipAssertion:'none',decisionAuthorityAssertion:'none',resultCausalityAssertion:'none',personPropertyAssertion:'none'});
const descriptors=sources.map((s,i)=>({descriptorRole:'work_phase',descriptiveValue:`fase documentata ${i+1}`,materialRef:`source:${s.id}`,grounding:{exactText:s.content,supportRef:`source:${s.id}:support:1`},provenance:{providerRef:'controlled:pd070i',proposalRef:`d${i+1}`},claimShape:dclaim('work_phase'),persistence:'representation_only'}));
const rclaim={subjectScope:'material_relationship',relationshipClaim:'descriptive_relationship',personPropertyAssertion:'none',capabilityAssertion:'none',ownershipAssertion:'none',responsibilityAssertion:'none',causalityAssertion:'none',fitReadinessAssertion:'none',sameEpisodeAssertion:'none',continuityAssertion:'none'};
const relationships=[{descriptorRefs:['descriptor:d1','descriptor:d2'],relationshipWording:'Le prime due situazioni documentano fasi operative correlate.',relationshipBasis:'bounded relation one',provenance:{providerRef:'controlled:pd070i',proposalRef:'r1'},claimShape:rclaim,persistence:'representation_only'},{descriptorRefs:['descriptor:d2','descriptor:d3'],relationshipWording:'La seconda e la terza situazione documentano configurazioni operative correlate.',relationshipBasis:'bounded relation two',provenance:{providerRef:'controlled:pd070i',proposalRef:'r2'},claimShape:rclaim,persistence:'representation_only'}];
const higherProvider=async({contributors:c})=>[{...good,contributorRefs:c.map(x=>x.relationshipId),claimShape:claim({structureClaim:'descriptive_combination'}),independenceBasis:{professionalBasisRefs:[]}}];
const rep=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,descriptorProposalProvider:async()=>descriptors,relationshipHypothesisProvider:async()=>relationships,higherOrderProposalProvider:higherProvider});
assert.equal(rep.professionalMeaning.higherOrderDescriptiveProfessionalStructures.length,1);assert.equal(rep.professionalMeaning.groundedDescriptiveRelationships.length,2);const ht=rep.professionalMeaning.professionalThreads.find(x=>x.kind==='higher_order_descriptive_structure');assert(ht);assert(rep.professionalMeaning.level1ProfessionalThreads.some(x=>x.threadId===ht.threadId));assert.equal(rep.professionalMeaning.level1ProfessionalThreads.filter(x=>x.kind==='grounded_descriptive_relationship').length,0);assert.deepEqual(rep.professionalMeaning.insufficientObservability,[]);assert(!JSON.stringify(rep).includes('personKnowledgeWriteback'));const html=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'purpose_understand',preInterview:{targetIndependentProfessionalRepresentation:rep}}});assert.match(html,/Tre situazioni documentate mostrano fasi operative correlate/);assert.doesNotMatch(html,/Le prime due situazioni documentano/,'subsumed lower-order relationship must not be re-presented as a second Representation');
// Level-1 nonredundancy: H1 subsumes R1/R2 while distinct R3 remains eligible.
const selectionMeaning={higherOrderDescriptiveProfessionalStructures:[{status:'accepted',structureId:'H1',structureWording:'bounded higher-order structure',compositionBasis:'controlled composition',contributorRefs:['R1','R2'],materialRefs:['m1','m2'],sourceRefs:['s1','s2'],persistent:false}],groundedDescriptiveRelationships:[rel('R1',['m1'],['s1']),rel('R2',['m2'],['s2']),rel('R3',['m3','m4'],['s3','s4'])],supportedPatterns:[],selectedEpisodeContributions:[],knowledgeContribution:[]};
const selectionThreads=composeProfessionalThreads({professionalMeaning:selectionMeaning});const selected=selectLevel1ProfessionalThreads(selectionThreads);assert(selected.some(x=>x?.meaning?.structureRef==='H1'));assert(selected.some(x=>x?.meaning?.relationshipRef==='R3'));assert(!selected.some(x=>['R1','R2'].includes(x?.meaning?.relationshipRef)));assert(selected.length<=3);
const multiHigher=composeProfessionalThreads({professionalMeaning:{...selectionMeaning,higherOrderDescriptiveProfessionalStructures:[selectionMeaning.higherOrderDescriptiveProfessionalStructures[0],{...selectionMeaning.higherOrderDescriptiveProfessionalStructures[0],structureId:'H2',structureWording:'second distinct structure',contributorRefs:['R3']},{...selectionMeaning.higherOrderDescriptiveProfessionalStructures[0],structureId:'H3',structureWording:'third distinct structure',contributorRefs:['R4']},{...selectionMeaning.higherOrderDescriptiveProfessionalStructures[0],structureId:'H4',structureWording:'fourth distinct structure',contributorRefs:['R5']}]}});assert.equal(selectLevel1ProfessionalThreads(multiHigher).length,3);
console.log('PD-070I controlled higher-order vertical slice: PASS');
