import assert from 'node:assert/strict';
import {buildTargetIndependentProfessionalRepresentation} from '../src/app/buildTargetIndependentProfessionalRepresentation.js';
import {buildCandidateApplicationMaterials} from '../src/app/opportunityApplication/candidateApplicationMaterial.js';
const policy='professional_semantic_policy:quantified_outcome:v1';
const qo=(relationship='contributed',causality='contribution_only',approximate=true)=>({semanticType:'quantified_outcome',semanticPolicyRef:policy,knowledgeSnapshot:{snapshotId:'ks-qo-20'},observation:{observationId:'qo:20',observationType:'quantified_outcome',observationStatus:'observed',evidenceIds:['e-qo-20'],measurableOutcome:'il progetto ha ridotto i tempi di attraversamento',quantitativeValue:{value:20,unit:'percent',approximate,direction:'decrease'},contributionRelationship:relationship,causalityBoundary:causality,context:{event:'intervento di miglioramento'},limitations:['Sole personal causality is not established.'],extensions:{semanticProvenance:{semanticPolicyRef:policy,knowledgeAcquisitionExecutionRef:'knowledgeAcquisitionExecution:qo-20'}}},measurementResult:{extensions:{projection:{meaning:'supported_presence_not_magnitude_score'}}}});
const rep=await buildTargetIndependentProfessionalRepresentation({reusableKnowledgeResults:[qo()],locale:'it',useModel:false});
const kc=rep.professionalMeaning.knowledgeContribution.find(x=>x.semanticType==='quantified_outcome');
assert(kc);assert.equal(kc.authorisedSemanticPayload.quantitativeValue.value,20);assert.equal(kc.authorisedSemanticPayload.quantitativeValue.approximate,true);assert.equal(kc.authorisedSemanticPayload.causalityBoundary,'contribution_only');
const identity={professionalSources:[],representationSnapshots:[{representation:rep}]};
const materials=buildCandidateApplicationMaterials({professionalIdentity:identity});
const item=materials.find(x=>x.materialKind==='canonical_quantified_outcome');assert(item);
assert.equal(item.semanticProtection.state,'established');assert.equal(item.languageTransformationEligibility,'eligible');assert.equal(item.authorisedPayload.quantitativeValue.value,20);assert.equal(item.authorisedPayload.quantitativeValue.approximate,true);assert.equal(item.authorisedPayload.contributionRelationship,'contributed');assert.equal(item.authorisedPayload.causalityBoundary,'contribution_only');
assert(item.semanticProtection.dimensions.some(x=>x.dimension==='result_attribution'&&x.value==='contribution_only'));
assert(item.semanticProtection.dimensions.some(x=>x.dimension==='epistemic'&&x.value==='approximate_quantitative_value'));
assert(item.provenance.evidenceRefs.includes('e-qo-20'));assert.equal(item.provenance.authority,policy);
const rawIdentity={professionalSources:[{id:'raw-20',sourceRole:'professional_declaration',content:'Risultato del progetto: circa 20%.'}],representationSnapshots:[]};
const raw=buildCandidateApplicationMaterials({professionalIdentity:rawIdentity}).find(x=>x.materialKind==='raw_legacy_source');assert(raw);assert.equal(raw.semanticProtection.state,'insufficiently_established');assert.equal(raw.languageTransformationEligibility,'not_eligible');
assert.equal(materials.some(x=>x.materialKind==='canonical_quantified_outcome'&&x.authorisedPayload.causalityBoundary==='sole_causality_established'),false);
assert(!JSON.stringify(item).match(/leadership|seniority|fit|readiness|language proficiency/i));
const biomedical=await buildTargetIndependentProfessionalRepresentation({reusableKnowledgeResults:[{...qo('contributed','contribution_only',true),observation:{...qo().observation,observationId:'qo:bio',evidenceIds:['e-bio'],measurableOutcome:'il protocollo di validazione ha ridotto i retest',context:{event:'diagnostic validation'}}}],locale:'it',useModel:false});
const bioItem=buildCandidateApplicationMaterials({professionalIdentity:{professionalSources:[],representationSnapshots:[{representation:biomedical}]}}).find(x=>x.materialKind==='canonical_quantified_outcome');assert(bioItem);assert.equal(bioItem.authorisedPayload.causalityBoundary,'contribution_only');
console.log('QO-01 quantified outcome Application Material routing PASSED');
