import assert from 'node:assert/strict';
import {evaluateCareerDirections} from '../src/app/careerDirection/evaluateCareerDirections.js';
import {startDirectionPeopleResponsibilityProductionAcquisition,answerDirectionPeopleResponsibilityProductionAcquisition} from '../src/app/careerDirection/directionKnowledgeAcquisition.js';
import {buildContinuingPeopleResponsibilityProductionSemanticPrompt} from '../src/app/knowledge/buildContinuingPeopleResponsibilityProductionSemanticPrompt.js';
const now='2026-09-28T19:00:00.000Z',subjectRef={type:'person',id:'pd073-fifth'};
const rep={professionalMeaning:{supportedPatterns:[{kind:'documented_cross_functional_coordination_recurrence'}],professionalSynthesis:{hasDocumentedRoleContinuity:true,currentRole:'Production Supervisor',previousRoles:['Industrialization Engineer'],domains:['production']},knowledgeContribution:[{primaryProfessionalMeaning:{kind:'bounded_decision_accountability'}},{primaryProfessionalMeaning:{kind:'bounded_measurable_outcome_contribution'}}]}};
const evaluation=evaluateCareerDirections({professionalRepresentation:rep,professionalRepresentationRef:'professionalRepresentation:pd073-fifth',now}),ops=evaluation.hypotheses.find(x=>x.metadata.roleFamilyRef==='operations_management');
const identity={type:'private_beta_professional_identity_continuity',personRef:subjectRef,professionalSources:[],reusableKnowledgeResults:[]};
const answer='Ho gestito continuativamente circa 5 persone di officina, assegnando le attività e definendo le priorità di lavoro.';
const base={interpretationStatus:'SUPPORTED',responsibilityPresence:'supported',continuity:'continuing',responsibilityKinds:['work_assignment_or_priority_setting'],peopleScope:{kind:'category',value:'circa 5 persone',min:null,max:null},professionalContext:{description:'officina',current:true},eventTime:{description:null},support:{presence:'Ho gestito',continuity:'continuativamente',mode:null,peopleScope:'circa 5 persone',professionalContext:'officina',responsibilityKinds:['assegnando le attività']},limitations:['formal reporting authority not established']};
const start=()=>startDirectionPeopleResponsibilityProductionAcquisition({careerDirectionEvaluation:evaluation,selectedDirectionRef:ops.id,userAction:'deepen_career_direction',professionalIdentity:identity,subjectRef,professionalRepresentationRef:'professionalRepresentation:pd073-fifth',now});
let state=await start();
let done=await answerDirectionPeopleResponsibilityProductionAcquisition({state,answer,careerDirectionEvaluation:evaluation,subjectRef,now,semanticExecutor:async()=>({supported:true,candidate:{...base,responsibilityMode:'insufficient'},provider:{model:'test'}})});
assert.equal(done.result.observation.observationStatus,'insufficient');
assert.equal(done.result.specializedMeasurementResult.resultStatus,'insufficient');
assert.equal(done.result.personKnowledgeMatrix,null);
assert.equal(done.operationalFailure.canonicalDiagnostic.insufficiencyReason,'responsibility_mode_insufficient');
assert.equal(done.operationalFailure.canonicalDiagnostic.responsibilityMode,'insufficient');
state=await start();
done=await answerDirectionPeopleResponsibilityProductionAcquisition({state,answer,careerDirectionEvaluation:evaluation,subjectRef,now,semanticExecutor:async()=>({supported:true,candidate:{...base,responsibilityMode:'informal_operational',support:{...base.support,mode:'assegnando le attività'}},provider:{model:'test'}})});
assert.equal(done.status,'resolved');
assert(done.knowledgeResult.personKnowledgeMatrix);
const detail=done.knowledgeResult.personKnowledgeMatrix.extensions.semanticDetails.continuing_people_responsibility;
assert.equal(detail.responsibilityMode,'informal_operational');
assert.equal(detail.continuity,'continuing');
assert.deepEqual(detail.responsibilityKinds,['work_assignment_or_priority_setting']);
assert.equal(detail.peopleScope.kind,'category');
assert(done.resolutions.every(x=>x.resolutionState==='resolved_by_current_authorised_state'));
const prompt=buildContinuingPeopleResponsibilityProductionSemanticPrompt({evidence:{content:{answerText:answer}}});
assert(prompt.systemText.includes('Use informal_operational when the Evidence explicitly establishes recurring/continuing responsibility over people-work through concrete operational responsibility such as assigning work or setting priorities'));
assert(prompt.systemText.includes('Generic coordination, collaboration, project leadership or team membership alone must remain insufficient'));
assert(prompt.systemText.includes('Do not propose formal_line'));
console.log('PD-073 fifth corrective CPR canonical Knowledge production completion tests passed.');
