import assert from 'node:assert/strict';
import {createPrivateBetaUiServer} from '../src/app/privateBetaUiServer.js';
import {evaluateCareerDirections} from '../src/app/careerDirection/evaluateCareerDirections.js';
import {startDirectionPeopleResponsibilityProductionAcquisition} from '../src/app/careerDirection/directionKnowledgeAcquisition.js';

const now='2026-09-28T15:00:00.000Z', personRef={type:'person',id:'operator-test'};
const rep={professionalMeaning:{supportedPatterns:[{kind:'documented_cross_functional_coordination_recurrence'}],professionalSynthesis:{hasDocumentedRoleContinuity:true,currentRole:'Production Supervisor',previousRoles:[],domains:['production']},knowledgeContribution:[]}};
const evaluation=evaluateCareerDirections({professionalRepresentation:rep,professionalRepresentationRef:'professionalRepresentation:operator-test',now});
const ops=evaluation.hypotheses.find(x=>x.metadata.roleFamilyRef==='operations_management');
async function baseState(){const acquisition=await startDirectionPeopleResponsibilityProductionAcquisition({careerDirectionEvaluation:evaluation,selectedDirectionRef:ops.id,userAction:'deepen_career_direction',professionalIdentity:{professionalSources:[],reusableKnowledgeResults:[]},subjectRef:personRef,professionalRepresentationRef:'professionalRepresentation:operator-test',now});return {type:'direction_explore_state',personRef,careerDirectionEvaluation:evaluation,directionAcquisition:acquisition,reusableProfessionalIdentity:{personRef,professionalSources:[],reusableKnowledgeResults:[]}};}
async function run({enabled,executor,sessionRef}){const sessionStore=new Map([[sessionRef,await baseState()]]);const logs=[];const prior=console.error;console.error=(...a)=>logs.push(a.join(' '));const server=createPrivateBetaUiServer({operatorDiagnosticsEnabled:enabled,sessionStore,locale:'it',journeyOptions:{directionPeopleResponsibilitySemanticExecutor:executor}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;try{const answer='SENSITIVE CANDIDATE ANSWER';const res=await fetch(`http://127.0.0.1:${port}/private-beta/direction/answer`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({sessionRef,answer})});assert.equal(res.status,200);const trace=await fetch(`http://127.0.0.1:${port}/private-beta/operator/semantic-trace?sessionRef=${sessionRef}`);return {logs,traceStatus:trace.status,payload:trace.status===200?await trace.json():null,answer};}finally{console.error=prior;await new Promise(r=>server.close(r));}}

const providerFailure=Object.assign(new Error('raw provider secret'),{providerDiagnostic:{failureKind:'rate_limit',status:429,providerCode:'rate_limit_exceeded',providerType:'tokens',model:'openai/gpt-oss-120b',outputMode:'json_object',structuredOutput:false,elapsedMs:1234,httpAttemptsUsed:2,rawResponse:'DO NOT EXPOSE'},initialStructuredOutputRecovery:{attempted:true,succeeded:false,mode:'json_object',initialFailureDiagnostic:{failureKind:'structured_output_rejected',raw:'DO NOT EXPOSE'}}});
let result=await run({enabled:true,sessionRef:'pd073sc-provider',executor:async()=>{throw providerFailure;}});
assert.equal(result.traceStatus,200);let d=result.payload.semanticExecutionTraces.find(x=>x.boundary==='career_direction_people_responsibility_acquisition');assert(d);assert.equal(d.providerFailureKind,'rate_limit');assert.equal(d.httpStatus,429);assert.equal(d.providerCode,'rate_limit_exceeded');assert.equal(d.pd073Recovery.attempted,true);assert.equal(d.pd073Recovery.succeeded,false);assert.equal(d.pd073Recovery.mode,'json_object');assert.equal(d.pd073Recovery.initialFailureKind,'structured_output_rejected');assert(result.logs.some(x=>x.startsWith('[IMAGO operator career direction acquisition diagnostic]')));let serialized=JSON.stringify({d,logs:result.logs});assert(!serialized.includes(result.answer));assert(!serialized.includes('raw provider secret'));assert(!serialized.includes('DO NOT EXPOSE'));assert(!serialized.includes('api'));

result=await run({enabled:true,sessionRef:'pd073sc-semantic',executor:async()=>({supported:false,reason:'invalid_provider_output',diagnostic:{category:'candidate_rejected',validationErrors:['responsibilityKinds are invalid.']}})});d=result.payload.semanticExecutionTraces.find(x=>x.boundary==='career_direction_people_responsibility_acquisition');assert.equal(d.stage,'semantic_candidate');assert.equal(d.category,'invalid_provider_candidate');assert.equal(d.providerCategory,'candidate_rejected');assert.equal(d.providerFailureKind,null);serialized=JSON.stringify({d,logs:result.logs});assert(serialized.includes('responsibilityKinds are invalid.'));

result=await run({enabled:false,sessionRef:'pd073sc-disabled',executor:async()=>{throw providerFailure;}});assert.equal(result.traceStatus,404);assert.equal(result.logs.length,0);
console.log('PD-073 second corrective operator diagnostic exposure tests passed.');
