import fs from 'node:fs';
import assert from 'node:assert/strict';
const ui=fs.readFileSync('src/app/renderPrivateBetaUiJourneyHtml.js','utf8');
assert.match(ui,/direction-preferences-compact/);
assert.match(ui,/direction-overview-card/);
assert.match(ui,/direction-detail/);
assert.match(ui,/direction-state-well-supported/);
assert.match(ui,/direction-state-needs-clarification/);
assert.match(ui,/direction-state-confirmed-absence/);
assert.match(ui,/direction-next-steps/);
assert.match(ui,/direction-traceability/);
assert.match(ui,/direction-state-needs-clarification>ul>li/);
assert.match(ui,/const populatedRelevance=.*filter\(x=>x\.material\|\|x\.requirement\|\|x\.relSources\.length\)/s);
assert.match(ui,/sources\.length\?`<p>\$\{escapeHtml\(m\.directionSourceSupportedBy\)\}/);
assert.match(ui,/meaningfulPresentationText/);
assert.match(ui,/\.map\(src=>\{const label=.*return head\|\|title\?`<li>/s);
assert.match(ui,/direction-technical-provenance ul:empty\{display:none\}/);
assert.match(ui,/@media\(max-width:720px\)/);
assert.match(ui,/<details class="direction-traceability"><summary>/);
assert.doesNotMatch(ui,/direction-traceability" open/);
console.log('PD-072G career direction visual hierarchy tests passed.');
