const assert=require('assert');const A=require('../src/app/knowledge');const {buildFixture}=require('./knowledge_acquisition_capability_configuration_fixture');
const f=buildFixture(),configuration=A.buildKnowledgeAcquisitionCapabilityConfiguration(f.composed.input);
const context=(overrides={})=>A.validateKnowledgeAcquisitionCapabilityConfigurationContext({capabilityConfiguration:configuration,knowledgeAcquisitionSolutionDecision:f.composed.solutionDecision,capabilityCompositionDesign:f.composed.compositionDesign,selectedCapabilitySnapshots:f.composed.selectedCapabilitySnapshots,configurationDefinition:f.composed.configurationDefinition,applicationConfigurationInput:f.composed.applicationConfigurationInput,...overrides});
assert(context().valid,context().errors.join(' | '));
const mismatch=JSON.parse(JSON.stringify(f.single.compositionDesign||f.composed.compositionDesign));mismatch.sourceSolutionDecisionRef='knowledgeAcquisitionSolutionDecision:wrong';assert(!context({capabilityCompositionDesign:mismatch}).valid);
const missing=JSON.parse(JSON.stringify(f.composed.applicationConfigurationInput));missing.configurationItems=missing.configurationItems.filter(x=>x.parameterRef!=='parameter:format');assert(context({applicationConfigurationInput:missing}).errors.some(x=>/Required parameter/.test(x)));
const unknown=JSON.parse(JSON.stringify(f.composed.applicationConfigurationInput));unknown.configurationItems.push({capabilityRef:f.composed.solutionDecision.selectedCapabilityRefs[0],parameterRef:'parameter:unknown',value:true});assert(context({applicationConfigurationInput:unknown}).errors.some(x=>/Unknown parameter/.test(x)));
const duplicate=JSON.parse(JSON.stringify(f.composed.applicationConfigurationInput));duplicate.configurationItems.push({...duplicate.configurationItems[0]});assert(context({applicationConfigurationInput:duplicate}).errors.some(x=>/Duplicate parameter/.test(x)));
console.log('Knowledge Acquisition Capability Configuration context tests PASSED');
