import assert from 'node:assert/strict';
import { buildTargetIndependentProfessionalRepresentation } from '../src/app/buildTargetIndependentProfessionalRepresentation.js';
import { createPrivateBetaUiServer } from '../src/app/privateBetaUiServer.js';
const sources=[{id:'a',sourceRole:'professional_declaration',content:'Alpha private raw source text'},{id:'b',sourceRole:'professional_declaration',content:'Beta private raw source text'}];
const projection=sources.map((s,i)=>({sourceId:s.id,sourceRole:s.sourceRole,facts:[`fact-${i}`],roleDescriptionFacts:[],domainSignals:[],experienceHighlights:[`bounded-${i}`],sourceFaithfulExperienceExcerpts:[`support-${i}`],activitySemantics:[]}));
const dclaim={subjectScope:'source_material',descriptiveRole:'work_phase',agencyLevel:'not_established',responsibilityScope:'not_established',ownershipAssertion:'none',decisionAuthorityAssertion:'none',resultCausalityAssertion:'none',personPropertyAssertion:'none'};
const rclaim={subjectScope:'material_relationship',relationshipClaim:'descriptive_relationship',personPropertyAssertion:'none',capabilityAssertion:'none',ownershipAssertion:'none',responsibilityAssertion:'none',causalityAssertion:'none',fitReadinessAssertion:'none',sameEpisodeAssertion:'none',continuityAssertion:'none'};
const descriptorProposalProvider=async()=>sources.map((s,i)=>({descriptorRole:'work_phase',descriptiveValue:`phase-${i}`,materialRef:`source:${s.id}`,grounding:{exactText:`support-${i}`,supportRef:`source:${s.id}:support:1`},provenance:{providerRef:'controlled',proposalRef:`d${i}`},claimShape:dclaim,persistence:'representation_only'}));
const relationshipHypothesisProvider=async({descriptors})=>[{descriptorRefs:descriptors.map(x=>x.descriptorId),relationshipWording:'Two documented materials expose a bounded operational relation.',relationshipBasis:'controlled bounded relation',provenance:{providerRef:'controlled',proposalRef:'r1'},claimShape:rclaim,persistence:'representation_only'}];
const hclaim={subjectScope:'documented_material_structure',structureClaim:'descriptive_combination',personPropertyAssertion:'none',continuityAssertion:'none',leadershipAssertion:'none',ownershipAssertion:'none',responsibilityAssertion:'none',generalAutonomyAssertion:'none',resultCausalityAssertion:'none',targetRelationAssertion:'none'};
const higherOrderProposalProvider=async({contributors})=>[{proposalRef:'h1',contributorRefs:contributors.map(x=>x.relationshipId),structureWording:'The documented situations jointly expose one bounded configuration.',compositionBasis:'controlled second-order composition',claimShape:hclaim,persistence:'representation_only',targetInputs:[],providerAuthority:false}];
const records=[];
const args={professionalSources:sources,sourceGroundedProjection:projection,descriptorProposalProvider,relationshipHypothesisProvider,higherOrderProposalProvider};
const without=await buildTargetIndependentProfessionalRepresentation(args);
const withDiag=await buildTargetIndependentProfessionalRepresentation({...args,higherOrderProviderDiagnosticReader:()=>({status:'ok',elapsedMs:17,result:{model:'controlled-model'}}),professionalSynthesisDiagnosticSink:r=>records.push(r)});
assert.deepEqual(withDiag,without,'operator diagnostics must not change semantic output');
assert.equal(records.length,1);const diag=records[0];
assert.equal(diag.pd069.acceptedRelationships.length,1);assert.equal(diag.pd070.inputContributorRefs.length,1);assert.equal(diag.pd070.model,'controlled-model');assert.equal(diag.pd070.elapsedMs,17);assert.equal(diag.pd070.proposals.length,1);assert.equal(diag.pd070.proposals[0].accepted,false); // only one relationship cannot satisfy min contributor count
assert(Array.isArray(diag.downstream.professionalThreads));assert(Array.isArray(diag.downstream.level1ThreadIds));
assert(diag.pd069.acceptedRelationships[0].descriptors.every(x=>'descriptorRole' in x&&'descriptiveValue' in x));
assert(diag.upstreamStructuredBreadth&&Array.isArray(diag.upstreamStructuredBreadth.episodeMeanings));
const serial=JSON.stringify(diag);assert(!serial.includes('Alpha private raw source text'));assert(!serial.includes('Beta private raw source text'));assert(!serial.includes('GROQ_API_KEY'));assert(!serial.includes('rawCv'));assert(!serial.includes('interviewTranscript'));assert(!serial.includes('jdText'));

const failureRecords=[];await buildTargetIndependentProfessionalRepresentation({...args,higherOrderProviderDiagnosticReader:()=>({status:'failed',elapsedMs:23,failure:{failureKind:'rate_limit',errorClass:'provider',httpStatus:429,providerCode:'rate_limit_exceeded',providerType:'tokens',providerMessage:'Provider rate limit reached.',stage:'model_call_failed',task:'higherOrderProfessionalSynthesis',model:'controlled-model',timeout:false,structuredOutput:false,parsing:false}}),professionalSynthesisDiagnosticSink:r=>failureRecords.push(r)});assert.equal(failureRecords[0].pd070.failure.failureKind,'rate_limit');assert.equal(failureRecords[0].pd070.failure.httpStatus,429);assert.equal(failureRecords[0].pd070.failure.providerCode,'rate_limit_exceeded');assert.equal(failureRecords[0].pd070.model,'controlled-model');
// Operator endpoint is gated and retrieves disposable context-scoped diagnostic state.
const store=[{requestRef:'req:1',contextRef:'ctx:1',boundary:'pd070_real_professional_synthesis',pd069:{acceptedRelationships:[]}}];
const enabled=createPrivateBetaUiServer({operatorDiagnosticsEnabled:true,professionalSynthesisDiagnosticStore:store});await new Promise(r=>enabled.listen(0,'127.0.0.1',r));let response=await fetch(`http://127.0.0.1:${enabled.address().port}/private-beta/operator/professional-synthesis-diagnostics?contextRef=ctx:1`);assert.equal(response.status,200);let payload=await response.json();assert.equal(payload.professionalSynthesisDiagnostics.length,1);await new Promise(r=>enabled.close(r));
const disabled=createPrivateBetaUiServer({operatorDiagnosticsEnabled:false,professionalSynthesisDiagnosticStore:store});await new Promise(r=>disabled.listen(0,'127.0.0.1',r));response=await fetch(`http://127.0.0.1:${disabled.address().port}/private-beta/operator/professional-synthesis-diagnostics?contextRef=ctx:1`);assert.equal(response.status,404);await new Promise(r=>disabled.close(r));
// Real server wiring passes the operator-only sink into the production staged preparation boundary.
const wiredStore=[];const wired=createPrivateBetaUiServer({operatorDiagnosticsEnabled:true,professionalSynthesisDiagnosticStore:wiredStore,contextIdFactory:()=> 'ctx-wired',stagedPrepare:async({professionalSynthesisDiagnosticSink})=>{professionalSynthesisDiagnosticSink?.({boundary:'pd070_real_professional_synthesis',pd069:{acceptedRelationships:[{relationshipId:'R-wired'}]},pd070:{inputContributorRefs:['R-wired'],proposals:[],acceptedStructureIds:[]},downstream:{professionalThreads:[],level1ThreadIds:[],explicitSubsumedRelationshipRefs:[]}});return {publicResult:{status:'understanding',completed:false,phase:'purpose_understand'},state:null};}});await new Promise(r=>wired.listen(0,'127.0.0.1',r));response=await fetch(`http://127.0.0.1:${wired.address().port}/private-beta/journey`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({identityAction:'create',productPurpose:'professional_representation_understand'})});assert.equal(response.status,200);response=await fetch(`http://127.0.0.1:${wired.address().port}/private-beta/operator/professional-synthesis-diagnostics?contextRef=ctx-wired`);payload=await response.json();assert.equal(payload.professionalSynthesisDiagnostics[0].pd069.acceptedRelationships[0].relationshipId,'R-wired');await new Promise(r=>wired.close(r));
assert(!JSON.stringify(withDiag).includes('professionalSynthesisDiagnostics'));assert(!JSON.stringify(withDiag).includes('personKnowledgeWriteback'));
console.log('PD-070O real professional synthesis observability: PASS');
