import assert from 'node:assert/strict';
import { buildTargetIndependentRepresentationSnapshotState, buildRepresentationMaterializationProvenance, materializeTargetIndependentRepresentationSnapshot, attachRepresentationSnapshotToProfessionalIdentity, findReusableTargetIndependentRepresentationSnapshot, isRepresentationSnapshotReuseEligible } from '../src/app/privateBetaProfessionalRepresentationSnapshots.js';

const at='2026-09-24T12:00:00.000Z',personRef={type:'person',id:'private-beta-person:gm04'};
const source={id:'current_cv',type:'text',sourceRole:'current_cv',content:'Production Supervisor',provenance:{origin:'current_cv',providedBy:'user',collectedAt:at}};
const base={version:'1.0',type:'private_beta_professional_identity_continuity',professionalIdentityRef:`professionalIdentity:${personRef.id}`,personRef,owner:'person',professionalSources:[source],reusableKnowledgeResults:[],representationSnapshots:[],currentRepresentationSnapshotRefs:{}};
const state=buildTargetIndependentRepresentationSnapshotState({professionalIdentity:base,professionalSources:[source],reusableKnowledgeResults:[],authorizationState:'accepted'});
const rep=label=>({type:'target_independent_professional_representation',label,professionalMeaning:{professionalThreads:[],level1ProfessionalThreads:[]},provenance:{sourceIds:['current_cv']},limitations:[]});
const degradedProv=buildRepresentationMaterializationProvenance({liveSynthesisRequired:true,pd069Status:'ok',pd070Status:'failed',higherOrderSynthesisApplicable:true});
assert.equal(degradedProv.materializationStatus,'degraded');assert.equal(degradedProv.providerFallbackUsed,true);assert.equal(degradedProv.higherOrderSynthesisCompleted,false);
const completeProv=buildRepresentationMaterializationProvenance({liveSynthesisRequired:true,pd069Status:'ok',pd070Status:'ok',higherOrderSynthesisApplicable:true});
assert.equal(completeProv.materializationStatus,'complete');assert.equal(completeProv.providerFallbackUsed,false);assert.equal(completeProv.higherOrderSynthesisCompleted,true);
const degraded=materializeTargetIndependentRepresentationSnapshot({professionalIdentity:base,state,representation:rep('degraded'),materializationProvenance:degradedProv,now:at});
let record=attachRepresentationSnapshotToProfessionalIdentity({professionalIdentity:base,snapshot:degraded});
assert.equal(findReusableTargetIndependentRepresentationSnapshot({professionalIdentity:record,state}).materializationStatus,'degraded','display-safe degraded snapshot remains reusable on ordinary view');
const complete=materializeTargetIndependentRepresentationSnapshot({professionalIdentity:record,state,representation:rep('complete'),materializationProvenance:completeProv,now:'2026-09-24T12:01:00.000Z'});
assert.equal(complete.snapshotId,degraded.snapshotId,'same Candidate-state fingerprint keeps stable snapshot identity');
record=attachRepresentationSnapshotToProfessionalIdentity({professionalIdentity:record,snapshot:complete});
assert.equal(record.representationSnapshots.length,1);assert.equal(record.representationSnapshots[0].materializationStatus,'complete');assert.equal(record.representationSnapshots[0].representation.label,'complete');
assert.equal(findReusableTargetIndependentRepresentationSnapshot({professionalIdentity:record,state}).materializationStatus,'complete');
const laterDegraded=materializeTargetIndependentRepresentationSnapshot({professionalIdentity:record,state,representation:rep('later degraded'),materializationProvenance:degradedProv,now:'2026-09-24T12:02:00.000Z'});
const preserved=attachRepresentationSnapshotToProfessionalIdentity({professionalIdentity:record,snapshot:laterDegraded});
assert.equal(preserved.representationSnapshots[0].materializationStatus,'complete');assert.equal(preserved.representationSnapshots[0].representation.label,'complete','COMPLETE must not be downgraded by later DEGRADED');
const incomplete={...complete,materializationStatus:'incomplete',materializationProvenance:{...complete.materializationProvenance,materializationStatus:'incomplete'},representation:null};
assert.equal(isRepresentationSnapshotReuseEligible(incomplete),false);assert.equal(findReusableTargetIndependentRepresentationSnapshot({professionalIdentity:{...base,representationSnapshots:[incomplete]},state}),null);
const roundTrip=JSON.parse(JSON.stringify(record));assert.equal(roundTrip.representationSnapshots[0].materializationProvenance.materializationStatus,'complete');
const changedState=buildTargetIndependentRepresentationSnapshotState({professionalIdentity:record,professionalSources:[{...source,content:'changed'}],reusableKnowledgeResults:[],authorizationState:'accepted'});assert.equal(findReusableTargetIndependentRepresentationSnapshot({professionalIdentity:record,state:changedState}),null);
assert.deepEqual(base.reusableKnowledgeResults,[],'snapshot completion must not mutate Person Knowledge');
console.log('GM-04 Representation completion provenance and same-fingerprint supersession: PASS');
