const assert=require('assert');
const fs=require('fs');
const {buildFhtLiveAcquisitionPurposePlanning}=require('../src/app/knowledge/buildFhtLiveAcquisitionPurposePlanning');
const {selectFhtAdaptiveAcquisitionDecision}=require('../src/app/knowledge/selectFhtAdaptiveAcquisitionDecision');
const {runFhtLiveAcquisitionSemanticBridge}=require('../src/app/knowledge/runFhtLiveAcquisitionSemanticBridge');
const NOW='2026-09-04T08:30:00.000Z';
(async()=>{
 const {buildGroundedConversationalContext,groundAdaptiveFollowupPack}=await import('../src/interview/groundAdaptiveFollowup.js');
 const planning=buildFhtLiveAcquisitionPurposePlanning({subjectRef:{type:'person',id:'as01'},sessionKey:'as01',now:NOW});
 assert.deepEqual(planning.activeGoals,['decision_accountability','quantified_outcome']);
 const daKnowledge=[{semanticType:'decision_accountability',knowledgeSnapshot:{snapshotId:'ks:da'}}];
 const available=['decision_tradeoff_probe','responsibility_probe','achievement_quantification'];
 const base=selectFhtAdaptiveAcquisitionDecision({planning,runtimeKnowledgeResults:daKnowledge,availableActionKeys:available,acceptedAnswerText:'Ho gestito il progetto con il team.'});
 assert(base.applicable);assert.equal(base.purpose,'quantified_outcome');assert.equal(base.actionKey,'achievement_quantification');
 assert(base.association.purposeRefs.some(x=>x.goal==='quantified_outcome'));
 const daState=base.trace.candidatePurposes.find(x=>x.goal==='decision_accountability');
 const qoState=base.trace.candidatePurposes.find(x=>x.goal==='quantified_outcome');
 assert.equal(daState.state,'represented');assert.equal(qoState.state,'not_observed');assert(qoState.priority>daState.priority);
 const opened=selectFhtAdaptiveAcquisitionDecision({planning,runtimeKnowledgeResults:daKnowledge,availableActionKeys:available,acceptedAnswerText:'Il progetto ha portato a un miglioramento misurabile delle performance, che posso descrivere più nel dettaglio.'});
 assert.equal(opened.purpose,'quantified_outcome');
 assert(opened.trace.candidatePurposes.find(x=>x.goal==='quantified_outcome').priority>qoState.priority);
 assert.equal(opened.cue.referent,'miglioramento misurabile');
 const hostile=selectFhtAdaptiveAcquisitionDecision({planning,runtimeKnowledgeResults:daKnowledge,availableActionKeys:available,acceptedAnswerText:'Ho creato una nuova dimensione leadership_universale con questa risposta.'});
 assert.deepEqual(hostile.trace.candidatePurposes.map(x=>x.goal).sort(),['decision_accountability','quantified_outcome']);
 const daOnly=buildFhtLiveAcquisitionPurposePlanning({subjectRef:{type:'person',id:'as01-da'},activeGoals:['decision_accountability'],sessionKey:'as01-da',now:NOW});
 const repeat=selectFhtAdaptiveAcquisitionDecision({planning:daOnly,availableActionKeys:['decision_tradeoff_probe','responsibility_probe'],usedActionKeys:['decision_tradeoff_probe']});
 assert.equal(repeat.actionKey,'responsibility_probe');
 const planningSource=fs.readFileSync(require.resolve('../src/app/knowledge/buildFhtLiveAcquisitionPurposePlanning'),'utf8');
 const selectorSource=fs.readFileSync(require.resolve('../src/app/knowledge/selectFhtAdaptiveAcquisitionDecision'),'utf8');
 assert(planningSource.includes('PURPOSE_RUNTIME_ACTION_IDENTITIES'));
 assert(!selectorSource.includes('PURPOSE_RUNTIME_ACTION_IDENTITIES'));assert(!selectorSource.includes('achievement_quantification'));assert(!selectorSource.includes('decision_tradeoff_probe'));
 const toolPack={triggerType:'tool_adaptation',followups:['Quanto è simile lo strumento che hai usato rispetto a quello richiesto qui?','Quanto rapidamente hai imparato nuovi strumenti nei ruoli precedenti?']};
 const missingTool=groundAdaptiveFollowupPack({followupPack:toolPack,groundedContext:buildGroundedConversationalContext({answerText:'Ho lavorato in diversi contesti.'})});
 assert(missingTool.valid);assert.equal(missingTool.validationOutcome,'safe_non_presuppositive_pivot');assert(!missingTool.pack.followups[0].includes('lo strumento che hai usato'));
 const groundedTool=groundAdaptiveFollowupPack({followupPack:toolPack,groundedContext:buildGroundedConversationalContext({explicitReferents:[{type:'tool_used',text:'SAP'},{type:'tool_required',text:'Oracle'}]})});
 assert(groundedTool.valid);assert.equal(groundedTool.validationOutcome,'grounded');assert.equal(groundedTool.selectedGroundedReferents.length,2);
 const measurable=buildGroundedConversationalContext({answerText:'Il progetto ha portato a un miglioramento misurabile delle performance.'});
 assert(measurable.referents.some(x=>x.type==='measurable_result'&&x.text.toLowerCase()==='miglioramento misurabile'));
 const qoPack={triggerType:'achievement_quantification',followups:['Come misuravi il successo in quel caso?']};
 const groundedQo=groundAdaptiveFollowupPack({followupPack:qoPack,groundedContext:measurable});assert(groundedQo.valid);assert.equal(groundedQo.selectedGroundedReferents[0].type,'measurable_result');
 const advanceSource=fs.readFileSync(require.resolve('../src/interview/advanceInterviewRuntime.js'),'utf8');
 assert(advanceSource.includes('selectFhtAdaptiveAcquisitionDecision'));assert(advanceSource.indexOf('selectFhtAdaptiveAcquisitionDecision')<advanceSource.indexOf('selectAdaptiveFollowup({'));
 assert(!selectorSource.includes('modelAdapter'))
 const noExecution=await runFhtLiveAcquisitionSemanticBridge({planning,acquisitionActionAssociation:null,acceptedAnswer:{answerText:'Miglioramento del 25%',timestamp:NOW},buildEvidenceStore:()=>({evidence:[]}),betaSessionId:'b',interviewSessionId:'i',subjectRef:{type:'person',id:'as01'},now:NOW});
 assert.deepEqual(noExecution,[]);
 console.log('FHT-AS01 adaptive acquisition decision and grounding tests PASS');
})().catch(e=>{console.error(e);process.exit(1)});
