import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {runGroqContinuingPeopleResponsibilitySemanticExecutor} from '../src/infrastructure/groq/runGroqContinuingPeopleResponsibilitySemanticExecutor.js';
import {runFullParserPipeline} from '../src/parser/runFullParserPipeline.js';
import {buildPrivateBetaSourceGroundedProjection} from '../src/app/buildPrivateBetaSourceGroundedProjection.js';
import {renderPrivateBetaUiJourneyHtml} from '../src/app/renderPrivateBetaUiJourneyHtml.js';
import {createPrivateBetaUiServer} from '../src/app/privateBetaUiServer.js';
import {createMemoryPrivateBetaFeedbackStore} from '../src/app/privateBetaContextualFeedback.js';

const answer='Da circa tre anni, in officina, gestisco direttamente circa 5 persone: assegno le attività e definisco le priorità di lavoro.';
const invalid={interpretationStatus:'SUPPORTED',responsibilityPresence:'supported',continuity:'continuing',responsibilityMode:'formal_line_management_NOT_AUTHORIZED',responsibilityKinds:['work_assignment_or_priority_setting'],peopleScope:{kind:'exact',value:'5',min:null,max:null},professionalContext:{description:'in officina',current:true},eventTime:{description:'Da circa tre anni'},support:{presence:'gestisco direttamente circa 5 persone',continuity:'Da circa tre anni',mode:'gestisco direttamente',peopleScope:'5',professionalContext:'in officina',responsibilityKinds:['assegno le attività e definisco le priorità di lavoro']},limitations:[]};
const valid={interpretationStatus:'SUPPORTED',responsibilityPresence:'supported',continuity:'continuing',responsibilityMode:'informal_operational',responsibilityKinds:['work_assignment_or_priority_setting'],peopleScope:{kind:'category',value:'circa 5 persone',min:null,max:null},professionalContext:{description:'in officina',current:true},eventTime:{description:'Da circa tre anni'},support:{presence:'gestisco direttamente circa 5 persone',continuity:'Da circa tre anni',mode:'gestisco direttamente',peopleScope:'circa 5 persone',professionalContext:'in officina',responsibilityKinds:['assegno le attività e definisco le priorità di lavoro']},limitations:['formal reporting authority not established']};
let semanticCalls=0;
const semantic=await runGroqContinuingPeopleResponsibilitySemanticExecutor({evidence:{content:{answerText:answer}},completionRunner:async args=>{semanticCalls++;return {content:JSON.stringify(semanticCalls===1?invalid:valid),model:'mock',outputMode:args.strictSchemaCompatible?'json_schema':'json_object',execution:{elapsedMs:10,httpAttemptsUsed:1}};}});
assert.equal(semantic.supported,true);assert.equal(semanticCalls,2);assert.equal(semantic.provider.pd073Recovery.attempted,true);assert.equal(semantic.provider.pd073Recovery.succeeded,true);

const candidateFixture=JSON.parse(await readFile(new URL('../fixtures/expected_candidate_profile_01.json',import.meta.url),'utf8'));
const roleFixture=JSON.parse(await readFile(new URL('../fixtures/expected_role_profile_01.json',import.meta.url),'utf8'));
const fitFixture=JSON.parse(await readFile(new URL('../fixtures/expected_job_fit_analysis_01.json',import.meta.url),'utf8'));
let parserTasks=[];
await runFullParserPipeline({cvText:'cached cv',jdText:'Operations Manager',professionalSources:[{id:'current_cv',content:'cached cv',sourceRole:'current_cv'}],precomputedCandidateProfile:candidateFixture.candidateProfile||candidateFixture,precomputedCandidateSourceProfiles:[{sourceId:'current_cv',candidateProfile:candidateFixture.candidateProfile||candidateFixture}],modelAdapter:async({task})=>{parserTasks.push(task);if(task==='candidateProfile')throw new Error('candidate profile should have been reused');if(task==='roleProfile')return JSON.stringify(roleFixture);if(task==='jobFitAnalysis')return JSON.stringify(fitFixture);return '{}';}});
assert(!parserTasks.includes('candidateProfile'));assert(parserTasks.includes('roleProfile'));assert(parserTasks.includes('jobFitAnalysis'));

const projection=buildPrivateBetaSourceGroundedProjection({professionalSources:[{id:'s1',content:'Per circa 3 anni ho diretto un team interfunzionale dedicato alla riduzione dei costi.',sourceRole:'professional_declaration'}],candidateSourceProfiles:[{sourceId:'s1',sourceRole:'professional_declaration',candidateProfile:{summary:'Direzione di un team interfunzionale per riduzione costi',currentPositioning:'unclear',domainSignals:['ottimizzazione dei costi'],experienceSignals:{roles:['Direzione di un team interfunzionale per riduzione costi'],contexts:['unclear'],yearsDetected:'3 anni',highlights:['Direzione di un team interfunzionale per riduzione costi'],supportExcerpts:['Per circa 3 anni ho diretto un team interfunzionale dedicato alla riduzione dei costi.']}}}]});
const facts=projection[0].facts;assert(!facts.includes('unclear'));assert(!facts.includes('3 anni'));assert.equal(facts.filter(x=>x==='Direzione di un team interfunzionale per riduzione costi').length,1);

const phases=[null,{phase:'profile'},{phase:'backup'},{phase:'start',navigationTarget:'professional_representation_understand'},{phase:'purpose_direction_explore',preInterview:{careerDirectionEvaluation:{hypotheses:[]}}},{phase:'start',navigationTarget:'opportunity_application'},{phase:'start',navigationTarget:'professional_identity_build_enrich'},{phase:'start',navigationTarget:'interview_practice'}];
for(const result of phases){const html=renderPrivateBetaUiJourneyHtml({locale:'it',result,identityAvailable:true,identitySummary:{professionalSources:[],reusableKnowledgeResults:[],knowledgeCount:0}});assert.match(html,/id="imago-beta-feedback-open"/);assert.match(html,/Feedback Beta/);assert.match(html,/Feedback inviati/);assert.match(html,/>Chiudi</);assert.match(html,/data-imago-processing/);}
const failSoft=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'interview',productPurpose:'interview_practice',preparationInput:{targetRole:'Operations Manager',jdText:'JD TEST'},error:{code:'SERVICE_UNAVAILABLE',retryable:true}},identityAvailable:true,identitySummary:{professionalSources:[],reusableKnowledgeResults:[]}});assert.match(failSoft,/JD TEST/);assert.match(failSoft,/Operations Manager/);assert.match(failSoft,/Riprova la preparazione/);assert.doesNotMatch(failSoft,/id="imago-product-landing"/);
const lowValue=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'purpose_build_enrich',productPurpose:'professional_identity_build_enrich',enrichmentOutcome:{rejectedLowValue:true,acceptedMaterial:false,changed:false},preInterview:{professionalSources:[]}},identityAvailable:true,identitySummary:{professionalSources:[],reusableKnowledgeResults:[]}});assert.match(lowValue,/non è sufficiente per aggiungere un nuovo elemento professionale/);
const serious=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'purpose_build_enrich',productPurpose:'professional_identity_build_enrich',enrichmentOutcome:{rejectedLowValue:false,acceptedMaterial:true,changed:true},preInterview:{professionalSources:[]}},identityAvailable:true,identitySummary:{professionalSources:[],reusableKnowledgeResults:[]}});assert.match(serious,/aggiunta ai materiali del tuo profilo/);

const feedbackStore=createMemoryPrivateBetaFeedbackStore();const feedbackConsentStore=new Map([['pd096c1',true]]);const server=createPrivateBetaUiServer({feedbackStore,feedbackConsentStore,contextIdFactory:()=> 'pd096c1'});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const base=`http://127.0.0.1:${server.address().port}`,cookie='imago_beta_repeat_context=pd096c1';let r=await fetch(base+'/private-beta/beta-feedback',{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({feedbackKind:'contextual',category:'positive_value',freeText:'Questa sintesi mi è stata utile',functionArea:'profile',route:'/private-beta/profile',workflowStep:'profile',profileLoaded:'true'})});assert.equal(r.status,201);r=await fetch(base+'/private-beta/beta-feedback?current=1',{headers:{cookie}});assert.equal(r.status,200);const payload=await r.json();assert.equal(payload.feedback.length,1);assert.equal(payload.feedback[0].freeText,'Questa sintesi mi è stata utile');assert.equal(Object.prototype.hasOwnProperty.call(payload.feedback[0],'route'),false);}finally{await new Promise(r=>server.close(r));}
console.log('PD-096 First Corrective Human-Test flow recovery completion: PASS');
