import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {buildAcceptedRuntimeAnswerEvidenceStore} from '../src/app/registerAcceptedRuntimeAnswerEvidence.js';
const require=createRequire(import.meta.url);
const K=require('../src/core/knowledge');const A=require('../src/app/knowledge');const I=require('../src/core/knowledge/knowledgeAcquisitionDeclarativeIdentity');const DF=require('./knowledge_acquisition_design_fixture');
const {resolveQuantifiedOutcomeSemanticAuthority}=require('../src/app/knowledge/resolveQuantifiedOutcomeSemanticAuthority');
const {runQuantifiedOutcomeSemanticKnowledgePath}=require('../src/app/knowledge/runQuantifiedOutcomeSemanticKnowledgePath');
const {validateKnowledgeAcquisitionDesign}=require('../src/core/knowledge/validateKnowledgeAcquisitionDesign');
const now='2026-09-03T10:00:00.000Z';const POLICY='professional_semantic_policy:quantified_outcome:v1';
function designFor(scopeRef='quantified_outcome',policy=POLICY){const c=DF.buildChain('elementary');const requirement=JSON.parse(JSON.stringify(c.requirement));requirement.scope='dimension';requirement.scopeRef=scopeRef;requirement.id=I.calculateKnowledgeAcquisitionRequirementId(requirement);return K.buildKnowledgeAcquisitionDesign({requirement,resolvedContext:c.resolvedContext,semanticPolicyRef:policy});}
function chain(){const design=designFor();const capability={capabilityRef:'capability:structured-input-v1',capabilityType:'structured_input',supportedDesignTypes:['elementary_acquisition_design'],supportedKnowledgeLayers:['elementary'],supportedOutputTopologies:['elementary_knowledge_contribution_set'],supportedPrerequisiteModes:['none'],supportedObligations:['must_preserve_source_traceability','must_produce_elementary_contribution'],constraints:{},metadata:{version:'1.0'},extensions:{}};const match=K.buildKnowledgeAcquisitionCapabilityMatch({design,capabilityCandidate:capability});const decision=A.buildKnowledgeAcquisitionSolutionDecision({design,matches:[match],candidateSnapshots:[{capabilityRef:capability.capabilityRef,capabilityType:'structured_input',metadata:{version:'1.0'},extensions:{}}],decisionContext:{contextRef:'applicationDecisionContext:fht-pa01',approvalState:'approved',decisionTimestamp:now},decisionPolicy:{policyRef:'applicationDecisionPolicy:fht-pa01',allowedModes:['single'],allowComposition:false,criteria:['explicit_request']},decisionRequest:{mode:'single',selectedCapabilityRefs:[capability.capabilityRef],reasons:[{code:'canonical_slice',category:'adoption',blocking:false}]}});const configuration=A.buildKnowledgeAcquisitionCapabilityConfiguration({solutionDecision:decision,selectedCapabilitySnapshots:[{capabilityRef:capability.capabilityRef,capabilityType:'structured_input',metadata:{version:'1.0'},extensions:{}}],configurationDefinition:{configurationDefinitionRef:'knowledgeAcquisitionConfigurationDefinition:fht-pa01',capabilityDefinitions:[{capabilityRef:capability.capabilityRef,parameters:[]}]},applicationConfigurationInput:{applicationConfigurationInputRef:'applicationConfigurationInput:fht-pa01',configurationItems:[]}});const plan=A.buildKnowledgeAcquisitionPlan({capabilityConfiguration:configuration});const item=plan.planItems[0].planItemRef;const session=A.buildKnowledgeAcquisitionRuntimeSession({knowledgeAcquisitionPlan:plan,sessionKey:'fht-pa01-session',status:'active',activePlanItemRef:item,itemStates:[{sourcePlanItemRef:item,status:'active',activatedAt:now,suspendedAt:null,completedAt:null,abandonedAt:null}],lifecycle:{createdAt:now,updatedAt:now,activatedAt:now,suspendedAt:null,completedAt:null,abandonedAt:null}},{now});const execution=A.buildKnowledgeAcquisitionExecution({knowledgeAcquisitionRuntimeSession:session,knowledgeAcquisitionPlan:plan,executionKey:'fht-pa01-execution'},{now});return{design,decision,configuration,plan,session,execution};}
function evidenceFor(c,text){return buildAcceptedRuntimeAnswerEvidenceStore({betaSessionId:'beta-fht-pa01',interviewSessionId:'interview-fht-pa01',answers:[{answerText:text,questionContext:{questionKey:'not-semantic-authority',expectedSignals:['20%']},stepType:'answer',phaseName:'interview',timestamp:now}],knowledgeAcquisitionExecutionRef:`knowledgeAcquisitionExecution:${c.execution.id}`}).evidence[0];}
function args(c,evidence,observationExecutor){return{evidence,knowledgeAcquisitionExecution:c.execution,knowledgeAcquisitionPlan:c.plan,capabilityConfiguration:c.configuration,solutionDecision:c.decision,knowledgeAcquisitionDesign:c.design,observationExecutor,subjectRef:{type:'person',id:'person-fht-pa01'},now};}
const c=chain();assert.equal(validateKnowledgeAcquisitionDesign(c.design).valid,true);assert.equal(c.design.semanticPolicyRef,POLICY);assert.equal(c.design.targetKnowledge.scopeRef,'quantified_outcome');
const evidence=evidenceFor(c,'After the intervention, monitored scrap decreased by approximately 20%; I contributed to the improvement actions.');const authority=resolveQuantifiedOutcomeSemanticAuthority(args(c,evidence));assert.equal(authority.resolved,true);assert.equal(authority.semanticPolicyRef,POLICY);
const positive=()=>({supported:true,observation:{observationId:'quantified_outcome:fht-pa01:1',measurableOutcome:'monitored scrap rate decreased',quantitativeValue:{value:20,unit:'percent',approximate:true,direction:'decrease'},contributionRelationship:'person contributed to the process-improvement intervention associated with the monitored outcome',causalityBoundary:'contribution_only',context:{event:'process-improvement intervention',domain:'production'},limitations:['Sole personal causality is not established.'],metadata:{createdAt:now}}});
const result=runQuantifiedOutcomeSemanticKnowledgePath(args(c,evidence,positive));assert(result.observation);assert.equal(result.observation.observationType,'quantified_outcome');assert.equal(result.observation.quantitativeValue.value,20);assert.equal(result.observation.causalityBoundary,'contribution_only');assert.deepEqual(result.observation.evidenceIds,[evidence.id]);assert.equal(result.observation.extensions.semanticProvenance.semanticPolicyRef,POLICY);assert.equal(result.specializedMeasurementResult.presence,1);assert.equal(result.measurementResult.measurementId,'quantified_outcome');assert.equal(result.measurementResult.characteristicId,'quantified_outcome');assert.equal(result.measurementResult.normalizedValue,1);assert.equal(result.measurementResult.extensions.projection.meaning,'supported_presence_not_magnitude_score');assert.equal(result.dimensionContributions.length,1);assert.equal(result.dimensionContributions[0].dimensionId,'quantified_outcome');assert.equal(result.knowledgeCoverage.dimensionCoverage[0].dimensionId,'quantified_outcome');assert(!JSON.stringify(result).includes('decision_accountability'));assert(!JSON.stringify(result).includes('leadership'));
// A: number is not authority. Same evidence with a Design that lacks this policy cannot resolve quantified_outcome authority.
const noPolicyDesign=DF.buildChain('elementary').design;assert.equal(resolveQuantifiedOutcomeSemanticAuthority({...args(c,evidence),knowledgeAcquisitionDesign:noPolicyDesign}).resolved,false);
// B: arbitrary numeric evidence does not fabricate Knowledge when the constrained interpreter does not support an outcome.
const arbitrary=evidenceFor(c,'The project team had 20 participants.');const arbitraryResult=runQuantifiedOutcomeSemanticKnowledgePath(args(c,arbitrary,()=>({supported:false})));assert.equal(arbitraryResult.observation,null);assert.equal(arbitraryResult.knowledgeSnapshot,null);
// C: contribution may support an event outcome, but sole causality is never added by the boundary.
assert.equal(result.observation.causalityBoundary,'contribution_only');assert.match(result.observation.limitations.join(' '),/causality/i);assert(!JSON.stringify(result).includes('person reduced scrap by 20%'));
// D: incomplete measurable semantics fail closed.
const insufficient=runQuantifiedOutcomeSemanticKnowledgePath(args(c,evidence,()=>({supported:true,observation:{observationId:'quantified_outcome:insufficient',measurableOutcome:'scrap changed',quantitativeValue:null,contributionRelationship:'contributed',causalityBoundary:'contribution_only',context:{event:'improvement'},metadata:{createdAt:now}}})));assert.equal(insufficient.observation,null);assert.equal(insufficient.knowledgeSnapshot,null);
// F: policy and target identity cannot be crossed.
const da=DF.buildChain('elementary');const bad=JSON.parse(JSON.stringify(c.design));bad.targetKnowledge.scopeRef='decision_accountability';bad.id=I.calculateKnowledgeAcquisitionDesignId(bad);assert.equal(validateKnowledgeAcquisitionDesign(bad).valid,false);
console.log('FHT-PA01 quantified outcome semantic authority PASSED');
