import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createPrivateBetaUiServer} from '../src/app/privateBetaUiServer.js';
import {createMemoryPrivateBetaProfessionalIdentityStore,privateBetaPersonRefFromContext} from '../src/app/privateBetaProfessionalIdentityContinuity.js';
import {startDirectionPeopleResponsibilityAcquisition} from '../src/app/careerDirection/directionKnowledgeAcquisition.js';

const contextId='bv03-corrective-human', personRef=privateBetaPersonRefFromContext(contextId), cookie=`imago_beta_repeat_context=${contextId}`;
const fixture=JSON.parse(await readFile(new URL('../fixtures/expected_candidate_profile_01.json',import.meta.url),'utf8'));
const adapter=async({task,user})=>{assert.equal(task,'candidateProfile');const x=structuredClone(fixture);(x.candidateProfile||x).summary=user.includes('Germany')?'Industrialization Engineer Germany':user.includes('Atlas')?'Atlas supplier ramp-up':user.includes('manutenzione')?'produzione manutenzione':'Production Supervisor';return JSON.stringify(x);};
const mk=(id,role,content)=>({id,type:'text',label:role,content,language:null,sourceRole:role,quality:null,provenance:{origin:role,providedBy:'user',collectedAt:'2026-09-14T10:00:00.000Z'},metadata:{createdAt:'2026-09-14T10:00:00.000Z',updatedAt:'2026-09-14T10:00:00.000Z'}});
const sources=[mk('current_cv','current_cv','Marco. Production Supervisor. Operations Manufacturing. Coordinamento produzione e manutenzione.'),mk('previous_cv','previous_cv','Industrialization Engineer. Start-up linea produttiva in Germany.'),mk('professional_declaration','professional_declaration','Project Atlas supplier ramp-up con supply chain, qualità e produzione.')];
const baseRecord={version:'1.0',type:'private_beta_professional_identity_continuity',professionalIdentityRef:`professionalIdentity:${personRef.id}`,personRef,owner:'person',authorizedMaterials:{cvText:sources[0].content,userNotes:''},professionalSources:sources,reusableKnowledgeResults:[],knowledgeRefs:[],revision:1,createdAt:'2026-09-14T10:00:00.000Z',updatedAt:'2026-09-14T10:00:00.000Z',lastEnrichedBySessionRef:null,representationSnapshots:[],currentRepresentationSnapshotRefs:{}};
const peopleCondition={id:'condition:people',reason:'people_responsibility_scope',roleRequirementRef:'req:people'};
const evaluation={hypotheses:[{id:'direction:ops',directionRef:'operations_management',conditionsToVerify:[peopleCondition],metadata:{roleLabel:'Operations Manager'}}]};
const semanticExecutor=async()=>({supported:true,candidate:{interpretationStatus:'SUPPORTED',responsibilityPresence:'supported',continuity:'continuing',responsibilityMode:'informal_operational',responsibilityKinds:['work_assignment_or_priority_setting','workload_shift_or_schedule_coordination','performance_follow_up_or_feedback'],peopleScope:{kind:'exact',value:10},professionalContext:{description:'reparto produttivo',current:true},eventTime:{description:'Da circa due anni'},support:{presence:'coordino stabilmente una decina di operatori',continuity:'Da circa due anni',mode:'coordino stabilmente',peopleScope:'una decina di operatori',professionalContext:'reparto produttivo',responsibilityKinds:['definire le priorità e distribuire le attività giornaliere','organizzo i turni','partecipo insieme al mio responsabile alle valutazioni periodiche delle persone']},limitations:['formal reporting authority not established']}});
const understandBody=new URLSearchParams({identityAction:'recover',workingMode:'independent',productPurpose:'professional_representation_understand',consentDecision:'accept',targetRole:'',cvText:'',previousCvText:'',professionalDeclaration:'',userNotes:'',jdText:'',uiLocale:'it',sessionLocale:'it'});
async function listen(server){await new Promise(r=>server.listen(0,'127.0.0.1',r));return `http://127.0.0.1:${server.address().port}`;}
async function close(server){await new Promise(r=>server.close(r));}

const store=createMemoryPrivateBetaProfessionalIdentityStore();await store.save({record:baseRecord});
// 1) Materialize the real pre-PD-056 Representation snapshot.
let server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:store,contextIdFactory:()=>contextId,journeyOptions:{modelAdapter:adapter}});let base=await listen(server);
let response=await fetch(base+'/private-beta/journey',{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body:understandBody});assert.equal(response.status,200,await response.text());
let prior=await store.load({personRef});assert.equal(prior.representationSnapshots.length,1);assert.equal(prior.reusableKnowledgeResults.length,0);
// 2) Acquire PD-056 through the production-compatible Direction acquisition path and production server persistence boundary.
const sessionRef='direction:bv03-corrective';const directionState=startDirectionPeopleResponsibilityAcquisition({careerDirectionEvaluation:evaluation,selectedDirectionRef:'direction:ops',userAction:'deepen_career_direction',professionalIdentity:prior,subjectRef:personRef,professionalRepresentationRef:prior.representationSnapshots[0].snapshotId,now:'2026-09-14T10:10:00.000Z'});
const sessionStore=new Map([[sessionRef,{type:'direction_explore_state',sessionRef,careerDirectionEvaluation:evaluation,directionAcquisition:directionState,personRef,reusableProfessionalIdentity:prior,professionalRepresentationRef:prior.representationSnapshots[0].snapshotId}]]);
await close(server);server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:store,sessionStore,contextIdFactory:()=>contextId,journeyOptions:{modelAdapter:adapter,directionPeopleResponsibilitySemanticExecutor:semanticExecutor}});base=await listen(server);
response=await fetch(base+'/private-beta/direction/answer',{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({sessionRef,answer:'Da circa due anni coordino stabilmente una decina di operatori nel reparto produttivo. Mi occupo di definire le priorità e distribuire le attività giornaliere, organizzo i turni e partecipo insieme al mio responsabile alle valutazioni periodiche delle persone.'})});
const acquisitionHtml=await response.text();assert.equal(response.status,200,acquisitionHtml);assert.match(acquisitionHtml,/id="imago-continuity-artifact"/,'Direction acquisition must refresh the durable browser continuity artifact');
const match=acquisitionHtml.match(/<script id="imago-continuity-artifact" type="application\/json">([\s\S]*?)<\/script>/);assert.ok(match);const persistedArtifact=JSON.parse(match[1]);
assert.equal(persistedArtifact.reusableKnowledgeResults.length,1);const realPd=persistedArtifact.reusableKnowledgeResults[0];assert.equal(realPd.semanticType,'continuing_people_responsibility');assert.equal(realPd.semanticPolicyRef,'professional_semantic_policy:continuing_people_responsibility:v1');assert.equal(realPd.observation.observationType,'observed_continuing_people_responsibility_context');assert.equal(realPd.specializedMeasurementResult.semanticDetail.peopleScope.value,10);
await close(server);
// 3) Simulate process restart: fresh store receives exactly the browser continuity artifact, then reopen Understand.
const restartedStore=createMemoryPrivateBetaProfessionalIdentityStore();server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:restartedStore,contextIdFactory:()=>contextId,journeyOptions:{modelAdapter:adapter}});base=await listen(server);
response=await fetch(base+'/private-beta/continuity/restore',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify(persistedArtifact)});assert.equal(response.status,204);
response=await fetch(base+'/private-beta/journey',{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body:understandBody});const html=await response.text();assert.equal(response.status,200,html);
assert.match(html,/coordini il lavoro di circa 10 persone/i);assert.match(html,/circa 10 persone/i);assert.match(html,/reparto produttivo/i);assert.match(html,/priorità/i);assert.match(html,/turni/i);assert.match(html,/valutazioni|feedback/i);assert.doesNotMatch(html,/responsabilità operativa continuativa su circa (?:dieci|10) persone/i,'informal_operational knowledge must not be surfaced as generic responsibility over people');assert.doesNotMatch(html,/responsabil(?:e|ità) (?:gerarchica|formale)|riporto formale|line manager|people leader/i,'formal reporting/line authority must not be invented');assert.doesNotMatch(html,/capacità manageriali|pronto per|idoneità per Operations Manager/i);
const reopened=await restartedStore.load({personRef});assert.equal(reopened.reusableKnowledgeResults.length,1);assert.equal(reopened.representationSnapshots.length,2,'stale pre-PD snapshot must not suppress rematerialization');assert.equal(reopened.representationSnapshots[1].changeCause,'knowledge_observability_change');
const currentId=reopened.representationSnapshots[1].snapshotId;
// 4) Unchanged reopen reuses the valid post-PD snapshot.
response=await fetch(base+'/private-beta/journey',{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body:understandBody});assert.equal(response.status,200,await response.text());const reused=await restartedStore.load({personRef});assert.equal(reused.representationSnapshots.length,2);assert.equal(reused.representationSnapshots[1].snapshotId,currentId);
await close(server);
console.log('BETA-VALUE-03 first corrective real persisted PD-056 reopen: PASS');
