import assert from 'node:assert/strict';
import {buildOpportunityUnderstanding,buildGroundedApplicationPackage,buildApplicationArtifacts,buildProfessionalHistoryStructure} from '../src/app/opportunityApplication/groundedApplicationPackage.js';
import {renderCvApplicationPdf,getCvPdfLayoutTrace} from '../src/app/opportunityApplication/renderApplicationPdf.js';
import {loadPrivateBetaUiMessages} from '../src/i18n/loadPrivateBetaUiMessages.js';
const snap=(roleHistory)=>[{snapshotId:'r1',representation:{type:'target_independent_professional_representation',roleHistory}}];
const identity={revision:7,professionalSources:[
{id:'cur',sourceRole:'current_cv',content:'Production Supervisor. Coordinated daily production activities. Collaborated with Quality and Maintenance.'},
{id:'prev',sourceRole:'previous_cv',content:'Industrialization Engineer. Participated in the launch of a new production line in Germany.'},
{id:'atlas',sourceRole:'professional_declaration',content:'Project Atlas participation supported supplier ramp-up; a project event improved approximately 20% with shared causality.'},
{id:'maint',sourceRole:'professional_declaration',content:'Supported production and maintenance coordination during start-up.'}],representationSnapshots:snap([
{sourceId:'prev',sourceRole:'previous_cv',role:'Industrialization Engineer',status:'previous',facts:[]},
{sourceId:'cur',sourceRole:'current_cv',role:'Production Supervisor',status:'current',facts:[]}
])};
const jd='Industrialization Project Engineer\nMain responsibilities:\nCoordinate industrialization projects and production-line start-up.\nRequirements:\nProject management experience required.\nEnglish required.\nPreferred qualifications:\nGerman is a plus.\nLocation: Turin.';
const u=buildOpportunityUnderstanding({opportunityText:jd,opportunityLabel:'Industrialization Project Engineer'});assert.ok(![...u.requirements,...u.responsibilities].some(x=>/^(Main responsibilities|Requirements):?$/i.test(x.statement)));assert.equal(u.source.content,jd);
const history=buildProfessionalHistoryStructure({professionalIdentity:identity});assert.equal(identity.professionalSources.length,4);assert.equal(history.length,2);assert.ok(identity.professionalSources.length>history.length);assert.deepEqual(history.map(x=>x.role),['Industrialization Engineer','Production Supervisor']);assert.ok(history[0].responsibilities.some(x=>x.includes('Germany')));assert.ok(!history.some(x=>/Atlas|maintenance/i.test(x.role)));
// One canonical source may support multiple explicit role-history identities; source count is not job count.
const one={revision:1,professionalSources:[{id:'cv',sourceRole:'current_cv',content:'Role A. Work A. Role B. Work B.'}],representationSnapshots:snap([{sourceId:'cv',role:'Role A',status:'previous'},{sourceId:'cv',role:'Role B',status:'current'}])};assert.equal(buildProfessionalHistoryStructure({professionalIdentity:one}).length,2);
const pkg=buildGroundedApplicationPackage({professionalIdentity:identity,opportunityUnderstanding:u,documentData:{displayName:'Marco'}});const fields=pkg.documentCompletenessState.needs.map(x=>x.field);assert.equal(pkg.documentCompletenessState.score,null);assert.equal(pkg.documentCompletenessState.evaluative,false);assert.equal(pkg.documentCompletenessState.targetIndependent,true);assert.equal(pkg.documentCompletenessState.mayProceed,true);assert.ok(fields.includes('contact_channel'));assert.ok(fields.includes('organisation'));assert.ok(fields.includes('period'));assert.ok(fields.includes('education'));assert.ok(fields.includes('secondary_professional_information'));
const u2=buildOpportunityUnderstanding({opportunityText:'Engineer. German is a plus.'});const pkg2=buildGroundedApplicationPackage({professionalIdentity:identity,opportunityUnderstanding:u2,documentData:{displayName:'Marco'}});assert.ok(pkg2.documentCompletenessState.needs.some(x=>x.field==='education'));assert.ok(pkg2.targetRelativeInformationMap.some(x=>/German/i.test(x.statement)));assert.notDeepEqual(pkg2.documentCompletenessState.needs,pkg2.targetRelativeInformationMap);
const it=loadPrivateBetaUiMessages('it');const arts=buildApplicationArtifacts({applicationPackage:pkg,opportunityUnderstanding:u,documentLanguage:'it',template:'essential',messages:it});assert.equal(arts.cvContentModel.professionalExperience.length,2);const naive=pkg.selectedCandidateMaterials.slice(0,2).map(x=>x.statement).join(' ');assert.notEqual(arts.cvContentModel.professionalSummary,naive);assert.ok(arts.cvContentModel.professionalSummary.includes('Production Supervisor'));assert.ok(arts.cvContentModel.professionalSummary.includes('Industrialization Engineer'));assert.ok(!/experienced|leader|forte|eccellent/i.test(arts.cvContentModel.professionalSummary));assert.ok(!/Ha guidato|led the launch/i.test(arts.targetedCv.content));assert.ok(!arts.coverLetter.content.includes('•'));assert.ok(!/entusiast|ammir|excited|thrilled/i.test(arts.coverLetter.content));
for(const template of ['essential','professional','compact']){const trace=getCvPdfLayoutTrace({cvContentModel:arts.cvContentModel,template});assert.ok(trace.entries.some(x=>x.kind==='experience_heading'));const pdf=renderCvApplicationPdf({cvContentModel:arts.cvContentModel,title:'CV',template,labels:{profile:it.applicationDocProfile,experience:it.applicationDocExperience,education:it.applicationDocEducation,skills:it.applicationDocSkills,languages:it.applicationDocLanguages}});assert.equal(pdf.subarray(0,5).toString(),'%PDF-');}
// Non-manufacturing: canonical representation identity, no domain-specific production rule.
const bio={revision:1,professionalSources:[{id:'b1',sourceRole:'current_cv',content:'System Engineer. Participated in diagnostic-system validation.'},{id:'b2',sourceRole:'professional_declaration',content:'Supported assay integration testing.'}],representationSnapshots:snap([{sourceId:'b1',role:'System Engineer',status:'current'}])};const bu=buildOpportunityUnderstanding({opportunityText:'Validation Engineer. Experience with diagnostic systems required.'});const bp=buildGroundedApplicationPackage({professionalIdentity:bio,opportunityUnderstanding:bu});assert.equal(bp.professionalHistory.length,1);assert.equal(bp.professionalHistory[0].role,'System Engineer');assert.ok(bp.documentCompletenessState.needs.some(x=>x.field==='education'));
const before=JSON.stringify(identity);buildGroundedApplicationPackage({professionalIdentity:identity,opportunityUnderstanding:u,documentData:{displayName:'Marco',email:'m@example.test'}});assert.equal(JSON.stringify(identity),before);
console.log('PD-062I Candidate Application Document Composition: PASS');
