import assert from 'node:assert/strict';
import http from 'node:http';
import {buildOpportunityUnderstanding,buildGroundedApplicationPackage,buildApplicationArtifacts} from '../src/app/opportunityApplication/groundedApplicationPackage.js';
import {renderApplicationDocumentDocx} from '../src/app/opportunityApplication/renderApplicationDocx.js';
import {renderApplicationDocumentPdf} from '../src/app/opportunityApplication/renderApplicationDocumentPdf.js';
import {applicationArtifactFilename,applicationArtifactIsCurrent,applicationDocumentClaims} from '../src/app/opportunityApplication/applicationDocumentModel.js';
import {loadPrivateBetaUiMessages} from '../src/i18n/loadPrivateBetaUiMessages.js';
import {createPrivateBetaUiServer} from '../src/app/privateBetaUiServer.js';

function storedZipEntries(buf){const out=new Map();let o=0;while(o+4<=buf.length&&buf.readUInt32LE(o)===0x04034b50){const method=buf.readUInt16LE(o+8),size=buf.readUInt32LE(o+18),nameLen=buf.readUInt16LE(o+26),extraLen=buf.readUInt16LE(o+28);assert.equal(method,0);const name=buf.subarray(o+30,o+30+nameLen).toString('utf8'),start=o+30+nameLen+extraLen;out.set(name,buf.subarray(start,start+size));o=start+size;}return out;}
function xmlText(xml){return String(xml).replace(/<w:tab\/>/g,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();}
function pdfText(buf){return [...buf.toString('latin1').matchAll(/\(([^()]*(?:\\[()][^()]*)*)\) Tj/g)].map(m=>m[1].replace(/\\([()\\])/g,'$1')).join(' ');}
const representation={type:'target_independent_professional_representation',roleHistory:[{sourceId:'cur',sourceRole:'current_cv',role:'Production Supervisor',status:'current'},{sourceId:'prev',sourceRole:'previous_cv',role:'Industrialization Engineer',status:'previous'}]};
const identity={revision:9,professionalSources:[
 {id:'cur',sourceRole:'current_cv',content:'Production Supervisor. Coordinated daily production activities. Collaborated with Quality and Maintenance. Improved line-changeover time by approximately 18% as a shared project result.',metadata:{role:'Production Supervisor',organisation:'Alfa Manufacturing',period:'2022 - 2026'}},
 {id:'prev',sourceRole:'previous_cv',content:'Industrialization Engineer. Participated in the launch of a new production line in Germany. Supported commissioning and supplier ramp-up.',metadata:{role:'Industrialization Engineer',organisation:'Beta Systems',period:'2018 - 2022'}}
],representationSnapshots:[{snapshotId:'r1',representation}]};
const jd='Industrialization Project Engineer\nResponsibilities:\nCoordinate industrialization projects and production-line start-up.\nRequirements:\nManufacturing experience required.\nCross-functional coordination required.\nEnglish required.';
const u=buildOpportunityUnderstanding({opportunityText:jd,opportunityLabel:'Industrialization Project Engineer',now:'2026-09-30T10:00:00Z'});
const pkg=buildGroundedApplicationPackage({professionalIdentity:identity,opportunityUnderstanding:u,documentData:{displayName:'Marco Rossi',email:'marco.rossi@example.test',phone:'+39 011 555 0101',linkedin:'linkedin.com/in/marco-rossi',location:'Torino'},now:'2026-09-30T10:00:00Z'});
const it=loadPrivateBetaUiMessages('it'),artifacts=buildApplicationArtifacts({applicationPackage:pkg,opportunityUnderstanding:u,documentLanguage:'it',template:'essential',messages:it});
assert.equal(artifacts.targetedCv.documentModel.type,'application_document_model');assert.equal(artifacts.coverLetter.documentModel.type,'application_document_model');assert.equal(artifacts.targetedCv.documentModel.packageRef,pkg.packageRef);assert.equal(artifacts.coverLetter.documentModel.packageRef,pkg.packageRef);
assert.ok(artifacts.targetedCv.content.includes('Production Supervisor'));assert.ok(artifacts.targetedCv.content.includes('Industrialization Engineer'));assert.ok(artifacts.coverLetter.content.includes(it.applicationDocOpening));assert.ok(!/owned the plant budget|gestiva il budget dello stabilimento/i.test(JSON.stringify(artifacts)));
for(const [kind,artifact] of [['cv',artifacts.targetedCv],['letter',artifacts.coverLetter]]){
 const docx=renderApplicationDocumentDocx({documentModel:artifact.documentModel}),entries=storedZipEntries(docx);assert.ok(docx.subarray(0,2).toString()==='PK');for(const required of ['[Content_Types].xml','_rels/.rels','word/document.xml','word/styles.xml','word/numbering.xml'])assert.ok(entries.has(required),`${kind} missing ${required}`);const wordText=xmlText(entries.get('word/document.xml').toString('utf8'));assert.ok(wordText.length>100);assert.ok(wordText.includes('Marco Rossi'));
 const pdf=renderApplicationDocumentPdf({documentModel:artifact.documentModel});assert.equal(pdf.subarray(0,5).toString(),'%PDF-');assert.ok(/\/Count [1-9]/.test(pdf.toString('latin1')));const ptext=pdfText(pdf);assert.ok(ptext.includes('Marco Rossi'));
 const claims=applicationDocumentClaims(artifact.documentModel).filter(x=>x.length>5);for(const claim of claims.slice(0,4)){const marker=claim.split(/\s+/).slice(0,4).join(' ');assert.ok(wordText.includes(marker),`${kind} DOCX claim missing: ${marker}`);assert.ok(ptext.includes(marker)||marker.length>45,`${kind} PDF claim missing: ${marker}`);}
 const nameDocx=applicationArtifactFilename({documentModel:artifact.documentModel,format:'docx'}),namePdf=applicationArtifactFilename({documentModel:artifact.documentModel,format:'pdf'});assert.ok(nameDocx.endsWith('.docx')&&namePdf.endsWith('.pdf'));assert.ok(!/[\\/:*?"<>|]/.test(nameDocx));assert.ok(!/applicationPackage|opportunity:|candidateMaterial/.test(nameDocx));
}
const changedPkg={...pkg,packageRef:'applicationPackage:changed'};assert.equal(applicationArtifactIsCurrent({applicationArtifacts:artifacts,groundedApplicationPackage:changedPkg}),false);assert.equal(applicationArtifactIsCurrent({applicationArtifacts:artifacts,groundedApplicationPackage:pkg}),true);
const restored=JSON.parse(JSON.stringify({applicationState:{groundedApplicationPackage:pkg,applicationArtifacts:artifacts}}));assert.equal(applicationArtifactIsCurrent({applicationArtifacts:restored.applicationState.applicationArtifacts,groundedApplicationPackage:restored.applicationState.groundedApplicationPackage}),true);assert.ok(renderApplicationDocumentDocx({documentModel:restored.applicationState.applicationArtifacts.targetedCv.documentModel}).length>500);
const store={async load(){return {applicationState:{groundedApplicationPackage:pkg,applicationArtifacts:artifacts}};},async save(){throw new Error('not expected');}};const server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:store,contextIdFactory:()=> 'pd087'});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;
function request(path){return new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port,path,headers:{cookie:'imago_beta_repeat_context=pd087'}},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:Buffer.concat(chunks)}));});req.on('error',reject);req.end();});}
for(const [kind,format,mime] of [['cv','docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document'],['cv','pdf','application/pdf'],['letter','docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document'],['letter','pdf','application/pdf']]){const r=await request(`/private-beta/application/download?kind=${kind}&format=${format}`);assert.equal(r.status,200);assert.equal(r.headers['content-type'],mime);assert.ok(String(r.headers['content-disposition']).includes(`.${format}`));assert.equal(r.headers['x-content-type-options'],'nosniff');assert.ok(r.body.length>500);}
assert.equal((await request('/private-beta/application/download?kind=../../x&format=pdf')).status,400);await new Promise(r=>server.close(r));
console.log('PD-087 Candidate Application Artifact Delivery: PASS');
