import assert from 'node:assert/strict';
import { validateCareerDirectionRequirementSupportProposal,buildCareerDirectionRequirementSupportProjection,buildRequirementSupportDiagnostic } from '../src/app/careerDirection/requirementSupportAuthority.js';
import { evaluateCareerDirections } from '../src/app/careerDirection/evaluateCareerDirections.js';
import { CURATED_ROLE_REPRESENTATIONS } from '../src/app/careerDirection/roleFixtures.js';
const role=CURATED_ROLE_REPRESENTATIONS.find(x=>x.roleIdentity.familyRef==='operations_management');
const d=(id,mat,agency='coordinated')=>({status:'accepted',descriptorId:id,descriptorRole:'activity',materialRef:mat,sourceId:mat,claimShape:{agencyLevel:agency}});
const rel={status:'accepted',relationshipId:'groundedRelationship:r1',kind:'grounded_descriptive_professional_relationship',descriptorRefs:['d1','d2'],materialRefs:['m1','m2'],sourceRefs:['s1','s2'],claimShape:{personPropertyAssertion:'none',responsibilityAssertion:'none'},persistent:false};
const ho={status:'accepted',structureId:'higherOrderStructure:h1',kind:'higher_order_descriptive_professional_structure',contributorRefs:['groundedRelationship:r1','groundedRelationship:r2'],professionalBasisRefs:['episode:e1','episode:e2'],materialRefs:['m1','m2','m3'],sourceRefs:['s1','s2','s3'],inheritedSemanticProtection:['pd070_representation_only','no_person_level_inference','no_semantic_strengthening'],persistent:false};
const rel2={...rel,relationshipId:'groundedRelationship:r2',descriptorRefs:['d2','d3'],materialRefs:['m2','m3'],sourceRefs:['s2','s3']};
const pm={groundedDescriptiveDescriptors:[d('d1','m1'),d('d2','m2'),d('d3','m3')],groundedDescriptiveRelationships:[rel,rel2],higherOrderDescriptiveProfessionalStructures:[ho],supportedPatterns:[{kind:'documented_cross_functional_coordination_recurrence',episodeRefs:['episode:e1','episode:e2'],sourceRefs:['s1','s2'],supportCount:2}],knowledgeContribution:[{sourceRef:'knowledge:k1',primaryProfessionalMeaning:{kind:'bounded_decision_accountability'}}]};
const proposal=(type,ref,id)=>({contributorType:type,contributorRef:ref,targetDirectionRef:role.id,targetRequirementRef:'operations_manager.cross_functional_operational_coordination',relationBasis:'bounded model proposal: contributor meaning is relevant to explicit cross-functional coordination requirement',provenance:{providerRef:'controlled:pd079',proposalRef:id}});
// A: canonical Knowledge remains existing bounded support and is single-grounded in the robustness authority model.
const knowledgeProjection=buildCareerDirectionRequirementSupportProjection({professionalMeaning:pm,role,proposals:[]});assert.equal(knowledgeProjection.aggregates.length,0,'PD079 must not invent a new target relation for Knowledge without proposal/explicit mapping; existing DIRECTION_MAPPING_POLICY remains authority');
// B: recurrence independence comes from canonical episode identities, never raw mentions.
const patternOnly={...pm,groundedDescriptiveRelationships:[],higherOrderDescriptiveProfessionalStructures:[]};const patternInventory=patternOnly.supportedPatterns[0];assert.equal(new Set(patternInventory.episodeRefs).size,2);
// C: accepted PD069 relation maps and preserves lineage.
const r=validateCareerDirectionRequirementSupportProposal(proposal('grounded_descriptive_professional_relationship',rel.relationshipId,'p-r1'),{professionalMeaning:pm,role});assert.equal(r.status,'accepted');assert.deepEqual(r.materialRefs,['m1','m2']);assert.deepEqual(r.sourceRefs,['s1','s2']);assert.equal(r.robustnessClass,'SINGLE_GROUNDED_BASIS','distinct materials alone must not be upgraded to independent recurrence');
// D: accepted PD070 maps and preserves independent professional bases.
const h=validateCareerDirectionRequirementSupportProposal(proposal('higher_order_descriptive_professional_structure',ho.structureId,'p-h1'),{professionalMeaning:pm,role});assert.equal(h.status,'accepted');assert.equal(h.robustnessClass,'COMPOSED_HIGHER_ORDER_BASIS');assert.deepEqual(h.professionalBasisRefs,['episode:e1','episode:e2']);
// E: same-source/material repetition cannot upgrade robustness.
const same={...rel,relationshipId:'groundedRelationship:same',descriptorRefs:['d1','d1'],materialRefs:['m1'],sourceRefs:['s1']};const pmSame={...pm,groundedDescriptiveRelationships:[same]};const sr=validateCareerDirectionRequirementSupportProposal(proposal('grounded_descriptive_professional_relationship','groundedRelationship:same','p-same'),{professionalMeaning:pmSame,role});assert.equal(sr.status,'accepted');assert.equal(sr.robustnessClass,'SINGLE_GROUNDED_BASIS');
// F: target strength exceeds Person semantic ceiling: non-coordinated material cannot support coordination.
const weakPm={...pm,groundedDescriptiveDescriptors:[d('d1','m1','participated'),d('d2','m2','contributed')]};const weak=validateCareerDirectionRequirementSupportProposal(proposal('grounded_descriptive_professional_relationship',rel.relationshipId,'p-weak'),{professionalMeaning:weakPm,role});assert.equal(weak.status,'rejected');assert(weak.errors.includes('semantic_ceiling_or_requirement_relevance_not_authorised'));
// G: lexical similarity only is never authority.
const lexical={...proposal('grounded_descriptive_professional_relationship',rel.relationshipId,'p-lex'),targetRequirementRef:'operations_manager.budget_operational_resources',relationBasis:'budget budget budget'};assert.equal(validateCareerDirectionRequirementSupportProposal(lexical,{professionalMeaning:pm,role}).status,'rejected');
// H: duration only is not a contributor and cannot upgrade robustness.
assert.equal(validateCareerDirectionRequirementSupportProposal({...proposal('formal_role_continuity','formal:10years','p-duration')},{professionalMeaning:pm,role}).status,'rejected');
// I: Career Direction consumes accepted PD069/PD070 support without duplicate target rows and preserves current unresolved semantics.
const richPm={...pm,supportedPatterns:[]};const ev=evaluateCareerDirections({professionalRepresentation:{professionalMeaning:richPm},professionalRepresentationRef:'rep:pd079',requirementSupportProposals:[proposal('grounded_descriptive_professional_relationship',rel.relationshipId,'p-r1'),proposal('higher_order_descriptive_professional_structure',ho.structureId,'p-h1')]});const ops=ev.hypotheses.find(x=>x.roleRepresentationRef===role.id);assert(ops);const cross=ops.supportBasis.filter(x=>x.roleRequirementRef==='operations_manager.cross_functional_operational_coordination');assert.equal(cross.length,1,'rich contributors for one requirement must aggregate to one Career Direction support row');const agg=cross[0].metadata.requirementSupportAggregate;assert.equal(agg.acceptedContributorRefs.length,2);assert.equal(agg.robustnessClass,'COMPOSED_HIGHER_ORDER_BASIS');assert(ops.conditionsToVerify.some(x=>x.reason==='broader_resource_budget_scope'),'budget/resource must remain unresolved informational-only');const diag=buildRequirementSupportDiagnostic(ops.metadata.requirementSupportProjection);assert(diag.requirements.some(x=>x.robustnessClass==='COMPOSED_HIGHER_ORDER_BASIS'&&x.semanticCeilingsPreserved));
// Provider cannot self-authorise.
assert.equal(validateCareerDirectionRequirementSupportProposal({...proposal('grounded_descriptive_professional_relationship',rel.relationshipId,'p-self'),providerAuthority:true},{professionalMeaning:pm,role}).status,'rejected');
console.log('PD-079 rich requirement support integration: PASS');
