import assert from 'assert';
import { readFile } from 'fs/promises';
import { prepareStagedPrivateBetaJourney, answerStagedPrivateBetaJourney } from '../src/app/privateBetaJourneyIntegration.js';
const load=async n=>JSON.parse(await readFile(new URL(`../fixtures/${n}`,import.meta.url),'utf8'));
const adapter=async({task})=>{if(task==='candidateProfile')return JSON.stringify(await load('expected_candidate_profile_01.json'));if(task==='roleProfile')return JSON.stringify(await load('expected_role_profile_01.json'));if(task==='jobFitAnalysis')return JSON.stringify(await load('expected_job_fit_analysis_01.json'));return '{}';};
const cv=await readFile(new URL('../fixtures/sample_cv_01.txt',import.meta.url),'utf8'),jd=await readFile(new URL('../fixtures/sample_jd_01.txt',import.meta.url),'utf8');
let reads=0;const refused={identityAction:'create',workingMode:'independent',consentDecision:'refuse'};Object.defineProperty(refused,'cvText',{get(){reads++;return cv;}});Object.defineProperty(refused,'jdText',{get(){reads++;return jd;}});
const no=await prepareStagedPrivateBetaJourney({uiInput:refused,modelAdapter:adapter});assert.equal(no.publicResult.error.code,'CONSENT_REFUSED');assert.equal(reads,0);
const prep=await prepareStagedPrivateBetaJourney({uiInput:{identityAction:'create',workingMode:'independent',consentDecision:'accept',cvText:cv,jdText:jd,targetRole:'Product Operations Manager',userNotes:'Responsabilità aggiuntiva non chiara nel CV.',uiLocale:'it'},modelAdapter:adapter});
assert.equal(prep.publicResult.phase,'understanding');assert.ok(prep.state.session.fhtAcquisitionPlanning);assert.equal(prep.state.fhtCurrentAcquisitionActionAssociation?.runtimeActionRef,'interviewQuestion:opening_career_walkthrough');assert.deepStrictEqual(prep.state.session.fhtAcquisitionPlanning.activeGoals,['decision_accountability','quantified_outcome']);assert.equal(prep.state.session.fhtAcquisitionPlanning.purposes.length,2);assert(prep.state.session.fhtAcquisitionPlanning.runtimeSessions.every(x=>x.status==='created'));assert(prep.state.session.fhtAcquisitionPlanning.runtimeActionAssociations.some(x=>x.runtimeActionRef==='interviewQuestion:opening_career_walkthrough'));assert.ok(prep.publicResult.preInterview?.cvReviewReport);assert.equal(prep.state.session.rawInput.userNotes,'Responsabilità aggiuntiva non chiara nel CV.');assert.equal(prep.state.session.rawInput.jdText,jd.trim());const continued=(await import('../src/app/privateBetaJourneyIntegration.js')).continueStagedPrivateBetaJourney({state:prep.state,representationAgreement:'incomplete'});assert.equal(continued.publicResult.phase,'interview');assert.equal(continued.state.preInterview.agreement,'incomplete');assert.ok(continued.publicResult.currentQuestion?.question);const first=continued.publicResult.currentQuestion;const beforeIndex=prep.state.session.interviewRuntime.runtimeState.currentStepIndex;
const one=await answerStagedPrivateBetaJourney({state:prep.state,answer:'Presento liberamente il mio percorso professionale, dalle attività di analisi fino alle responsabilità operative più recenti.'});
assert.equal(one.state.session.interviewRuntime.runtimeState.answers.length,1);const nextPayload=one.state.session.interviewRuntime?.currentStep?.payload||{};const nextKey=nextPayload.questionKey||nextPayload.familyKey||'';if(['achievement_quantification','decision_tradeoff_probe','responsibility_probe'].includes(nextKey))assert.equal(one.state.fhtCurrentAcquisitionActionAssociation?.runtimeActionRef,`interviewQuestion:${nextKey}`);if(nextKey==='consistency_probe'&&nextPayload.sourceQuestionKey){const sourceAssociation=one.state.session.fhtAcquisitionPlanning.runtimeActionAssociations.find(x=>x.runtimeActionRef===`interviewQuestion:${nextPayload.sourceQuestionKey}`)||null;assert.equal(Boolean(one.state.fhtCurrentAcquisitionActionAssociation),Boolean(sourceAssociation));}
assert.equal(one.state.usedQuestionHistory.length,1);assert.equal(one.state.usedQuestionHistory[0].key,one.state.session.interviewRuntime.runtimeState.answers[0].questionContext.questionKey);assert.equal(one.state.session.interviewRuntime.runtimeState.answers[0].stepType,first.stepType);assert.ok(one.state.session.interviewRuntime.runtimeState.currentStepIndex>beforeIndex);assert.ok(one.publicResult.currentQuestion?.question || one.publicResult.phase==='feedback');
const semanticPrep=await prepareStagedPrivateBetaJourney({uiInput:{identityAction:'create',workingMode:'independent',consentDecision:'accept',cvText:cv,jdText:jd,targetRole:'Product Operations Manager',uiLocale:'it'},modelAdapter:adapter});(await import('../src/app/privateBetaJourneyIntegration.js')).continueStagedPrivateBetaJourney({state:semanticPrep.state,representationAgreement:'continue'});const daExec=()=>({supported:true,observation:{observationId:'da:staged',decisionAuthority:'final',consequenceScope:'team',accountabilityEvidence:'explicit_with_outcomes',responsibilityContinuityMonths:12,context:{episode:'delivery'},inferenceSupportInputs:{evidenceQuality:{state:'not_yet_derived'},sourceConvergence:{state:'not_yet_derived'},consistency:{state:'not_yet_derived'},coverage:{state:'not_yet_derived'}},limitations:[],metadata:{createdAt:'2026-09-03T14:00:00.000Z'}}});const qoExec=()=>({supported:true,observation:{observationId:'qo:staged',measurableOutcome:'riduzione tempi circa 20%',quantitativeValue:{value:20,unit:'percent',approximation:'approximate',lowerBound:null,upperBound:null},contributionRelationship:'contributed',causalityBoundary:'contribution_only',context:{event:'delivery improvement'},limitations:['contribution only'],metadata:{createdAt:'2026-09-03T14:00:00.000Z'}}});const semanticOne=await answerStagedPrivateBetaJourney({state:semanticPrep.state,answer:'Ho preso la decisione e ho contribuito a ridurre i tempi di circa 20%.',decisionAccountabilityExecutor:daExec,quantifiedOutcomeExecutor:qoExec});assert.equal(semanticOne.state.productPurpose,'interview_practice');assert.equal(semanticOne.state.session.fhtLastAcquisitionAction.association.purposeRefs.length,2);assert.equal(semanticOne.state.session.fhtLastAcquisitionAction.results.length,0);assert.equal(semanticOne.state.session.runtimeKnowledgeResults.filter(x=>x.semanticType==='decision_accountability').length,0);assert.equal(semanticOne.state.session.runtimeKnowledgeResults.filter(x=>x.semanticType==='quantified_outcome').length,0);assert.equal(semanticOne.state.session.imagoEvidenceStore.evidence.length,0);assert.equal(semanticOne.state.session.interviewRuntime.runtimeState.answers.length,1);
const repeat=await prepareStagedPrivateBetaJourney({uiInput:{identityAction:'create',workingMode:'independent',consentDecision:'accept',cvText:cv,jdText:jd,targetRole:'Product Operations Manager',uiLocale:'it'},modelAdapter:adapter,recentQuestionKeys:one.state.usedQuestionHistory.map(x=>x.key),recentQuestionHistory:one.state.usedQuestionHistory});assert.equal(repeat.publicResult.phase,'understanding');assert.deepStrictEqual(repeat.state.session.interviewQuestionSet.contextualSelection.questionSelectionStrategy.recentQuestionKeys,one.state.usedQuestionHistory.map(x=>x.key));console.log('ME-01D/ME-02C staged application boundary tests PASSED');
