import assert from 'node:assert/strict';
import {evaluateCareerDirections} from '../src/app/careerDirection/evaluateCareerDirections.js';
import {startDirectionPeopleResponsibilityProductionAcquisition,answerDirectionPeopleResponsibilityProductionAcquisition,resolveCurrentDirectionPeopleResponsibilityConditions} from '../src/app/careerDirection/directionKnowledgeAcquisition.js';
import {buildCareerDirectionClarificationQueue} from '../src/app/careerDirection/buildCareerDirectionClarificationQueue.js';
import {renderPrivateBetaUiJourneyHtml} from '../src/app/renderPrivateBetaUiJourneyHtml.js';
const now='2026-09-29T10:00:00.000Z',subjectRef={type:'person',id:'pd074fc'};
const rep={professionalMeaning:{supportedPatterns:[{kind:'documented_cross_functional_coordination_recurrence'}],professionalSynthesis:{hasDocumentedRoleContinuity:true,currentRole:'Production Supervisor',previousRoles:['Industrialization Engineer'],domains:['production']},knowledgeContribution:[{primaryProfessionalMeaning:{kind:'bounded_decision_accountability'}},{primaryProfessionalMeaning:{kind:'bounded_measurable_outcome_contribution'}}]}};
const evaluation=evaluateCareerDirections({professionalRepresentation:rep,professionalRepresentationRef:'professionalRepresentation:pd074fc',now});
const ops=evaluation.hypotheses.find(x=>x.metadata.roleFamilyRef==='operations_management');
const identity={type:'private_beta_professional_identity_continuity',personRef:subjectRef,professionalSources:[],reusableKnowledgeResults:[]};
const answer='Ho gestito continuativamente circa 5 persone di officina, assegnando le attività e definendo le priorità di lavoro.';
const candidate={interpretationStatus:'SUPPORTED',responsibilityPresence:'supported',continuity:'continuing',responsibilityMode:'informal_operational',responsibilityKinds:['work_assignment_or_priority_setting'],peopleScope:{kind:'category',value:'circa 5 persone',min:null,max:null},professionalContext:{description:'officina',current:true},eventTime:{description:null},support:{presence:'Ho gestito',continuity:'continuativamente',mode:'assegnando le attività',peopleScope:'circa 5 persone',professionalContext:'officina',responsibilityKinds:['assegnando le attività']},limitations:['formal reporting authority not established']};
const started=await startDirectionPeopleResponsibilityProductionAcquisition({careerDirectionEvaluation:evaluation,selectedDirectionRef:ops.id,userAction:'deepen_career_direction',professionalIdentity:identity,subjectRef,professionalRepresentationRef:'professionalRepresentation:pd074fc',now});
const done=await answerDirectionPeopleResponsibilityProductionAcquisition({state:started,answer,careerDirectionEvaluation:evaluation,subjectRef,now,semanticExecutor:async()=>({supported:true,candidate,provider:{model:'test'}})});
assert.equal(done.status,'resolved');
const persisted={...identity,reusableKnowledgeResults:[{...done.knowledgeResult,semanticType:'continuing_people_responsibility',semanticPolicyRef:done.ka.design.semanticPolicyRef,knowledgeRef:`knowledgeSnapshot:${done.knowledgeResult.knowledgeSnapshot.id}`}]};
const resolutions=resolveCurrentDirectionPeopleResponsibilityConditions({careerDirectionEvaluation:evaluation,professionalIdentity:persisted,subjectRef,now});
assert.equal(resolutions.length,2);assert(resolutions.every(x=>x.resolutionState==='resolved_by_current_authorised_state'));
const queue=buildCareerDirectionClarificationQueue({careerDirectionEvaluation:evaluation,directionResolutions:resolutions});
assert.equal(queue.some(x=>x.conditionReason==='people_responsibility_scope'),false);
assert.equal(queue.length,2);assert(queue.every(x=>x.actionability==='informational_only'));
assert.deepEqual(new Set(queue.map(x=>x.conditionReason)),new Set(['broader_resource_budget_scope','production_planning_scope']));
const html=renderPrivateBetaUiJourneyHtml({locale:'it',result:{status:'understanding',completed:false,phase:'purpose_direction_explore',sessionRef:'pd074fc-session',preInterview:{careerDirectionEvaluation:evaluation,directionResolutions:resolutions}}});
const peopleQuestion='Hai già avuto responsabilità continuativa sulle persone, oltre al coordinamento operativo?';
assert.equal(html.includes(peopleQuestion),false);
assert.equal((html.match(/1 aspetto resta da chiarire\./g)||[]).length,2);
assert.match(html,/risorse o budget su un perimetro operativo più ampio/i);assert.match(html,/pianificazione e programmazione della produzione/i);
assert.equal((html.match(/Approfondisci questo aspetto/g)||[]).length,2); // PD-086 makes the two bounded responsibility clarifications actionable in the current UI.
const source=await import('node:fs').then(fs=>fs.readFileSync('src/app/privateBetaUiServer.js','utf8'));
assert.match(source,/projectCurrentCareerDirectionState/);
assert.match(source,/currentDirectionState/);
// PD-074 Second Corrective restart/rehydration case: continuity ordering is not recency.
const oldItem=JSON.parse(JSON.stringify(persisted.reusableKnowledgeResults[0]));
oldItem.knowledgeRef='knowledgeSnapshot:zzzz-stale-pre-acquisition';
oldItem.knowledgeSnapshot.metadata.createdAt='2026-09-28T08:00:00.000Z';
oldItem.knowledgeLedger.metadata.createdAt='2026-09-28T08:00:00.000Z';
oldItem.knowledgeLedger.metadata.updatedAt='2026-09-28T08:00:00.000Z';
oldItem.specializedMeasurementResult=null;
const currentItem=JSON.parse(JSON.stringify(persisted.reusableKnowledgeResults[0]));
currentItem.knowledgeRef='knowledgeSnapshot:aaaa-current-pd073';
currentItem.knowledgeSnapshot.metadata.createdAt='2026-09-29T10:00:00.000Z';
const rehydrated=JSON.parse(JSON.stringify({...persisted,reusableKnowledgeResults:[currentItem,oldItem].sort((a,b)=>a.knowledgeRef.localeCompare(b.knowledgeRef))}));
const rehydratedResolutions=resolveCurrentDirectionPeopleResponsibilityConditions({careerDirectionEvaluation:evaluation,professionalIdentity:rehydrated,subjectRef,now:'2026-09-29T10:05:00.000Z'});
assert(rehydratedResolutions.every(x=>x.resolutionState==='resolved_by_current_authorised_state'),'rehydration must select current canonical CPR Knowledge by canonical timestamp, not knowledgeRef ordering');
const guarded=await startDirectionPeopleResponsibilityProductionAcquisition({careerDirectionEvaluation:evaluation,selectedDirectionRef:ops.id,userAction:'deepen_career_direction',professionalIdentity:rehydrated,subjectRef,professionalRepresentationRef:'professionalRepresentation:pd074fc',now:'2026-09-29T10:05:00.000Z'});
assert.equal(guarded.status,'resolved_by_existing_knowledge');
assert.deepEqual(guarded.resolutions.map(x=>x.resolutionState),rehydratedResolutions.map(x=>x.resolutionState));
console.log('PD-074 Second Corrective resolved clarification projection alignment tests passed.');
