import assert from 'node:assert/strict';
import { buildGroundedRelationshipModelInput,createLiveGroundedRelationshipProposalProviders } from '../src/app/liveGroundedRelationshipProposalProvider.js';
import { buildTargetIndependentProfessionalRepresentation } from '../src/app/buildTargetIndependentProfessionalRepresentation.js';
import { renderPrivateBetaUiJourneyHtml } from '../src/app/renderPrivateBetaUiJourneyHtml.js';
const materials=[{materialRef:'source:a',sourceId:'a',summary:'Avviamento linea',facts:['Avviamento della linea con qualità e produzione.'],exactSupports:['Avviamento della linea con qualità e produzione.'],semanticCeiling:{subjectScopes:['source_material'],agencyLevel:'not_established',responsibilityScope:'not_established',ownershipAssertion:'none',decisionAuthorityAssertion:'none',resultCausalityAssertion:'none'}},{materialRef:'source:b',sourceId:'b',summary:'Stabilizzazione processo',facts:['Stabilizzazione del processo con supply chain e engineering.'],exactSupports:['Stabilizzazione del processo con supply chain e engineering.'],semanticCeiling:{subjectScopes:['source_material'],agencyLevel:'not_established',responsibilityScope:'not_established',ownershipAssertion:'none',decisionAuthorityAssertion:'none',resultCausalityAssertion:'none'}}];
const claim=(role)=>({subjectScope:'source_material',descriptiveRole:role,agencyLevel:'not_established',responsibilityScope:'not_established',ownershipAssertion:'none',decisionAuthorityAssertion:'none',resultCausalityAssertion:'none',personPropertyAssertion:'none'});
const relClaim=()=>({subjectScope:'material_relationship',relationshipClaim:'recurrence',personPropertyAssertion:'none',capabilityAssertion:'none',ownershipAssertion:'none',responsibilityAssertion:'none',causalityAssertion:'none',fitReadinessAssertion:'none',sameEpisodeAssertion:'none',continuityAssertion:'none'});
const structured={descriptorProposals:[{proposalRef:'d1',descriptorRole:'work_phase',descriptiveValue:'avviamento della linea',materialRef:'source:a',grounding:{exactText:materials[0].exactSupports[0],supportRef:'source:a:support:1'},claimShape:claim('work_phase')},{proposalRef:'d2',descriptorRole:'work_phase',descriptiveValue:'stabilizzazione del processo',materialRef:'source:b',grounding:{exactText:materials[1].exactSupports[0],supportRef:'source:b:support:1'},claimShape:claim('work_phase')}],relationshipHypotheses:[{proposalRef:'r1',descriptorProposalRefs:['d1','d2'],relationshipWording:'Esperienze documentate distinte comprendono fasi collegate all’avvio o alla stabilizzazione di attività produttive.',relationshipBasis:'bounded_open_semantic_relationship',claimShape:relClaim()}]};
let calls=0,lastPrompt='';const diagnostics=[];const runner=async x=>{calls++;lastPrompt=x.userPrompt;return {model:'controlled-model',outputMode:'json_schema',structured}};
const providers=createLiveGroundedRelationshipProposalProviders({modelRunner:runner,diagnosticSink:x=>diagnostics.push(x)});const d=await providers.descriptorProposalProvider({materials,locale:'it'});const r=await providers.relationshipHypothesisProvider({descriptors:d.map((x,i)=>({status:'accepted',descriptorId:`descriptor:d${i+1}`,provenance:x.provenance})),materials,locale:'it'});assert.equal(calls,1);assert.equal(d.length,2);assert.deepEqual(r[0].descriptorRefs,['descriptor:d1','descriptor:d2']);assert(!lastPrompt.includes('targetRole'));assert(!lastPrompt.includes('Career Preference'));assert(!lastPrompt.includes('Training answer'));assert(d.every(x=>x.persistence==='representation_only'));assert(d.every(x=>!('semanticCeiling' in x)));
const bounded=buildGroundedRelationshipModelInput({materials:[...materials,{materialRef:'',sourceId:'secret',summary:'ignore'}],locale:'it'});assert.equal(bounded.materials.length,2);assert.equal(bounded.materials[0].supports[0].supportRef,'source:a:support:1');assert.equal(bounded.materials[0].supports[0].exactText,materials[0].exactSupports[0]);assert(!JSON.stringify(bounded).includes('productFeedback'));
const sources=[{id:'a',sourceRole:'professional_declaration',content:materials[0].exactSupports[0]},{id:'b',sourceRole:'professional_declaration',content:materials[1].exactSupports[0]}];const projection=sources.map(s=>({sourceId:s.id,sourceRole:s.sourceRole,facts:[s.content],roleDescriptionFacts:[],domainSignals:[],experienceHighlights:[s.content],sourceFaithfulExperienceExcerpts:[s.content],activitySemantics:[]}));
const live=createLiveGroundedRelationshipProposalProviders({modelRunner:runner});const rep=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,descriptorProposalProvider:live.descriptorProposalProvider,relationshipHypothesisProvider:live.relationshipHypothesisProvider});assert.equal(rep.professionalMeaning.groundedDescriptiveRelationships.length,1);assert(rep.professionalMeaning.professionalThreads.some(x=>x.kind==='grounded_descriptive_relationship'));assert(rep.professionalMeaning.level1ProfessionalThreads.some(x=>x.kind==='grounded_descriptive_relationship'));assert(!JSON.stringify(rep).includes('personKnowledgeWriteback":true'));
const html=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'purpose_understand',preInterview:{targetIndependentProfessionalRepresentation:rep}}});assert.match(html,/Esperienze documentate distinte comprendono/);assert.doesNotMatch(html,/LLM|claimShape|semantic ceiling|proposal provider|validator|hypothesis/i);assert.match(html,/Avviamento della linea/);assert.match(html,/Stabilizzazione del processo/);
const invalidRunner=async()=>({model:'controlled',outputMode:'json_schema',structured:{descriptorProposals:[{...structured.descriptorProposals[0],materialRef:'invented'}],relationshipHypotheses:structured.relationshipHypotheses}});const bad=createLiveGroundedRelationshipProposalProviders({modelRunner:invalidRunner});const badRep=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,descriptorProposalProvider:bad.descriptorProposalProvider,relationshipHypothesisProvider:bad.relationshipHypothesisProvider});assert.equal(badRep.professionalMeaning.groundedDescriptiveRelationships.length,0);assert(badRep.professionalMeaning.pd069Validation.descriptorRejections.length>0);
const failed=createLiveGroundedRelationshipProposalProviders({modelRunner:async()=>{throw new Error('provider down')}});const fallback=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,descriptorProposalProvider:failed.descriptorProposalProvider,relationshipHypothesisProvider:failed.relationshipHypothesisProvider});assert.equal(fallback.professionalMeaning.groundedDescriptiveRelationships.length,0);assert(fallback.professionalMeaning.professionalThreads.length>=0);
assert(diagnostics.some(x=>x.stage==='model_call_start'));assert(diagnostics.some(x=>x.stage==='model_call_end'));

const invented=structured.descriptorProposals.map((x,i)=>i?x:{...x,grounding:{...x.grounding,supportRef:'invented:support'}});const inv=createLiveGroundedRelationshipProposalProviders({modelRunner:async()=>({model:'controlled',outputMode:'json_schema',structured:{...structured,descriptorProposals:invented}})});const invRep=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,descriptorProposalProvider:inv.descriptorProposalProvider,relationshipHypothesisProvider:inv.relationshipHypothesisProvider});assert(invRep.professionalMeaning.pd069Validation.descriptorRejections.some(x=>x.errors.includes('unknown_or_cross_material_support_ref')));
const cross=structured.descriptorProposals.map((x,i)=>i?x:{...x,grounding:{...x.grounding,supportRef:'source:b:support:1'}});const crossP=createLiveGroundedRelationshipProposalProviders({modelRunner:async()=>({model:'controlled',outputMode:'json_schema',structured:{...structured,descriptorProposals:cross}})});const crossRep=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,descriptorProposalProvider:crossP.descriptorProposalProvider,relationshipHypothesisProvider:crossP.relationshipHypothesisProvider});assert(crossRep.professionalMeaning.pd069Validation.descriptorRejections.some(x=>x.errors.includes('unknown_or_cross_material_support_ref')));
const mismatch=structured.descriptorProposals.map((x,i)=>i?x:{...x,grounding:{...x.grounding,exactText:'wrong text'}});const mismatchP=createLiveGroundedRelationshipProposalProviders({modelRunner:async()=>({model:'controlled',outputMode:'json_schema',structured:{...structured,descriptorProposals:mismatch}})});const mismatchRep=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,descriptorProposalProvider:mismatchP.descriptorProposalProvider,relationshipHypothesisProvider:mismatchP.relationshipHypothesisProvider});assert(mismatchRep.professionalMeaning.pd069Validation.descriptorRejections.some(x=>x.errors.includes('support_text_mismatch')));
const dupStructured={descriptorProposals:[structured.descriptorProposals[0],{...structured.descriptorProposals[1],proposalRef:'d1'}],relationshipHypotheses:structured.relationshipHypotheses};const dupP=createLiveGroundedRelationshipProposalProviders({modelRunner:async()=>({model:'controlled',outputMode:'json_schema',structured:dupStructured})});const dupRep=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,descriptorProposalProvider:dupP.descriptorProposalProvider,relationshipHypothesisProvider:dupP.relationshipHypothesisProvider});assert.equal(dupRep.professionalMeaning.groundedDescriptiveRelationships.length,0);assert(dupRep.professionalMeaning.pd069Validation.descriptorRejections.some(x=>x.errors.includes('duplicate_descriptor_proposal_ref')));
const dupRel={...structured,relationshipHypotheses:[structured.relationshipHypotheses[0],{...structured.relationshipHypotheses[0]}]};const dupRP=createLiveGroundedRelationshipProposalProviders({modelRunner:async()=>({model:'controlled',outputMode:'json_schema',structured:dupRel})});const dupRRep=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,descriptorProposalProvider:dupRP.descriptorProposalProvider,relationshipHypothesisProvider:dupRP.relationshipHypothesisProvider});assert.equal(dupRRep.professionalMeaning.groundedDescriptiveRelationships.length,0);assert(dupRRep.professionalMeaning.pd069Validation.relationshipRejections.some(x=>x.errors.includes('duplicate_relationship_proposal_ref')));
console.log('PD-069L live grounded relationship proposal controlled integration: PASS');

// PD-069L Second Corrective: the live proposal boundary targets material relationships,
// while unchanged deterministic authority still rejects person-continuity strengthening.
assert.match(lastPrompt,/relationships BETWEEN the documented materials\/situations\/phases\/configurations/i);
assert.match(lastPrompt,/continuityAssertion to none/i);
assert.match(lastPrompt,/Do not turn recurrence or related operational phases into professional continuity/i);
assert.equal(structured.relationshipHypotheses[0].claimShape.continuityAssertion,'none');
assert.match(structured.relationshipHypotheses[0].relationshipWording,/Esperienze documentate distinte/i);
assert.notEqual(structured.relationshipHypotheses[0].relationshipWording,`${structured.descriptorProposals[0].descriptiveValue}. ${structured.descriptorProposals[1].descriptiveValue}.`);
const continuityStructured={...structured,relationshipHypotheses:[{...structured.relationshipHypotheses[0],proposalRef:'r-continuity',relationshipWording:'Il percorso professionale dimostra continuità tra le due attività.',claimShape:{...relClaim(),continuityAssertion:'professional_continuity'}}]};
const continuityProvider=createLiveGroundedRelationshipProposalProviders({modelRunner:async()=>({model:'controlled',outputMode:'json_schema',structured:continuityStructured})});
const continuityRep=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,descriptorProposalProvider:continuityProvider.descriptorProposalProvider,relationshipHypothesisProvider:continuityProvider.relationshipHypothesisProvider});
assert.equal(continuityRep.professionalMeaning.groundedDescriptiveRelationships.length,0);
assert(continuityRep.professionalMeaning.pd069Validation.relationshipRejections.some(x=>x.errors.includes('relationship_continuity_prohibited')));
assert.equal(continuityStructured.relationshipHypotheses[0].claimShape.continuityAssertion,'professional_continuity');
