import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createPrivateBetaUiServer } from '../src/app/privateBetaUiServer.js';
import { createMemoryPrivateBetaProfessionalIdentityStore, privateBetaPersonRefFromContext, validatePrivateBetaProfessionalIdentityContinuityRecord } from '../src/app/privateBetaProfessionalIdentityContinuity.js';
import { buildTargetIndependentRepresentationSnapshotState, findReusableTargetIndependentRepresentationSnapshot, classifyRepresentationSnapshotChange } from '../src/app/privateBetaProfessionalRepresentationSnapshots.js';

const fixture=JSON.parse(await readFile(new URL('../fixtures/expected_candidate_profile_01.json',import.meta.url),'utf8'));
const candidate=summary=>{const x=structuredClone(fixture);(x.candidateProfile||x).summary=summary;return x;};
const adapter=async({task,user})=>{assert.equal(task,'candidateProfile');return JSON.stringify(candidate(user.includes('Germany')?'Industrialization Engineer Germany':user.includes('Atlas')?'Atlas supplier ramp-up':user.includes('manutenzione')?'produzione manutenzione':'Production Supervisor'));};
const personRef=privateBetaPersonRefFromContext('pr04-human');
const mk=(id,role,content)=>({id,type:'text',label:role,content,language:null,sourceRole:role,quality:null,provenance:{origin:role,providedBy:'user',collectedAt:'2026-09-10T06:00:00.000Z'},metadata:{createdAt:'2026-09-10T06:00:00.000Z',updatedAt:'2026-09-10T06:00:00.000Z'}});
const sources=[mk('current_cv','current_cv','Marco. Production Supervisor. Operations Manufacturing. 12 anni.'),mk('previous_cv','previous_cv','Industrialization Engineer. Start-up linea produttiva in Germany.'),mk('professional_declaration','professional_declaration','Project Atlas supplier ramp-up con supply chain, qualità e produzione.'),mk('professional_declaration_2','professional_declaration','Coordinamento produzione e manutenzione durante interventi pianificati. Nessun risultato quantitativo consolidato.')];
const da={semanticType:'decision_accountability',semanticPolicyRef:'professional_semantic_policy:decision_accountability:v1',knowledgeRef:'ks-da',knowledgeSnapshot:{id:'ks-da'},observation:{observationType:'decision_accountability',observationStatus:'observed',observationId:'o-da',evidenceIds:['e-da'],decisionAuthority:'shared',consequenceScope:'team',accountabilityEvidence:'explicit_with_outcomes',context:{decision:'trade-off operativo',responsibility:'decisione condivisa',consequence:'continuità produttiva'},limitations:[]}};
const qo={semanticType:'quantified_outcome',semanticPolicyRef:'professional_semantic_policy:quantified_outcome:v1',knowledgeRef:'ks-qo',knowledgeSnapshot:{id:'ks-qo'},observation:{observationType:'quantified_outcome',observationId:'o-qo',evidenceIds:['e-qo'],measurableOutcome:'miglioramento osservato',quantitativeValue:{value:20,unit:'percent',approximate:true,direction:'increase'},contributionRelationship:'contributed',causalityBoundary:'contribution_only',context:{event:'miglioramento produttivo'},limitations:['contribution only']}};
const baseRecord={version:'1.0',type:'private_beta_professional_identity_continuity',professionalIdentityRef:`professionalIdentity:${personRef.id}`,personRef,owner:'person',authorizedMaterials:{cvText:sources[0].content,userNotes:''},professionalSources:sources,reusableKnowledgeResults:[da],knowledgeRefs:['ks-da'],revision:3,createdAt:'2026-09-10T06:00:00.000Z',updatedAt:'2026-09-10T06:00:00.000Z',lastEnrichedBySessionRef:null};
const body=new URLSearchParams({identityAction:'recover',workingMode:'independent',productPurpose:'professional_representation_understand',consentDecision:'accept',targetRole:'',cvText:'',previousCvText:'',professionalDeclaration:'',userNotes:'',jdText:'',uiLocale:'it',sessionLocale:'it'});
let synthesisCalls=0;const narrativeRealizer=async()=>{synthesisCalls++;return {rawContent:'{}'};};
async function understand(store,{recipeVersion='1.1'}={}){const server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:store,contextIdFactory:()=> 'pr04-human',journeyOptions:{modelAdapter:adapter,useRepresentationModel:true,representationNarrativeRealizer:narrativeRealizer,representationRecipeVersion:recipeVersion}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const response=await fetch(`http://127.0.0.1:${server.address().port}/private-beta/journey`,{method:'POST',headers:{cookie:'imago_beta_repeat_context=pr04-human','content-type':'application/x-www-form-urlencoded'},body});const html=await response.text();await new Promise(r=>server.close(r));assert.equal(response.status,200,html);return store.load({personRef});}
const store=createMemoryPrivateBetaProfessionalIdentityStore();await store.save({record:baseRecord});
const s1Record=await understand(store);assert.equal(synthesisCalls,1);assert.equal(s1Record.revision,3,'Understand must not increment PI revision');assert.equal(s1Record.representationSnapshots.length,1);const s1=structuredClone(s1Record.representationSnapshots[0]);assert.equal(s1.changeCause,'initial_materialization');assert.equal(s1.purpose,'professional_representation_understand');assert.equal(s1.context,'target_independent');assert.equal(s1.representation.type,'target_independent_professional_representation');
const same=await understand(store);assert.equal(synthesisCalls,1,'same state must bypass synthesis provider');assert.equal(same.representationSnapshots.length,1);assert.equal(same.representationSnapshots[0].snapshotId,s1.snapshotId);assert.deepEqual(same.representationSnapshots[0].representation,s1.representation);assert.equal(same.revision,3);
// Serialization/restart boundary: restore the persisted PI artifact into a fresh process-local store.
const restoredArtifact=JSON.parse(JSON.stringify(same));validatePrivateBetaProfessionalIdentityContinuityRecord(restoredArtifact,{personRef});const restartedStore=createMemoryPrivateBetaProfessionalIdentityStore();await restartedStore.save({record:restoredArtifact});const afterRestart=await understand(restartedStore);assert.equal(synthesisCalls,1,'restart/reopen with same artifact must reuse snapshot');assert.equal(afterRestart.representationSnapshots.length,1);
// Source change -> S2, S1 immutable; repeat S2 reuses.
const sourceChanged=structuredClone(afterRestart);sourceChanged.professionalSources.push(mk('professional_declaration_3','professional_declaration','Nuova esperienza autorizzata: supporto al passaggio consegne tra due turni.'));sourceChanged.revision++;sourceChanged.updatedAt='2026-09-10T07:00:00.000Z';await restartedStore.save({record:sourceChanged});const s2Record=await understand(restartedStore);assert.equal(synthesisCalls,2);assert.equal(s2Record.representationSnapshots.length,2);assert.deepEqual(s2Record.representationSnapshots[0],s1);assert.equal(s2Record.representationSnapshots[1].changeCause,'professional_source_state_change');const s2=s2Record.representationSnapshots[1];assert.notEqual(s2.snapshotId,s1.snapshotId);await understand(restartedStore);assert.equal(synthesisCalls,2);assert.equal((await restartedStore.load({personRef})).representationSnapshots.length,2);
// Knowledge/observability change -> new snapshot, not person improvement.
const knowledgeChanged=await restartedStore.load({personRef});knowledgeChanged.reusableKnowledgeResults.push(qo);knowledgeChanged.knowledgeRefs.push('ks-qo');knowledgeChanged.revision++;knowledgeChanged.updatedAt='2026-09-10T07:10:00.000Z';await restartedStore.save({record:knowledgeChanged});const s3Record=await understand(restartedStore);assert.equal(synthesisCalls,3);assert.equal(s3Record.representationSnapshots.length,3);assert.equal(s3Record.representationSnapshots[2].changeCause,'knowledge_observability_change');assert.doesNotMatch(JSON.stringify(s3Record.representationSnapshots[2]),/professional_improvement|greater_competence/i);
// Recipe-only change -> new snapshot and independent cause.
const s4Record=await understand(restartedStore,{recipeVersion:'1.2-test'});assert.equal(synthesisCalls,4);assert.equal(s4Record.representationSnapshots.length,4);assert.equal(s4Record.representationSnapshots[3].changeCause,'representation_recipe_change');assert.deepEqual(s4Record.representationSnapshots.slice(0,3),s3Record.representationSnapshots);await understand(restartedStore,{recipeVersion:'1.2-test'});assert.equal(synthesisCalls,4);assert.equal((await restartedStore.load({personRef})).representationSnapshots.length,4);
// Authorization guard: current authorization participates in deterministic reuse eligibility.
const revokedState=buildTargetIndependentRepresentationSnapshotState({professionalIdentity:s4Record,professionalSources:s4Record.professionalSources,reusableKnowledgeResults:s4Record.reusableKnowledgeResults,authorizationState:'withdrawn',recipe:{id:'target_independent_professional_representation',version:'1.2-test'}});assert.equal(findReusableTargetIndependentRepresentationSnapshot({professionalIdentity:s4Record,state:revokedState}),null);assert.equal(classifyRepresentationSnapshotChange({previousSnapshot:s4Record.representationSnapshots[3],state:revokedState}),'authorization_change');
// Backward compatibility already exercised by baseRecord: no representationSnapshots field, first Understand created S1.
assert.equal(baseRecord.representationSnapshots,undefined);assert.equal(baseRecord.currentRepresentationSnapshotRefs,undefined);
assert.equal((await restartedStore.load({personRef})).reusableKnowledgeResults.length,2);assert.equal((await restartedStore.load({personRef})).professionalSources.length,5);
console.log('PR-04 target-independent Representation snapshot reuse vertical slice: PASS');
