const assert = require('assert');
const api = require('../src/core/observation');
const fixture = require('./registered_evidence_observation_construction_fixture').buildFixture();
const before = JSON.stringify(fixture);
const observations = api.constructObservationsFromRegisteredEvidence(fixture);
assert.equal(observations.length, 2, 'one Evidence may emit several atomic Observations');
assert.deepStrictEqual(observations, api.constructObservationsFromRegisteredEvidence(fixture), 'construction must be deterministic');
assert(observations.every((item, index) => index === 0 || observations[index - 1].id.localeCompare(item.id) < 0), 'output must be canonical');
assert(observations.every(item => item.measurementId === fixture.measurement.id && item.contentRef.id === fixture.evidence[0].id && item.sourceRef.id === fixture.evidence[0].sourceId));
assert(observations.every(item => api.validateObservation(item).valid && Object.isFrozen(item) && Object.isFrozen(item.extensions)));
assert.deepStrictEqual(api.constructObservationsFromRegisteredEvidence({ ...fixture, evidence: [] }), [], 'empty input must not infer absence');
assert.deepStrictEqual(api.constructObservationsFromRegisteredEvidence({ ...fixture, evidence: [fixture.evidence[1]] }), [], 'unmatched Evidence must not infer absence');
const reversed = { ...fixture, evidence: [...fixture.evidence].reverse(), construction: { ...fixture.construction, rules: [...fixture.construction.rules].reverse() } };
assert.deepStrictEqual(api.constructObservationsFromRegisteredEvidence(reversed), observations, 'accidental input and rule order must not affect output');
const objectEvidence = { ...fixture.evidence[0], content: { b: 2, a: 1 } };
const objectRule = { ...fixture.construction.rules[0], match: { field: 'content', operator: 'equals', value: { a: 1, b: 2 } } };
const structural = api.constructObservationsFromRegisteredEvidence({ ...fixture, evidence: [objectEvidence], construction: { ...fixture.construction, rules: [objectRule] } });
const reorderedContent = api.constructObservationsFromRegisteredEvidence({ ...fixture, evidence: [{ ...objectEvidence, content: { a: 1, b: 2 } }], construction: { ...fixture.construction, rules: [objectRule] } });
assert.equal(structural.length, 1, 'structurally equal content must match');
assert.equal(structural[0].id, reorderedContent[0].id, 'object key order must not affect identity');
const changedEvidence = { ...objectEvidence, content: { a: 1, b: 3 } };
const changedRule = { ...objectRule, match: { field: 'content', operator: 'equals', value: { a: 1, b: 3 } } };
const changed = api.constructObservationsFromRegisteredEvidence({ ...fixture, evidence: [changedEvidence], construction: { ...fixture.construction, rules: [changedRule] } });
assert.notEqual(structural[0].id, changed[0].id, 'changed Evidence content must not retain a stale Observation identity');
assert.equal(JSON.stringify(fixture), before, 'inputs must remain unchanged');
console.log('Registered Evidence Observation Construction tests PASSED');
