const assert=require('assert');
const M=require('../src/core/measurement/decisionAccountability');
const D=require('../src/core/dimension');
const {projectDecisionAccountabilityMeasureResult}=require('../src/core/measurement/decisionAccountability/projectDecisionAccountabilityMeasureResult');
const {buildDecisionAccountabilityMeasurementDimensionMapping}=require('../src/core/dimension/buildDecisionAccountabilityMeasurementDimensionMapping');
const now='2026-09-03T16:00:00.000Z';
function observation(inferenceSupportInputs){return M.buildDecisionAccountabilityObservation({observationId:'obs:kc01',decisionAuthority:'final',consequenceScope:'site',accountabilityEvidence:'explicit_with_outcomes',responsibilityContinuity:{state:'known',qualification:'exact',months:30},context:{decision:'release'},evidenceIds:['ev:kc01'],inferenceSupportInputs});}
const knownInputs={evidenceQuality:{state:'known',value:.9,producer:{producerRef:'eq:1'}},sourceConvergence:{state:'known',value:.85,producer:{producerRef:'sc:1'}},consistency:{state:'known',value:.9,producer:{producerRef:'co:1'}},coverage:{state:'known',value:.8,producer:{producerRef:'cv:1'}}};
const partialInputs={evidenceQuality:{state:'known',value:.9,producer:{producerRef:'eq:1'}},sourceConvergence:{state:'not_yet_derived'},consistency:{state:'not_yet_derived'},coverage:{state:'not_yet_derived'}};
const mapping=buildDecisionAccountabilityMeasurementDimensionMapping({now});
const knownSpecial=M.buildDecisionAccountabilityMeasureResult({observation:observation(knownInputs)});const known=projectDecisionAccountabilityMeasureResult(knownSpecial,{calculatedAt:now});assert.equal(known.confidenceState,'known');assert.equal(known.confidence,knownSpecial.inferenceSupport.value);const knownC=D.mapMeasurementResultToDimensionContributions(known,mapping)[0];assert.equal(knownC.confidenceState,'known');assert.equal(knownC.confidence,known.confidence);const knownK=D.aggregateDimensionContributions('decision_accountability',[knownC],{now});assert.equal(knownK.confidenceState,'known');assert.equal(knownK.confidence,knownC.confidence);
const partialSpecial=M.buildDecisionAccountabilityMeasureResult({observation:observation(partialInputs)});assert.equal(partialSpecial.resultStatus,'draft');assert.equal(partialSpecial.inferenceSupport.state,'partial');const partial=projectDecisionAccountabilityMeasureResult(partialSpecial,{calculatedAt:now});assert(D.validateMeasurementResult?D.validateMeasurementResult(partial).valid:true);assert.equal(partial.normalizedValue,partialSpecial.score);assert.equal(partial.direction,'positive');assert.equal(partial.confidenceState,'partial');assert.equal(partial.confidence,null);assert.deepEqual(partial.extensions.inferenceSupport,partialSpecial.inferenceSupport);
const partialC=D.mapMeasurementResultToDimensionContributions(partial,mapping)[0];assert.equal(partialC.confidenceState,'partial');assert.equal(partialC.confidence,null);assert.equal(partialC.contributionValue,partial.normalizedValue);const partialK=D.aggregateDimensionContributions('decision_accountability',[partialC],{now});assert.equal(partialK.stateType,'observed');assert.equal(partialK.direction,'supporting');assert.equal(partialK.confidenceState,'partial');assert.equal(partialK.confidence,null);assert(partialK.estimate>.5);assert.equal(partialK.extensions.aggregation.confidenceStrategy,'not_derived_no_numeric_weight_v1');
const mixed=D.aggregateDimensionContributions('decision_accountability',[knownC,partialC],{now});assert.equal(mixed.confidenceState,'partial');assert.equal(mixed.confidence,null);assert.equal(mixed.extensions.aggregation.strategy,'semantic_signed_mean_with_explicit_unknown_confidence_v1');
const again=projectDecisionAccountabilityMeasureResult(partialSpecial,{calculatedAt:now});assert.deepStrictEqual(again,partial);assert.equal(projectDecisionAccountabilityMeasureResult(M.buildDecisionAccountabilityMeasureResult({observation:M.buildDecisionAccountabilityObservation({observationId:'obs:bad'})}),{calculatedAt:now}),null);
console.log('FHT-KC01 uncertainty preservation tests PASS');
