import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
import {createHash} from 'node:crypto';
import {buildProfessionalProfileBackup,serializeProfessionalProfileBackup,serializeProtectedProfessionalProfileBackup,parseProfessionalProfileBackup,restoreProfessionalProfileBackup,inspectProfessionalProfileBackupEnvelope,IMAGO_PROFILE_BACKUP_SCRYPT,IMAGO_PROFILE_BACKUP_CIPHER} from '../src/app/privateBetaProfessionalProfileBackup.js';
import {privateBetaPersonRefFromContext,attachPrivateBetaProfessionalSourceAsset,createMemoryPrivateBetaProfessionalIdentityStore} from '../src/app/privateBetaProfessionalIdentityContinuity.js';
import {buildProfessionalSourceAsset} from '../src/app/privateBetaProfessionalSourceAssets.js';
import {createPrivateBetaUiServer} from '../src/app/privateBetaUiServer.js';
import {renderApplicationDocumentDocx} from '../src/app/opportunityApplication/renderApplicationDocx.js';
import {renderApplicationDocumentPdf} from '../src/app/opportunityApplication/renderApplicationDocumentPdf.js';
import {renderPrivateBetaUiJourneyHtml} from '../src/app/renderPrivateBetaUiJourneyHtml.js';

const sha=b=>createHash('sha256').update(b).digest('hex');
const sourcePerson=privateBetaPersonRefFromContext('pd088b-source');
const sources=[{id:'current-cv',type:'text',sourceRole:'current_cv',content:'Marco Rossi. Production Supervisor. Coordinamento produzione e pianificazione.',metadata:{candidateName:'Marco Rossi'},provenance:{origin:'candidate_upload',providedBy:'user'}}];
const knowledge=[{semanticType:'resource_budget_responsibility_scope',semanticPolicyRef:'policy:resource_budget_responsibility_scope',knowledgeSnapshot:{id:'budget-1',subjectRef:sourcePerson},knowledgeRef:'knowledgeSnapshot:budget-1',sourceEvidenceRef:'evidence:budget-1'}];
const dm={type:'application_document_model',documentType:'cv',generatedAt:'2026-09-30T14:00:00Z',sections:[{kind:'cv_header',blocks:[{kind:'candidate_name',text:'Marco Rossi'}]}]};
const appArtifacts={targetedCv:{documentModel:dm}};
let record={version:'1.0',type:'private_beta_professional_identity_continuity',professionalIdentityRef:`professionalIdentity:${sourcePerson.id}`,personRef:sourcePerson,owner:'person',authorizedMaterials:{cvText:sources[0].content},professionalSources:sources,sourceAssets:[],reusableKnowledgeResults:knowledge,knowledgeRefs:['knowledgeSnapshot:budget-1'],revision:1,createdAt:'2026-09-30T13:50:00Z',updatedAt:'2026-09-30T13:50:00Z',lastEnrichedBySessionRef:null,representationSnapshots:[],currentRepresentationSnapshotRefs:{},applicationState:{careerPreferenceContext:{candidateDeclared:true,preferredThemes:['operations']},applicationArtifacts:appArtifacts}};
const docx=renderApplicationDocumentDocx({documentModel:dm}),pdf=renderApplicationDocumentPdf({documentModel:dm});
record=attachPrivateBetaProfessionalSourceAsset({priorRecord:record,sourceAsset:buildProfessionalSourceAsset({sourceRef:'current-cv',originalFilename:'Marco Rossi CV.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',bytes:docx}),now:'2026-09-30T13:51:00Z'});
record=attachPrivateBetaProfessionalSourceAsset({priorRecord:record,sourceAsset:buildProfessionalSourceAsset({sourceRef:'current-cv',originalFilename:'Marco Rossi Portfolio.pdf',mimeType:'application/pdf',bytes:pdf}),now:'2026-09-30T13:52:00Z'});
const backup=buildProfessionalProfileBackup({record,exportedAt:'2026-09-30T14:00:00Z',locale:'it'}),password='frase lunga 2026!';
const t0=performance.now(),protectedBytes=serializeProtectedProfessionalProfileBackup(backup,{password}),exportMs=performance.now()-t0;
assert.equal(inspectProfessionalProfileBackupEnvelope(protectedBytes).encrypted,true);assert.equal(inspectProfessionalProfileBackupEnvelope(protectedBytes).containerVersion,3);assert.equal(IMAGO_PROFILE_BACKUP_CIPHER,'aes-256-gcm');assert.equal(IMAGO_PROFILE_BACKUP_SCRYPT.N,16384);
assert.doesNotMatch(protectedBytes.toString('latin1'),/Marco Rossi|Production Supervisor|\.docx|\.pdf|frase lunga/);
const t1=performance.now(),parsed=parseProfessionalProfileBackup(protectedBytes,{password}),importMs=performance.now()-t1;assert.equal(parsed.security.encrypted,true);assert.equal(parsed.sourceAssetBytes[record.sourceAssets[0].assetId].compare(Buffer.from(record.sourceAssets[0].contentBase64,'base64')),0);
assert.throws(()=>parseProfessionalProfileBackup(protectedBytes,{password:'password sbagliata'}),/AUTHENTICATION_FAILED/);assert.throws(()=>parseProfessionalProfileBackup(protectedBytes),/PASSWORD_REQUIRED/);
const modified=Buffer.from(protectedBytes);modified[modified.length-30]^=0x01;assert.throws(()=>parseProfessionalProfileBackup(modified,{password}),/AUTHENTICATION_FAILED/);
const headerModified=Buffer.from(protectedBytes);const headerStart=7+4;headerModified[headerStart+5]^=0x01;assert.throws(()=>parseProfessionalProfileBackup(headerModified,{password}),/AUTHENTICATION_FAILED|INVALID_FORMAT/);
const destination=privateBetaPersonRefFromContext('pd088b-fresh'),restored=restoreProfessionalProfileBackup({backup:parsed,destinationPersonRef:destination,now:'2026-09-30T14:10:00Z'});assert.equal(restored.reusableKnowledgeResults.length,1);assert.equal(restored.sourceAssets.length,2);assert.equal(sha(Buffer.from(restored.sourceAssets[0].contentBase64,'base64')),record.sourceAssets[0].sha256);assert.ok(renderApplicationDocumentDocx({documentModel:restored.applicationState.applicationArtifacts.targetedCv.documentModel}).length>500);
// v2 remains directly importable.
const v2=serializeProfessionalProfileBackup(backup);assert.equal(inspectProfessionalProfileBackupEnvelope(v2).containerVersion,2);assert.equal(parseProfessionalProfileBackup(v2).schemaVersion,2);
// Server protected export/import: wrong password never mutates fresh profile.
const sourceStore=createMemoryPrivateBetaProfessionalIdentityStore();await sourceStore.save({record});let server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:sourceStore,contextIdFactory:()=> 'pd088b-source'});await new Promise(r=>server.listen(0,'127.0.0.1',r));let base=`http://127.0.0.1:${server.address().port}`;let form=new URLSearchParams({protected:'true',password,confirmPassword:password}),r=await fetch(base+'/private-beta/profile-backup/export',{method:'POST',headers:{cookie:'imago_beta_repeat_context=pd088b-source','content-type':'application/x-www-form-urlencoded'},body:form.toString()});assert.equal(r.status,200);assert.equal(r.headers.get('x-imago-backup-encrypted'),'true');const exported=Buffer.from(await r.arrayBuffer());await new Promise(r=>server.close(r));
const freshStore=createMemoryPrivateBetaProfessionalIdentityStore();server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:freshStore,contextIdFactory:()=> 'pd088b-fresh'});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;const cookie='imago_beta_repeat_context=pd088b-fresh',b64=s=>Buffer.from(s,'utf8').toString('base64');r=await fetch(base+'/private-beta/profile-backup/preview',{method:'POST',headers:{cookie,'content-type':'application/vnd.imago.profile-backup'},body:exported});assert.equal(r.status,428);assert.equal((await r.json()).error,'PROFILE_BACKUP_PASSWORD_REQUIRED');r=await fetch(base+'/private-beta/profile-backup/restore',{method:'POST',headers:{cookie,'content-type':'application/vnd.imago.profile-backup','x-imago-backup-password-b64':b64('password sbagliata')},body:exported});assert.equal(r.status,422);assert.equal(await freshStore.load({personRef:destination}),null);r=await fetch(base+'/private-beta/profile-backup/preview',{method:'POST',headers:{cookie,'content-type':'application/vnd.imago.profile-backup','x-imago-backup-password-b64':b64(password)},body:exported});assert.equal(r.status,200);const preview=await r.json();assert.equal(preview.encrypted,true);assert.equal(preview.containerVersion,3);r=await fetch(base+'/private-beta/profile-backup/restore',{method:'POST',headers:{cookie,'content-type':'application/vnd.imago.profile-backup','x-imago-backup-password-b64':b64(password)},body:exported});assert.equal(r.status,200);assert.equal((await freshStore.load({personRef:destination})).sourceAssets.length,2);await new Promise(r=>server.close(r));
const htmlIt=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'backup'},identityAvailable:true,identitySummary:{professionalSources:sources,knowledgeCount:1}}),htmlEn=renderPrivateBetaUiJourneyHtml({locale:'en',result:{phase:'backup'},identityAvailable:true,identitySummary:{professionalSources:sources,knowledgeCount:1}});assert.match(htmlIt,/Proteggi con password/);assert.match(htmlIt,/non salva questa password/i);assert.match(htmlEn,/Protect with password/);assert.doesNotMatch(htmlIt,/AES-256-GCM|scrypt/);
console.log(`PD-088B Portable Backup Security Envelope: PASS (export ${exportMs.toFixed(1)} ms, decrypt ${importMs.toFixed(1)} ms, ${protectedBytes.length} bytes)`);
