import assert from 'node:assert/strict';
import {buildGroundedApplicationPackage,buildOpportunityUnderstanding,buildProtectedApplicationArtifacts} from '../src/app/opportunityApplication/groundedApplicationPackage.js';
import {establishApplicationMaterialPresentationLanguage} from '../src/app/opportunityApplication/presentationLanguageBasis.js';
import {loadPrivateBetaUiMessages} from '../src/i18n/loadPrivateBetaUiMessages.js';
const valid=async({input})=>({materialRef:input.materialRef,verdict:'VALID',violations:[]});
function identity(role,description,id='cv1'){return {revision:1,professionalSources:[{id,sourceRole:'current_cv',content:`${role}. Legacy.`}],representationSnapshots:[{representation:{type:'target_independent_professional_representation',roleHistory:[{sourceId:id,role,status:'current'}],episodeMeanings:[{episodeMeaningId:`e-${id}`,sourceId:id,description,participation:'participated',activity:'bounded activity',object:'work',professionalContext:'professional',limitations:['participation_not_ownership_or_management'],support:[{evidenceRef:`ev-${id}`}]}],professionalMeaning:{knowledgeContribution:[]}}}]};}
function setup(role,description){const professionalIdentity=identity(role,description),u=buildOpportunityUnderstanding({opportunityText:'Role requirement.',opportunityLabel:'Role'}),pkg=buildGroundedApplicationPackage({professionalIdentity,opportunityUnderstanding:u,documentData:{displayName:'Candidate'}});return {professionalIdentity,u,pkg};}
const translations=(lang)=>async({input})=>({materialRef:input.materialRef,transformedText:lang==='it'?(input.materialKind==='professional_role'?'Tecnico Qualità':'Supervisione di impianti industriali.'):(input.materialKind==='professional_role'?'Quality Technician':'Industrial plant supervision.')});
async function render(pkg,u,lang,runner=translations(lang),validator=valid){let calls=0;const arts=await buildProtectedApplicationArtifacts({applicationPackage:pkg,opportunityUnderstanding:u,documentLanguage:lang,messages:loadPrivateBetaUiMessages(lang),maxAttempts:1,transformRunner:async x=>{calls++;return runner(x)},validationRunner:validator});return {arts,calls};}
// Real Private Beta-equivalent missing artifactLanguage: UNKNOWN English -> IT must materialize.
{const {u,pkg}=setup('Quality Technician','Supervised industrial plant operations.');assert(pkg.candidateApplicationMaterials.filter(x=>x.languageTransformationEligibility==='eligible').every(x=>x.presentationLanguageBasis.state==='unknown'));const {arts,calls}=await render(pkg,u,'it');assert(calls>=2);assert(arts.targetedCv.content.includes('Tecnico Qualità'));assert(!arts.targetedCv.content.includes('Quality Technician'));}
// UNKNOWN Italian -> EN and same-looking UNKNOWN -> IT/EN both require VALID.
{const {u,pkg}=setup('Tecnico Qualità','Supervisione impianti industriali.');assert((await render(pkg,u,'en')).calls>=2);assert((await render(pkg,u,'it')).calls>=2);}
{const {u,pkg}=setup('Quality Technician','Industrial plant supervision.');assert((await render(pkg,u,'en')).calls>=2);}
// Established direct same-language fast paths; cross-language still materializes.
for(const [basis,requested,expectCalls] of [['it','it',0],['en','en',0],['it','en',2],['en','it',2]]){const {u,pkg}=setup(basis==='it'?'Tecnico Qualità':'Quality Technician',basis==='it'?'Supervisione impianti industriali.':'Industrial plant supervision.');const mats=pkg.candidateApplicationMaterials.map(m=>m.languageTransformationEligibility==='eligible'?establishApplicationMaterialPresentationLanguage(m,{language:basis,authority:'test_explicit_application_realization'}):m);const p=Object.freeze({...pkg,candidateApplicationMaterials:Object.freeze(mats)});const {calls}=await render(p,u,requested);expectCalls===0?assert.equal(calls,0):assert(calls>=expectCalls);}
// Partial validation fails closed; no source fallback.
{const {u,pkg}=setup('Quality Technician','Supervised industrial plant operations.');let n=0;await assert.rejects(()=>render(pkg,u,'it',translations('it'),async({input})=>({materialRef:input.materialRef,verdict:++n===1?'VALID':'REJECTED',violations:n===1?[]:['reject']})),/CQ05_LANGUAGE_MATERIALIZATION_REJECTED/);}
// Duplicate visible text: one established direct, the other UNKNOWN must still invoke transformation by identity.
{const {u,pkg}=setup('Same Text','Same Text');const eligible=pkg.candidateApplicationMaterials.filter(x=>x.languageTransformationEligibility==='eligible');assert(eligible.length>=2);const first=eligible[0].id;const mats=pkg.candidateApplicationMaterials.map(m=>m.id===first?establishApplicationMaterialPresentationLanguage(m,{language:'en',authority:'test_explicit_application_realization'}):m);const p=Object.freeze({...pkg,candidateApplicationMaterials:Object.freeze(mats)});let calls=[];await buildProtectedApplicationArtifacts({applicationPackage:p,opportunityUnderstanding:u,documentLanguage:'en',messages:loadPrivateBetaUiMessages('en'),maxAttempts:1,transformRunner:async({input})=>{calls.push(input.materialRef);return {materialRef:input.materialRef,transformedText:'Same Text'}},validationRunner:valid});assert(!calls.includes(first));assert(calls.some(x=>x!==first));}
// UI/JD/requested language never mutate UNKNOWN basis; PI immutable; derived VALID basis is exposed on materialization.
{const {professionalIdentity,u,pkg}=setup('Quality Technician','Supervised industrial plant operations.');const before=JSON.stringify(professionalIdentity);const {arts}=await render(pkg,u,'it');assert.equal(JSON.stringify(professionalIdentity),before);assert(arts.languageMaterializations.filter(x=>x.status==='VALID').every(x=>x.presentationLanguageBasis?.state==='established'&&x.presentationLanguageBasis.language==='it'));assert.deepEqual(arts.cvContentModel.languages,[]);}
// Non-manufacturing fixture.
{const {u,pkg}=setup('Biomedical Systems Specialist','Diagnostic instrumentation verification.');const {arts}=await render(pkg,u,'it');assert(arts.targetedCv.content.includes('Supervisione di impianti industriali.')||arts.targetedCv.content.includes('Tecnico Qualità'));}
console.log('CQ-05I-R2 resumed language-basis integration tests passed.');
