const assert=require("assert");
const {buildMeasurementDimensionMapping,validateMeasurementDimensionMapping}=require("../src/core/dimension");
const at="2026-07-23T10:00:00.000Z";
const input={id:" mapping_1 ",measurementId:" measurement_1 ",targets:[{dimensionId:" ownership ",contributionType:"supporting",extensions:{note:true}},{dimensionId:"decision_clarity",contributionType:"contradicting",weight:0.5,confidenceFactor:0.8}],metadata:{createdAt:at,updatedAt:at},extensions:{mode:"test"}};
const snapshot=JSON.parse(JSON.stringify(input));
const a=buildMeasurementDimensionMapping(input,{now:at});
const b=buildMeasurementDimensionMapping(input,{now:at});
assert.deepStrictEqual(input,snapshot);
assert.deepStrictEqual(a,b);
assert.strictEqual(a.id,"mapping_1");
assert.strictEqual(a.targets[0].dimensionId,"ownership");
assert.strictEqual(a.targets[0].weight,1);
assert.strictEqual(a.targets[0].confidenceFactor,1);
assert.notStrictEqual(a.targets,input.targets);
assert.notStrictEqual(a.targets[0].extensions,input.targets[0].extensions);
assert.strictEqual(validateMeasurementDimensionMapping(a).valid,true);
const minimal=buildMeasurementDimensionMapping({id:"minimal",measurementId:"m",targets:[{dimensionId:"leadership",contributionType:"supporting"}]},{now:at});
assert.strictEqual(validateMeasurementDimensionMapping(minimal).valid,true);
console.log("test_build_measurement_dimension_mapping PASS");
