import assert from 'node:assert/strict';
import { buildProfessionalRepresentationSynthesisInput,buildDeterministicProfessionalRepresentation,reconcileProfessionalRepresentationRealization } from '../src/app/buildProfessionalRepresentationSynthesis.js';
import { runProfessionalRepresentationSynthesis } from '../src/app/runProfessionalRepresentationSynthesis.js';
import { renderPrivateBetaUiJourneyHtml } from '../src/app/renderPrivateBetaUiJourneyHtml.js';
const rawOnly='KPI segreto ZX-417, monitorato per 11 settimane con una metodologia non canonica.';
const da={semanticType:'decision_accountability',sourceRef:'runtimeKnowledgeResults[0]',evidenceIds:['e-da'],decisionAuthority:'shared',consequenceScope:'team',accountabilityEvidence:null,responsibilityContinuity:{state:'unknown'},context:{decision:'trade-off continuità produttiva / intervento completo',responsibility:'decisione operativa nel proprio perimetro con authority condivisa',consequence:'continuità produttiva'},limitations:['No sole authority.']};
const qo={semanticType:'quantified_outcome',sourceRef:'runtimeKnowledgeResults[1]',evidenceIds:['e-qo'],measurableOutcome:rawOnly,quantitativeValue:{value:20,unit:'percent',approximate:true,direction:'increase'},contributionRelationship:'contributed',causalityBoundary:'contribution_only',context:{event:'miglioramento del processo produttivo'},limitations:['Sole causality not established.']};
const input=buildProfessionalRepresentationSynthesisInput({authorizedSemanticMaterial:[da,qo],locale:'it'});
assert.equal(input.semanticUnits.length,2);
const dau=input.semanticUnits.find(x=>x.semanticType==='decision_accountability');
assert.equal(dau.facts.accountabilityEvidence,null);assert.deepEqual(dau.facts.responsibilityContinuity,{state:'unknown'});
const rep=buildDeterministicProfessionalRepresentation({synthesisInput:input,locale:'it'});
assert.equal(rep.claims.length,2);assert.deepEqual(rep.claims.map(x=>x.semanticType),['decision_accountability','quantified_outcome']);
const dac=rep.claims[0],qoc=rep.claims[1];
assert.match(dac.professionalClaim,/condivisa/i);assert.match(dac.professionalClaim,/team/i);assert.match(dac.explanation,/trade-off continuità produttiva/i);assert.match(dac.explanation,/authority condivisa/i);
assert.equal(dac.supportingSemanticFacts[0].accountabilityEvidence,null);assert.equal(dac.supportingSemanticFacts[0].responsibilityContinuity.state,'unknown');
assert.doesNotMatch(JSON.stringify(dac),/weak|debole|short duration|breve durata|low confidence/i);
assert.match(qoc.professionalClaim,/circa 20%/i);assert.equal(qoc.supportingSemanticFacts[0].contributionRelationship,'contributed');assert.equal(qoc.supportingSemanticFacts[0].causalityBoundary,'contribution_only');assert.doesNotMatch(qoc.explanation,/miglioramento del processo produttivo/i);assert.match(qoc.limitations.join(' '),/causalità esclusiva/i);
assert.doesNotMatch(JSON.stringify(rep),/ZX-417|11 settimane|metodologia non canonica/i);
assert.equal(dac.semanticSupportRefs[0],'runtimeKnowledgeResults[0]');assert.equal(qoc.semanticSupportRefs[0],'runtimeKnowledgeResults[1]');
const malicious={claims:[{id:dac.id,professionalClaim:'È un leader pronto per Operations Manager con piena ownership.',explanation:'Leadership strategica.'},{id:qoc.id,professionalClaim:'Ha ottenuto il 99% con causalità esclusiva.',explanation:'Risultato certo.'}]};
assert.equal(reconcileProfessionalRepresentationRealization({synthesisInput:input,deterministicRepresentation:rep,realization:malicious}),null);
const omitted={claims:[{id:dac.id,professionalClaim:dac.professionalClaim,explanation:dac.explanation}]};assert.equal(reconcileProfessionalRepresentationRealization({synthesisInput:input,deterministicRepresentation:rep,realization:omitted}),null);
const safe={claims:rep.claims.map(c=>({id:c.id,professionalClaim:c.professionalClaim,explanation:c.explanation}))};const reconciled=reconcileProfessionalRepresentationRealization({synthesisInput:input,deterministicRepresentation:rep,realization:safe});assert.equal(reconciled.claims.length,2);assert.deepEqual(reconciled.claims[0].supportingSemanticFacts,dac.supportingSemanticFacts);assert.deepEqual(reconciled.claims[1].limitations,qoc.limitations);
const fallback=await runProfessionalRepresentationSynthesis({authorizedSemanticMaterial:[da,qo],locale:'it',useModel:true,narrativeRealizer:async()=>{throw new Error('provider down')}});assert.equal(fallback.representation.claims.length,2);assert.equal(fallback.representation.realization.mode,'deterministic_fallback');
const html=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'feedback',sessionRef:'rr01',report:{available:true,professionalRepresentation:rep}}});assert.match(html,/trade-off continuità produttiva/i);assert.match(html,/circa 20%/i);assert.doesNotMatch(html,/ZX-417|11 settimane/i);
console.log('FHT-RR01 professional representation semantic richness preservation: PASS');
