import assert from 'node:assert/strict';
import {createPrivateBetaUiServer} from '../src/app/privateBetaUiServer.js';
import {evaluateCareerDirections} from '../src/app/careerDirection/evaluateCareerDirections.js';
import {startDirectionPeopleResponsibilityProductionAcquisition} from '../src/app/careerDirection/directionKnowledgeAcquisition.js';
import {runGroqContinuingPeopleResponsibilitySemanticExecutor} from '../src/infrastructure/groq/runGroqContinuingPeopleResponsibilitySemanticExecutor.js';

const now='2026-09-28T16:45:00.000Z',personRef={type:'person',id:'pd073tc'};
const rep={professionalMeaning:{supportedPatterns:[{kind:'documented_cross_functional_coordination_recurrence'}],professionalSynthesis:{hasDocumentedRoleContinuity:true,currentRole:'Production Supervisor',previousRoles:[],domains:['production']},knowledgeContribution:[]}};
const evaluation=evaluateCareerDirections({professionalRepresentation:rep,professionalRepresentationRef:'professionalRepresentation:pd073tc',now});
const ops=evaluation.hypotheses.find(x=>x.metadata.roleFamilyRef==='operations_management');
async function baseState(){const acquisition=await startDirectionPeopleResponsibilityProductionAcquisition({careerDirectionEvaluation:evaluation,selectedDirectionRef:ops.id,userAction:'deepen_career_direction',professionalIdentity:{professionalSources:[],reusableKnowledgeResults:[]},subjectRef:personRef,professionalRepresentationRef:'professionalRepresentation:pd073tc',now});return {type:'direction_explore_state',personRef,careerDirectionEvaluation:evaluation,directionAcquisition:acquisition,reusableProfessionalIdentity:{personRef,professionalSources:[],reusableKnowledgeResults:[]}};}
async function run({enabled=true,executor,sessionRef}){const sessionStore=new Map([[sessionRef,await baseState()]]),logs=[];const prior=console.error;console.error=(...a)=>logs.push(a.join(' '));const server=createPrivateBetaUiServer({operatorDiagnosticsEnabled:enabled,sessionStore,locale:'it',journeyOptions:{directionPeopleResponsibilitySemanticExecutor:executor}});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const port=server.address().port,answer='CANDIDATE PRIVATE ANSWER';const response=await fetch(`http://127.0.0.1:${port}/private-beta/direction/answer`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({sessionRef,answer})});const html=await response.text();const trace=await fetch(`http://127.0.0.1:${port}/private-beta/operator/semantic-trace?sessionRef=${sessionRef}`);return{answer,html,logs,status:trace.status,payload:trace.status===200?await trace.json():null};}finally{console.error=prior;await new Promise(r=>server.close(r));}}

const rawCandidate={interpretationStatus:'SUPPORTED',responsibilityPresence:'supported',continuity:'continuing',responsibilityMode:'formal_line_management_NOT_AUTHORIZED',responsibilityKinds:['work_assignment_or_priority_setting'],peopleScope:{kind:'exact',value:'5',min:null,max:null},professionalContext:{description:'PRIVATE WORKSHOP CONTEXT',current:true},eventTime:{description:'PRIVATE TIME'},support:{presence:'PRIVATE SUPPORT',continuity:'PRIVATE SUPPORT',mode:'PRIVATE SUPPORT',peopleScope:'PRIVATE SUPPORT',professionalContext:'PRIVATE SUPPORT',responsibilityKinds:['PRIVATE SUPPORT']},limitations:['PRIVATE LIMITATION']};
const executorResult=await runGroqContinuingPeopleResponsibilitySemanticExecutor({evidence:{content:{answerText:'PRIVATE EVIDENCE TEXT'}},completionRunner:async()=>({content:JSON.stringify(rawCandidate),model:'openai/gpt-oss-120b',outputMode:'json_schema',attemptsUsed:1,execution:{elapsedMs:321,httpAttemptsUsed:1}})});
assert.equal(executorResult.supported,false);assert.equal(executorResult.diagnostic.category,'candidate_rejected');assert(executorResult.diagnostic.validationErrors.some(x=>x.includes('bounded responsibility semantics')));assert.equal(executorResult.diagnostic.candidateShape.peopleScopeValueType,'string');assert.equal(executorResult.diagnostic.candidateShape.responsibilityMode,'formal_line_management_NOT_AUTHORIZED');assert.equal(executorResult.diagnostic.providerDiagnostic.model,'openai/gpt-oss-120b');assert.equal(executorResult.diagnostic.providerDiagnostic.outputMode,'json_schema');assert.equal(executorResult.diagnostic.providerDiagnostic.structuredOutput,true);assert.equal(executorResult.diagnostic.providerDiagnostic.elapsedMs,321);
let serialized=JSON.stringify(executorResult.diagnostic.candidateShape);for(const secret of ['PRIVATE WORKSHOP CONTEXT','PRIVATE TIME','PRIVATE SUPPORT','PRIVATE LIMITATION','PRIVATE EVIDENCE TEXT'])assert(!serialized.includes(secret));

let result=await run({sessionRef:'pd073tc-candidate',executor:async()=>executorResult});assert.equal(result.status,200);let d=result.payload.semanticExecutionTraces.find(x=>x.boundary==='career_direction_people_responsibility_acquisition');assert(d);assert.equal(d.stage,'semantic_candidate');assert.equal(d.providerCategory,'candidate_rejected');assert(d.validationErrors.some(x=>x.includes('bounded responsibility semantics')));assert.equal(d.candidateShape.peopleScopeValueType,'string');assert.equal(d.model,'openai/gpt-oss-120b');assert.equal(d.outputMode,'json_schema');assert.equal(d.structuredOutput,true);assert.equal(d.elapsedMs,321);assert.equal(d.httpAttemptsUsed,1);assert(result.logs.some(x=>x.startsWith('[IMAGO operator career direction acquisition diagnostic]')));
serialized=JSON.stringify({d,logs:result.logs});for(const secret of [result.answer,'PRIVATE WORKSHOP CONTEXT','PRIVATE TIME','PRIVATE SUPPORT','PRIVATE LIMITATION','PRIVATE EVIDENCE TEXT'])assert(!serialized.includes(secret));

const transport=Object.assign(new Error('provider'),{providerDiagnostic:{failureKind:'timeout',model:'openai/gpt-oss-120b',outputMode:'json_schema',structuredOutput:true,elapsedMs:999,httpAttemptsUsed:2}});result=await run({sessionRef:'pd073tc-transport',executor:async()=>{throw transport;}});d=result.payload.semanticExecutionTraces.find(x=>x.boundary==='career_direction_people_responsibility_acquisition');assert.equal(d.stage,'provider_execution');assert.equal(d.providerFailureKind,'timeout');assert.deepEqual(d.validationErrors,[]);assert.equal(d.candidateShape,null);

const structured=Object.assign(new Error('schema'),{providerDiagnostic:{failureKind:'structured_output_rejected',model:'openai/gpt-oss-120b',outputMode:'json_schema',structuredOutput:true},initialStructuredOutputRecovery:{attempted:true,succeeded:false,mode:'json_object',initialFailureDiagnostic:{failureKind:'structured_output_rejected'}}});result=await run({sessionRef:'pd073tc-structured',executor:async()=>{throw structured;}});d=result.payload.semanticExecutionTraces.find(x=>x.boundary==='career_direction_people_responsibility_acquisition');assert.equal(d.providerFailureKind,'structured_output_rejected');assert.equal(d.pd073Recovery.attempted,true);assert.equal(d.pd073Recovery.mode,'json_object');

result=await run({enabled:false,sessionRef:'pd073tc-disabled',executor:async()=>executorResult});assert.equal(result.status,404);assert.equal(result.logs.length,0);assert(result.html.includes('Non sono riuscito a interpretare la risposta per un problema tecnico.'));
console.log('PD-073 third corrective CPR candidate rejection diagnostic completion tests passed.');
