import assert from 'assert';
import {readFile} from 'fs/promises';
import {performance} from 'perf_hooks';
import {prepareStagedPrivateBetaJourney,continueStagedPrivateBetaJourney,answerStagedPrivateBetaJourney} from '../src/app/privateBetaJourneyIntegration.js';
import {renderPrivateBetaUiJourneyHtml} from '../src/app/renderPrivateBetaUiJourneyHtml.js';
import {runFullParserPipeline} from '../src/parser/runFullParserPipeline.js';
const load=async n=>JSON.parse(await readFile(new URL(`../fixtures/${n}`,import.meta.url),'utf8'));
const baseCandidate=await load('expected_candidate_profile_01.json'),role=await load('expected_role_profile_01.json'),fit=await load('expected_job_fit_analysis_01.json');
function candidate(summary){const x=structuredClone(baseCandidate);const p=x.candidateProfile||x;p.summary=summary;return x;}
const adapter=async({task,user})=>{if(task==='candidateProfile'){if(user.includes('Germany'))return JSON.stringify(candidate('Industrialization Engineer; launch of a production line in Germany.'));if(user.includes('Project Atlas'))return JSON.stringify(candidate('Project Atlas supplier ramp-up with supply chain, quality and production.'));return JSON.stringify(candidate('Production Supervisor with operational coordination and production performance responsibilities.'));}if(task==='roleProfile')return JSON.stringify(role);if(task==='jobFitAnalysis')return JSON.stringify(fit);return '{}';};
const input={identityAction:'create',workingMode:'independent',consentDecision:'accept',targetRole:'Operations Manager',jdText:'Operations Manager role',cvText:'Marco Bianchi. Production Supervisor. 12 years industrial experience. Operational coordination, production performance, maintenance, quality, supply chain and engineering.',previousCvText:'Previous role Industrialization Engineer. Launch of a new production line in Germany; installation, start-up and process stabilization.',professionalDeclaration:'Project Atlas: supplier ramp-up, production continuity problems, competing priorities with supply chain, quality and production.',userNotes:'Growing cross-functional operational responsibility.',uiLocale:'it'};
const prep=await prepareStagedPrivateBetaJourney({uiInput:input,modelAdapter:adapter,now:()=> '2026-09-08T12:00:00.000Z'});assert(prep.state);const html=renderPrivateBetaUiJourneyHtml({locale:'it',result:prep.publicResult});for(const expected of ['Production Supervisor','Industrialization Engineer','Germany','Project Atlas'])assert(html.includes(expected),`missing visible source-grounded fact: ${expected}`);assert.equal(prep.state.session.runtimeKnowledgeResults.length,0,'source information must not become canonical Knowledge');assert(html.includes('Informazioni professionali riconosciute nelle fonti'));
// Incomplete understanding has a bounded enrich/regenerate path.
assert(html.includes('/private-beta/understanding/enrich'));
// Adaptive framing no longer falsely claims interruption.
const packs=JSON.parse(await readFile(new URL('../config/followup_packs.it.json',import.meta.url),'utf8'));assert(!packs.packs.decision_tradeoff_probe.followups[0].startsWith('Ti fermo'));
// Second corrective: provider calls are deliberately serialized because real-provider failure followed the wide parallel wave.
const delay=ms=>new Promise(r=>setTimeout(r,ms));let calls=[],active=0,maxActive=0;const timed=async({task})=>{calls.push(task);active++;maxActive=Math.max(maxActive,active);await delay(20);active--;if(task==='candidateProfile')return JSON.stringify(candidate('timed'));if(task==='roleProfile')return JSON.stringify(role);if(task==='jobFitAnalysis')return JSON.stringify(fit);};const t0=performance.now();await runFullParserPipeline({cvText:'current',jdText:'target',professionalSources:[{id:'a',content:'a',sourceRole:'current_cv'},{id:'b',content:'b',sourceRole:'previous_cv'},{id:'c',content:'c',sourceRole:'professional_declaration'}],modelAdapter:timed});const elapsed=performance.now()-t0;assert.equal(calls.length,6);assert.equal(maxActive,1,'parser provider calls must be serialized in the safe provider path');assert(elapsed>=100,`serialized parser path unexpectedly concurrent: ${elapsed}`);console.log(`EAR second corrective scheduling: 6 provider calls, max concurrency ${maxActive}, ${elapsed.toFixed(0)}ms controlled wall clock.`);
console.log('EAR corrective acceptance/value projection PASS');
