import assert from 'node:assert/strict';
import {createPrivateBetaUiServer} from '../src/app/privateBetaUiServer.js';
import {createMemoryPrivateBetaProfessionalIdentityStore,privateBetaPersonRefFromContext} from '../src/app/privateBetaProfessionalIdentityContinuity.js';
import {evaluateCareerDirections} from '../src/app/careerDirection/evaluateCareerDirections.js';
import {startDirectionPeopleResponsibilityProductionAcquisition,answerDirectionPeopleResponsibilityProductionAcquisition,projectCurrentCareerDirectionState} from '../src/app/careerDirection/directionKnowledgeAcquisition.js';
import {prepareStagedPrivateBetaJourney} from '../src/app/privateBetaStagedInterviewJourney.js';

const contextId='pd074tc-initial-route',personRef=privateBetaPersonRefFromContext(contextId),at='2026-09-29T12:00:00.000Z';
const representation={type:'target_independent_professional_representation',version:'1.2',persistent:false,target:null,professionalMeaning:{supportedPatterns:[{kind:'documented_cross_functional_coordination_recurrence',sourceRefs:['atlas','maintenance'],episodeRefs:['atlas-episode','maintenance-episode'],episodeBasis:'distinct_source_grounded_experiences',supportCount:2,traitInference:false}],professionalSynthesis:{currentRole:'Production Supervisor',previousRoles:['Industrialization Engineer'],domains:['manufacturing'],hasDocumentedRoleContinuity:true,supportedPatternKinds:['documented_cross_functional_coordination_recurrence']},knowledgeContribution:[{semanticType:'decision_accountability',primaryProfessionalMeaning:{kind:'bounded_decision_accountability'}},{semanticType:'quantified_outcome',primaryProfessionalMeaning:{kind:'bounded_measurable_outcome_contribution'}}],insufficientObservability:[]},roleHistory:[{role:'Industrialization Engineer'},{role:'Production Supervisor'}],supportingExperiences:[],assets:[],limitations:[],provenance:{sourceIds:['current_cv'],knowledgeRefs:[]}};
const snapshotId='representationSnapshot:pd074tc';
const evaluation=evaluateCareerDirections({professionalRepresentation:representation,professionalRepresentationRef:snapshotId,now:at});
const ops=evaluation.hypotheses.find(x=>x.metadata.roleFamilyRef==='operations_management');
const baseIdentity={version:'1.0',type:'private_beta_professional_identity_continuity',professionalIdentityRef:`professionalIdentity:${personRef.id}`,personRef,owner:'person',authorizedMaterials:{cvText:'Production Supervisor',userNotes:''},professionalSources:[{id:'current_cv',type:'text',sourceRole:'current_cv',content:'Production Supervisor',provenance:{origin:'current_cv',providedBy:'user',collectedAt:at}}],reusableKnowledgeResults:[],knowledgeRefs:[],revision:5,createdAt:at,updatedAt:at,lastEnrichedBySessionRef:'pd074tc',representationSnapshots:[{version:'1.0',type:'professional_representation_snapshot',snapshotId,personRef,professionalIdentityRef:`professionalIdentity:${personRef.id}`,purpose:'professional_representation_understand',context:'target_independent',materializedAt:at,relevantStateFingerprint:'pd074tc',sourceStateFingerprint:'s',knowledgeStateFingerprint:'k',authorizationStateFingerprint:'a',recipe:{id:'target_independent_professional_representation',version:'1.8'},changeCause:'initial_materialization',representation,provenance:representation.provenance,limitations:[]}],currentRepresentationSnapshotRefs:{professional_representation_understand:snapshotId}};
const started=await startDirectionPeopleResponsibilityProductionAcquisition({careerDirectionEvaluation:evaluation,selectedDirectionRef:ops.id,userAction:'deepen_career_direction',professionalIdentity:baseIdentity,subjectRef:personRef,professionalRepresentationRef:snapshotId,now:at});
const candidate={interpretationStatus:'SUPPORTED',responsibilityPresence:'supported',continuity:'continuing',responsibilityMode:'informal_operational',responsibilityKinds:['work_assignment_or_priority_setting'],peopleScope:{kind:'category',value:'circa 5 persone',min:null,max:null},professionalContext:{description:'officina',current:true},eventTime:{description:null},support:{presence:'Ho gestito',continuity:'continuativamente',mode:'assegnando le attività',peopleScope:'circa 5 persone',professionalContext:'officina',responsibilityKinds:['assegnando le attività']},limitations:['formal reporting authority not established']};
const done=await answerDirectionPeopleResponsibilityProductionAcquisition({state:started,answer:'Ho gestito continuativamente circa 5 persone di officina, assegnando le attività e definendo le priorità di lavoro.',careerDirectionEvaluation:evaluation,subjectRef:personRef,now:at,semanticExecutor:async()=>({supported:true,candidate,provider:{model:'test'}})});
assert.equal(done.status,'resolved');
const persisted=JSON.parse(JSON.stringify({...baseIdentity,reusableKnowledgeResults:[{...done.knowledgeResult,semanticType:'continuing_people_responsibility',semanticPolicyRef:done.ka.design.semanticPolicyRef,knowledgeRef:`knowledgeSnapshot:${done.knowledgeResult.knowledgeSnapshot.id}`}]}));

// Cross-path agreement: initial prepare must use the same current projection helper as later outcomes.
const prepared=await prepareStagedPrivateBetaJourney({uiInput:{identityAction:'recover',workingMode:'independent',consentDecision:'accept',productPurpose:'professional_direction_explore',cvText:'',userNotes:'',jdText:'',targetRole:''},reusableProfessionalIdentity:persisted,knowledgeSubjectRef:personRef,now:()=>at,modelAdapter:async()=>{throw new Error('provider must not run')}});
const initialRes=prepared.publicResult.preInterview.directionResolutions;
assert.equal(initialRes.length,2);assert(initialRes.every(x=>x.resolutionState==='resolved_by_current_authorised_state'));
const later=projectCurrentCareerDirectionState({careerDirectionEvaluation:prepared.state.careerDirectionEvaluation,professionalIdentity:persisted,subjectRef:personRef,now:at});
assert.deepEqual(initialRes,later.directionResolutions);

// Actual restarted HTTP initial route: no transient acquisition/resolution state survives.
const store=createMemoryPrivateBetaProfessionalIdentityStore();await store.save({record:persisted});
const server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:store,contextIdFactory:()=>contextId,journeyOptions:{modelAdapter:async()=>{throw new Error('provider must not run')}}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${server.address().port}`;const body=new URLSearchParams({identityAction:'recover',workingMode:'independent',productPurpose:'professional_direction_explore',consentDecision:'accept',targetRole:'',cvText:'',previousCvText:'',professionalDeclaration:'',userNotes:'',jdText:'',uiLocale:'it',sessionLocale:'it'});
const res=await fetch(base+'/private-beta/journey',{method:'POST',headers:{cookie:`imago_beta_repeat_context=${contextId}`,'content-type':'application/x-www-form-urlencoded'},body});const html=await res.text();assert.equal(res.status,200,html);
const peopleQuestion='Hai già avuto responsabilità continuativa sulle persone, oltre al coordinamento operativo?';assert.equal(html.includes(peopleQuestion),false);assert.equal((html.match(/1 aspetto resta da chiarire\./g)||[]).length,2);assert.match(html,/risorse o budget su un perimetro operativo più ampio/i);assert.match(html,/pianificazione e programmazione della produzione/i);assert.equal((html.match(/Approfondisci questo aspetto/g)||[]).length,2); // PD-086 makes these two bounded clarifications actionable.
await new Promise(r=>server.close(r));
console.log('PD-074 Third Corrective initial Career Direction current-resolution projection tests passed.');
