import assert from 'node:assert/strict';
import {buildOpportunityUnderstanding,buildGroundedApplicationPackage,buildApplicationArtifacts} from '../src/app/opportunityApplication/groundedApplicationPackage.js';
import {buildOpportunityRequirementSupportContributorInventory,validateOpportunityRequirementSupportProposal,buildOpportunityRequirementSupportProjection} from '../src/app/opportunityApplication/requirementSupportAuthority.js';
const d=(id,source,agency)=>({status:'accepted',descriptorId:id,descriptorRole:'activity',materialRef:source,sourceId:source,claimShape:{agencyLevel:agency}});
const rel={status:'accepted',relationshipId:'rel:coord',descriptorRefs:['d1','d2'],materialRefs:['cv:1','cv:2'],sourceRefs:['cv:1','cv:2'],relationshipWording:'Coordinamento tra funzioni in due iniziative industriali.',claimShape:{personPropertyAssertion:'none'}};
const relWeak={...rel,relationshipId:'rel:weak',descriptorRefs:['dw'],materialRefs:['cv:3'],sourceRefs:['cv:3']};
const ho={status:'accepted',structureId:'ho:coord',contributorRefs:['rel:coord'],professionalBasisRefs:['episode:1','episode:2'],materialRefs:['cv:1','cv:2'],sourceRefs:['cv:1','cv:2'],structureWording:'Ricorrenza documentata di coordinamento cross-funzionale.',inheritedSemanticProtection:['pd070_representation_only','no_semantic_strengthening']};
const rep={type:'target_independent_professional_representation',roleHistory:[{sourceId:'cv:1',role:'Industrialization Engineer',status:'previous'}],episodeMeanings:[{episodeMeaningId:'episode:1',sourceId:'cv:1',description:'Ha coordinato attività tra produzione e qualità.',participation:'coordinated',support:[{evidenceRef:'ev:1'}],limitations:[]},{episodeMeaningId:'episode:2',sourceId:'cv:2',description:'Ha coordinato attività tra engineering e operations.',participation:'coordinated',support:[{evidenceRef:'ev:2'}],limitations:[]}],professionalMeaning:{groundedDescriptiveDescriptors:[d('d1','cv:1','coordinated'),d('d2','cv:2','coordinated'),d('dw','cv:3','contributed')],groundedDescriptiveRelationships:[rel,relWeak],higherOrderDescriptiveProfessionalStructures:[ho],supportedPatterns:[{kind:'cross_functional_coordination',episodeRefs:['episode:1','episode:2'],sourceRefs:['cv:1','cv:2']}],knowledgeContribution:[{sourceRef:'knowledge:q1',professionalMeaning:'Riduzione documentata dei tempi di avviamento.',authorisedSemanticPayload:{measurableOutcome:'lead time reduction',quantitativeValue:{value:18,unit:'percent'},contributionRelationship:'contributed',causalityBoundary:'contribution_only',sourceRef:'cv:1',evidenceIds:['ev:q1']},limitations:['contribution_only']}]}};
const identity={revision:8,professionalSources:[{id:'cv:1',sourceRole:'previous_cv',role:'Industrialization Engineer',content:'Industrialization Engineer. Coordinated launch activities across quality and production.'},{id:'cv:2',sourceRole:'professional_declaration',content:'Worked across engineering and operations.'},{id:'cv:3',sourceRole:'professional_declaration',content:'Managed stakeholder coordination budget planning.'}],representationSnapshots:[{representation:rep}]};
const jd=`Industrialization Project Engineer\nResponsibilities\nOrchestrate alignment across manufacturing, quality and engineering workstreams.\nRequirements\nDeliver measurable industrialization improvements.\nOwn resource budget allocation.\nPreferred\nProduction scheduling experience preferred.`;
const u=buildOpportunityUnderstanding({opportunityText:jd,opportunityLabel:'Industrialization Project Engineer',now:'2026-09-30T09:00:00Z'});
const reqCoord=u.responsibilities.find(x=>/Orchestrate/.test(x.statement));const reqImprove=u.requirements.find(x=>/measurable/.test(x.statement));const reqBudget=u.requirements.find(x=>/budget/.test(x.statement));const reqScheduling=u.preferredRequirements.find(x=>/scheduling/.test(x.statement));
assert(reqCoord&&reqImprove&&reqBudget&&reqScheduling);
const inv=buildOpportunityRequirementSupportContributorInventory({professionalIdentity:identity});assert(inv.some(x=>x.contributorType==='higher_order_descriptive_professional_structure'));assert(inv.some(x=>x.contributorType==='bounded_canonical_knowledge_meaning'));
const proposal=(type,ref,req,id,extra={})=>({contributorType:type,contributorRef:ref,opportunityRef:u.opportunityRef,opportunityRequirementRef:req.id,relationBasis:'bounded semantic support from accepted professional structure',provenance:{providerRef:'controlled:pd085',proposalRef:id},...extra});
// A/B/C canonical rich contributors.
assert.equal(validateOpportunityRequirementSupportProposal(proposal('episode_meaning','episode:1',reqCoord,'p-ep'),{professionalIdentity:identity,opportunityUnderstanding:u}).status,'accepted');
assert.equal(validateOpportunityRequirementSupportProposal(proposal('grounded_descriptive_professional_relationship','rel:coord',reqCoord,'p-rel'),{professionalIdentity:identity,opportunityUnderstanding:u}).status,'accepted');
const hr=validateOpportunityRequirementSupportProposal(proposal('higher_order_descriptive_professional_structure','ho:coord',reqCoord,'p-ho'),{professionalIdentity:identity,opportunityUnderstanding:u});assert.equal(hr.status,'accepted');assert.equal(hr.supportRobustnessClass,'COMPOSED_HIGHER_ORDER_BASIS');
assert.equal(validateOpportunityRequirementSupportProposal(proposal('bounded_canonical_knowledge_meaning','knowledge:q1',reqImprove,'p-k'),{professionalIdentity:identity,opportunityUnderstanding:u}).status,'accepted');
// D weak lexical overlap is irrelevant once the bounded proposal is validated.
assert.equal(validateOpportunityRequirementSupportProposal(proposal('higher_order_descriptive_professional_structure','ho:coord',reqCoord,'p-semantic'),{professionalIdentity:identity,opportunityUnderstanding:u}).status,'accepted');
// E lexical overlap alone cannot establish sufficiently documented.
const lexicalOnly=buildGroundedApplicationPackage({professionalIdentity:identity,opportunityUnderstanding:u,requirementSupportProposals:[]});assert(lexicalOnly.targetRelativeInformationMap.filter(x=>x.state==='sufficiently_documented').length===0);
// F agency strengthening fails closed.
const weak=validateOpportunityRequirementSupportProposal(proposal('grounded_descriptive_professional_relationship','rel:weak',reqCoord,'p-weak'),{professionalIdentity:identity,opportunityUnderstanding:u});assert.equal(weak.status,'rejected');assert(weak.errors.includes('claim_strength_exceeds_contributor_ceiling'));
// G contribution-only causality is preserved.
const kr=validateOpportunityRequirementSupportProposal(proposal('bounded_canonical_knowledge_meaning','knowledge:q1',reqImprove,'p-causal'),{professionalIdentity:identity,opportunityUnderstanding:u});assert.equal(kr.semanticCeiling.causality,'contribution_only');assert(kr.semanticProtection.includes('no_semantic_strengthening'));
// H temporal context is not an authorised contributor.
assert.equal(validateOpportunityRequirementSupportProposal(proposal('formal_role_continuity','role:10years',reqImprove,'p-time'),{professionalIdentity:identity,opportunityUnderstanding:u}).status,'rejected');
// I unknown != absent; J preferred stays preferred. Pending budget/scheduling authority remains fail-closed.
assert.equal(validateOpportunityRequirementSupportProposal(proposal('higher_order_descriptive_professional_structure','ho:coord',reqBudget,'p-budget'),{professionalIdentity:identity,opportunityUnderstanding:u}).status,'rejected');
assert.equal(validateOpportunityRequirementSupportProposal(proposal('higher_order_descriptive_professional_structure','ho:coord',reqScheduling,'p-schedule'),{professionalIdentity:identity,opportunityUnderstanding:u}).status,'rejected');
const proposals=[proposal('higher_order_descriptive_professional_structure','ho:coord',reqCoord,'p1'),proposal('bounded_canonical_knowledge_meaning','knowledge:q1',reqImprove,'p2')];const projection=buildOpportunityRequirementSupportProjection({professionalIdentity:identity,opportunityUnderstanding:u,proposals});assert.equal(projection.relations.length,2);assert.equal(projection.personKnowledgeWriteback,false);
const pkg=buildGroundedApplicationPackage({professionalIdentity:identity,opportunityUnderstanding:u,requirementSupportProposals:proposals,documentData:{displayName:'Marco'}});assert.equal(pkg.version,'1.4');assert(pkg.targetRelativeInformationMap.find(x=>x.requirementRef===reqCoord.id).state==='sufficiently_documented');assert(pkg.targetRelativeInformationMap.find(x=>x.requirementRef===reqBudget.id).state!=='sufficiently_documented');assert.equal(pkg.opportunityRequirementSupportProjection.lexicalOverlapRole,'proposal_aid_retrieval_preselection_fallback_diagnostic_only');assert(pkg.selectedCandidateMaterials.some(x=>x.sourceRef==='cv:1'));
const arts=buildApplicationArtifacts({applicationPackage:pkg,opportunityUnderstanding:u});assert(!/fit score|readiness score|match %/i.test(JSON.stringify(arts)));
console.log('PD-085 Opportunity-Specific Rich Requirement Support Authority: PASS');
