import assert from 'assert';
import {readFile} from 'fs/promises';
import {prepareStagedPrivateBetaJourney,continueStagedPrivateBetaJourney,answerStagedPrivateBetaJourney} from '../src/app/privateBetaJourneyIntegration.js';
const load=async n=>JSON.parse(await readFile(new URL(`../fixtures/${n}`,import.meta.url),'utf8'));
const adapter=async({task})=>task==='candidateProfile'?JSON.stringify(await load('expected_candidate_profile_01.json')):task==='roleProfile'?JSON.stringify(await load('expected_role_profile_01.json')):task==='jobFitAnalysis'?JSON.stringify(await load('expected_job_fit_analysis_01.json')):'{}';
const cv=await readFile(new URL('../fixtures/sample_cv_01.txt',import.meta.url),'utf8');const jd=await readFile(new URL('../fixtures/sample_jd_01.txt',import.meta.url),'utf8');
const input={identityAction:'create',workingMode:'independent',consentDecision:'accept',cvText:cv,jdText:jd,targetRole:'Product Operations Manager',uiLocale:'it'};
const daObservation={observationId:'da:as01-corrective',decisionAuthority:'final',consequenceScope:'team',accountabilityEvidence:'explicit_with_outcomes',responsibilityContinuityMonths:12,context:{episode:'delivery'},inferenceSupportInputs:{evidenceQuality:{state:'not_yet_derived'},sourceConvergence:{state:'not_yet_derived'},consistency:{state:'not_yet_derived'},coverage:{state:'not_yet_derived'}},limitations:[],metadata:{createdAt:'2026-09-04T10:00:00.000Z'}};
const daExec=({evidence})=>/DA_SUPPORTED/.test(evidence?.content?.answerText||'')?{supported:true,observation:daObservation}:{supported:false};
const qoExec=()=>({supported:false});
let prep=await prepareStagedPrivateBetaJourney({uiInput:input,modelAdapter:adapter});continueStagedPrivateBetaJourney({state:prep.state});
let step=await answerStagedPrivateBetaJourney({state:prep.state,answer:'Il progetto ha portato a un miglioramento misurabile delle performance, che posso descrivere più nel dettaglio.',decisionAccountabilityExecutor:daExec,quantifiedOutcomeExecutor:qoExec});
assert.equal(step.state.session.runtimeKnowledgeResults.length,0,'cue alone must not create Knowledge');
assert.deepEqual(step.state.session.fhtAcquisitionCues.map(x=>x.purposeRef),['quantified_outcome']);
assert(step.state.session.fhtAcquisitionCues[0].sourceRef.startsWith('runtimeAnswer:'));
assert(step.state.session.groundedConversationalReferents.some(x=>x.type==='measurable_result'&&/miglioramento misurabile/i.test(x.text)));
step=await answerStagedPrivateBetaJourney({state:step.state,answer:'Il ruolo è il passo successivo perché amplia il mio perimetro operativo.',decisionAccountabilityExecutor:daExec,quantifiedOutcomeExecutor:qoExec});
assert.equal(step.state.session.interviewRuntime.currentStep?.payload?.questionKey,'achievement_quantification','retained QO cue must survive an intervening answer and drive the authorized QO action');
assert.equal(step.state.session.interviewRuntime.runtimeState.injectedAdaptiveFollowupCount,1);assert.equal(step.state.session.interviewRuntime.runtimeState.adaptiveFollowupBudget,2);
const trace=step.state.session.interviewRuntime.runtimeState.lastAdaptiveAcquisitionDecisionTrace;assert.equal(trace.selectedPurpose,'quantified_outcome');assert.equal(trace.selectedAction,'achievement_quantification');assert(trace.selectedGroundedReferents.some(x=>x.type==='measurable_result'));
assert.equal(trace.groundingValidationOutcome,'grounded_or_non_presuppositive');
// A separate journey proves current-answer DA Knowledge is visible to the same next-action decision before a second adaptive slot is spent.
prep=await prepareStagedPrivateBetaJourney({uiInput:input,modelAdapter:adapter});continueStagedPrivateBetaJourney({state:prep.state});
step=await answerStagedPrivateBetaJourney({state:prep.state,answer:'Percorso professionale senza risultato quantitativo.',decisionAccountabilityExecutor:daExec,quantifiedOutcomeExecutor:qoExec});
step=await answerStagedPrivateBetaJourney({state:step.state,answer:'Il ruolo amplia coerentemente il mio perimetro operativo.',decisionAccountabilityExecutor:daExec,quantifiedOutcomeExecutor:qoExec});
assert(['decision_tradeoff_probe','responsibility_probe'].includes(step.state.session.interviewRuntime.currentStep?.payload?.questionKey),'first adaptive action must be DA-capable in the no-cue journey');
step=await answerStagedPrivateBetaJourney({state:step.state,answer:'DA_SUPPORTED Ho preso una decisione nel mio perimetro e ne ho assunto la responsabilità.',decisionAccountabilityExecutor:daExec,quantifiedOutcomeExecutor:qoExec});
assert.equal(step.state.session.runtimeKnowledgeResults.filter(x=>x.semanticType==='decision_accountability').length,1,'current answer DA Knowledge must be appended exactly once');
const postDaTrace=step.state.session.interviewRuntime.runtimeState.lastAdaptiveAcquisitionDecisionTrace;assert(postDaTrace,'AS01 trace required after current-answer semantic feedback');
const daState=postDaTrace.candidatePurposes.find(x=>x.goal==='decision_accountability');const qoState=postDaTrace.candidatePurposes.find(x=>x.goal==='quantified_outcome');assert.equal(daState.state,'represented');assert.equal(qoState.state,'not_observed');assert(qoState.priority>daState.priority);assert.equal(postDaTrace.selectedPurpose,'quantified_outcome');assert.equal(postDaTrace.selectedAction,'achievement_quantification');
assert.equal(step.state.session.interviewRuntime.runtimeState.injectedAdaptiveFollowupCount,2,'second slot may be spent only on the preferred QO action, not redundant DA');
assert.equal(step.state.session.interviewRuntime.runtimeState.adaptiveFollowupBudget,2,'standard adaptive budget must remain unchanged');
const goals=step.state.session.fhtAcquisitionPlanning.activeGoals;assert.deepEqual(goals,['decision_accountability','quantified_outcome']);
console.log('FHT-AS01 first corrective lifecycle regression PASS');
