import assert from 'node:assert/strict';
import { createPrivateBetaUiServer } from '../src/app/privateBetaUiServer.js';
import { createMemoryPrivateBetaProfessionalIdentityStore, privateBetaPersonRefFromContext } from '../src/app/privateBetaProfessionalIdentityContinuity.js';
import { PRIVATE_BETA_PRODUCT_PURPOSES, normalizePrivateBetaProductPurpose } from '../src/app/privateBetaProductPurpose.js';

const store=createMemoryPrivateBetaProfessionalIdentityStore();
const personRef=privateBetaPersonRefFromContext('pa01-person');
const source={id:'current_cv',type:'text',label:'Current CV',content:'Production Supervisor',language:null,sourceRole:'current_cv',quality:null,provenance:{origin:'current_cv',providedBy:'user',collectedAt:'2026-09-09T00:00:00.000Z'},metadata:{createdAt:'2026-09-09T00:00:00.000Z',updatedAt:'2026-09-09T00:00:00.000Z'}};
await store.save({record:{version:'1.0',type:'private_beta_professional_identity_continuity',professionalIdentityRef:`professionalIdentity:${personRef.id}`,personRef,owner:'person',authorizedMaterials:{cvText:'Production Supervisor',userNotes:''},professionalSources:[source],reusableKnowledgeResults:[],knowledgeRefs:[],revision:1,createdAt:'2026-09-09T00:00:00.000Z',updatedAt:'2026-09-09T00:00:00.000Z',lastEnrichedBySessionRef:null}});
let seq=0; const seen=[];
const stagedPrepare=async ({uiInput,reusableProfessionalIdentity,knowledgeSubjectRef})=>{seen.push({purpose:uiInput.productPurpose,recovered:!!reusableProfessionalIdentity,person:knowledgeSubjectRef.id});const id=`pa01-${++seq}`;return {state:{sessionId:id,session:{rawInput:{},professionalSources:reusableProfessionalIdentity.professionalSources},consent:{status:'accepted'},knowledgeSubjectRef,reusableProfessionalIdentity,now:()=>new Date().toISOString()},publicResult:{status:'understanding',completed:false,phase:'understanding',sessionRef:id,preInterview:{professionalIdentityContinuity:{recovered:true,reusedKnowledgeCount:0},sourceGroundedProjection:[{sourceRole:'current_cv',facts:['Production Supervisor']}],professionalSources:[{sourceRole:'current_cv'}],productPurpose:uiInput.productPurpose}}};};
const server=createPrivateBetaUiServer({professionalIdentityStore:store,contextIdFactory:()=> 'pa01-person',stagedPrepare});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;const cookie='imago_beta_repeat_context=pa01-person';
async function post(purpose){const body=new URLSearchParams({identityAction:'recover',productPurpose:purpose,workingMode:'independent',consentDecision:'accept',targetRole:'Program Manager',cvText:'',previousCvText:'',professionalDeclaration:'',userNotes:'',jdText:'JD'});const r=await fetch(base+'/private-beta/journey',{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body});return r.text();}
const start=await (await fetch(base+'/private-beta',{headers:{cookie}})).text();assert.match(start,/professional_identity_build_enrich/);assert.match(start,/professional_representation_understand/);assert.match(start,/interview_practice/);assert.doesNotMatch(start,/opportunity_application/);
const build=await post(PRIVATE_BETA_PRODUCT_PURPOSES.BUILD_ENRICH);assert.match(build,/purpose-known/);assert.match(build,/private-beta\/journey/);assert.match(build,/professional_identity_build_enrich/);assert.doesNotMatch(build,/runtime-question/);
const understand=await post(PRIVATE_BETA_PRODUCT_PURPOSES.UNDERSTAND);assert.match(understand,/purpose-no-interview/);assert.doesNotMatch(understand,/runtime-question/);
const practice=await post(PRIVATE_BETA_PRODUCT_PURPOSES.INTERVIEW_PRACTICE);assert.match(practice,/pre-interview-understanding/);assert.match(practice,/understanding\/continue/);
assert.equal(new Set(seen.map(x=>x.person)).size,1);assert.ok(seen.every(x=>x.recovered));assert.equal(normalizePrivateBetaProductPurpose('opportunity_application'), 'opportunity_application');
assert.equal(seen.length,3);console.log('PA-01 purpose-aware Private Beta: PASS');server.close();
