import assert from 'node:assert/strict';
import {renderPrivateBetaUiJourneyHtml} from '../src/app/renderPrivateBetaUiJourneyHtml.js';
const pattern={kind:'documented_cross_functional_coordination_recurrence',supportCount:2,episodeRefs:['e1','e2'],supports:[{sourceId:'atlas',sourceRole:'professional_declaration',supportExcerpt:'Ho coordinato qualità e produzione nel ramp-up.'},{sourceId:'maint',sourceRole:'professional_declaration',supportExcerpt:'Ho coordinato produzione e manutenzione negli interventi.'}]};
const rep={professionalMeaning:{supportedPatterns:[pattern],knowledgeContribution:[{semanticType:'decision_accountability',primaryProfessionalMeaning:{kind:'bounded_decision_accountability',observedContext:'progetto Atlas',personContribution:'definire le priorità',sharedAuthority:true},supportingEvidence:[{summary:'Responsabilità condivisa sul follow-up operativo.'}]},{semanticType:'quantified_outcome',primaryProfessionalMeaning:{kind:'bounded_measurable_outcome_contribution',quantification:'circa 20%',personContribution:'contributo al miglioramento'},supportingEvidence:[{summary:'Risultato del progetto: circa 20%.'}]}]},assets:[{supportClass:'source_grounded',sourceId:'atlas',sourceRole:'professional_declaration',sourceLabel:'professional_declaration',sourceFaithfulExperienceExcerpts:['Ho coordinato qualità e produzione nel ramp-up.']},{supportClass:'source_grounded',sourceId:'maint',sourceRole:'professional_declaration',sourceLabel:'professional_declaration',sourceFaithfulExperienceExcerpts:['Ho coordinato produzione e manutenzione negli interventi.']}]};
const html=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'purpose_understand',sessionRef:'pd068',preInterview:{targetIndependentProfessionalRepresentation:rep,professionalIdentityContinuity:{recovered:true,reusedKnowledgeCount:2}}}});
assert.match(html,/Quello che vale la pena notare/);assert.match(html,/coordinamento tra funzioni ricorre/);assert.equal((html.match(/coordinamento tra funzioni ricorre/g)||[]).length,1);assert.match(html,/Da dove emerge/);assert.match(html,/Ho coordinato qualità e produzione nel ramp-up/);assert.match(html,/Da un tuo approfondimento professionale/);assert.match(html,/Da un tuo approfondimento professionale/);assert.match(html,/circa 20%/);assert.match(html,/senza attribuirlo interamente a te/);assert.match(html,/responsabilità era condivisa/i);assert.doesNotMatch(html,/professional_declaration|candidate_application_material_item|Stato epistemico/);
const home=renderPrivateBetaUiJourneyHtml({locale:'it',identityAvailable:true,identitySummary:{professionalSources:[{sourceRole:'current_cv'},{sourceRole:'professional_declaration'}],knowledgeCount:3}});assert.match(home,/<h1 class="landing-motto"><span>Ti conosce professionalmente\.<\/span><span>Ti valorizza senza inventarti\.<\/span><\/h1>/);assert.doesNotMatch(home,/Materiali professionali disponibili: 2/);assert.doesNotMatch(home,/Conoscenze professionali riutilizzabili: 3/);assert.match(home,/Profilo IMAGO disponibile/);assert.match(home,/Apri il mio profilo/);assert.match(home,/Scopri cosa puoi fare con IMAGO/);assert.doesNotMatch(home,/id="purpose-start"|id="purpose-actions"|Cosa vuoi fare oggi\?/);for(const href of ['professional_representation_understand','professional_direction_explore','opportunity_application','professional_identity_build_enrich','interview_practice'])assert.match(home,new RegExp(`/private-beta\\?purpose=${href}`));assert.doesNotMatch(home,/profilo buono|profile good|% complete/i);
const en=renderPrivateBetaUiJourneyHtml({locale:'en',result:{phase:'purpose_understand',sessionRef:'pd068-en',preInterview:{targetIndependentProfessionalRepresentation:rep}}});assert.match(en,/What is worth noticing/);assert.match(en,/Where this comes from/);
console.log('PD-068 Candidate-facing Representation/Home: PASS');
