const assert=require('assert');const A=require('../src/app/knowledge');const F=require('./knowledge_acquisition_invocation_boundary_fixture');const {calculateKnowledgeAcquisitionInvocationInputFingerprint}=require('../src/app/knowledge/knowledgeAcquisitionInvocationInputIdentity');
const f=F.buildFixture(),before=JSON.stringify(f),value=A.buildKnowledgeAcquisitionInvocationInput(f.context),item=f.plan.planItems.find(i=>i.planItemRef===f.ready.sourcePlanItemRef);
assert(A.validateKnowledgeAcquisitionInvocationInput(value).valid);assert(A.validateKnowledgeAcquisitionInvocationInputContext({...f.context,knowledgeAcquisitionInvocationInput:value}).valid);assert.strictEqual(value.sourceExecutionRef,`knowledgeAcquisitionExecution:${f.ready.id}`);assert.strictEqual(value.operation.capabilityRef,item.capabilityRef);assert.deepStrictEqual(value.operation.configurationItemRefs,item.configurationItemRefs);assert.deepStrictEqual(Object.keys(value).sort(),['integrityFingerprint','invocationInputVersion','operation','sourceExecutionRef','sourcePlanItemRef','sourcePlanRef','sourceRuntimeSessionRef','type'].sort());
for(const x of [f.created,f.selected])assert.throws(()=>A.buildKnowledgeAcquisitionInvocationInput({...f.context,knowledgeAcquisitionExecution:x}),/ready_for_invocation/);assert(Object.isFrozen(value)&&Object.isFrozen(value.operation)&&Object.isFrozen(value.operation.configurationItemRefs));assert.strictEqual(JSON.stringify(f),before);
for(const field of ['sourceExecutionRef','sourceRuntimeSessionRef','sourcePlanRef','sourcePlanItemRef']){const bad={...value,[field]:undefined};assert(!A.validateKnowledgeAcquisitionInvocationInput(bad).valid)}
for(const field of ['provider','adapter','endpoint','retry','status','result','outcome'])assert(!A.validateKnowledgeAcquisitionInvocationInput({...value,[field]:true}).valid);
const nested={...value,operation:{...value.operation,metadata:{transport:'http'}}};nested.integrityFingerprint=calculateKnowledgeAcquisitionInvocationInputFingerprint(nested);assert(!A.validateKnowledgeAcquisitionInvocationInput(nested).valid);assert(!A.validateKnowledgeAcquisitionInvocationInput({...value,integrityFingerprint:'0'.repeat(64)}).valid);
const foreign=F.buildFixture();foreign.ready={...foreign.ready,id:'knowledgeAcquisitionExecution_'+'0'.repeat(32)};assert(!A.validateKnowledgeAcquisitionInvocationInputContext({...f.context,knowledgeAcquisitionExecution:foreign.ready,knowledgeAcquisitionInvocationInput:value}).valid);
let received=null;const port={invoke(input){received=input}};assert(A.validateKnowledgeAcquisitionInvocationPort(port).valid);assert(!A.validateKnowledgeAcquisitionInvocationPort({}).valid);assert(!A.validateKnowledgeAcquisitionInvocationPort({invoke(){},extra:true}).valid);port.invoke(value);assert.strictEqual(received,value);assert(!('status'in value)&&!('lifecycle'in value)&&!('result'in value)&&!('outcome'in value));
console.log('Knowledge Acquisition Invocation Boundary tests PASSED');
