import assert from 'node:assert/strict';
import {naturalizeCandidateWording,naturalizeEpisodeMeaning,normalizeCandidatePunctuation} from '../src/app/candidateFacingRepresentationPresentation.js';
import {renderPrivateBetaUiJourneyHtml} from '../src/app/renderPrivateBetaUiJourneyHtml.js';
import fs from 'node:fs';
const it=JSON.parse(fs.readFileSync(new URL('../config/private_beta_ui.it.json',import.meta.url)));
assert.equal(naturalizeCandidateWording('Nel percorso si manifesta nella conduzione di ramp-up di nuovi fornitori.',{locale:'it',claimShape:{responsibilityAssertion:'none'}}),'Nel percorso si manifesta nel lavoro svolto durante ramp-up di nuovi fornitori.');
assert.equal(naturalizeEpisodeMeaning({description:'Lancio di una nuova linea produttiva in Germania.',participation:'participated'},{locale:'it'}),'Hai partecipato a lancio di una nuova linea produttiva in Germania.');
assert.equal(normalizeCandidatePunctuation('Una frase..'),'Una frase.');
const ep={threadId:'professionalThread:episode:e1',kind:'distinct_episode',level1SelectionClass:'standalone_distinct_contribution',meaning:{description:'Lancio di una nuova linea produttiva in Germania.',participation:'participated',distinctUnitRefs:['u1']},manifestations:[{episodeMeaningRef:'e1',sourceId:'cv',description:'Lancio di una nuova linea produttiva in Germania.'}],supportRefs:['cv']};
const noSupport={...ep,threadId:'professionalThread:episode:e2',meaning:{description:'Secondo episodio.',participation:'contributed',distinctUnitRefs:['u2']},manifestations:[{episodeMeaningRef:'e2',sourceId:'missing',description:''}],supportRefs:['missing']};
const representation={professionalMeaning:{professionalThreads:[ep,noSupport],level1ProfessionalThreads:[ep,noSupport],supportedPatterns:[],groundedDescriptiveRelationships:[],knowledgeContribution:[]},assets:[{supportClass:'source_grounded',sourceId:'cv',sourceRole:'current_cv',formalRole:'Production Supervisor',sourceFaithfulExperienceExcerpts:['Testo adiacente che non prova il lancio.']}],episodeMeanings:[]};
const html=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'purpose_understand',preInterview:{targetIndependentProfessionalRepresentation:representation}}});
assert.match(html,/Hai partecipato a lancio di una nuova linea produttiva in Germania\./);
assert.doesNotMatch(html,/Questa esperienza rende visibile/);
assert.match(html,/Supporto strutturato:/);
assert.match(html,/Lancio di una nuova linea produttiva in Germania\./);
assert.match(html,/Da dove emerge<\/summary><ul><li><strong>Dal tuo CV — Production Supervisor<\/strong><p>Supporto strutturato:/);
assert.match(html,/Hai contribuito a secondo episodio\./);
console.log('PD-071B focused tests passed');
