import assert from "assert";
import {createPrivateBetaUiServer} from "../src/app/privateBetaUiServer.js";
import {createMemoryPrivateBetaFeedbackStore,buildPrivateBetaContextualFeedbackRecord} from "../src/app/privateBetaContextualFeedback.js";
import {renderPrivateBetaUiJourneyHtml} from "../src/app/renderPrivateBetaUiJourneyHtml.js";
const now=()=>"2026-09-08T09:30:00.000Z",personRef={type:"person",id:"p1"},store=createMemoryPrivateBetaFeedbackStore();
const a=buildPrivateBetaContextualFeedbackRecord({sessionRef:"A",personRef,checkpoint:"professional_representation",objectRef:"representation:1",purpose:"professional_representation_understand",reaction:"missing",comment:"manca un'esperienza",now});await store.append(a);assert.equal(a.comment,"manca un'esperienza");assert.equal("answer" in a,false);assert.equal("knowledge" in a,false);
for(const locale of ["it","en"]){const htmlR=renderPrivateBetaUiJourneyHtml({locale,result:{phase:"feedback",sessionRef:"A",report:{available:true,professionalRepresentation:{claims:[]}}}});assert.doesNotMatch(htmlR,/class="contextual-feedback"/);assert.match(htmlR,/id="imago-beta-feedback-open"/);assert.doesNotMatch(renderPrivateBetaUiJourneyHtml({locale,result:{phase:"interview",sessionRef:"A",currentQuestion:{question:"Q"}}}),/contextual-feedback/);}
const sessionStore=new Map([["A",{sessionId:"A",personRef,feedbackSequence:1,now,productPurpose:"interview_practice",consent:{status:"accepted"}}]]);const server=createPrivateBetaUiServer({sessionStore,feedbackStore:store,operatorDiagnosticsEnabled:true});await new Promise(r=>server.listen(0,"127.0.0.1",r));const base=`http://127.0.0.1:${server.address().port}`;let r=await fetch(base+"/private-beta/contextual-feedback",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({sessionRef:"A",checkpoint:"journey_conclusion",reaction:"useful",comment:"finale"})});assert.equal(r.status,204);r=await fetch(base+"/private-beta/operator/feedback?sessionRef=A");assert.equal(r.status,200);const data=await r.json();assert.equal(data.feedback.length,2);assert.equal(data.feedback[1].checkpoint,"journey_conclusion");await new Promise(r=>server.close(r));
console.log("BVL-06 contextual feedback/operator retrieval tests PASSED");
