import assert from 'node:assert/strict';
import { CURATED_ROLE_REPRESENTATIONS } from '../src/app/careerDirection/roleFixtures.js';
import { deriveSustainedRoleExposure,deriveTemporalRequirementSupport,aggregateTemporalRequirementSupport,TEMPORAL_SUPPORT_CLASSES } from '../src/app/careerDirection/temporalRequirementSupportAuthority.js';
const ops=CURATED_ROLE_REPRESENTATIONS.find(r=>r.roleIdentity.familyRef==='operations_management');const req=ops.requirements.find(r=>r.semanticKey==='cross_functional_coordination');const priority=ops.extensions.targetRequirementPriorities.find(p=>p.targetRequirementRef===req.id);
const short=deriveSustainedRoleExposure({roleRef:'role:short',formalRole:'Operations Manager',startDate:'2026-01',endDate:'2026-06'});assert.equal(short.durationMonths,6);let r=deriveTemporalRequirementSupport({targetDirectionRef:ops.id,targetRequirementRef:req.id,roleExposure:short,occupationalPriority:priority});assert.equal(r.temporalSupportClass,TEMPORAL_SUPPORT_CLASSES.EPISODIC_OR_UNESTABLISHED);
const sustained=deriveSustainedRoleExposure({roleRef:'role:ops',formalRole:'Operations Manager',startDate:'2022-01',endDate:'2025-12'});r=deriveTemporalRequirementSupport({targetDirectionRef:ops.id,targetRequirementRef:req.id,roleExposure:sustained,occupationalPriority:priority});assert.equal(r.temporalSupportClass,TEMPORAL_SUPPORT_CLASSES.SUSTAINED_ROLE_CONTEXT);assert.equal(r.existingRequirementSupportRef,null);
const direct={id:'support:req',targetRequirementRef:req.id};r=deriveTemporalRequirementSupport({targetDirectionRef:ops.id,targetRequirementRef:req.id,roleExposure:sustained,occupationalPriority:priority,existingRequirementSupport:direct,supportRoleRefs:['role:ops']});assert.equal(r.temporalSupportClass,TEMPORAL_SUPPORT_CLASSES.SUSTAINED_REQUIREMENT_SUPPORT);
const rich={id:'support:pd070',targetRequirementRef:req.id,metadata:{supportRobustnessClass:'COMPOSED_HIGHER_ORDER_BASIS'}};const richTemporal=deriveTemporalRequirementSupport({targetDirectionRef:ops.id,targetRequirementRef:req.id,roleExposure:sustained,occupationalPriority:priority,existingRequirementSupport:rich,supportRoleRefs:['role:ops']});assert.equal(richTemporal.temporalSupportClass,TEMPORAL_SUPPORT_CLASSES.SUSTAINED_REQUIREMENT_SUPPORT);assert.equal(rich.metadata.supportRobustnessClass,'COMPOSED_HIGHER_ORDER_BASIS');
const repeat=deriveTemporalRequirementSupport({targetDirectionRef:ops.id,targetRequirementRef:req.id,roleExposure:sustained,occupationalPriority:priority,existingRequirementSupport:direct,supportRoleRefs:['role:ops','role:ops','role:ops']});assert.equal(repeat.temporalSupportClass,TEMPORAL_SUPPORT_CLASSES.SUSTAINED_REQUIREMENT_SUPPORT);
const second=deriveSustainedRoleExposure({roleRef:'role:ops2',formalRole:'Operations Manager',startDate:'2018-01',endDate:'2020-12'});const r2=deriveTemporalRequirementSupport({targetDirectionRef:ops.id,targetRequirementRef:req.id,roleExposure:second,occupationalPriority:priority,existingRequirementSupport:direct,supportRoleRefs:['role:ops2']});assert.equal(aggregateTemporalRequirementSupport([r,r2]).temporalSupportClass,TEMPORAL_SUPPORT_CLASSES.CROSS_ROLE_SUSTAINED_RECURRENT_SUPPORT);
const supplemental=JSON.parse(JSON.stringify(priority));supplemental.descriptors[0].rawPriorityRelation.taskType='Supplemental';assert.equal(deriveTemporalRequirementSupport({targetDirectionRef:ops.id,targetRequirementRef:req.id,roleExposure:sustained,occupationalPriority:supplemental}).accepted,false);
assert.equal(deriveTemporalRequirementSupport({targetDirectionRef:ops.id,targetRequirementRef:'missing',roleExposure:sustained,occupationalPriority:null}).accepted,false);
assert.equal(deriveSustainedRoleExposure({roleRef:'role:title',formalRole:'Manager',startDate:'circa 2020',endDate:'2025'}).accepted,false);
const current=deriveSustainedRoleExposure({roleRef:'role:current',formalRole:'Manager',startDate:'2024-01',current:true,now:'2026-09-30'});assert.equal(current.durationMonths,33);
// Overlap is not summed: each role remains an independent exposure; aggregate uses role identity, never total months.
const overlap=deriveSustainedRoleExposure({roleRef:'role:overlap',formalRole:'Manager',startDate:'2024-06',endDate:'2025-06'});assert.equal(overlap.durationMonths,13);assert.equal(aggregateTemporalRequirementSupport([r,r]).roleExposureRefs.length,1);
console.log('PD-081 sustained role exposure / temporal requirement support authority: PASS');
