import assert from 'node:assert/strict';
import fs from 'node:fs';

const decisions = fs.readFileSync(new URL('../docs/20-product/PRODUCT_DECISIONS.md', import.meta.url), 'utf8');
const section = decisions.split('## PD-070 — Higher-Order Descriptive Professional Structure Authority')[1] || '';
assert(section, 'PD-070 canonical Product Decision must exist');
assert.match(section, /\*\*Status:\*\* CANONICAL \/ CLOSED/);
assert.match(section, /Representation-only/i);
assert.match(section, /persistent = false/i);
assert.match(section, /Person Knowledge write-back/i);
assert.match(section, /multiple independently grounded/i);
assert.match(section, /at least two independently grounded professional material\/episode bases/i);
assert.match(section, /Repeated representations of one episode/i);
assert.match(section, /chronology.*cannot manufacture recurrence, episode identity, continuity/i);
assert.match(section, /Runtime\/acquisition lineage/i);
assert.match(section, /project\/organisation name/i);
assert.match(section, /Participation cannot become ownership/i);
assert.match(section, /shared responsibility cannot become exclusive responsibility/i);
assert.match(section, /coordination cannot become leadership/i);
assert.match(section, /bounded Decision Accountability cannot become general decision autonomy/i);
assert.match(section, /project result cannot become Candidate-caused achievement/i);
assert.match(section, /recurrence of documented situations cannot become stable Person capability/i);
assert.match(section, /JD, Opportunity, Career Preference, Career Direction desirability/i);
assert.match(section, /model is proposal-only/i);
assert.match(section, /Deterministic validation remains acceptance authority/i);
assert.match(section, /Professional Thread is downstream carrier/i);
assert.match(section, /PD-058 remains downstream selection authority/i);
assert.match(section, /Interesting Unknown is explicitly outside PD-070/i);
assert.match(section, /insufficientObservability.*not authorised/i);
assert.match(section, /no universal professional ontology/i);
assert.match(section, /lexical blacklists, embeddings and provider\/model self-attestation are not semantic acceptance authority/i);
assert.match(section, /No Candidate score\/ranking/i);
console.log('PD-070 Higher-Order Descriptive Professional Structure Product Authority: PASS');
