import assert from 'node:assert/strict';
import { evaluateCareerDirections } from '../src/app/careerDirection/evaluateCareerDirections.js';
import { createCareerPreferenceContext, reviseCareerPreferenceContext } from '../src/app/careerDirection/careerPreferenceContext.js';
import { createPrivateBetaUiServer } from '../src/app/privateBetaUiServer.js';
import { renderPrivateBetaUiJourneyHtml } from '../src/app/renderPrivateBetaUiJourneyHtml.js';
import { createMemoryPrivateBetaProfessionalIdentityStore,privateBetaPersonRefFromContext,updatePrivateBetaCareerPreferenceContext } from '../src/app/privateBetaProfessionalIdentityContinuity.js';

const emptyRep={type:'target_independent_professional_representation',version:'1.4',professionalMeaning:{supportedPatterns:[],professionalSynthesis:{hasDocumentedRoleContinuity:false},knowledgeContribution:[]},episodeMeanings:[],assets:[],limitations:[],provenance:{sourceIds:[],knowledgeRefs:[]}};
const preferred={preferenceState:'declared',preferredThemes:['people_coordination']};
const early=evaluateCareerDirections({professionalRepresentation:emptyRep,professionalRepresentationRef:'representationSnapshot:early',explorationContext:preferred,now:'2026-09-16T15:00:00.000Z'});
assert.equal(early.hypotheses.length,2,'explicit people-coordination interest may broaden exploration even with limited professional support');
for(const h of early.hypotheses){assert.equal(h.supportBasis.length,0,'preference must never fabricate professional support');assert(h.preferenceBasis.length>0);assert(h.conditionsToVerify.length>0);assert(h.preferenceBasis.every(x=>x.candidateDeclared===true));}
const enHtml=renderPrivateBetaUiJourneyHtml({locale:'en',result:{phase:'purpose_direction_explore',sessionRef:'early',preInterview:{careerDirectionEvaluation:early,directionResolutions:[]}}});assert.match(enHtml,/From what you told me you want to explore/);assert.match(enHtml,/What this direction requires/);assert.doesNotMatch(enHtml,/supported_relevance/);
const noPref=evaluateCareerDirections({professionalRepresentation:emptyRep,professionalRepresentationRef:'representationSnapshot:early',explorationContext:{preferenceState:'no_preference',preferredThemes:['people_coordination']}});assert.equal(noPref.hypotheses.length,0,'explicit no preference must not silently activate preference themes');
const unsupportedTheme=evaluateCareerDirections({professionalRepresentation:emptyRep,professionalRepresentationRef:'representationSnapshot:early',explorationContext:{preferenceState:'declared',preferredThemes:['analytical_problem_solving']}});assert.equal(unsupportedTheme.hypotheses.length,0,'missing bounded preference mapping must fail closed');

const prior=createCareerPreferenceContext({...preferred,revision:1,confirmedAt:'2026-09-16T15:00:00.000Z'});const revised=reviseCareerPreferenceContext({priorContext:prior,input:{preferenceState:'declared',preferredThemes:['production_operations']},now:'2026-09-16T16:00:00.000Z'});assert.equal(revised.revision,2);assert.deepEqual(revised.preferredThemes,['production_operations']);assert.deepEqual(prior.preferredThemes,['people_coordination']);

const contextId='pd059-early-career',personRef=privateBetaPersonRefFromContext(contextId),snapshotId='representationSnapshot:pd059-early';
const record={version:'1.0',type:'private_beta_professional_identity_continuity',professionalIdentityRef:`professionalIdentity:${personRef.id}`,personRef,owner:'person',authorizedMaterials:{cvText:'Recent graduate with a documented internship project',userNotes:''},professionalSources:[{id:'current_cv',type:'text',sourceRole:'current_cv',content:'Recent graduate with a documented internship project',provenance:{origin:'current_cv',providedBy:'user',collectedAt:'2026-09-16T14:00:00.000Z'}}],reusableKnowledgeResults:[],knowledgeRefs:[],revision:2,createdAt:'2026-09-16T14:00:00.000Z',updatedAt:'2026-09-16T14:00:00.000Z',lastEnrichedBySessionRef:null,representationSnapshots:[{version:'1.0',type:'professional_representation_snapshot',snapshotId,personRef,professionalIdentityRef:`professionalIdentity:${personRef.id}`,purpose:'professional_representation_understand',context:'target_independent',materializedAt:'2026-09-16T14:00:00.000Z',relevantStateFingerprint:'pd059',sourceStateFingerprint:'s',knowledgeStateFingerprint:'k',authorizationStateFingerprint:'a',recipe:{id:'target_independent_professional_representation',version:'2.0'},changeCause:'initial_materialization',representation:emptyRep,provenance:emptyRep.provenance,limitations:[]}],currentRepresentationSnapshotRefs:{professional_representation_understand:snapshotId},applicationState:{}};
const store=createMemoryPrivateBetaProfessionalIdentityStore();await store.save({record});
const before=await store.load({personRef}),beforeKnowledge=JSON.stringify(before.reusableKnowledgeResults),beforeRepresentation=JSON.stringify(before.representationSnapshots);
const server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:store,contextIdFactory:()=>contextId,journeyOptions:{modelAdapter:async()=>{throw new Error('PD-059 direction preference path must not require provider');}}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,cookie=`imago_beta_repeat_context=${contextId}`;
const body=new URLSearchParams({identityAction:'recover',workingMode:'independent',productPurpose:'professional_direction_explore',consentDecision:'accept',careerPreferenceState:'declared',careerPreferenceTheme:'people_coordination',careerPreferenceAvoidance:'primarily_commercial',careerPreferenceUncertainty:'specialist_vs_coordination',targetRole:'',cvText:'',previousCvText:'',professionalDeclaration:'',userNotes:'',jdText:'',uiLocale:'it',sessionLocale:'it'});
const res=await fetch(base+'/private-beta/journey',{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body});const html=await res.text();assert.equal(res.status,200,html);assert.match(html,/Da ciò che mi hai detto di voler esplorare/);assert.match(html,/interesse per attività con più coordinamento e lavoro con le persone/);assert.match(html,/Cosa richiede questa direzione/);assert.match(html,/Cosa richiede questa direzione/);assert.match(html,/Da approfondire/);assert.doesNotMatch(html,/professionalmente sostenuta perché.*interess/i);for(const unsafe of [/supported_relevance/,/fit score/i,/readiness/i,/sei adatto/i,/capacità di leadership/i])assert.doesNotMatch(html,unsafe);
const sessionRef=(html.match(/action="\/private-beta\/direction\/preferences"[\s\S]*?name="sessionRef" value="([^"]+)"/)||[])[1];assert(sessionRef);
let after=await store.load({personRef});assert.equal(JSON.stringify(after.reusableKnowledgeResults),beforeKnowledge);assert.equal(JSON.stringify(after.representationSnapshots),beforeRepresentation,'preference creation must not rematerialize factual Professional Representation');assert.deepEqual(after.applicationState.careerPreferenceContext.preferredThemes,['people_coordination']);assert.equal(after.applicationState.careerPreferenceContext.preferenceState,'declared');
const revBody=new URLSearchParams({sessionRef,careerPreferenceState:'declared',careerPreferenceTheme:'production_operations',careerPreferenceAvoidance:'primarily_commercial',careerPreferenceUncertainty:'specialist_vs_coordination'});const revRes=await fetch(base+'/private-beta/direction/preferences',{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body:revBody});const revHtml=await revRes.text();assert.equal(revRes.status,200,revHtml);assert.match(revHtml,/produzione e operations industriali/i);assert.doesNotMatch(revHtml,/attività con più coordinamento e lavoro con le persone/i);after=await store.load({personRef});assert.equal(after.applicationState.careerPreferenceContext.revision,2);assert.deepEqual(after.applicationState.careerPreferenceContext.preferredThemes,['production_operations']);assert.equal(JSON.stringify(after.reusableKnowledgeResults),beforeKnowledge);assert.equal(JSON.stringify(after.representationSnapshots),beforeRepresentation);
await new Promise(r=>server.close(r));

const supportedRep={professionalMeaning:{supportedPatterns:[{kind:'documented_cross_functional_coordination_recurrence',sourceRefs:['a','b'],episodeRefs:['a','b'],traitInference:false}]}};const supportedNoPref=evaluateCareerDirections({professionalRepresentation:supportedRep,professionalRepresentationRef:'supported',explorationContext:{preferenceState:'no_preference'}});assert(supportedNoPref.hypotheses.length>=2);assert(supportedNoPref.hypotheses.every(h=>h.supportBasis.length>0&&h.preferenceBasis.length===0),'supported professional meaning remains factual without preference');

const applicationUpdated=updatePrivateBetaCareerPreferenceContext({priorRecord:record,careerPreferenceContext:createCareerPreferenceContext({preferenceState:'uncertain',uncertainties:['specialist_vs_coordination'],confirmedAt:'2026-09-16T17:00:00.000Z'}),now:'2026-09-16T17:00:00.000Z'});assert.equal(JSON.stringify(applicationUpdated.reusableKnowledgeResults),JSON.stringify(record.reusableKnowledgeResults));assert.equal(JSON.stringify(applicationUpdated.representationSnapshots),JSON.stringify(record.representationSnapshots));
console.log('PD-059 Career Preference Context Beta integration: PASS');
