const assert=require('assert');const {buildDecisionAccountabilityObservation,validateDecisionAccountabilityObservation}=require('../src/core/measurement/decisionAccountability');
function base(o={}){return buildDecisionAccountabilityObservation({observationId:'obs:1',decisionAuthority:'final',consequenceScope:'team',accountabilityEvidence:'explicit',responsibilityContinuity:{state:'known',qualification:'exact',months:12},context:{decision:'release'},evidenceIds:['ev:1'],inferenceSupportInputs:{evidenceQuality:{state:'known',value:.8,producer:{producerRef:'evidenceAssessment:1'}},sourceConvergence:{state:'not_yet_derived'},consistency:{state:'unknown'},coverage:{state:'not_yet_derived'}},...o})}
const p=base();assert(validateDecisionAccountabilityObservation(p).isValid);assert.equal(p.observationStatus,'observed');assert.equal(p.responsibilityContinuity.months,12);assert.equal(p.inferenceSupportInputs.evidenceQuality.producer.producerRef,'evidenceAssessment:1');
const u=base({accountabilityEvidence:undefined,responsibilityContinuity:{state:'unknown'}});assert.equal(u.accountabilityEvidence,null);assert.equal(u.responsibilityContinuityMonths,null);assert.equal(u.responsibilityContinuity.state,'unknown');assert(validateDecisionAccountabilityObservation(u).isValid);
for(const t of [{state:'known',qualification:'approximate',months:12},{state:'known',qualification:'lower_bound',months:12},{state:'known',qualification:'upper_bound',months:12},{state:'known',qualification:'range',minimumMonths:6,maximumMonths:12}]){const x=base({responsibilityContinuity:t});assert(validateDecisionAccountabilityObservation(x).isValid);assert.equal(x.responsibilityContinuityMonths,null)}
const missing=buildDecisionAccountabilityObservation({observationId:'obs:m',context:{decision:'x'},evidenceIds:['ev:1']});assert.equal(missing.decisionAuthority,null);assert.equal(missing.consequenceScope,null);assert.equal(missing.accountabilityEvidence,null);assert.equal(missing.responsibilityContinuityMonths,null);assert.equal(missing.inferenceSupportInputs.evidenceQuality.state,'not_yet_derived');assert.equal(missing.observationStatus,'insufficient');
const none=base({decisionAuthority:'none'});assert.equal(none.observationStatus,'contextual');assert(validateDecisionAccountabilityObservation(none).isValid);
const bad=base({responsibilityContinuity:{state:'known',qualification:'range',minimumMonths:12,maximumMonths:6}});assert.equal(validateDecisionAccountabilityObservation(bad).isValid,false);const badInf=base({inferenceSupportInputs:{evidenceQuality:{state:'known',value:2},sourceConvergence:{state:'unknown'},consistency:{state:'unknown'},coverage:{state:'unknown'}}});assert.equal(validateDecisionAccountabilityObservation(badInf).isValid,false);
console.log('Decision Accountability Observation unknown-safe tests passed.');
