import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createPrivateBetaUiServer} from '../src/app/privateBetaUiServer.js';
import {createMemoryPrivateBetaProfessionalIdentityStore,privateBetaPersonRefFromContext,attachPrivateBetaProfessionalSourceAsset} from '../src/app/privateBetaProfessionalIdentityContinuity.js';
import {buildProfessionalSourceAsset,mergeProfessionalSourceAssets,PROFESSIONAL_SOURCE_ASSET_MAX_BYTES} from '../src/app/privateBetaProfessionalSourceAssets.js';
import {buildProfessionalProfileBackup,serializeProfessionalProfileBackup,parseProfessionalProfileBackup,restoreProfessionalProfileBackup,validateProfessionalProfileBackup} from '../src/app/privateBetaProfessionalProfileBackup.js';
import {renderApplicationDocumentDocx} from '../src/app/opportunityApplication/renderApplicationDocx.js';
import {renderApplicationDocumentPdf} from '../src/app/opportunityApplication/renderApplicationDocumentPdf.js';

const stable=v=>Array.isArray(v)?`[${v.map(stable).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')}}`:JSON.stringify(v);
const payloadSha=v=>createHash('sha256').update(stable(v),'utf8').digest('hex');
const sha=b=>createHash('sha256').update(b).digest('hex');
const person=privateBetaPersonRefFromContext('pd088a-source');
const sources=[
 {id:'current-cv',type:'text',sourceRole:'current_cv',content:'Marco Rossi. Production Supervisor. 2022-2026. Coordinamento produzione.',metadata:{role:'Production Supervisor'},provenance:{origin:'candidate_upload',providedBy:'user'}},
 {id:'previous-cv',type:'text',sourceRole:'previous_cv',content:'Marco Rossi. Process Engineer. 2018-2022.',metadata:{role:'Process Engineer'},provenance:{origin:'candidate_upload',providedBy:'user'}}
];
const base={version:'1.0',type:'private_beta_professional_identity_continuity',professionalIdentityRef:`professionalIdentity:${person.id}`,personRef:person,owner:'person',authorizedMaterials:{cvText:sources[0].content,userNotes:''},professionalSources:sources,sourceAssets:[],reusableKnowledgeResults:[],knowledgeRefs:[],revision:1,createdAt:'2026-09-30T12:30:00Z',updatedAt:'2026-09-30T12:30:00Z',lastEnrichedBySessionRef:null,representationSnapshots:[],currentRepresentationSnapshotRefs:{},applicationState:{}};
const dm={type:'application_document_model',documentType:'cv',generatedAt:'2026-09-30T12:30:00Z',sections:[{kind:'cv_header',blocks:[{kind:'candidate_name',text:'Marco Rossi'}]}]};
const docx=renderApplicationDocumentDocx({documentModel:dm});
const pdf=renderApplicationDocumentPdf({documentModel:dm});
const docxAsset=buildProfessionalSourceAsset({sourceRef:'current-cv',originalFilename:'../../Marco Rossi CV.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',bytes:docx});
const pdfAsset=buildProfessionalSourceAsset({sourceRef:'previous-cv',originalFilename:'Marco Rossi CV precedente.pdf',mimeType:'application/pdf',bytes:pdf});
// Bounded upload/attach boundary preserves original bytes against an existing semantic professionalSource.
const attachStore=createMemoryPrivateBetaProfessionalIdentityStore();await attachStore.save({record:base});let attachServer=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:attachStore,contextIdFactory:()=> 'pd088a-source'});await new Promise(r=>attachServer.listen(0,'127.0.0.1',r));const attachBase=`http://127.0.0.1:${attachServer.address().port}`,attachCookie='imago_beta_repeat_context=pd088a-source';let attachResponse=await fetch(attachBase+'/private-beta/profile-source/attach',{method:'POST',headers:{cookie:attachCookie,'content-type':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','x-imago-source-ref':'current-cv','x-imago-filename':'Marco Rossi CV.docx'},body:docx});assert.equal(attachResponse.status,201);assert.equal((await attachStore.load({personRef:person})).sourceAssets.length,1);await new Promise(r=>attachServer.close(r));
assert.equal(docxAsset.originalFilename,'Marco Rossi CV.docx');assert.equal(docxAsset.sha256,sha(docx));assert.equal(pdfAsset.sha256,sha(pdf));
let record=attachPrivateBetaProfessionalSourceAsset({priorRecord:base,sourceAsset:docxAsset,now:'2026-09-30T12:31:00Z'});record=attachPrivateBetaProfessionalSourceAsset({priorRecord:record,sourceAsset:pdfAsset,now:'2026-09-30T12:32:00Z'});assert.equal(record.sourceAssets.length,2);
// duplicate bytes are deduplicated by checksum while source linkage is merged safely
const duplicate=buildProfessionalSourceAsset({sourceRef:'previous-cv',originalFilename:'same.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',bytes:docx});
const merged=mergeProfessionalSourceAssets(record.sourceAssets,[duplicate]);assert.equal(merged.length,2);assert.deepEqual([...merged.find(x=>x.sha256===sha(docx)).sourceRefs].sort(),['current-cv','previous-cv']);
const backup=buildProfessionalProfileBackup({record,exportedAt:'2026-09-30T12:35:00Z',locale:'it'}),bytes=serializeProfessionalProfileBackup(backup);assert.equal(backup.schemaVersion,2);assert.ok(Buffer.isBuffer(bytes));assert.equal(bytes.subarray(0,2).toString(),'PK');const parsed=parseProfessionalProfileBackup(bytes);assert.equal(parsed.manifest.sourceAssets.length,2);assert.equal(parsed.payload.profile.sourceAssets[0].contentBase64,undefined);
const destination=privateBetaPersonRefFromContext('pd088a-fresh'),restored=restoreProfessionalProfileBackup({backup:parsed,destinationPersonRef:destination,now:'2026-09-30T12:40:00Z'});assert.equal(restored.professionalSources[0].content,sources[0].content);assert.equal(restored.sourceAssets.length,2);for(const original of record.sourceAssets){const got=restored.sourceAssets.find(x=>x.sha256===original.sha256);assert.ok(got);assert.equal(Buffer.from(got.contentBase64,'base64').compare(Buffer.from(original.contentBase64,'base64')),0);assert.equal(got.mimeType,original.mimeType);assert.equal(got.originalFilename,original.originalFilename);}
// Corrupted embedded bytes fail closed.
const corrupt=Buffer.from(bytes);const needle=Buffer.from(pdf);const ix=corrupt.indexOf(needle);assert.ok(ix>0);corrupt[ix+10]^=0xff;assert.throws(()=>parseProfessionalProfileBackup(corrupt),/CORRUPTED/);
// Path traversal entry fails closed (same-length mutation of both local and central entry names).
const traversal=Buffer.from(bytes);let start=0,changed=0;while((start=traversal.indexOf(Buffer.from('sources/'),start))>=0){Buffer.from('../evil/').copy(traversal,start);start+=8;changed++;}assert.ok(changed>=2);assert.throws(()=>parseProfessionalProfileBackup(traversal),/UNSAFE_ENTRY|INVALID_ARCHIVE|CORRUPTED/);
assert.throws(()=>buildProfessionalSourceAsset({sourceRef:'current-cv',originalFilename:'large.pdf',mimeType:'application/pdf',bytes:Buffer.concat([Buffer.from('%PDF-'),Buffer.alloc(PROFESSIONAL_SOURCE_ASSET_MAX_BYTES)])}),/TOO_LARGE/);
// v1 semantic-only backup remains importable and explicitly contains no original assets.
const legacyProfile={continuityVersion:'1.0',authorizedMaterials:base.authorizedMaterials,professionalSources:sources,reusableKnowledgeResults:[],knowledgeRefs:[],representationSnapshots:[],currentRepresentationSnapshotRefs:{},applicationState:{},revision:1,createdAt:base.createdAt,updatedAt:base.updatedAt};
const legacyPayload={profileIdentityMarker:'legacy-marker',sourcePersonId:person.id,profile:legacyProfile};const legacy={format:'imago_professional_profile_backup',schemaVersion:1,manifest:{exportedAt:'2026-09-30T12:00:00Z',buildVersion:'private-beta',locale:'it',includedSections:['authorised_source_material'],integrityAlgorithm:'sha256'},payload:legacyPayload,integrity:{payloadSha256:payloadSha(legacyPayload)}};validateProfessionalProfileBackup(legacy);const legacyRestored=restoreProfessionalProfileBackup({backup:legacy,destinationPersonRef:destination});assert.equal(legacyRestored.professionalSources.length,2);assert.deepEqual(legacyRestored.sourceAssets,[]);
// Fresh environment: only application + .imago bytes; source originals remain downloadable.
const sourceStore=createMemoryPrivateBetaProfessionalIdentityStore();await sourceStore.save({record});let server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:sourceStore,contextIdFactory:()=> 'pd088a-source'});await new Promise(r=>server.listen(0,'127.0.0.1',r));let baseUrl=`http://127.0.0.1:${server.address().port}`;let response=await fetch(baseUrl+'/private-beta/profile-backup/export',{headers:{cookie:'imago_beta_repeat_context=pd088a-source'}});assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/application\/vnd\.imago\.profile-backup/);const exported=Buffer.from(await response.arrayBuffer());await new Promise(r=>server.close(r));
const freshStore=createMemoryPrivateBetaProfessionalIdentityStore();server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:freshStore,contextIdFactory:()=> 'pd088a-fresh'});await new Promise(r=>server.listen(0,'127.0.0.1',r));baseUrl=`http://127.0.0.1:${server.address().port}`;const cookie='imago_beta_repeat_context=pd088a-fresh';response=await fetch(baseUrl+'/private-beta/profile-backup/preview',{method:'POST',headers:{cookie,'content-type':'application/vnd.imago.profile-backup'},body:exported});assert.equal(response.status,200);let preview=await response.json();assert.equal(preview.sourceAssetCount,2);assert.equal(preview.originalSourceAssetAvailability,'included_when_present');response=await fetch(baseUrl+'/private-beta/profile-backup/restore',{method:'POST',headers:{cookie,'content-type':'application/vnd.imago.profile-backup'},body:exported});assert.equal(response.status,200);const imported=await response.json();assert.equal(imported.restored,true);const fresh=await freshStore.load({personRef:destination});assert.equal(fresh.sourceAssets.length,2);const restoredDocx=fresh.sourceAssets.find(x=>x.mimeType.includes('wordprocessingml'));response=await fetch(baseUrl+`/private-beta/profile-source/download?assetId=${encodeURIComponent(restoredDocx.assetId)}`,{headers:{cookie}});assert.equal(response.status,200);assert.equal(Buffer.from(await response.arrayBuffer()).compare(docx),0);assert.equal(response.headers.get('content-type'),'application/vnd.openxmlformats-officedocument.wordprocessingml.document');assert.match(response.headers.get('content-disposition'),/Marco Rossi CV\.docx/);
// legacy preview is explicit about originals not being in that backup
response=await fetch(baseUrl+'/private-beta/profile-backup/preview',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify(legacy)});assert.equal(response.status,200);preview=await response.json();assert.equal(preview.originalSourceAssetAvailability,'not_in_backup');
await new Promise(r=>server.close(r));
console.log('PD-088A Original Uploaded Source Asset Portability: PASS');
