import assert from 'node:assert/strict';
import { proposeLiveCareerDirectionRequirementSupport,clearCareerDirectionRequirementSupportProposalCache } from '../src/app/careerDirection/liveRequirementSupportProposalProvider.js';
import { evaluateCareerDirections } from '../src/app/careerDirection/evaluateCareerDirections.js';
import { CURATED_ROLE_REPRESENTATIONS } from '../src/app/careerDirection/roleFixtures.js';
const ops=CURATED_ROLE_REPRESENTATIONS.find(x=>x.roleIdentity.familyRef==='operations_management');
const d=(id,mat,agency='coordinated')=>({status:'accepted',descriptorId:id,descriptorRole:'activity',materialRef:mat,sourceId:mat,claimShape:{agencyLevel:agency}});
const rel={status:'accepted',relationshipId:'groundedRelationship:live-r1',descriptorRefs:['d1','d2'],materialRefs:['m1','m2'],sourceRefs:['s1','s2'],claimShape:{personPropertyAssertion:'none',responsibilityAssertion:'none'}};
const rel2={...rel,relationshipId:'groundedRelationship:live-r2',descriptorRefs:['d2','d3'],materialRefs:['m2','m3'],sourceRefs:['s2','s3']};
const ho={status:'accepted',structureId:'higherOrderStructure:live-h1',contributorRefs:[rel.relationshipId,rel2.relationshipId],professionalBasisRefs:['episode:e1','episode:e2'],materialRefs:['m1','m2','m3'],sourceRefs:['s1','s2','s3'],inheritedSemanticProtection:['pd070_representation_only','no_semantic_strengthening']};
const representation={type:'target_independent_professional_representation',version:'1.2',persistent:false,target:null,roleHistory:[],supportingExperiences:[],assets:[],limitations:[],provenance:{sourceIds:['current_cv'],knowledgeRefs:[]},professionalMeaning:{groundedDescriptiveDescriptors:[d('d1','m1'),d('d2','m2'),d('d3','m3')],groundedDescriptiveRelationships:[rel,rel2],higherOrderDescriptiveProfessionalStructures:[ho],supportedPatterns:[],knowledgeContribution:[]}};
let calls=0;const goodRunner=async()=>{calls++;return {model:'controlled-live-model',structured:{proposals:[{contributorRef:rel.relationshipId,targetDirectionRef:ops.id,targetRequirementRef:'operations_manager.cross_functional_operational_coordination',relationBasis:'accepted relationship describes coordinated cross-functional activity relevant to this atomic requirement'},{contributorRef:ho.structureId,targetDirectionRef:ops.id,targetRequirementRef:'operations_manager.cross_functional_operational_coordination',relationBasis:'accepted higher-order structure composes coordinated cross-functional activity relevant to this atomic requirement'}]}}};
clearCareerDirectionRequirementSupportProposalCache();const diagnostics=[];const first=await proposeLiveCareerDirectionRequirementSupport({professionalRepresentation:representation,roles:CURATED_ROLE_REPRESENTATIONS,modelRunner:goodRunner,diagnosticSink:x=>diagnostics.push(x)});assert.equal(calls,1);assert.equal(first.proposals.length,2);assert.equal(first.diagnostic.acceptedCount,2);assert.deepEqual(new Set(first.diagnostic.resultingRobustnessClasses),new Set(['SINGLE_GROUNDED_BASIS','COMPOSED_HIGHER_ORDER_BASIS']));
const ev=evaluateCareerDirections({professionalRepresentation:representation,professionalRepresentationRef:'rep:live',requirementSupportProposals:first.proposals});const dir=ev.hypotheses.find(x=>x.roleRepresentationRef===ops.id);const row=dir.supportBasis.find(x=>x.roleRequirementRef==='operations_manager.cross_functional_operational_coordination');assert(row);assert.equal(row.metadata.requirementSupportAggregate.robustnessClass,'COMPOSED_HIGHER_ORDER_BASIS');assert.equal(row.metadata.requirementSupportAggregate.acceptedContributorRefs.length,2);assert(!row.metadata.requirementSupportAggregate.acceptedContributorRefs.includes('budget_resource_scope'),'coordination support must not manufacture budget support');
const second=await proposeLiveCareerDirectionRequirementSupport({professionalRepresentation:representation,roles:CURATED_ROLE_REPRESENTATIONS,modelRunner:goodRunner,diagnosticSink:x=>diagnostics.push(x)});assert.equal(calls,1,'unchanged representation/contributors/requirements must reuse proposal result');assert.equal(second.reused,true);assert.equal(diagnostics.at(-1).providerAttempted,false);
// Negative live-style batch: every proposal reaches PD-079 validation; none can self-authorise or bypass semantic keys/ceilings.
clearCareerDirectionRequirementSupportProposalCache();const badRunner=async()=>({model:'controlled-live-model',structured:{proposals:[{contributorRef:rel.relationshipId,targetDirectionRef:ops.id,targetRequirementRef:'operations_manager.budget_operational_resources',relationBasis:'lexical budget mapping from coordination material'},{contributorRef:'unknown:contributor',targetDirectionRef:ops.id,targetRequirementRef:'operations_manager.cross_functional_operational_coordination',relationBasis:'unknown contributor'},{contributorRef:rel.relationshipId,targetDirectionRef:ops.id,targetRequirementRef:'unknown:req',relationBasis:'unknown requirement'}]}});const bad=await proposeLiveCareerDirectionRequirementSupport({professionalRepresentation:representation,roles:CURATED_ROLE_REPRESENTATIONS,modelRunner:badRunner});assert.equal(bad.diagnostic.acceptedCount,0);assert.equal(bad.diagnostic.rejectedCount,3);assert.equal(evaluateCareerDirections({professionalRepresentation:representation,professionalRepresentationRef:'rep:bad',requirementSupportProposals:bad.proposals}).hypotheses.length,0,'rejected rich proposals must not fabricate Career Direction support');
// Participated/contributed material cannot become coordinated support.
clearCareerDirectionRequirementSupportProposalCache();const weakRep={professionalMeaning:{...representation.professionalMeaning,groundedDescriptiveDescriptors:[d('d1','m1','participated'),d('d2','m2','contributed'),d('d3','m3','contributed')]}};const weak=await proposeLiveCareerDirectionRequirementSupport({professionalRepresentation:weakRep,roles:CURATED_ROLE_REPRESENTATIONS,modelRunner:goodRunner});assert.equal(weak.diagnostic.acceptedCount,0);
// Provider failure degrades to empty enrichment and existing deterministic support remains usable.
clearCareerDirectionRequirementSupportProposalCache();const existingRep={professionalMeaning:{...representation.professionalMeaning,supportedPatterns:[{kind:'documented_cross_functional_coordination_recurrence',episodeRefs:['e1','e2'],sourceRefs:['s1','s2']}]}};const failed=await proposeLiveCareerDirectionRequirementSupport({professionalRepresentation:existingRep,roles:CURATED_ROLE_REPRESENTATIONS,modelRunner:async()=>{throw Object.assign(new Error('timeout'),{providerDiagnostic:{failureKind:'timeout',model:'controlled-live-model'}})}});assert.equal(failed.degraded,true);assert.deepEqual(failed.proposals,[]);const fallback=evaluateCareerDirections({professionalRepresentation:existingRep,professionalRepresentationRef:'rep:fallback',requirementSupportProposals:failed.proposals});const fallbackOps=fallback.hypotheses.find(x=>x.roleRepresentationRef===ops.id);assert(fallbackOps.supportBasis.some(x=>x.roleRequirementRef==='operations_manager.cross_functional_operational_coordination'),'provider failure must preserve pre-PD079 deterministic support');

// Real production wiring point: staged Career Direction journey invokes one bounded batch and passes proposals into PD-079 evaluation.
const {prepareStagedPrivateBetaJourney}=await import('../src/app/privateBetaStagedInterviewJourney.js');
const {privateBetaPersonRefFromContext}=await import('../src/app/privateBetaProfessionalIdentityContinuity.js');const personRef=privateBetaPersonRefFromContext('pd079l');const at='2026-09-30T08:00:00.000Z';const snapshotId='representationSnapshot:pd079l';
const identity={version:'1.0',type:'private_beta_professional_identity_continuity',professionalIdentityRef:'professionalIdentity:pd079l',personRef,owner:'person',authorizedMaterials:{cvText:'bounded current cv',userNotes:''},professionalSources:[{id:'current_cv',type:'text',sourceRole:'current_cv',content:'bounded current cv',provenance:{origin:'current_cv',providedBy:'user',collectedAt:at}}],reusableKnowledgeResults:[],knowledgeRefs:[],revision:1,createdAt:at,updatedAt:at,lastEnrichedBySessionRef:'pd079l',representationSnapshots:[{version:'1.0',type:'professional_representation_snapshot',snapshotId,personRef,professionalIdentityRef:'professionalIdentity:pd079l',purpose:'professional_representation_understand',context:'target_independent',materializedAt:at,relevantStateFingerprint:'pd079l',sourceStateFingerprint:'s',knowledgeStateFingerprint:'k',authorizationStateFingerprint:'a',recipe:{id:'target_independent_professional_representation',version:'1.8'},changeCause:'initial_materialization',representation,provenance:{sourceIds:['current_cv']},limitations:[]}],currentRepresentationSnapshotRefs:{professional_representation_understand:snapshotId}};
clearCareerDirectionRequirementSupportProposalCache();let stagedCalls=0;const staged=await prepareStagedPrivateBetaJourney({uiInput:{identityAction:'recover',workingMode:'independent',consentDecision:'accept',productPurpose:'professional_direction_explore'},reusableProfessionalIdentity:identity,knowledgeSubjectRef:personRef,now:()=>at,careerDirectionRequirementSupportModelRunner:async()=>{stagedCalls++;return {model:'controlled-live-model',structured:{proposals:[{contributorRef:rel.relationshipId,targetDirectionRef:ops.id,targetRequirementRef:'operations_manager.cross_functional_operational_coordination',relationBasis:'bounded coordinated cross-functional relevance'}]}}}});assert.equal(stagedCalls,1);assert.equal(staged.state.requirementSupportProposals.length,1);const stagedOps=staged.state.careerDirectionEvaluation.hypotheses.find(x=>x.roleRepresentationRef===ops.id);assert(stagedOps.supportBasis.some(x=>x.roleRequirementRef==='operations_manager.cross_functional_operational_coordination'));

console.log('PD-079L live requirement support proposal integration: PASS');
