import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {runGroqContinuingPeopleResponsibilitySemanticExecutor} from '../src/infrastructure/groq/runGroqContinuingPeopleResponsibilitySemanticExecutor.js';
const require=createRequire(import.meta.url);const {buildEvidence}=require('../src/core/evidence/buildEvidence');
function evidence(text){return buildEvidence({sourceType:'runtime_answer',sourceRef:'runtime:pdir11',content:{answerText:text},provenance:{capturedAt:'2026-09-11T08:00:00.000Z'},metadata:{version:'1.0'}})}
const base={interpretationStatus:'SUPPORTED',responsibilityPresence:'supported',continuity:'continuing',responsibilityMode:'informal_operational',responsibilityKinds:['work_assignment_or_priority_setting','workload_shift_or_schedule_coordination','performance_follow_up_or_feedback'],peopleScope:{kind:'category',value:'circa 10 operatori',min:null,max:null},professionalContext:{description:'reparto',current:true},eventTime:{description:'da circa due anni'},support:{presence:'coordino stabilmente 10 operatori',continuity:'Da circa due anni',mode:'coordino stabilmente',peopleScope:'10 operatori',professionalContext:'del reparto',responsibilityKinds:['Definisco priorità','organizzo i turni','valutazioni periodiche']},limitations:['formal reporting authority not established']};
const strong='Da circa due anni coordino stabilmente 10 operatori del reparto. Definisco priorità e attività giornaliere, organizzo i turni e partecipo alle valutazioni periodiche insieme al mio responsabile.';
const completion=c=>async()=>({content:JSON.stringify(c),model:'mock',outputMode:'json_schema'});
let r=await runGroqContinuingPeopleResponsibilitySemanticExecutor({evidence:evidence(strong),completionRunner:completion(base)});assert.equal(r.supported,true);
for(const text of ['Sì, coordino delle persone.','Ho lavorato con un team.','Ho guidato un progetto con colleghi di diversi reparti.']){r=await runGroqContinuingPeopleResponsibilitySemanticExecutor({evidence:evidence(text),completionRunner:completion({...base,interpretationStatus:'UNSUPPORTED',responsibilityPresence:'insufficient',continuity:'insufficient',responsibilityMode:'insufficient',responsibilityKinds:[],peopleScope:{kind:'unknown',value:null,min:null,max:null},professionalContext:{description:null,current:null},eventTime:{description:null},support:{presence:null,continuity:null,mode:null,peopleScope:null,professionalContext:null,responsibilityKinds:[]},limitations:['insufficient explicit evidence']})});assert.equal(r.supported,false);assert.equal(r.reason,'unsupported_semantics');}
const temporary={...base,continuity:'temporary',responsibilityMode:'temporary_assignment',responsibilityKinds:[],peopleScope:{kind:'exact',value:15,min:null,max:null},professionalContext:{description:'sostituito il responsabile del reparto',current:false},eventTime:{description:'Per tre mesi'},support:{presence:'coordinato 15 persone',continuity:'Per tre mesi',mode:'sostituito il responsabile',peopleScope:'15 persone',professionalContext:'responsabile del reparto',responsibilityKinds:[]}};r=await runGroqContinuingPeopleResponsibilitySemanticExecutor({evidence:evidence('Per tre mesi ho sostituito il responsabile del reparto e coordinato 15 persone.'),completionRunner:completion(temporary)});assert.equal(r.supported,true);assert.equal(r.candidate.continuity,'temporary');
const contextual={interpretationStatus:'SUPPORTED',responsibilityPresence:'contextual_non_responsibility',continuity:'insufficient',responsibilityMode:'insufficient',responsibilityKinds:[],peopleScope:{kind:'unknown',value:null,min:null,max:null},professionalContext:{description:'ruolo attuale',current:true},eventTime:{description:null},support:{presence:null,continuity:null,mode:null,peopleScope:null,professionalContext:null,responsibilityKinds:[]},limitations:['no global negative']};r=await runGroqContinuingPeopleResponsibilitySemanticExecutor({evidence:evidence('Non ho riporti diretti nel ruolo attuale. Nei progetti coordino attività di colleghi di altri reparti.'),completionRunner:completion(contextual)});assert.equal(r.supported,true);assert.equal(r.candidate.responsibilityPresence,'contextual_non_responsibility');
const hallucinated={...base,support:{...base.support,presence:'coordino alcune persone',continuity:'coordino alcune persone',mode:'coordino alcune persone',peopleScope:'coordino alcune persone',professionalContext:'coordino alcune persone',responsibilityKinds:['coordino alcune persone','coordino alcune persone','coordino alcune persone']}};r=await runGroqContinuingPeopleResponsibilitySemanticExecutor({evidence:evidence('coordino alcune persone.'),completionRunner:completion(hallucinated)});assert.equal(r.supported,false);assert.equal(r.reason,'unsupported_candidate_support');
console.log('PDIR-11 production semantic adapter tests passed.');
