const assert=require('assert');
const {buildFhtLiveAcquisitionPurposePlanning,FHT_ACTIVE_KNOWLEDGE_GOALS}=require('../src/app/knowledge/buildFhtLiveAcquisitionPurposePlanning');
const now='2026-09-03T12:00:00.000Z',subjectRef={type:'person',id:'marco-controlled'};
const x=buildFhtLiveAcquisitionPurposePlanning({subjectRef,sessionKey:'fht-ap01-marco',now});
assert.deepEqual(x.activeGoals,['decision_accountability','quantified_outcome']);
assert.equal(x.personKnowledgeMatrix.summary.status,'empty');assert.equal(x.personKnowledgeMatrix.summary.totalStateCount,0);
for(const goal of x.activeGoals){const c=x.knowledgeCoverage.dimensionCoverage.find(d=>d.dimensionId===goal);assert(c);assert.equal(c.coverageState,'empty');assert.equal(c.totalStateCount,0);const p=x.purposes.find(v=>v.goal===goal);assert(p);assert.equal(p.opportunity.opportunityType,'active_goal_not_observed');assert.equal(p.opportunity.coverageState,'empty');assert.equal(p.need.requiredKnowledgeLayer,'elementary');assert.equal(p.requirement.requiredKnowledgeLayer,'elementary');assert.equal(p.design.targetKnowledge.scopeRef,goal);assert.equal(p.design.semanticPolicyRef,FHT_ACTIVE_KNOWLEDGE_GOALS[goal]);assert.equal(p.plan.sourceCapabilityConfigurationRef,`knowledgeAcquisitionCapabilityConfiguration:${p.capabilityConfiguration.id}`);assert.equal(p.runtimeSession.sourceKnowledgeAcquisitionPlanRef,`knowledgeAcquisitionPlan:${p.plan.id}`);assert.equal(p.runtimeSession.status,'created');assert.equal(p.runtimeSession.activePlanItemRef,null);assert(x.handoffItems.some(h=>h.goal===goal&&h.knowledgeAcquisitionDesignRef===`knowledgeAcquisitionDesign:${p.design.id}`));}
assert(Array.isArray(x.runtimeActionAssociations)&&x.runtimeActionAssociations.length>=6);const openingAssociation=x.runtimeActionAssociations.find(a=>a.runtimeActionRef==='interviewQuestion:opening_career_walkthrough');assert(openingAssociation);assert.deepEqual(openingAssociation.purposeRefs.map(r=>r.goal).sort(),['decision_accountability','quantified_outcome']);
for(const [key,goals] of [['achievement_quantification',['quantified_outcome']],['decision_tradeoff_probe',['decision_accountability']],['responsibility_probe',['decision_accountability']]]){const a=x.runtimeActionAssociations.find(v=>v.runtimeActionRef===`interviewQuestion:${key}`);assert(a);assert.deepEqual(a.purposeRefs.map(r=>r.goal),goals);}
for(const key of ['stakeholder_examples','transferability_probe','consistency_probe','leadership_depth','tool_adaptation'])assert(!x.runtimeActionAssociations.some(v=>v.runtimeActionRef===`interviewQuestion:${key}`));
assert(!JSON.stringify(x.runtimeActionAssociations).includes('semanticPolicyRef'));
assert.equal(new Set(x.purposes.map(p=>p.design.id)).size,2);assert.equal(new Set(x.purposes.map(p=>p.requirement.id)).size,2);assert.equal(new Set(x.handoffItems.map(h=>h.planItemRef)).size,2);
assert.throws(()=>buildFhtLiveAcquisitionPurposePlanning({subjectRef,activeGoals:['people_leadership'],sessionKey:'bad',now}),e=>e.code==='UNAUTHORIZED_FHT_ACTIVE_KNOWLEDGE_GOAL');
const json=JSON.stringify(x);assert(!/CandidateProfile|JobFit|answerText|expectedSignals|question category|percentage/i.test(json));
console.log('FHT-AP01 live acquisition purpose planning PASSED');
