import assert from 'node:assert/strict';
import { buildPrivateBetaSourceGroundedProjection } from '../src/app/buildPrivateBetaSourceGroundedProjection.js';
import { buildTargetIndependentProfessionalRepresentation } from '../src/app/buildTargetIndependentProfessionalRepresentation.js';
import { renderPrivateBetaUiJourneyHtml } from '../src/app/renderPrivateBetaUiJourneyHtml.js';
import { TARGET_INDEPENDENT_REPRESENTATION_RECIPE,buildTargetIndependentRepresentationSnapshotState,materializeTargetIndependentRepresentationSnapshot,attachRepresentationSnapshotToProfessionalIdentity,findReusableTargetIndependentRepresentationSnapshot } from '../src/app/privateBetaProfessionalRepresentationSnapshots.js';

const sources=[
{id:'current',sourceRole:'current_cv',content:'Production Supervisor. Operations / Manufacturing. Coordinamento produzione, performance e priorità.',provenance:{label:'Current CV'}},
{id:'previous',sourceRole:'previous_cv',content:'Industrialization Engineer. Industrializzazione e start-up. Partecipazione al lancio di una nuova linea produttiva in Germany, in collaborazione con engineering, produzione e qualità.',provenance:{label:'Previous CV'}},
{id:'atlas',sourceRole:'professional_declaration',content:'Nel progetto Atlas ho coordinato attività di ramp-up fornitore con supply chain, qualità e produzione, definendo priorità.',provenance:{label:'Added Experience'}},
{id:'maintenance',sourceRole:'professional_declaration',content:'Ho iniziato a coordinare le attività tra produzione e manutenzione durante interventi programmati. Non ho ancora risultati quantitativi consolidati.',provenance:{label:'Added Experience'}}];
const profiles=[
{sourceId:'current',sourceRole:'current_cv',candidateProfile:{currentPositioning:'Production Supervisor',summary:'Operations / Manufacturing',domainSignals:['Operations','Manufacturing'],careerSignals:{crossFunctionalCollaboration:'partial'},experienceSignals:{supportExcerpts:['Production Supervisor. Operations / Manufacturing. Coordinamento produzione, performance e priorità.']}}},
{sourceId:'previous',sourceRole:'previous_cv',candidateProfile:{currentPositioning:'Industrialization Engineer',summary:'Industrializzazione e start-up',domainSignals:['Industrialization','Manufacturing'],careerSignals:{crossFunctionalCollaboration:'partial'},experienceSignals:{highlights:['Partecipazione al lancio in Germany'],supportExcerpts:['Partecipazione al lancio di una nuova linea produttiva in Germany, in collaborazione con engineering, produzione e qualità.']}}},
{sourceId:'atlas',sourceRole:'professional_declaration',candidateProfile:{summary:'Ramp-up fornitore',careerSignals:{crossFunctionalCollaboration:'strong'},experienceSignals:{supportExcerpts:['Nel progetto Atlas ho coordinato attività di ramp-up fornitore con supply chain, qualità e produzione, definendo priorità.']}}},
{sourceId:'maintenance',sourceRole:'professional_declaration',candidateProfile:{summary:'Interventi programmati produzione/manutenzione',careerSignals:{crossFunctionalCollaboration:'strong'},experienceSignals:{supportExcerpts:['Ho iniziato a coordinare le attività tra produzione e manutenzione durante interventi programmati.']}}}];
const knowledge=[
{semanticType:'decision_accountability',semanticPolicyRef:'professional_semantic_policy:decision_accountability:v1',knowledgeRef:'ks-da',knowledgeSnapshot:{id:'ks-da'},observation:{observationType:'decision_accountability',observationStatus:'observed',observationId:'o-da',evidenceIds:['e-da'],decisionAuthority:'shared',consequenceScope:'team',accountabilityEvidence:'explicit_with_outcomes',context:{decision:'definire priorità nel progetto Atlas',responsibility:'coordinare azioni nel ramp-up del fornitore',consequence:'stabilizzazione operativa'},limitations:[]}},
{semanticType:'quantified_outcome',semanticPolicyRef:'professional_semantic_policy:quantified_outcome:v1',knowledgeRef:'ks-qo',knowledgeSnapshot:{id:'ks-qo'},observation:{observationType:'quantified_outcome',observationId:'o-qo',evidenceIds:['e-qo'],measurableOutcome:'miglioramento operativo',quantitativeValue:{value:20,unit:'percent',approximate:true},contributionRelationship:'contributed',causalityBoundary:'contribution_only',context:{event:'Atlas'},limitations:['contribution only']}}];
const projection=buildPrivateBetaSourceGroundedProjection({candidateSourceProfiles:profiles,professionalSources:sources});
const r=await buildTargetIndependentProfessionalRepresentation({professionalSources:sources,sourceGroundedProjection:projection,reusableKnowledgeResults:knowledge,useModel:false});
const m=r.professionalMeaning;
const pattern=m.supportedPatterns.find(x=>x.kind==='documented_cross_functional_coordination_recurrence');
assert(pattern,'distinct source-grounded experiences must support bounded recurrence');assert.equal(pattern.traitInference,false);assert(pattern.supportCount>=2);assert(pattern.sourceRefs.includes('atlas')&&pattern.sourceRefs.includes('maintenance'));assert.equal(new Set(pattern.episodeRefs).size,pattern.episodeRefs.length);
assert(m.professionalSynthesis.supportedPatternKinds.includes(pattern.kind));
const da=m.knowledgeContribution.find(x=>x.semanticType==='decision_accountability');const qo=m.knowledgeContribution.find(x=>x.semanticType==='quantified_outcome');
assert.equal(da.primaryProfessionalMeaning.kind,'bounded_decision_accountability');assert.match(da.primaryProfessionalMeaning.observedContext,/Atlas/i);assert.match(da.primaryProfessionalMeaning.personContribution,/ramp-up/i);assert(da.limitations.length>=1);
assert.equal(qo.primaryProfessionalMeaning.kind,'bounded_measurable_outcome_contribution');assert.match(qo.primaryProfessionalMeaning.quantification,/20/);assert(qo.limitations.length>=1);
assert.deepEqual(m.insufficientObservability,[]);assert.equal(r.target,null);
const json=JSON.stringify(r);assert.doesNotMatch(json,/stable leadership|stable coordination trait|competence score|readiness|target fit|professionaltrajectory/i);
const germany=r.supportingExperiences.find(x=>x.sourceId==='previous');assert.match(germany.summary,/Germany/i);assert.doesNotMatch(germany.summary,/gestito|guidato|coordinato il lancio/i);
// Duplicate representation of Atlas must not increase distinct episode support.
const dupSources=[...sources,{...sources[2],id:'atlas-copy'}];const dupProfiles=[...profiles,{...profiles[2],sourceId:'atlas-copy'}];const dupProj=buildPrivateBetaSourceGroundedProjection({candidateSourceProfiles:dupProfiles,professionalSources:dupSources});const dup=await buildTargetIndependentProfessionalRepresentation({professionalSources:dupSources,sourceGroundedProjection:dupProj,reusableKnowledgeResults:knowledge,useModel:false});const dupPattern=dup.professionalMeaning.supportedPatterns.find(x=>x.kind===pattern.kind);assert.equal(dupPattern.supportCount,pattern.supportCount);
const html=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'purpose_understand',preInterview:{targetIndependentProfessionalRepresentation:r,sourceGroundedProjection:projection,professionalIdentityContinuity:{recovered:true,reusedKnowledgeCount:2}}}});assert.match(html,/coordinamento tra funzioni ricorre in più esperienze/i);assert.match(html,/definire priorità nel progetto Atlas/i);assert.match(html,/20%/);const primaryKnowledge=html.split('<details class="professional-representation-support">')[0];assert.doesNotMatch(primaryKnowledge,/responsabilità decisionale circoscritta/i);
assert.equal(TARGET_INDEPENDENT_REPRESENTATION_RECIPE.version,'2.0');const pi={personRef:{type:'person',id:'pr05c'},professionalIdentityRef:'pi-pr05c',revision:4,representationSnapshots:[]};const oldState=buildTargetIndependentRepresentationSnapshotState({professionalIdentity:pi,professionalSources:sources,reusableKnowledgeResults:knowledge,recipe:{...TARGET_INDEPENDENT_REPRESENTATION_RECIPE,version:'1.5'}});const old=materializeTargetIndependentRepresentationSnapshot({professionalIdentity:pi,state:oldState,representation:r,now:'2026-09-10T10:00:00Z'});const withOld=attachRepresentationSnapshotToProfessionalIdentity({professionalIdentity:pi,snapshot:old});const state=buildTargetIndependentRepresentationSnapshotState({professionalIdentity:withOld,professionalSources:sources,reusableKnowledgeResults:knowledge});assert.equal(findReusableTargetIndependentRepresentationSnapshot({professionalIdentity:withOld,state}),null);const fresh=materializeTargetIndependentRepresentationSnapshot({professionalIdentity:withOld,state,representation:r,now:'2026-09-10T10:01:00Z'});assert.equal(fresh.changeCause,'representation_recipe_change');const withFresh=attachRepresentationSnapshotToProfessionalIdentity({professionalIdentity:withOld,snapshot:fresh});assert.equal(findReusableTargetIndependentRepresentationSnapshot({professionalIdentity:withFresh,state}).snapshotId,fresh.snapshotId);assert.equal(withFresh.representationSnapshots.length,2);assert.equal(withFresh.revision,4);
console.log('PR-05 corrective professional pattern and meaning-first composition: PASS');
