import assert from 'node:assert/strict';
import {materializeCandidateApplicationMaterial,materializeCandidateApplicationMaterials} from '../src/app/opportunityApplication/candidateArtifactLanguageMaterialization.js';
import {buildGroundedApplicationPackage,buildOpportunityUnderstanding,buildProtectedApplicationArtifacts} from '../src/app/opportunityApplication/groundedApplicationPackage.js';
import {loadPrivateBetaUiMessages} from '../src/i18n/loadPrivateBetaUiMessages.js';
const protect=(dimensions)=>({state:'established',dimensions,protectionProvenance:['p1']});
const material=(id,description,dimensions=[],kind='source_grounded_episode_meaning')=>({id,type:'candidate_application_material_item',materialKind:kind,authorisedPayload:{description},semanticProtection:protect(dimensions),languageTransformationEligibility:'eligible'});
const valid=async({input})=>({materialRef:input.materialRef,verdict:'VALID',violations:[]});
const run=async(m,out,validator=valid,maxAttempts=1)=>materializeCandidateApplicationMaterial({material:m,requestedLanguage:'en',maxAttempts,transformRunner:async({input})=>({materialRef:input.materialRef,transformedText:out}),validationRunner:validator});
let r=await run(material('p','Ha partecipato al lancio.',[{dimension:'agency',value:'participated'}]),'Led the launch.');assert.equal(r.status,'REJECTED');
r=await run(material('s','Responsabilità condivisa sul follow-up.',[{dimension:'responsibility_scope',value:'shared_non_exclusive'}]),'Shared responsibility for operational follow-up.');assert.equal(r.status,'VALID');
r=await run(material('s2','Responsabilità condivisa.',[{dimension:'responsibility_scope',value:'shared_non_exclusive'}]),'Solely responsible for follow-up.');assert.equal(r.status,'REJECTED');
const sharedIt=material('sit','Shared responsibility for follow-up.',[{dimension:'responsibility_scope',value:'shared_non_exclusive'}]);const itRejected=await materializeCandidateApplicationMaterial({material:sharedIt,requestedLanguage:'it',maxAttempts:1,transformRunner:async({input})=>({materialRef:input.materialRef,transformedText:'Responsabilità esclusiva per il follow-up.'}),validationRunner:valid});assert.equal(itRejected.status,'REJECTED');
const q={id:'q',type:'candidate_application_material_item',materialKind:'canonical_quantified_outcome',authorisedPayload:{representationText:'Il progetto ha registrato un miglioramento di circa 20%; contributo del candidato.',quantitativeValue:{value:20,unit:'percent',approximate:true},contributionRelationship:'contributed',causalityBoundary:'contribution_only'},semanticProtection:protect([{dimension:'agency',value:'contributed'},{dimension:'result_attribution',value:'contribution_only'},{dimension:'epistemic',value:'approximate_quantitative_value'}]),languageTransformationEligibility:'eligible'};
r=await run(q,'The project recorded approximately 20% improvement; the candidate contributed to the improvement activity.');assert.equal(r.status,'VALID');
r=await run(q,'The candidate achieved 20% improvement.');assert.equal(r.status,'REJECTED');
const raw={...material('raw','test'),semanticProtection:{state:'insufficiently_established',dimensions:[],protectionProvenance:[]},languageTransformationEligibility:'not_eligible'};r=await materializeCandidateApplicationMaterial({material:raw,requestedLanguage:'en'});assert.equal(r.status,'UNSUPPORTED');
r=await run(material('u','Unknown.',[{dimension:'epistemic',value:'unknown_not_established'}]),'Established capability.',async({input})=>({materialRef:input.materialRef,verdict:'UNSUPPORTED',violations:['cannot establish preservation']}));assert.equal(r.status,'UNSUPPORTED');
r=await materializeCandidateApplicationMaterial({material:material('fail','Partecipato.',[{dimension:'agency',value:'participated'}]),requestedLanguage:'en',maxAttempts:1,transformRunner:async()=>{throw new Error('provider')},validationRunner:valid});assert.equal(r.status,'UNSUPPORTED');
// Duplicate/equal source text remains ID-owned end to end in materialization.
const a=material('material-A','Stesso testo.',[{dimension:'agency',value:'participated'}]),b=material('material-B','Stesso testo.',[{dimension:'agency',value:'participated'}]);const many=await materializeCandidateApplicationMaterials({materials:[a,b],requestedLanguage:'en',transformRunner:async({input})=>({materialRef:input.materialRef,transformedText:input.materialRef==='material-A'?'Participated in activity A.':'Participated in activity B.'}),validationRunner:valid});assert.deepEqual(many.map(x=>x.materialRef),['material-A','material-B']);
// Controlled Marco-shaped technical fixture: protected Episode + shared scope, no raw generative input.
const rep={type:'target_independent_professional_representation',roleHistory:[{sourceId:'cv1',role:'Production Supervisor',status:'current'}],episodeMeanings:[{episodeMeaningId:'e1',sourceId:'cv1',description:'Ha partecipato al lancio della linea.',participation:'participated',activity:'line launch',object:'line',professionalContext:'production',limitations:['participation_not_ownership_or_management'],support:[{evidenceRef:'ev1'}]},{episodeMeaningId:'e2',sourceId:'cv1',description:'Responsabilità condivisa sul follow-up operativo.',participation:'contributed',activity:'follow-up',object:'operations',professionalContext:'production',responsibilityScope:{state:'shared_non_exclusive',referent:{id:'followup'},provenance:{sourceId:'cv1'}},limitations:[],support:[{evidenceRef:'ev2'}]}],professionalMeaning:{knowledgeContribution:[]}};
const identity={revision:1,professionalSources:[{id:'cv1',sourceRole:'current_cv',content:'Production Supervisor. Materiale legacy.'}],representationSnapshots:[{representation:rep}]};const before=JSON.stringify(identity);const u=buildOpportunityUnderstanding({opportunityText:'Production role with operational follow-up.',opportunityLabel:'Production role'});const pkg=buildGroundedApplicationPackage({professionalIdentity:identity,opportunityUnderstanding:u});const dictionary=new Map(pkg.candidateApplicationMaterials.filter(x=>x.languageTransformationEligibility==='eligible').map(x=>[x.id,x.materialKind==='professional_role'?'Production Supervisor':x.authorisedPayload.description.includes('condivisa')?'Shared responsibility for operational follow-up.':'Participated in the line launch.']));const arts=await buildProtectedApplicationArtifacts({applicationPackage:pkg,opportunityUnderstanding:u,documentLanguage:'en',messages:loadPrivateBetaUiMessages('en'),transformRunner:async({input})=>({materialRef:input.materialRef,transformedText:dictionary.get(input.materialRef)}),validationRunner:valid});assert(arts.targetedCv.content.includes('Participated in the line launch.'));assert(arts.targetedCv.content.includes('Shared responsibility for operational follow-up.'));assert(arts.coverLetter.content.includes('Participated in the line launch.')||arts.coverLetter.content.includes('Shared responsibility for operational follow-up.'));assert(!arts.targetedCv.content.includes('material-A'));assert.equal(JSON.stringify(identity),before);assert.deepEqual(arts.cvContentModel.languages,[]);const itDictionary=new Map(pkg.candidateApplicationMaterials.filter(x=>x.languageTransformationEligibility==='eligible').map(x=>[x.id,x.materialKind==='professional_role'?'Production Supervisor':x.authorisedPayload.description]));const itArts=await buildProtectedApplicationArtifacts({applicationPackage:pkg,opportunityUnderstanding:u,documentLanguage:'it',messages:loadPrivateBetaUiMessages('it'),transformRunner:async({input})=>({materialRef:input.materialRef,transformedText:itDictionary.get(input.materialRef)}),validationRunner:valid});assert.equal(itArts.documentLanguage,'it');assert.equal(JSON.stringify(identity),before);
// Non-manufacturing fixture proves generic structured operation.
const bio=material('bio','Ha collaborato alla validazione diagnostica.',[{dimension:'agency',value:'collaborated'}]);const br=await run(bio,'Collaborated on diagnostic validation.');assert.equal(br.status,'VALID');
console.log('CQ-05I protected Candidate artifact language materialization tests passed.');
