import assert from 'node:assert/strict';
import {createPrivateBetaUiServer} from '../src/app/privateBetaUiServer.js';
import {createMemoryPrivateBetaProfessionalIdentityStore,privateBetaPersonRefFromContext} from '../src/app/privateBetaProfessionalIdentityContinuity.js';
import {buildProfessionalProfileBackup,serializeProfessionalProfileBackup,validateProfessionalProfileBackup,restoreProfessionalProfileBackup,parseProfessionalProfileBackup} from '../src/app/privateBetaProfessionalProfileBackup.js';
import {buildOpportunityUnderstanding,buildGroundedApplicationPackage,buildApplicationArtifacts} from '../src/app/opportunityApplication/groundedApplicationPackage.js';
import {renderApplicationDocumentDocx} from '../src/app/opportunityApplication/renderApplicationDocx.js';
import {loadPrivateBetaUiMessages} from '../src/i18n/loadPrivateBetaUiMessages.js';
import {renderPrivateBetaUiJourneyHtml} from '../src/app/renderPrivateBetaUiJourneyHtml.js';

const sourcePerson=privateBetaPersonRefFromContext('pd088-source');
const sources=[{id:'current-cv',type:'text',sourceRole:'current_cv',content:'Production Supervisor, Alfa. 2022 - 2026. Coordinamento attività produttive.',metadata:{role:'Production Supervisor',organisation:'Alfa',period:'2022 - 2026'},provenance:{origin:'candidate'}}];
const k=(semanticType,n)=>({semanticType,semanticPolicyRef:`policy:${semanticType}`,knowledgeSnapshot:{id:`snapshot_${n}`,subjectRef:sourcePerson},knowledgeRef:`knowledgeSnapshot:snapshot_${n}`,sourceEvidenceRef:`evidence:${n}`});
const knowledge=[k('resource_budget_responsibility_scope',1),k('production_planning_scheduling_responsibility_scope',2)];
const identityBase={revision:4,professionalSources:sources,representationSnapshots:[]};
const u=buildOpportunityUnderstanding({opportunityText:'Production Manager\nResponsibilities:\nProduction planning and resource allocation.',opportunityLabel:'Production Manager',now:'2026-09-30T11:00:00Z'});
const pkg=buildGroundedApplicationPackage({professionalIdentity:identityBase,opportunityUnderstanding:u,documentData:{displayName:'Marco Rossi'},now:'2026-09-30T11:00:00Z'});
const arts=buildApplicationArtifacts({applicationPackage:pkg,opportunityUnderstanding:u,documentLanguage:'it',template:'essential',messages:loadPrivateBetaUiMessages('it')});
const record={version:'1.0',type:'private_beta_professional_identity_continuity',professionalIdentityRef:`professionalIdentity:${sourcePerson.id}`,personRef:sourcePerson,owner:'person',authorizedMaterials:{cvText:sources[0].content,userNotes:'Preferisco contesti industriali.'},professionalSources:sources,reusableKnowledgeResults:knowledge,knowledgeRefs:knowledge.map(x=>x.knowledgeRef),revision:4,createdAt:'2026-09-29T10:00:00Z',updatedAt:'2026-09-30T11:00:00Z',lastEnrichedBySessionRef:'session:old',representationSnapshots:[],currentRepresentationSnapshotRefs:{},candidateProfileDerivedPreparation:{providerCache:'must-not-export'},applicationState:{careerPreferenceContext:{candidateDeclared:true,preferenceState:'declared',preferredThemes:['operations']},opportunityUnderstanding:u,groundedApplicationPackage:pkg,applicationArtifacts:arts,transientDiagnostic:{provider:'x'}}};

const backup=buildProfessionalProfileBackup({record,exportedAt:'2026-09-30T11:30:00Z',locale:'it'});validateProfessionalProfileBackup(backup);const raw=serializeProfessionalProfileBackup(backup);assert.ok(raw.length>500);assert.equal(backup.schemaVersion,2);assert.equal(backup.payload.profile.professionalSources[0].content,sources[0].content);assert.equal(backup.payload.profile.reusableKnowledgeResults.length,2);assert.equal(backup.payload.profile.applicationState.careerPreferenceContext.preferredThemes[0],'operations');assert.ok(backup.payload.profile.applicationState.applicationArtifacts);assert.equal(backup.payload.profile.candidateProfileDerivedPreparation,undefined);assert.equal(backup.payload.profile.applicationState.transientDiagnostic,undefined);assert.doesNotMatch(raw.toString('latin1'),/session:old|providerCache/);assert.equal(parseProfessionalProfileBackup(raw).schemaVersion,2);
const destination=privateBetaPersonRefFromContext('pd088-destination'),restored=restoreProfessionalProfileBackup({backup,destinationPersonRef:destination,now:'2026-09-30T12:00:00Z'});assert.equal(restored.personRef.id,destination.id);assert.equal(restored.reusableKnowledgeResults.length,2);assert.equal(restored.reusableKnowledgeResults[0].knowledgeSnapshot.subjectRef.id,destination.id);assert.equal(restored.applicationState.careerPreferenceContext.preferredThemes[0],'operations');assert.ok(renderApplicationDocumentDocx({documentModel:restored.applicationState.applicationArtifacts.targetedCv.documentModel}).length>500);
const corrupted=structuredClone(backup);corrupted.payload.profile.authorizedMaterials.cvText+='X';assert.throws(()=>validateProfessionalProfileBackup(corrupted),/CORRUPTED/);const newer=structuredClone(backup);newer.schemaVersion=99;assert.throws(()=>validateProfessionalProfileBackup(newer),/NEWER_VERSION/);
const secretRecord=structuredClone(record);secretRecord.professionalSources[0].metadata.apiKey='sk-should-not-leak';assert.throws(()=>buildProfessionalProfileBackup({record:secretRecord}),/SECRET/);

const sourceStore=createMemoryPrivateBetaProfessionalIdentityStore();await sourceStore.save({record});let server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:sourceStore,contextIdFactory:()=> 'pd088-source'});await new Promise(r=>server.listen(0,'127.0.0.1',r));let base=`http://127.0.0.1:${server.address().port}`;let r=await fetch(base+'/private-beta/profile-backup/export',{headers:{cookie:'imago_beta_repeat_context=pd088-source'}});assert.equal(r.status,200);assert.match(r.headers.get('content-type'),/application\/vnd\.imago\.profile-backup/);assert.match(r.headers.get('content-disposition'),/\.imago/);const exported=Buffer.from(await r.arrayBuffer());await new Promise(r=>server.close(r));
const freshStore=createMemoryPrivateBetaProfessionalIdentityStore();server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:freshStore,contextIdFactory:()=> 'pd088-fresh'});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;const cookie='imago_beta_repeat_context=pd088-fresh';r=await fetch(base+'/private-beta/profile-backup/preview',{method:'POST',headers:{cookie,'content-type':'application/vnd.imago.profile-backup'},body:exported});assert.equal(r.status,200);let preview=await r.json();assert.equal(preview.requiresReplacementConfirmation,false);r=await fetch(base+'/private-beta/profile-backup/restore',{method:'POST',headers:{cookie,'content-type':'application/vnd.imago.profile-backup'},body:exported});assert.equal(r.status,200);const imported=await r.json();assert.equal(imported.restored,true);assert.ok(imported.continuityArtifact);const freshPerson=privateBetaPersonRefFromContext('pd088-fresh'),fresh=await freshStore.load({personRef:freshPerson});assert.equal(fresh.professionalSources[0].content,sources[0].content);assert.equal(fresh.reusableKnowledgeResults.length,2);assert.equal(fresh.applicationState.careerPreferenceContext.preferredThemes[0],'operations');
// Duplicate restore replaces the complete profile and does not duplicate canonical state.
r=await fetch(base+'/private-beta/profile-backup/restore',{method:'POST',headers:{cookie,'content-type':'application/vnd.imago.profile-backup','x-imago-confirm-restore':'replace'},body:exported});assert.equal(r.status,200);assert.equal((await freshStore.load({personRef:freshPerson})).reusableKnowledgeResults.length,2);
// Current profile conflict must not silently merge/replace.
r=await fetch(base+'/private-beta/profile-backup/restore',{method:'POST',headers:{cookie,'content-type':'application/vnd.imago.profile-backup'},body:exported});assert.equal(r.status,409);
await new Promise(r=>server.close(r));
// Subsequent server restart can rehydrate from the continuity artifact created by import.
const restartedStore=createMemoryPrivateBetaProfessionalIdentityStore();server=createPrivateBetaUiServer({locale:'it',professionalIdentityStore:restartedStore,contextIdFactory:()=> 'pd088-fresh'});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;r=await fetch(base+'/private-beta/continuity/restore',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify(imported.continuityArtifact)});assert.equal(r.status,204);assert.equal((await restartedStore.load({personRef:freshPerson})).reusableKnowledgeResults.length,2);await new Promise(r=>server.close(r));
const htmlIt=renderPrivateBetaUiJourneyHtml({locale:'it',result:{phase:'backup'},identityAvailable:true,identitySummary:{professionalSources:sources,reusableKnowledgeResults:knowledge,knowledgeCount:2}}),htmlEn=renderPrivateBetaUiJourneyHtml({locale:'en',result:{phase:'backup'}});assert.match(htmlIt,/Scarica backup del profilo/);assert.match(htmlIt,/Importa|ripristina|backup/i);assert.match(htmlEn,/profile backup/i);assert.match(htmlIt,/profile-backup\/export/);assert.match(htmlIt,/profile-backup\/preview/);assert.match(htmlIt,/X-IMAGO-Confirm-Restore/);
console.log('PD-088 Portable Professional Profile Backup: PASS');
