import assert from "assert";
import {createPrivateBetaUiServer} from "../src/app/privateBetaUiServer.js";
import {createMemoryPrivateBetaFeedbackStore,createJsonlPrivateBetaFeedbackStore,buildPrivateBetaContextualFeedbackRecord} from "../src/app/privateBetaContextualFeedback.js";
import {mkdtemp,rm} from "fs/promises";
import {tmpdir} from "os";
import {join} from "path";
import {renderPrivateBetaUiJourneyHtml} from "../src/app/renderPrivateBetaUiJourneyHtml.js";
const store=createMemoryPrivateBetaFeedbackStore(),now=()=>"2026-09-21T12:00:00.000Z";
const pi=Object.freeze({id:"pi:1",knowledge:Object.freeze([{id:"k1"}])}),before=JSON.stringify(pi);
const rec=buildPrivateBetaContextualFeedbackRecord({sessionRef:"S",personRef:{type:"person",id:"p"},purpose:"opportunity_application",checkpoint:"application_output",objectRef:"applicationPackage:1",uiLanguage:"it",artifactLanguage:"en",reaction:"missing",comment:"I actually managed 12 people",now});await store.append(rec);assert.equal(rec.comment,"I actually managed 12 people");assert.equal(rec.objectRef,"applicationPackage:1");assert.equal(rec.uiLanguage,"it");assert.equal(rec.artifactLanguage,"en");assert.equal(JSON.stringify(pi),before);for(const forbidden of ["cv","jd","professionalIdentity","knowledge","applicationPackage","coverLetter"])assert.equal(forbidden in rec,false);
const rep={phase:"purpose_understand",sessionRef:"S",preInterview:{targetIndependentProfessionalRepresentation:{id:"representation:1",claims:[]},sourceGroundedProjection:[]}};const dir={phase:"purpose_direction_explore",sessionRef:"S",preInterview:{careerDirectionEvaluation:{professionalRepresentationRef:"representation:1",hypotheses:[]},directionResolutions:[]}};const app={phase:"purpose_opportunity_application",opportunityApplication:{opportunityUnderstanding:{opportunityRef:"opp:1",label:"Role",responsibilities:[],requirements:[],preferredRequirements:[],constraints:[],unclassified:[],source:{content:"JD"}},groundedApplicationPackage:{packageRef:"pkg:1",targetRelativeInformationMap:[],documentCompletenessState:{needs:[]},professionalHistory:[],candidateDocumentData:{}},applicationArtifacts:{template:"essential",documentLanguage:"en",cvContentModel:{identity:{}},targetedCv:{content:"CV"},coverLetter:{content:"Letter"}}}};
for(const locale of ["it","en"]){const h1=renderPrivateBetaUiJourneyHtml({locale,result:rep}),h2=renderPrivateBetaUiJourneyHtml({locale,result:dir}),h3=renderPrivateBetaUiJourneyHtml({locale,result:app});for(const html of [h1,h2,h3]){assert.doesNotMatch(html,/class="contextual-feedback"/);assert.match(html,/id="imago-beta-feedback-open"/);}assert.doesNotMatch(h2,/checkpoint" value="career_direction/);assert.doesNotMatch(h1,/checkpoint" value="professional_representation/);assert.doesNotMatch(h3,/checkpoint" value="application_output/);}
const interview=renderPrivateBetaUiJourneyHtml({locale:"it",result:{phase:"interview",sessionRef:"S",currentQuestion:{question:"Q"}}});assert.doesNotMatch(interview,/contextual-feedback/);
const server=createPrivateBetaUiServer({feedbackStore:store,feedbackConsentStore:new Map([["ctx-fixed",true]]),operatorDiagnosticsEnabled:true,contextIdFactory:()=>"ctx-fixed"});await new Promise(r=>server.listen(0,"127.0.0.1",r));const base=`http://127.0.0.1:${server.address().port}`;const post=()=>fetch(base+"/private-beta/contextual-feedback",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({checkpoint:"application_output",objectRef:"pkg:2",purpose:"opportunity_application",artifactLanguage:"en",reaction:"useful",comment:"helpful"})});assert.equal((await post()).status,204);assert.equal((await post()).status,204);const all=await store.list({contextRef:"ctx-fixed"});assert.equal(all.length,1);assert.equal(all[0].checkpoint,"application_output");assert.equal(all[0].comment,"helpful");let r=await fetch(base+"/private-beta/operator/feedback?contextRef=ctx-fixed");assert.equal(r.status,200);assert.equal((await r.json()).feedback.length,1);await new Promise(r=>server.close(r));
const root=await mkdtemp(join(tmpdir(),"imago-fb01-")),fileStore=createJsonlPrivateBetaFeedbackStore({filePath:join(root,"feedback.jsonl")});await fileStore.append(rec);const reopened=createJsonlPrivateBetaFeedbackStore({filePath:join(root,"feedback.jsonl")});assert.equal((await reopened.list({sessionRef:"S"})).length,1);await rm(root,{recursive:true,force:true});
const gated=createPrivateBetaUiServer({feedbackStore:store,operatorDiagnosticsEnabled:false});await new Promise(r=>gated.listen(0,"127.0.0.1",r));r=await fetch(`http://127.0.0.1:${gated.address().port}/private-beta/operator/feedback`);assert.equal(r.status,404);await new Promise(r=>gated.close(r));
console.log("FB-01 Candidate-facing Private Beta feedback: PASS");
