const PRESENCE=['supported','contextual_non_responsibility','insufficient'];
const CONTINUITY=['temporary','recurring','continuing','insufficient'];
const MODES=['matrix_or_dotted_line','informal_operational','temporary_assignment','insufficient'];
const KINDS=['work_assignment_or_priority_setting','workload_shift_or_schedule_coordination','performance_follow_up_or_feedback'];
const obj=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const str=v=>typeof v==='string'&&Boolean(v.trim());
const nullableString={anyOf:[{type:'string'},{type:'null'}]};
const SUPPORT_SCHEMA={type:'object',properties:{presence:nullableString,continuity:nullableString,mode:nullableString,peopleScope:nullableString,professionalContext:nullableString,responsibilityKinds:{type:'array',items:{type:'string'}}},required:['presence','continuity','mode','peopleScope','professionalContext','responsibilityKinds'],additionalProperties:false};
const CONTINUING_PEOPLE_RESPONSIBILITY_SEMANTIC_CANDIDATE_SCHEMA=Object.freeze({type:'object',properties:{interpretationStatus:{type:'string',enum:['SUPPORTED','UNSUPPORTED']},responsibilityPresence:{type:'string',enum:PRESENCE},continuity:{type:'string',enum:CONTINUITY},responsibilityMode:{type:'string',enum:MODES},responsibilityKinds:{type:'array',items:{type:'string',enum:KINDS}},peopleScope:{type:'object',properties:{kind:{type:'string',enum:['exact','range','category','unknown']},value:{anyOf:[{type:'integer',minimum:1},{type:'string'},{type:'null'}]},min:{anyOf:[{type:'integer',minimum:1},{type:'null'}]},max:{anyOf:[{type:'integer',minimum:1},{type:'null'}]}},required:['kind','value','min','max'],additionalProperties:false},professionalContext:{type:'object',properties:{description:nullableString,current:{anyOf:[{type:'boolean'},{type:'null'}]}},required:['description','current'],additionalProperties:false},eventTime:{type:'object',properties:{description:nullableString},required:['description'],additionalProperties:false},support:SUPPORT_SCHEMA,limitations:{type:'array',items:{type:'string'}}},required:['interpretationStatus','responsibilityPresence','continuity','responsibilityMode','responsibilityKinds','peopleScope','professionalContext','eventTime','support','limitations'],additionalProperties:false});
function validateContinuingPeopleResponsibilityProductionSemanticCandidate(c={}){const e=[];if(!obj(c))return{isValid:false,errors:['semantic candidate must be an object.']};const allowed=['interpretationStatus','responsibilityPresence','continuity','responsibilityMode','responsibilityKinds','peopleScope','professionalContext','eventTime','support','limitations'];Object.keys(c).filter(k=>!allowed.includes(k)).forEach(k=>e.push(`unauthorized semantic candidate field: ${k}.`));if(!['SUPPORTED','UNSUPPORTED'].includes(c.interpretationStatus))e.push('interpretationStatus is invalid.');if(!PRESENCE.includes(c.responsibilityPresence)||!CONTINUITY.includes(c.continuity)||!MODES.includes(c.responsibilityMode))e.push('bounded responsibility semantics are invalid.');if(!Array.isArray(c.responsibilityKinds)||c.responsibilityKinds.some(x=>!KINDS.includes(x)))e.push('responsibilityKinds are invalid.');if(!obj(c.peopleScope)||!['exact','range','category','unknown'].includes(c.peopleScope.kind))e.push('peopleScope is invalid.');if(c.peopleScope?.kind==='exact'&&(!Number.isInteger(c.peopleScope.value)||c.peopleScope.value<1))e.push('exact peopleScope is invalid.');if(c.peopleScope?.kind==='range'&&(!Number.isInteger(c.peopleScope.min)||!Number.isInteger(c.peopleScope.max)||c.peopleScope.min<1||c.peopleScope.max<c.peopleScope.min))e.push('range peopleScope is invalid.');if(!obj(c.professionalContext)||!obj(c.eventTime)||!obj(c.support)||!Array.isArray(c.limitations))e.push('candidate structure is invalid.');if(c.interpretationStatus==='SUPPORTED'&&c.responsibilityPresence==='supported'){if(!str(c.support?.presence))e.push('supported presence requires Evidence support.');if(['recurring','continuing','temporary'].includes(c.continuity)&&!str(c.support?.continuity))e.push('continuity requires Evidence support.');if(c.responsibilityMode!=='insufficient'&&!str(c.support?.mode))e.push('mode requires Evidence support.');if(c.peopleScope?.kind!=='unknown'&&!str(c.support?.peopleScope))e.push('people scope requires Evidence support.');if(c.responsibilityKinds.length&&(!Array.isArray(c.support?.responsibilityKinds)||c.support.responsibilityKinds.length<c.responsibilityKinds.length))e.push('responsibility kinds require Evidence support.');if(!str(c.professionalContext?.description)||!str(c.support?.professionalContext))e.push('professional context requires Evidence support.');}return{isValid:e.length===0,errors:e};}
function supportIsVerbatim(candidate,text){const hay=String(text||'').toLocaleLowerCase('it');const kindSupports=(candidate.support?.responsibilityKinds||[]).filter(str);const vals=[candidate.support?.presence,candidate.support?.continuity,candidate.support?.mode,candidate.support?.peopleScope,candidate.support?.professionalContext,...kindSupports].filter(str);if(!vals.every(x=>hay.includes(x.trim().toLocaleLowerCase('it'))))return false;if(kindSupports.length!==new Set(kindSupports.map(x=>x.trim().toLocaleLowerCase('it'))).size)return false;if(candidate.peopleScope?.kind==='exact'&&!String(candidate.support?.peopleScope||'').includes(String(candidate.peopleScope.value)))return false;if(['temporary','recurring','continuing'].includes(candidate.continuity)&&candidate.eventTime?.description&&!hay.includes(candidate.eventTime.description.trim().toLocaleLowerCase('it')))return false;return true;}
function candidateToObservationInput(c){return{responsibilityPresence:c.responsibilityPresence,continuity:c.continuity,responsibilityMode:c.responsibilityMode,responsibilityKinds:c.responsibilityKinds,peopleScope:c.peopleScope.kind==='exact'?{kind:'exact',value:c.peopleScope.value}:c.peopleScope.kind==='range'?{kind:'range',min:c.peopleScope.min,max:c.peopleScope.max}:c.peopleScope.kind==='category'?{kind:'category',value:String(c.peopleScope.value||'').trim()}:{kind:'unknown'},professionalContext:{description:c.professionalContext.description,current:c.professionalContext.current},eventTime:c.eventTime?.description?{description:c.eventTime.description}:null,limitations:c.limitations};}
module.exports={CONTINUING_PEOPLE_RESPONSIBILITY_SEMANTIC_CANDIDATE_SCHEMA,validateContinuingPeopleResponsibilityProductionSemanticCandidate,supportIsVerbatim,candidateToObservationInput};
