module.exports={
 buildKnowledgeAcquisitionSolutionDecision:require('./buildKnowledgeAcquisitionSolutionDecision').buildKnowledgeAcquisitionSolutionDecision,
 validateKnowledgeAcquisitionSolutionDecision:require('./validateKnowledgeAcquisitionSolutionDecision').validateKnowledgeAcquisitionSolutionDecision,
 healthKnowledgeAcquisitionSolutionDecision:require('./healthKnowledgeAcquisitionSolutionDecision').healthKnowledgeAcquisitionSolutionDecision
};
