import knowledgeDecisionApi from './index.js';
export const buildKnowledgeAcquisitionSolutionDecision=knowledgeDecisionApi.buildKnowledgeAcquisitionSolutionDecision;
export const validateKnowledgeAcquisitionSolutionDecision=knowledgeDecisionApi.validateKnowledgeAcquisitionSolutionDecision;
export const healthKnowledgeAcquisitionSolutionDecision=knowledgeDecisionApi.healthKnowledgeAcquisitionSolutionDecision;
export const buildKnowledgeAcquisitionCapabilityConfiguration=knowledgeDecisionApi.buildKnowledgeAcquisitionCapabilityConfiguration;
export const validateKnowledgeAcquisitionCapabilityConfiguration=knowledgeDecisionApi.validateKnowledgeAcquisitionCapabilityConfiguration;
export const validateKnowledgeAcquisitionCapabilityConfigurationContext=knowledgeDecisionApi.validateKnowledgeAcquisitionCapabilityConfigurationContext;
export const healthKnowledgeAcquisitionCapabilityConfiguration=knowledgeDecisionApi.healthKnowledgeAcquisitionCapabilityConfiguration;
