const {calculateKnowledgeAcquisitionExecutionId}=require('./knowledgeAcquisitionExecutionIdentity');
const {stableStringify}=require('./knowledgeAcquisitionCapabilityConfigurationIdentity');
const TOP=['id','executionVersion','type','sourceRuntimeSessionRef','sourcePlanRef','sourcePlanItemRef','executionKey','status','selectedUnit','readiness','lifecycle','provenance','dependencyRefs','metadata','extensions'];
const STATUSES=['created','selected','ready_for_invocation'];
const FORBIDDEN=new Set(['provider','adapter','registry','endpoint','url','request','response','apiKey','prompt','model','transport','callback','webhook','retry','timeout','result','outcome','failure','persistence','event','knowledgeUpdate','knowledgeBase']);
function obj(v){return v!==null&&typeof v==='object'&&!Array.isArray(v)}function str(v){return typeof v==='string'&&v.trim().length>0}function exact(v,k){return obj(v)&&Object.keys(v).every(x=>k.includes(x))&&k.every(x=>x in v)}function iso(v){return typeof v==='string'&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString()===v}function ni(v){return v===null||iso(v)}function forbidden(v){if(Array.isArray(v))return v.some(forbidden);if(!obj(v))return false;return Object.entries(v).some(([k,x])=>FORBIDDEN.has(k)||forbidden(x))}
function validateKnowledgeAcquisitionExecution(x){const errors=[],warnings=[];if(!obj(x))return{valid:false,errors:['KnowledgeAcquisitionExecution must be an object.'],warnings};for(const k of TOP)if(!(k in x))errors.push(`Missing property: ${k}.`);for(const k of Object.keys(x))if(!TOP.includes(k))errors.push(`knowledgeAcquisitionExecution.${k} is not allowed.`);
 if(!str(x.id)||!x.id.startsWith('knowledgeAcquisitionExecution_'))errors.push('id is invalid.');if(x.executionVersion!=='1.0')errors.push('executionVersion is invalid.');if(x.type!=='knowledge_acquisition_execution')errors.push('type is invalid.');if(!str(x.sourceRuntimeSessionRef)||!x.sourceRuntimeSessionRef.startsWith('knowledgeAcquisitionRuntimeSession:'))errors.push('sourceRuntimeSessionRef is invalid.');if(!str(x.sourcePlanRef)||!x.sourcePlanRef.startsWith('knowledgeAcquisitionPlan:'))errors.push('sourcePlanRef is invalid.');if(!str(x.sourcePlanItemRef)||!str(x.executionKey))errors.push('Execution causality is invalid.');if(!STATUSES.includes(x.status))errors.push('status is invalid.');
 if(x.status==='created'&&x.selectedUnit!==null)errors.push('created execution cannot have a selected unit.');if(x.status!=='created'&&(!exact(x.selectedUnit,['sourcePlanItemRef'])||x.selectedUnit.sourcePlanItemRef!==x.sourcePlanItemRef))errors.push('selectedUnit is invalid.');
 if(!exact(x.readiness,['readyForInvocation'])||x.readiness.readyForInvocation!==(x.status==='ready_for_invocation'))errors.push('readiness is inconsistent with status.');
 if(!exact(x.lifecycle,['createdAt','updatedAt','selectedAt','readyForInvocationAt'])||!iso(x.lifecycle?.createdAt)||!iso(x.lifecycle?.updatedAt)||!ni(x.lifecycle?.selectedAt)||!ni(x.lifecycle?.readyForInvocationAt))errors.push('lifecycle is invalid.');else{const l=x.lifecycle;if(Date.parse(l.updatedAt)<Date.parse(l.createdAt))errors.push('lifecycle.updatedAt precedes createdAt.');if(x.status==='created'&&(l.selectedAt!==null||l.readyForInvocationAt!==null))errors.push('created lifecycle is inconsistent.');if(x.status==='selected'&&(l.selectedAt===null||l.readyForInvocationAt!==null))errors.push('selected lifecycle is inconsistent.');if(x.status==='ready_for_invocation'&&(l.selectedAt===null||l.readyForInvocationAt===null))errors.push('ready lifecycle is inconsistent.');}
 if(!exact(x.provenance,['type','producerVersion','deterministic','interpretive'])||x.provenance.type!=='knowledge_acquisition_execution_snapshot'||x.provenance.producerVersion!=='1.0'||x.provenance.deterministic!==true||x.provenance.interpretive!==false)errors.push('provenance is invalid.');const deps=[x.sourceRuntimeSessionRef,x.sourcePlanRef,x.sourcePlanItemRef].sort();if(!Array.isArray(x.dependencyRefs)||stableStringify(x.dependencyRefs)!==stableStringify(deps))errors.push('dependencyRefs are invalid.');if(!exact(x.metadata,['contractVersion','readOnly','sideEffectFree'])||x.metadata.contractVersion!=='1.0'||x.metadata.readOnly!==true||x.metadata.sideEffectFree!==true)errors.push('metadata is invalid.');if(!obj(x.extensions))errors.push('extensions must be an object.');if(forbidden(x))errors.push('Execution contains forbidden downstream or integration structure.');try{JSON.stringify(x)}catch{errors.push('KnowledgeAcquisitionExecution must be serializable.')}if(TOP.every(k=>k in x)&&str(x.id))try{if(x.id!==calculateKnowledgeAcquisitionExecutionId(x))errors.push('id does not match the stable execution identity.')}catch{errors.push('id cannot be calculated.')}return{valid:errors.length===0,errors,warnings}}
module.exports={validateKnowledgeAcquisitionExecution,EXECUTION_STATUSES:STATUSES};
