const {calculateKnowledgeAcquisitionPlanId}=require('./knowledgeAcquisitionPlanIdentity');
const {stableStringify}=require('./knowledgeAcquisitionCapabilityConfigurationIdentity');
const TOP=['id','planVersion','type','sourceCapabilityConfigurationRef','sourceCompositionDesignRef','decisionMode','selectedCapabilityRefs','planScope','planItems','planDependencies','provenance','dependencyRefs','metadata','extensions'];
const ITEM=['planItemRef','capabilityRef','configurationItemRefs','compositionRoleAssignmentRef'];
const DEP=['planDependencyRef','dependentPlanItemRef','prerequisitePlanItemRefs','dependencyMode','sourceLogicalDependencyRef'];
const FORBIDDEN=new Set(['provider','adapter','registry','dispatch','queue','job','progress','status','credentials','endpoint','payload','prompt','model','token','invocation','execution','runtime','scheduler','schedule','scheduling','priority','sequence','step','retry','timeout','result','results','report','reporting','satisfaction','knowledgeUpdate','persistence']);
function obj(v){return v!==null&&typeof v==='object'&&!Array.isArray(v)}function str(v){return typeof v==='string'&&v.trim().length>0}function exact(v,k){return obj(v)&&Object.keys(v).every(x=>k.includes(x))&&k.every(x=>x in v)}function su(v){return Array.isArray(v)&&v.every(str)&&new Set(v).size===v.length&&stableStringify(v)===stableStringify([...v].sort())}function forbidden(v){if(Array.isArray(v))return v.some(forbidden);if(!obj(v))return false;return Object.entries(v).some(([k,x])=>FORBIDDEN.has(k)||forbidden(x))}
function validateKnowledgeAcquisitionPlan(p){const errors=[],warnings=[];if(!obj(p))return{valid:false,errors:['KnowledgeAcquisitionPlan must be an object.'],warnings};for(const k of TOP)if(!(k in p))errors.push(`Missing property: ${k}.`);for(const k of Object.keys(p))if(!TOP.includes(k))errors.push(`knowledgeAcquisitionPlan.${k} is not allowed.`);
 if(!str(p.id)||!p.id.startsWith('knowledgeAcquisitionPlan_'))errors.push('id is invalid.');if(p.planVersion!=='1.0')errors.push('planVersion is invalid.');if(p.type!=='knowledge_acquisition_plan')errors.push('type is invalid.');if(!str(p.sourceCapabilityConfigurationRef)||!p.sourceCapabilityConfigurationRef.startsWith('knowledgeAcquisitionCapabilityConfiguration:'))errors.push('sourceCapabilityConfigurationRef is invalid.');if(!['single','composed'].includes(p.decisionMode))errors.push('decisionMode is invalid.');if(p.decisionMode==='single'&&p.sourceCompositionDesignRef!==null)errors.push('single mode cannot reference Composition Design.');if(p.decisionMode==='composed'&&(!str(p.sourceCompositionDesignRef)||!p.sourceCompositionDesignRef.startsWith('knowledgeAcquisitionCapabilityCompositionDesign:')))errors.push('composed mode requires Composition Design.');if(!su(p.selectedCapabilityRefs)||(p.decisionMode==='single'&&p.selectedCapabilityRefs?.length!==1)||(p.decisionMode==='composed'&&p.selectedCapabilityRefs?.length<2))errors.push('selectedCapabilityRefs are invalid.');
 if(!exact(p.planScope,['kind','capabilityRefs'])||p.planScope.kind!=='selected_capabilities'||stableStringify(p.planScope.capabilityRefs)!==stableStringify(p.selectedCapabilityRefs))errors.push('planScope is invalid.');
 const refs=new Set(),caps=new Set();if(!Array.isArray(p.planItems)||p.planItems.length!==p.selectedCapabilityRefs?.length)errors.push('planItems must contain exactly one item per selected capability.');else for(const [i,x]of p.planItems.entries()){if(!exact(x,ITEM)||!str(x.planItemRef)||!p.selectedCapabilityRefs.includes(x.capabilityRef)||caps.has(x.capabilityRef)||!su(x.configurationItemRefs)||(p.decisionMode==='single'&&x.compositionRoleAssignmentRef!==null)||(p.decisionMode==='composed'&&!str(x.compositionRoleAssignmentRef))){errors.push(`planItems[${i}] is invalid.`);continue}caps.add(x.capabilityRef);refs.add(x.planItemRef)}if(stableStringify((p.planItems||[]).map(x=>x.capabilityRef))!==stableStringify(p.selectedCapabilityRefs))errors.push('planItems are not canonically ordered.');
 const depKeys=new Set();if(!Array.isArray(p.planDependencies)||(p.decisionMode==='single'&&p.planDependencies.length))errors.push('planDependencies are invalid.');else for(const [i,x]of p.planDependencies.entries()){if(!exact(x,DEP)||!str(x.planDependencyRef)||depKeys.has(x.planDependencyRef)||!refs.has(x.dependentPlanItemRef)||!su(x.prerequisitePlanItemRefs)||!x.prerequisitePlanItemRefs.length||x.prerequisitePlanItemRefs.includes(x.dependentPlanItemRef)||!x.prerequisitePlanItemRefs.every(r=>refs.has(r))||!['all_required','any_required'].includes(x.dependencyMode)||x.sourceLogicalDependencyRef!==x.planDependencyRef)errors.push(`planDependencies[${i}] is invalid.`);depKeys.add(x.planDependencyRef)}if(stableStringify(p.planDependencies)!==stableStringify([...(p.planDependencies||[])].sort((a,b)=>String(a.planDependencyRef).localeCompare(String(b.planDependencyRef)))))errors.push('planDependencies are not canonically ordered.');
 if(!exact(p.provenance,['type','producerVersion','deterministic','interpretive'])||p.provenance.type!=='knowledge_acquisition_plan_derivation'||p.provenance.producerVersion!=='1.0'||p.provenance.deterministic!==true||p.provenance.interpretive!==false)errors.push('provenance is invalid.');if(!su(p.dependencyRefs)||![p.sourceCapabilityConfigurationRef,...(p.sourceCompositionDesignRef?[p.sourceCompositionDesignRef]:[]),...(p.selectedCapabilityRefs||[])].every(x=>p.dependencyRefs.includes(x)))errors.push('dependencyRefs are invalid.');if(!exact(p.metadata,['contractVersion','planStrategyVersion','readOnly'])||p.metadata.contractVersion!=='1.0'||p.metadata.planStrategyVersion!=='1.0'||p.metadata.readOnly!==true)errors.push('metadata is invalid.');if(!obj(p.extensions))errors.push('extensions must be an object.');if(forbidden(p))errors.push('Plan contains forbidden operational structure.');try{JSON.stringify(p)}catch{errors.push('KnowledgeAcquisitionPlan must be serializable.')}if(TOP.every(k=>k in p)&&str(p.id))try{if(p.id!==calculateKnowledgeAcquisitionPlanId(p))errors.push('id does not match the deterministic content fingerprint.')}catch{errors.push('id fingerprint cannot be calculated.')}return{valid:errors.length===0,errors,warnings}}
module.exports={validateKnowledgeAcquisitionPlan};
