import { loadProfessionalRepresentationSynthesisMessages } from '../i18n/loadProfessionalRepresentationSynthesisMessages.js';
function arr(v){return Array.isArray(v)?v:[];} function txt(v){return typeof v==='string'?v.trim():'';}
function freeze(v){if(Array.isArray(v)){v.forEach(freeze);return Object.freeze(v);}if(v&&typeof v==='object'){Object.values(v).forEach(freeze);return Object.freeze(v);}return v;}
function tpl(s,v={}){return txt(s).replace(/\{([A-Za-z0-9_]+)\}/g,(_,k)=>String(v[k]??''));}
function quantity(q,m){if(!q||typeof q.value!=='number'||!Number.isFinite(q.value))return '';const unit=q.unit==='percent'?m.unit_percent:'';if(!unit)return '';return `${q.approximate===true?m.approximatePrefix:''}${q.value}${unit}`;}
function refs(item){return [txt(item.sourceRef),...arr(item.evidenceIds).map(txt)].filter(Boolean);}
function cleanContext(context,keys){const out={};for(const k of keys){const v=txt(context?.[k]);if(v)out[k]=v;}return out;}
function cleanContinuity(v){if(!v||typeof v!=='object')return {state:'unknown'};if(v.state!=='known')return {state:'unknown'};const out={state:'known',qualification:txt(v.qualification)||null};for(const k of ['months','minimumMonths','maximumMonths'])if(typeof v[k]==='number'&&Number.isFinite(v[k]))out[k]=v[k];return out;}
export function buildProfessionalRepresentationSynthesisInput({authorizedSemanticMaterial=[],locale='it'}={}){
 const units=[];
 for(const [i,item] of arr(authorizedSemanticMaterial).entries()){
  const supportRef=txt(item?.sourceRef), evidenceRefs=arr(item?.evidenceIds).map(txt).filter(Boolean); if(!supportRef||!evidenceRefs.length)continue;
  if(item?.semanticType==='decision_accountability') units.push(freeze({id:`semantic_unit_da_${i}`,semanticType:'decision_accountability',epistemicState:'observed',facts:{decisionAuthority:item.decisionAuthority??null,consequenceScope:item.consequenceScope??null,accountabilityEvidence:item.accountabilityEvidence??null,responsibilityContinuity:cleanContinuity(item.responsibilityContinuity)},context:cleanContext(item.context,['decision','responsibility','consequence']),limitations:arr(item.limitations),confidenceState:item.confidenceState??null,inferenceSupport:item.inferenceSupport??null,semanticSupportRef:supportRef,evidenceRefs,provenance:{scope:'current_session',knowledgeRef:txt(item.sourceRef)}}));
  if(item?.semanticType==='quantified_outcome') units.push(freeze({id:`semantic_unit_qo_${i}`,semanticType:'quantified_outcome',epistemicState:'observed',facts:{measurableOutcome:txt(item.measurableOutcome),quantitativeValue:item.quantitativeValue||null,contributionRelationship:txt(item.contributionRelationship),causalityBoundary:txt(item.causalityBoundary)},context:cleanContext(item.context,['event','metric','comparison','monitoring']),limitations:arr(item.limitations),confidenceState:item.confidenceState??null,inferenceSupport:item.inferenceSupport??null,semanticSupportRef:supportRef,evidenceRefs,provenance:{scope:'current_session',knowledgeRef:txt(item.sourceRef)}}));
  if(item?.semanticType==='continuing_people_responsibility') units.push(freeze({id:`semantic_unit_cpr_${i}`,semanticType:'continuing_people_responsibility',epistemicState:'observed',facts:{responsibilityPresence:txt(item.responsibilityPresence),continuity:txt(item.continuity),responsibilityMode:txt(item.responsibilityMode),responsibilityKinds:arr(item.responsibilityKinds).map(txt).filter(Boolean),peopleScope:item.peopleScope||{kind:'unknown'}},context:item.professionalContext&&typeof item.professionalContext==='object'?item.professionalContext:{},limitations:arr(item.limitations),confidenceState:null,inferenceSupport:null,semanticSupportRef:supportRef,evidenceRefs,provenance:{scope:'reusable_person_knowledge',knowledgeRef:txt(item.sourceRef)}}));
 }
 return freeze({type:'professional_representation_synthesis_input',version:'1.1',profileRef:loadProfessionalRepresentationSynthesisMessages(locale).profileRef,locale,semanticUnits:units,targetMaterial:null});
}
function decisionEvidence(unit,m){const a=m[`decisionAuthority_${unit?.facts?.decisionAuthority}`]||m.decisionAuthority_shared,sc=m[`decisionScope_${unit?.facts?.consequenceScope}`]||m.decisionScope_individual;return tpl(m.decisionEvidencePattern,{authority:a,scope:sc});}
function decisionContext(unit,m){const c=unit?.context||{};const parts=[];if(txt(c.decision))parts.push(tpl(m.decisionContextDecision,{context:c.decision}));if(txt(c.responsibility))parts.push(tpl(m.decisionContextResponsibility,{context:c.responsibility}));if(txt(c.consequence))parts.push(tpl(m.decisionContextConsequence,{context:c.consequence}));return parts.join(m.contextSeparator);}
function outcomeContext(){return '';}
function peopleScopeText(scope,m){if(scope?.kind==='exact')return tpl(m.peopleScopeExact,{count:scope.value});if(scope?.kind==='range')return tpl(m.peopleScopeRange,{min:scope.min,max:scope.max});if(scope?.kind==='category')return tpl(m.peopleScopeCategory,{scope:scope.value});return '';}
function professionalContextText(context){return txt(context?.description||context?.domain||context?.context||context?.area||context?.department);}
function detail(kind,value){const v=txt(value);return v?freeze({kind,value:v}):null;}
function semanticDetails(unit,m){const d=[];if(unit?.semanticType==='decision_accountability'){const c=unit.context||{};d.push(detail('observed_context',c.decision),detail('person_contribution',c.responsibility));const authority=m[`decisionAuthority_${unit.facts?.decisionAuthority}`]||'',scope=m[`decisionScope_${unit.facts?.consequenceScope}`]||'';if(authority||scope)d.push(detail('responsibility_boundary',tpl(m.responsibilityBoundaryPattern,{authority,scope})));d.push(detail('outcome',c.consequence));}else if(unit?.semanticType==='quantified_outcome'){const amount=quantity(unit.facts?.quantitativeValue,m);d.push(detail('quantification',amount));const contribution=m[`contribution_${unit.facts?.contributionRelationship}`]||'';if(contribution)d.push(detail('person_contribution',tpl(m.contributionBoundaryPattern,{contribution})));}else if(unit?.semanticType==='continuing_people_responsibility'){d.push(detail('continuity',unit.facts?.continuity),detail('people_scope',peopleScopeText(unit.facts?.peopleScope,m)),detail('professional_context',professionalContextText(unit.context)));for(const k of arr(unit.facts?.responsibilityKinds))d.push(detail('responsibility_kind',k));}return freeze(d.filter(Boolean));}
function localizedSemanticLimitations(unit,m){const out=[];if(unit?.semanticType==='quantified_outcome'&&unit?.facts?.causalityBoundary==='contribution_only'&&txt(m.limitationContributionOnly))out.push(m.limitationContributionOnly);if(unit?.semanticType==='decision_accountability'&&txt(m.limitationDecisionEventScoped))out.push(m.limitationDecisionEventScoped);if(unit?.semanticType==='decision_accountability'&&unit?.facts?.decisionAuthority==='shared'&&txt(m.limitationSharedDecision))out.push(m.limitationSharedDecision);return out;}
function semanticFacts(unit){if(unit.semanticType==='decision_accountability')return freeze({decisionAuthority:unit.facts.decisionAuthority,consequenceScope:unit.facts.consequenceScope,accountabilityEvidence:unit.facts.accountabilityEvidence,responsibilityContinuity:unit.facts.responsibilityContinuity,context:unit.context});if(unit.semanticType==='continuing_people_responsibility')return freeze({responsibilityPresence:unit.facts.responsibilityPresence,continuity:unit.facts.continuity,responsibilityMode:unit.facts.responsibilityMode,responsibilityKinds:unit.facts.responsibilityKinds,peopleScope:unit.facts.peopleScope,context:unit.context});return freeze({measurableOutcome:unit.facts.measurableOutcome,quantitativeValue:unit.facts.quantitativeValue,contributionRelationship:unit.facts.contributionRelationship,causalityBoundary:unit.facts.causalityBoundary,context:unit.context});}
function makeClaim({id,semanticType,claim,explanation,units,evidence,limitations=[],messages}){const support=units.map(u=>u.semanticSupportRef).filter(Boolean), ev=[...new Set(units.flatMap(u=>u.evidenceRefs))];return freeze({id,semanticType,professionalClaim:claim,explanation,supportingSemanticFacts:units.map(semanticFacts),semanticSupportRefs:support,evidenceRefs:ev,epistemicState:'observed',limitations:[...new Set(limitations.filter(Boolean))],representationDetails:units.flatMap(u=>semanticDetails(u,messages||{})),targetRelation:null,provenance:{source:'authorized_semantic_material',semanticUnitRefs:units.map(u=>u.id),sourceLimitations:units.flatMap(u=>u.limitations)},supportingEvidence:evidence});}
export function buildDeterministicProfessionalRepresentation({synthesisInput,locale='it'}={}){
 const m=loadProfessionalRepresentationSynthesisMessages(locale), units=arr(synthesisInput?.semanticUnits), da=units.filter(x=>x.semanticType==='decision_accountability'), qo=units.filter(x=>x.semanticType==='quantified_outcome'), cpr=units.filter(x=>x.semanticType==='continuing_people_responsibility'); const claims=[];
 for(const [i,u] of da.entries()){const ctx=decisionContext(u,m);claims.push(makeClaim({id:`professional_representation_da_${i}`,semanticType:'decision_accountability',claim:tpl(m.decisionClaim,{authority:m[`decisionAuthority_${u.facts?.decisionAuthority}`]||m.decisionAuthority_shared,scope:m[`decisionScope_${u.facts?.consequenceScope}`]||m.decisionScope_individual}),explanation:ctx?tpl(m.decisionExplanationWithContext,{context:ctx}):m.decisionExplanation,units:[u],messages:m,evidence:[{summary:decisionEvidence(u,m),sourceRefs:refs(u)}],limitations:localizedSemanticLimitations(u,m)}));}
 for(const [i,u] of qo.entries()){const amount=quantity(u.facts?.quantitativeValue,m);if(!amount)continue;const qoLimits=localizedSemanticLimitations(u,m);const ctx=outcomeContext(u,m);claims.push(makeClaim({id:`professional_representation_qo_${i}`,semanticType:'quantified_outcome',claim:tpl(m.outcomeClaim,{quantity:amount}),explanation:ctx?tpl(m.outcomeExplanationWithContext,{context:ctx}):m.outcomeExplanation,units:[u],messages:m,evidence:[{summary:tpl(m.outcomeEvidence,{quantity:amount,contribution:m[`contribution_${u.facts?.contributionRelationship}`]||m.contribution_contributed}),sourceRefs:refs(u)}],limitations:qoLimits}));}
 for(const [i,u] of cpr.entries()){const scope=peopleScopeText(u.facts?.peopleScope,m),context=professionalContextText(u.context),kindLabels=arr(u.facts?.responsibilityKinds).map(k=>m[`peopleKind_${k}`]).filter(Boolean);if(!scope||!['recurring','continuing'].includes(u.facts?.continuity)||!kindLabels.length)continue;claims.push(makeClaim({id:`professional_representation_cpr_${i}`,semanticType:'continuing_people_responsibility',claim:tpl(m.peopleResponsibilityClaim,{continuity:m[`peopleContinuity_${u.facts.continuity}`]||'',scope,context:context?tpl(m.peopleContext,{context}):''}),explanation:tpl(m.peopleResponsibilityExplanation,{responsibilities:kindLabels.join(m.contextSeparator)}),units:[u],messages:m,evidence:[{summary:tpl(m.peopleResponsibilityEvidence,{scope,responsibilities:kindLabels.join(m.contextSeparator)}),sourceRefs:refs(u)}],limitations:[]}));}
 return freeze({type:'professional_representation_synthesis',version:'1.1',profileRef:synthesisInput?.profileRef||m.profileRef,sourceOfTruth:false,persistent:false,claims,sourceSemanticUnitRefs:units.map(x=>x.id),realization:{mode:'deterministic_fallback',validated:true}});
}
export function reconcileProfessionalRepresentationRealization({synthesisInput,realization,deterministicRepresentation,locale='it'}={}){
 if(!realization||!Array.isArray(realization.claims)||!deterministicRepresentation)return null; const base=new Map(deterministicRepresentation.claims.map(c=>[c.id,c])); const numbers=new Set(JSON.stringify(synthesisInput).match(/\b\d+(?:[.,]\d+)?\b/g)||[]); const allowedText=deterministicRepresentation.claims.map(c=>`${c.professionalClaim} ${c.explanation} ${(c.supportingEvidence||[]).map(e=>e.summary).join(' ')}`).join(' ').toLowerCase(); const rawContextTokens=new Set((synthesisInput?.semanticUnits||[]).flatMap(u=>Object.values(u?.context||{})).flatMap(v=>txt(v).toLowerCase().match(/[a-zà-ÿ0-9_]{5,}/g)||[]).filter(token=>!allowedText.includes(token))); const banned=/\b(sole owner|sole ownership|sole causality|piena ownership|ownership esclusiva|causalità esclusiva|leadership|leader naturale|people management|gestione persone|investment|investimenti|capacity planning|operations manager readiness|readiness|personalità|personality|strategic leadership)\b/i;
 const out=[]; const seen=new Set(); for(const r of realization.claims){const b=base.get(r?.id), claim=txt(r?.professionalClaim), explanation=txt(r?.explanation);if(!b||seen.has(r.id)||!claim||!explanation||banned.test(`${claim} ${explanation}`)||/\d+percent\b/i.test(`${claim} ${explanation}`))return null;const proposed=`${claim} ${explanation}`.toLowerCase();if([...rawContextTokens].some(token=>proposed.includes(token)))return null;for(const n of (`${claim} ${explanation}`.match(/\b\d+(?:[.,]\d+)?\b/g)||[]))if(!numbers.has(n))return null;seen.add(r.id);out.push(freeze(b.semanticType==='continuing_people_responsibility'?{...b}:{...b,professionalClaim:claim,explanation}));}
 if(out.length!==base.size)return null;return freeze({...deterministicRepresentation,claims:out,realization:{mode:'bounded_model',validated:true}});
}
export default buildDeterministicProfessionalRepresentation;
