import { buildAuthorizedSemanticMaterial } from '../report/buildProReportV2.js';
import { runProfessionalRepresentationSynthesis } from './runProfessionalRepresentationSynthesis.js';
import { materializeSourceGroundedProfessionalEpisodeMeanings } from './sourceGroundedProfessionalEpisodeMeaning.js';
import { buildEpisodeMeaningInformationalUnits, deriveRepresentationInformationalContributions } from './representationInformationalContribution.js';
import { composeProfessionalThreads, selectLevel1ProfessionalThreads } from './professionalThreadComposition.js';
import { runGroundedDescriptiveRelationshipVerticalSlice } from './groundedDescriptiveRelationshipVerticalSlice.js';
import { runHigherOrderDescriptiveProfessionalStructureVerticalSlice } from './higherOrderDescriptiveProfessionalStructureVerticalSlice.js';
import { buildHigherOrderCompositionInput } from './higherOrderCompositionInput.js';
import { deriveExplicitCrossTypePrimaryCompositionSubsumption } from './crossTypePrimaryCompositionSubsumption.js';
import { extractSourceGroundedRoleChronology } from './careerDirection/roleChronologyAuthority.js';
const text=v=>typeof v==='string'?v.trim():'';
const arr=v=>Array.isArray(v)?v:[];
const freeze=v=>{if(Array.isArray(v)){v.forEach(freeze);return Object.freeze(v)}if(v&&typeof v==='object'){Object.values(v).forEach(freeze);return Object.freeze(v)}return v};
const formalRole=/\b(production supervisor|industrialization engineer|manufacturing engineer|operations manager|project manager|plant manager)\b/i;
function unique(values){const out=[];for(const value of values){const x=text(value);if(x&&!out.includes(x))out.push(x)}return out;}
function explicitRole(source){const m=text(source?.content).match(formalRole);return m?m[0]:'';}
function safeFacts(item,source){const role=explicitRole(source);return arr(item?.facts).map(text).filter(Boolean).filter(f=>{
  if(/\b(coordinator|coordinatore|manager|responsabile|leader)\b/i.test(f)&&!role)return false;
  return true;
});}
function sourceAsset(item,source){
 const facts=safeFacts(item,source);if(!facts.length)return null;
 const role=explicitRole(source)||null;
 const kind=source.sourceRole==='current_cv'&&role?'current_role':source.sourceRole==='previous_cv'&&role?'previous_role':'supporting_experience';
 const roleDescriptionFacts=arr(item?.roleDescriptionFacts).map(text).filter(Boolean).filter(f=>!arr(item?.experienceHighlights).includes(f));
 return {id:`source:${source.id}`,supportClass:'source_grounded',assetKind:kind,sourceId:source.id,sourceRole:source.sourceRole,sourceLabel:text(source?.provenance?.label)||source.sourceRole,formalRole:role,summary:facts[0],facts,roleDescriptionFacts,domainSignals:unique(item?.domainSignals||[]),experienceHighlights:unique(item?.experienceHighlights||[]),sourceFaithfulExperienceExcerpts:unique(item?.sourceFaithfulExperienceExcerpts||[]),activitySemantics:arr(item?.activitySemantics).map(x=>({kind:text(x?.kind),supportExcerpt:text(x?.supportExcerpt)})).filter(x=>x.kind&&x.supportExcerpt),limitations:['source_grounded_projection']};
}
function buildRoleHistory(sourceAssets,byId){
 const entry=(x,status)=>{const roleRef=`formalRole:${x.sourceId}`;const chronology=extractSourceGroundedRoleChronology({source:byId.get(x.sourceId),roleRef,formalRole:x.formalRole});return {roleRef,sourceId:x.sourceId,sourceRole:x.sourceRole,role:x.formalRole,status,facts:x.facts,detail:x.roleDescriptionFacts.find(f=>text(f).toLowerCase()!==text(x.formalRole).toLowerCase())||null,chronology};};
 const previous=sourceAssets.filter(x=>x.assetKind==='previous_role').map(x=>entry(x,'previous'));
 const current=sourceAssets.filter(x=>x.assetKind==='current_role').map(x=>entry(x,'current'));
 return [...previous,...current];
}
function buildSynthesis(sourceAssets,knowledgeAssets,roleHistory){
 const currentRole=roleHistory.find(x=>x.status==='current')?.role||null;
 const previousRoles=roleHistory.filter(x=>x.status==='previous').map(x=>x.role);
 const domains=unique(sourceAssets.flatMap(x=>x.domainSignals)).slice(0,3);
 const supportingExperiences=sourceAssets.filter(x=>x.assetKind==='supporting_experience').map(x=>({sourceId:x.sourceId,summary:x.summary,facts:x.facts}));
 return {kind:'integrated_professional_synthesis',currentRole,previousRoles,domains,supportingExperienceCount:supportingExperiences.length,knowledgeSignals:unique(knowledgeAssets.map(x=>x.semanticType)),hasContextBoundedDecisionEvidence:knowledgeAssets.some(x=>x.semanticType==='decision_accountability'),hasMeasurableOutcomeEvidence:knowledgeAssets.some(x=>x.semanticType==='quantified_outcome'),hasContinuingPeopleResponsibilityEvidence:knowledgeAssets.some(x=>x.semanticType==='continuing_people_responsibility')};
}
function normalizedEpisodeKey(value){return text(value).toLocaleLowerCase().replace(/\s+/g,' ');}
function knowledgePrimaryMeaning(asset){
 const details=arr(asset?.representationDetails);const value=kind=>text(details.find(x=>x?.kind===kind)?.value);
 if(asset?.semanticType==='decision_accountability')return {kind:'bounded_decision_accountability',observedContext:value('observed_context'),personContribution:value('person_contribution'),responsibilityBoundary:value('responsibility_boundary'),sharedAuthority:arr(asset?.limitations).some(x=>/shared|condivis/i.test(text(x)))};
 if(asset?.semanticType==='quantified_outcome')return {kind:'bounded_measurable_outcome_contribution',quantification:value('quantification'),personContribution:value('person_contribution')};
 if(asset?.semanticType==='continuing_people_responsibility')return {kind:'bounded_continuing_people_responsibility',continuity:value('continuity'),peopleScope:value('people_scope'),professionalContext:value('professional_context'),responsibilityKinds:details.filter(x=>x?.kind==='responsibility_kind').map(x=>text(x.value)).filter(Boolean)};
 if(asset?.semanticType==='resource_budget_responsibility_scope')return {kind:'bounded_resource_budget_responsibility',responsibilityStrength:value('responsibility_strength'),responsibilityScope:value('responsibility_scope'),professionalContext:value('professional_context')};
 if(asset?.semanticType==='production_planning_scheduling_responsibility_scope')return {kind:'bounded_production_planning_scheduling_responsibility',responsibilityStrength:value('responsibility_strength'),responsibilityScope:value('responsibility_scope'),professionalContext:value('professional_context')};
 return {kind:'bounded_observation',summary:asset?.summary||''};
}
function buildProfessionalMeaning({sourceAssets,knowledgeAssets,roleHistory,supportingExperiences,episodeMeanings=[]}){
 const current=roleHistory.find(x=>x.status==='current')||null,previous=roleHistory.filter(x=>x.status==='previous');
 const domains=unique(sourceAssets.flatMap(x=>x.domainSignals)).slice(0,4);
 const sourceRefs=unique(sourceAssets.map(x=>x.sourceId));
 const knowledgeRefs=unique(knowledgeAssets.map(x=>x.sourceRef));
 const formalRoleAssets=sourceAssets.filter(x=>['current_role','previous_role'].includes(x.assetKind)&&x.formalRole);
 const supportedPatterns=[];
 for(const domain of domains){const support=formalRoleAssets.filter(x=>x.domainSignals.includes(domain));const distinctRoles=unique(support.map(x=>x.formalRole));if(support.length>=2&&distinctRoles.length>=2)supportedPatterns.push({kind:'documented_domain_continuity',domain,sourceRefs:unique(support.map(x=>x.sourceId)),roleRefs:distinctRoles,episodeRefs:distinctRoles.map(role=>`formal_role:${role}`),episodeBasis:'distinct_formal_roles',supportCount:distinctRoles.length,traitInference:false});}
 const coordinationSupport=[];
 for(const asset of sourceAssets){for(const semantic of arr(asset.activitySemantics)){if(semantic.kind!=='cross_functional_coordination')continue;const episodeKey=normalizedEpisodeKey(semantic.supportExcerpt);if(!episodeKey||coordinationSupport.some(x=>x.episodeKey===episodeKey))continue;coordinationSupport.push({episodeKey,sourceId:asset.sourceId,sourceRole:asset.sourceRole,supportExcerpt:semantic.supportExcerpt});}}
 if(coordinationSupport.length>=2)supportedPatterns.push({kind:'documented_cross_functional_coordination_recurrence',sourceRefs:unique(coordinationSupport.map(x=>x.sourceId)),episodeRefs:coordinationSupport.map(x=>x.episodeKey),supports:coordinationSupport,episodeBasis:'distinct_source_grounded_experiences',supportCount:coordinationSupport.length,traitInference:false});
 const boundedPatterns=supportedPatterns.slice(0,3);
 return {
  kind:'target_independent_professional_meaning',
  professionalSynthesis:{kind:'documented_professional_configuration',currentRole:current?.role||null,previousRoles:previous.map(x=>x.role),domains,hasDocumentedRoleContinuity:Boolean(current&&previous.length),supportingExperienceCount:supportingExperiences.length,sourceRefs,knowledgeRefs,supportedPatternKinds:boundedPatterns.map(x=>x.kind),knowledgeSemanticTypes:knowledgeAssets.map(x=>x.semanticType)},
  supportedPatterns:boundedPatterns,
  credibilityBasis:{sourceRefs,roleRefs:roleHistory.map(x=>({sourceId:x.sourceId,role:x.role,status:x.status})),supportingExperienceRefs:supportingExperiences.map(x=>({sourceId:x.sourceId})),knowledgeRefs},
  knowledgeContribution:knowledgeAssets.map(x=>({semanticType:x.semanticType,primaryProfessionalMeaning:knowledgePrimaryMeaning(x),professionalMeaning:x.summary,explanation:x.explanation,sourceRef:x.sourceRef,limitations:x.limitations||[],supportingEvidence:x.supportingEvidence||[],authorisedSemanticPayload:x.semanticPayload||null,lineage:x.semanticPayload?.lineage||null})),
  episodeInformationalUnits:episodeMeanings.flatMap(buildEpisodeMeaningInformationalUnits),
  insufficientObservability:[],
  progressiveExplanation:{primary:['professional_synthesis','supported_patterns','knowledge_contribution','insufficient_observability'],explanatory:['credibility_basis','supporting_experiences','provenance'],epistemic:['knowledge_limitations','source_scoped_support']}
 };
}

export async function buildTargetIndependentProfessionalRepresentation({professionalSources=[],sourceGroundedProjection=[],reusableKnowledgeResults=[],responsibilityScopeResults=[],locale='it',narrativeRealizer,useModel=false,descriptorProposalProvider,relationshipHypothesisProvider,pd069DiagnosticSink,higherOrderProposalProvider,higherOrderProviderDiagnosticReader,professionalSynthesisDiagnosticSink}={}){
 const byId=new Map(arr(professionalSources).map(x=>[x.id,x]));
 const episodeMeanings=materializeSourceGroundedProfessionalEpisodeMeanings({professionalSources,responsibilityScopeResults});
 const sourceAssets=arr(sourceGroundedProjection).map((item,i)=>sourceAsset(item,byId.get(item.sourceId)||professionalSources[i]||{})).filter(Boolean);
 const baseAuthorizedSemanticMaterial=buildAuthorizedSemanticMaterial(reusableKnowledgeResults).map(item=>{const i=Number((text(item.sourceRef).match(/\[(\d+)\]/)||[])[1]);const r=Number.isInteger(i)?reusableKnowledgeResults[i]:null;return {...item,lineage:{sourceExecutionRef:text(r?.sourceExecutionRef),sourceRuntimeSessionRef:text(r?.sourceRuntimeSessionRef),sourceRuntimeActionRef:text(r?.sourceRuntimeActionRef),sourceEvidenceRef:text(r?.sourceEvidenceRef)}};});
 const peopleMaterial=arr(reusableKnowledgeResults).flatMap((result,index)=>{
  const policy=text(result?.semanticPolicyRef||result?.semanticAuthority?.semanticPolicyRef||result?.observation?.extensions?.semanticProvenance?.semanticPolicyRef);
  const observation=result?.observation, detail=result?.specializedMeasurementResult?.semanticDetail, context=result?.specializedMeasurementResult?.context||observation?.professionalContext||{};
  if(text(result?.semanticType)!=='continuing_people_responsibility'||!result?.knowledgeSnapshot||policy!=='professional_semantic_policy:continuing_people_responsibility:v1'||observation?.observationType!=='observed_continuing_people_responsibility_context'||observation?.observationStatus!=='observed'||detail?.responsibilityPresence!=='supported'||!['recurring','continuing'].includes(detail?.continuity))return [];
  return [{semanticType:'continuing_people_responsibility',sourceRef:text(result?.knowledgeRef)||`reusableKnowledgeResults[${index}]`,observationId:observation.observationId,evidenceIds:arr(observation.evidenceIds),responsibilityPresence:detail.responsibilityPresence,continuity:detail.continuity,responsibilityMode:detail.responsibilityMode,responsibilityKinds:arr(detail.responsibilityKinds),peopleScope:detail.peopleScope||{kind:'unknown'},professionalContext:context,limitations:arr(observation.limitations),lineage:{sourceExecutionRef:text(result?.sourceExecutionRef),sourceRuntimeSessionRef:text(result?.sourceRuntimeSessionRef),sourceRuntimeActionRef:text(result?.sourceRuntimeActionRef),sourceEvidenceRef:text(result?.sourceEvidenceRef)}}];
 });
 const authorizedSemanticMaterial=[...baseAuthorizedSemanticMaterial,...peopleMaterial];
 const pd086Material=arr(reusableKnowledgeResults).flatMap((result,index)=>{const semanticType=text(result?.semanticType),detail=result?.specializedMeasurementResult?.semanticDetail,observation=result?.observation;if(!['resource_budget_responsibility_scope','production_planning_scheduling_responsibility_scope'].includes(semanticType)||!result?.knowledgeSnapshot||result?.specializedMeasurementResult?.resultStatus!=='draft'||observation?.observationStatus!=='observed'||detail?.stateKind!=='supported_responsibility')return [];return [{semanticType,sourceRef:text(result?.knowledgeRef)||`reusableKnowledgeResults[${index}]`,evidenceIds:arr(observation?.evidenceIds),responsibilityStrength:text(detail?.responsibilityStrength),directness:text(detail?.directness),scope:text(detail?.scope),continuity:text(detail?.continuity),professionalContext:detail?.professionalContext||{},budgetResources:detail?.budgetResources||null,productionPlanning:detail?.productionPlanning||null,limitations:arr(detail?.limitations),lineage:{sourceExecutionRef:text(result?.sourceExecutionRef),sourceRuntimeSessionRef:text(result?.sourceRuntimeSessionRef),sourceRuntimeActionRef:text(result?.sourceRuntimeActionRef),sourceEvidenceRef:text(result?.sourceEvidenceRef)}}];});
 const {representation:knowledgeRepresentation}=await runProfessionalRepresentationSynthesis({authorizedSemanticMaterial,locale,narrativeRealizer,useModel});
 const synthesizedKnowledgeAssets=arr(knowledgeRepresentation?.claims).map((claim,i)=>{const semanticPayload=authorizedSemanticMaterial.find(x=>x?.semanticType===claim.semanticType&&(!claim.semanticSupportRefs?.length||claim.semanticSupportRefs.includes(x.sourceRef)))||authorizedSemanticMaterial.find(x=>x?.semanticType===claim.semanticType)||null;return {id:`knowledge:${claim.semanticType}:${i}`,supportClass:'canonical_knowledge',assetKind:'knowledge_claim',semanticType:claim.semanticType,summary:claim.professionalClaim,explanation:claim.explanation,supportingEvidence:claim.supportingEvidence||[],limitations:claim.limitations||[],representationDetails:claim.representationDetails||[],sourceRef:claim.semanticSupportRefs?.[0]||semanticPayload?.sourceRef||null,semanticPayload:semanticPayload?freeze({...semanticPayload}):null};});
 const pd086KnowledgeAssets=pd086Material.map((item,i)=>({id:`knowledge:${item.semanticType}:pd086:${i}`,supportClass:'canonical_knowledge',assetKind:'knowledge_claim',semanticType:item.semanticType,summary:item.semanticType,explanation:'',supportingEvidence:item.evidenceIds.map(ref=>({sourceRefs:[ref]})),limitations:item.limitations,representationDetails:[{kind:'responsibility_strength',value:item.responsibilityStrength},{kind:'professional_context',value:text(item.professionalContext?.description)},{kind:'responsibility_scope',value:item.scope}].filter(x=>x.value),sourceRef:item.sourceRef,semanticPayload:freeze({...item})}));
 const knowledgeAssets=[...synthesizedKnowledgeAssets,...pd086KnowledgeAssets];
 const roleHistory=buildRoleHistory(sourceAssets,byId);
 const supportingExperiences=sourceAssets.filter(x=>x.sourceFaithfulExperienceExcerpts.length||x.assetKind==='supporting_experience').map(x=>({sourceId:x.sourceId,sourceRole:x.sourceRole,summary:x.sourceFaithfulExperienceExcerpts[0]||x.summary,facts:x.facts,experienceHighlights:x.experienceHighlights,sourceFaithfulExperienceExcerpts:x.sourceFaithfulExperienceExcerpts}));
 const synthesis=buildSynthesis(sourceAssets,knowledgeAssets,roleHistory);
 let professionalMeaning=buildProfessionalMeaning({sourceAssets,knowledgeAssets,roleHistory,supportingExperiences,episodeMeanings});
 const informationalContributions=deriveRepresentationInformationalContributions({episodeMeanings,professionalMeaning});
 const episodeById=new Map(episodeMeanings.map(x=>[x.episodeMeaningId,x]));
 const selectedEpisodeContributions=informationalContributions.map(c=>{const e=episodeById.get(c.episodeMeaningRef);return e?{episodeMeaningRef:c.episodeMeaningRef,description:e.description,participation:e.participation,activity:e.activity,object:e.object,phases:e.phases,professionalContext:e.professionalContext,temporalContext:e.temporalContext,responsibilityScope:e.responsibilityScope||null,distinctUnitRefs:c.distinctUnitRefs,sourceId:e.sourceId,sourceRole:e.sourceRole}:null;}).filter(Boolean);
 professionalMeaning={...professionalMeaning,informationalContributions,selectedEpisodeContributions};
 const pd069Materials=[...sourceAssets.map(a=>({materialRef:a.id,sourceId:a.sourceId,summary:a.summary,facts:a.facts,sourceFaithfulExperienceExcerpts:a.sourceFaithfulExperienceExcerpts,exactSupports:[...a.sourceFaithfulExperienceExcerpts,...a.activitySemantics.map(x=>x.supportExcerpt).filter(Boolean)],structuredSupports:a.activitySemantics.map(x=>({exactText:text(x.supportExcerpt),semanticClasses:x.kind==='cross_functional_coordination'?['cross_functional_coordination']:[]})).filter(x=>x.exactText&&x.semanticClasses.length),semanticCeiling:{subjectScopes:['source_material'],agencyLevel:'not_established',responsibilityScope:'not_established',ownershipAssertion:'none',decisionAuthorityAssertion:'none',resultCausalityAssertion:'none'}})),...episodeMeanings.map(e=>({materialRef:e.episodeMeaningId,sourceId:e.sourceId,episodeRef:e.episodeMeaningId,summary:e.description,exactSupports:[sourceAssets.find(a=>a.sourceId===e.sourceId)?.sourceFaithfulExperienceExcerpts?.[0]].filter(Boolean),structuredSupports:e?.responsibilityScope&&text(e.responsibilityScope?.state)!=='unknown_not_established'&&text(e.responsibilityScope?.referent?.semanticType)==='continuing_people_responsibility'?[{exactText:text(sourceAssets.find(a=>a.sourceId===e.sourceId)?.sourceFaithfulExperienceExcerpts?.[0]),semanticClasses:['people_responsibility']}].filter(x=>x.exactText):[],semanticCeiling:{subjectScopes:['episode'],agencyLevel:['participated','contributed'].includes(e.participation)?e.participation:'not_established',responsibilityScope:e.responsibilityScope?.state||'not_established',ownershipAssertion:'none',decisionAuthorityAssertion:'none',resultCausalityAssertion:'none'}}))];
 const groundedRelationshipSynthesis=await runGroundedDescriptiveRelationshipVerticalSlice({materials:pd069Materials,descriptorProposalProvider,relationshipHypothesisProvider,locale});
 if(typeof pd069DiagnosticSink==='function')pd069DiagnosticSink(freeze({boundary:'pd069l_live_proposal',stage:'validation_complete',inputMaterialCount:pd069Materials.length,acceptedDescriptorCount:groundedRelationshipSynthesis.descriptors.length,rejectedDescriptorCount:groundedRelationshipSynthesis.descriptorRejections.length,acceptedRelationshipCount:groundedRelationshipSynthesis.relationships.length,rejectedRelationshipCount:groundedRelationshipSynthesis.relationshipRejections.length,fallbackReason:groundedRelationshipSynthesis.relationships.length?'none':(groundedRelationshipSynthesis.providerStatus==='not_configured'?'provider_not_configured':'no_accepted_relationship')}));
 professionalMeaning={...professionalMeaning,groundedDescriptiveDescriptors:groundedRelationshipSynthesis.descriptors,groundedDescriptiveRelationships:groundedRelationshipSynthesis.relationships,pd069Validation:{descriptorRejections:groundedRelationshipSynthesis.descriptorRejections,relationshipRejections:groundedRelationshipSynthesis.relationshipRejections,providerStatus:groundedRelationshipSynthesis.providerStatus}};
 const pd069DescriptorById=new Map(groundedRelationshipSynthesis.descriptors.map(d=>[d.descriptorId,d]));
 const pd070Contributors=buildHigherOrderCompositionInput({relationships:groundedRelationshipSynthesis.relationships,descriptors:groundedRelationshipSynthesis.descriptors,episodeMeanings,supportedPatterns:professionalMeaning.supportedPatterns,knowledgeContribution:professionalMeaning.knowledgeContribution});
 let pd070ObservedProposals=[];
 const observedHigherOrderProposalProvider=typeof higherOrderProposalProvider==='function'?async args=>{const proposals=await higherOrderProposalProvider(args);pd070ObservedProposals=arr(proposals).map(x=>({...x}));return proposals}:higherOrderProposalProvider;
 const pd070Synthesis=await runHigherOrderDescriptiveProfessionalStructureVerticalSlice({contributors:pd070Contributors,proposalProvider:observedHigherOrderProposalProvider,locale});
 const pd071aStructures=deriveExplicitCrossTypePrimaryCompositionSubsumption({structures:pd070Synthesis.structures,contributors:pd070Contributors});
 professionalMeaning={...professionalMeaning,higherOrderDescriptiveProfessionalStructures:pd071aStructures,pd070Validation:{rejections:pd070Synthesis.rejections,providerStatus:pd070Synthesis.providerStatus}};
 professionalMeaning={...professionalMeaning,professionalThreads:composeProfessionalThreads({professionalMeaning})};
 professionalMeaning={...professionalMeaning,level1ProfessionalThreads:selectLevel1ProfessionalThreads(professionalMeaning.professionalThreads)};
 if(typeof professionalSynthesisDiagnosticSink==='function'){
  const acceptedStructureIds=new Set(pd071aStructures.map(x=>text(x.structureId)));
  const rejectionByProposal=new Map(pd070Synthesis.rejections.map(x=>[text(x.proposalRef),arr(x.errors)]));
  const selectedIds=new Set(professionalMeaning.level1ProfessionalThreads.map(x=>text(x.threadId)));
  const selectedHigher=professionalMeaning.level1ProfessionalThreads.filter(x=>x.kind==='higher_order_descriptive_structure');
  const subsumedContributorRefs=unique(selectedHigher.flatMap(x=>arr(x?.meaning?.contributorRefs)));const subsumedRelationshipRefs=subsumedContributorRefs.filter(x=>!x.includes(':')||groundedRelationshipSynthesis.relationships.some(r=>text(r.relationshipId)===x));
  const descriptorById=new Map(groundedRelationshipSynthesis.descriptors.map(x=>[text(x.descriptorId),x]));
  const relationshipInventory=groundedRelationshipSynthesis.relationships.map(r=>({relationshipId:text(r.relationshipId),descriptorRefs:unique(arr(r.descriptorRefs)),relationshipWording:text(r.relationshipWording),relationshipBasis:text(r.relationshipBasis),claimShape:r.claimShape?{...r.claimShape}:null,materialRefs:unique(arr(r.materialRefs)),sourceRefs:unique(arr(r.sourceRefs)),professionalBasisRefs:unique(arr(r.descriptorRefs).map(ref=>text(descriptorById.get(ref)?.episodeRef)).filter(Boolean)),descriptors:arr(r.descriptorRefs).map(ref=>descriptorById.get(ref)).filter(Boolean).map(d=>({descriptorId:text(d.descriptorId),descriptorRole:text(d.descriptorRole),descriptiveValue:text(d.descriptiveValue),materialRef:text(d.materialRef),episodeRef:text(d.episodeRef)}))}));
  const upstreamBreadth={episodeMeanings:episodeMeanings.map(e=>({episodeMeaningId:text(e.episodeMeaningId),sourceId:text(e.sourceId),activity:e.activity||null,object:e.object||null,phases:arr(e.phases),professionalContext:e.professionalContext||null,participation:text(e.participation)})),supportedPatterns:arr(professionalMeaning.supportedPatterns).map(x=>({kind:text(x.kind),sourceRefs:unique(arr(x.sourceRefs)),episodeRefs:unique(arr(x.episodeRefs)),supportCount:Number(x.supportCount||0)})),knowledgeContributions:arr(professionalMeaning.knowledgeContribution).map((x,i)=>({knowledgeRef:text(x.sourceRef)||`knowledge:${i}`,semanticType:text(x.semanticType),primaryProfessionalMeaning:x.primaryProfessionalMeaning||null}))};
  const liveHigherOrderRun=typeof higherOrderProviderDiagnosticReader==='function'?higherOrderProviderDiagnosticReader():null;
  const proposalInventory=pd070ObservedProposals.map(p=>{const ref=text(p.proposalRef),accepted=pd070Synthesis.structures.find(x=>text(x.structureId)===`higherOrderStructure:${ref}`);return {proposalRef:ref,contributorRefs:unique(arr(p.contributorRefs)),structureWording:text(p.structureWording),compositionBasis:text(p.compositionBasis),claimShape:p.claimShape?{...p.claimShape}:null,accepted:Boolean(accepted),rejectionReasons:rejectionByProposal.get(ref)||[],resolvedProfessionalBasisRefs:accepted?unique(arr(accepted.professionalBasisRefs)):unique(arr(p?.independenceBasis?.professionalBasisRefs))}});
  const threadInventory=professionalMeaning.professionalThreads.map(t=>({threadId:text(t.threadId),kind:text(t.kind),semanticSourceRef:text(t?.meaning?.structureRef)||text(t?.meaning?.relationshipRef)||text(t?.meaning?.patternKind)||text(t?.meaning?.episodeMeaningRef)||text(t?.manifestations?.[0]?.sourceRef)||null,level1SelectionClass:text(t.level1SelectionClass),level1Eligible:['higher_order_structure','cross_material_relationship','cross_role_authorised_pattern','standalone_distinct_contribution','standalone_canonical_knowledge'].includes(t.level1SelectionClass),selectedLevel1:selectedIds.has(text(t.threadId)),higherOrderContributorRefs:unique(arr(t?.meaning?.contributorRefs)),suppressedByExplicitRelationshipSubsumption:t.kind==='grounded_descriptive_relationship'&&subsumedRelationshipRefs.includes(text(t?.meaning?.relationshipRef))?selectedHigher.filter(h=>arr(h?.meaning?.contributorRefs).includes(text(t?.meaning?.relationshipRef))).map(h=>text(h?.meaning?.structureRef)):[],suppressedByExplicitCrossTypeSubsumption:selectedHigher.filter(h=>{const refs=arr(h?.meaning?.contributorRefs);if(t.kind==='recurring_pattern'||t.kind==='documented_continuity')return refs.some(r=>r===`pattern:${text(t.threadId).replace(/^professionalThread:pattern:/,'')}`);if(t.kind==='distinct_episode')return refs.includes(`episodeMeaning:${text(t?.manifestations?.[0]?.episodeMeaningRef)}`);if(t.kind==='bounded_knowledge_meaning')return refs.includes(`knowledge:${text(t?.manifestations?.[0]?.sourceRef)}`);return false}).map(h=>text(h?.meaning?.structureRef))}));
  professionalSynthesisDiagnosticSink(freeze({boundary:'pd070_real_professional_synthesis',pd069:{providerStatus:groundedRelationshipSynthesis.providerStatus,acceptedRelationships:relationshipInventory},upstreamStructuredBreadth:upstreamBreadth,pd070:{providerStatus:liveHigherOrderRun?.status||pd070Synthesis.providerStatus,model:text(liveHigherOrderRun?.result?.model)||text(liveHigherOrderRun?.failure?.model)||null,elapsedMs:Number.isFinite(Number(liveHigherOrderRun?.elapsedMs))?Number(liveHigherOrderRun.elapsedMs):null,failure:liveHigherOrderRun?.status==='failed'&&liveHigherOrderRun?.failure?{...liveHigherOrderRun.failure}:null,inputContributorCount:pd070Contributors.length,inputContributorRefs:pd070Contributors.map(x=>text(x.contributorRef)),inputContributors:pd070Contributors.map(x=>({contributorRef:text(x.contributorRef),contributorType:text(x.contributorType),professionalBasisRefs:unique(arr(x.professionalBasisRefs)),sentToPd070L:true})),proposals:proposalInventory,acceptedStructureIds:[...acceptedStructureIds]},downstream:{professionalThreads:threadInventory,level1ThreadIds:professionalMeaning.level1ProfessionalThreads.map(x=>text(x.threadId)),explicitSubsumedRelationshipRefs:subsumedRelationshipRefs,explicitSubsumedContributorRefs:subsumedContributorRefs}}));
 }
 const limitations=[];if(!knowledgeAssets.length)limitations.push({supportClass:'insufficiently_observed',messageKey:'representationInsufficientCanonicalObservation'});
 return freeze({type:'target_independent_professional_representation',version:'1.4',persistent:false,target:null,synthesis:{...synthesis,episodeMeaningCount:episodeMeanings.length},professionalMeaning,roleHistory,supportingExperiences,episodeMeanings,assets:[...sourceAssets,...knowledgeAssets,...episodeMeanings.map(x=>({id:x.episodeMeaningId,supportClass:'source_grounded_episode_meaning',assetKind:'episode_meaning',sourceId:x.sourceId,sourceRole:x.sourceRole,summary:x.description,limitations:x.limitations}))],limitations,provenance:{sourceIds:sourceAssets.map(x=>x.sourceId),knowledgeRefs:arr(reusableKnowledgeResults).map(x=>text(x.knowledgeRef)).filter(Boolean),episodeMeaningRefs:episodeMeanings.map(x=>x.episodeMeaningId)}});
}
export default buildTargetIndependentProfessionalRepresentation;
