import { performance } from 'node:perf_hooks';
import { setTimeout as delay } from 'node:timers/promises';
import { runGroqHigherOrderProfessionalSynthesisModel } from '../infrastructure/groq/runGroqHigherOrderProfessionalSynthesisModel.js';
import { MAX_DEPENDENT_TOKEN_RESET_WAIT_MS } from '../infrastructure/groq/runGroqChatCompletion.js';
const arr=v=>Array.isArray(v)?v:[];const text=v=>typeof v==='string'?v.trim():'';const unique=v=>[...new Set(arr(v).map(text).filter(Boolean))];const freeze=v=>{if(Array.isArray(v)){v.forEach(freeze);return Object.freeze(v)}if(v&&typeof v==='object'){Object.values(v).forEach(freeze);return Object.freeze(v)}return v};
function boundedContributor(c){return {contributorRef:text(c?.contributorRef||c?.relationshipId),contributorType:text(c?.contributorType||c?.kind),nativeRef:text(c?.nativeRef||c?.relationshipId),semanticContent:c?.semanticContent||{wording:text(c?.relationshipWording),basis:text(c?.relationshipBasis)},structuredSemanticIdentity:c?.structuredSemanticIdentity||{status:'unestablished',classes:[],basis:'not_available'},claimShape:c?.claimShape?{...c.claimShape}:null,materialRefs:unique(c?.materialRefs),sourceRefs:unique(c?.sourceRefs),professionalBasisRefs:unique(c?.professionalBasisRefs),semanticCeiling:c?.semanticCeiling||null};}
export function buildHigherOrderProfessionalSynthesisModelInput({contributors=[],locale='it'}={}){return freeze({locale:text(locale)||'it',task:'higher_order_descriptive_professional_structure_proposal',contributors:arr(contributors).map(boundedContributor).filter(x=>x.contributorRef&&x.contributorType)});}
function systemPrompt(locale){return `You propose Higher-Order Descriptive Professional Structures for IMAGO from already-authorised structured Representation contributors. Return only required structured output. MODEL PROPOSES; deterministic code accepts or rejects. Use only supplied application-owned contributorRef values; never invent contributor identities or facts. This is SECOND-ORDER synthesis: identify a bounded configuration, recurrence or sequence visible only when several authorised contributors are considered together. Do not merely concatenate, paraphrase or pairwise-restatement their wording. The subject is documented situations/episodes/activities/work phases/professional contexts/function configurations/problems/forms of participation — never the Candidate as a stable property. RICHER SYNTHESIS IS NOT A STRONGER PERSON CLAIM. Prefer the least semantically strong supported claim. Preserve UNKNOWN. Do not infer capability, trait, personality, leadership, seniority, strength/weakness, professional identity, career trajectory/continuity, fit/readiness/employability, ownership, exclusive responsibility, general autonomy or Candidate-caused results. Participation is not ownership; coordination is not leadership; shared responsibility is not exclusive; bounded decision accountability is not general autonomy; project result is not Candidate-caused achievement; recurrence of situations is not Candidate capability; chronology is not professional continuity. A recurrence proposal may be made only as a proposal; deterministic code decides independence from canonical professionalBasisRefs. Do not use project/company/function-name coincidence, vocabulary overlap, generic collaboration/process-improvement wording or chronology as sufficient synthesis. Wording, compositionBasis, compositionSemanticClass and claimShape must be semantically consistent and produced together. compositionSemanticClass is a bounded proposal label, not semantic authority; choose one of generic_descriptive_combination, cross_functional_coordination, people_responsibility, decision_accountability, quantified_outcome, production_planning, budget_resource, process_performance_improvement, decision_accountability_quantified_outcome. Use generic_descriptive_combination when no narrower bounded class is established by the structured contributor identities. No target/JD/Career Direction reasoning. Propose at most 3 genuinely distinct structures; omit weak/trivial proposals. Output natural wording in ${locale==='en'?'English':'Italian'}.`;}
function userPrompt(input){return `Consider only these authorised structured contributors. Ask what broader bounded descriptive structure becomes visible across several of them that is less apparent from each separately. Select only supplied contributorRef values. For ordinary combination use structureClaim=descriptive_combination. Use recurrence only when the wording actually asserts recurrence; deterministic validation will separately establish canonical professional independence. Keep personPropertyAssertion, continuityAssertion, leadershipAssertion, ownershipAssertion, responsibilityAssertion, generalAutonomyAssertion, resultCausalityAssertion and targetRelationAssertion at none unless you are intentionally expressing such a claim for rejection.\n${JSON.stringify(input)}`;}
function safeReason(e){return text(e?.providerDiagnostic?.failureKind)||text(e?.message)||'provider_failure';}
function boundedFailure(error){
 const d=error?.providerDiagnostic&&typeof error.providerDiagnostic==='object'?error.providerDiagnostic:{};
 const message=text(error?.message);
 const timeout=d.failureKind==='timeout'||error?.name==='AbortError'||/timeout|timed out/i.test(message);
 const parsing=/PD070L_MALFORMED_STRUCTURED_OUTPUT|invalid response envelope|invalid json|json parse/i.test(message);
 const schema=d.failureKind==='structured_output_rejected'||/PD070L_INVALID_STRUCTURED_OUTPUT|schema|structured output/i.test(message);
 const failureKind=text(d.failureKind)||(timeout?'timeout':parsing?'parsing_failure':schema?'structured_output_rejected':'provider_or_model_adapter_error');
 const errorClass=timeout?'timeout':parsing?'parsing':schema?'structured_output':(d.failureKind||error?.status?'provider':'unexpected');
 const providerMessage=text(d.providerMessage)||(timeout?'Provider/model call timed out.':parsing?'Provider/model output could not be parsed as the required structured output.':schema?'Provider/model output did not satisfy the required structured-output contract.':'Provider/model call failed.');
 return freeze({failureKind,errorClass,httpStatus:Number.isFinite(Number(error?.status??d.status))?Number(error?.status??d.status):null,providerCode:text(d.providerCode)||null,providerType:text(d.providerType)||null,providerMessage:providerMessage.slice(0,600),stage:'model_call_failed',task:text(error?.task||d.task)||'higherOrderProfessionalSynthesis',model:text(error?.model||d.model)||null,timeout,structuredOutput:schema,parsing});
}
export function projectHigherOrderProviderFailure(error){return boundedFailure(error);}
export function resolveDependentTokenHeadroomPacing({previousTask='groundedRelationshipProposal',nextTask='higherOrderProfessionalSynthesis',rateLimitMetadata,nextCompletionTokenBudget}={}){
 const remainingTokens=Number(rateLimitMetadata?.remainingTokens);
 const budget=Number(nextCompletionTokenBudget);
 const hasRemaining=rateLimitMetadata?.remainingTokens!==null&&rateLimitMetadata?.remainingTokens!==undefined&&Number.isFinite(remainingTokens)&&remainingTokens>=0;
 const hasBudget=Number.isFinite(budget)&&budget>0;
 const tokenHeadroomSufficient=hasRemaining&&hasBudget?remainingTokens>=budget:null;
 if(tokenHeadroomSufficient!==false)return freeze({previousTask,nextTask,remainingTokens:hasRemaining?remainingTokens:null,nextCompletionTokenBudget:hasBudget?budget:null,tokenHeadroomSufficient,resetTokens:text(rateLimitMetadata?.resetTokens)||null,chosenWaitMs:0,pacingReason:tokenHeadroomSufficient===true?'token_headroom_sufficient':'token_headroom_unknown'});
 const retryAfterMs=rateLimitMetadata?.retryAfterMs==null?null:Number(rateLimitMetadata.retryAfterMs);
 const tokenResetMs=rateLimitMetadata?.tokenResetMs==null?null:Number(rateLimitMetadata.tokenResetMs);
 const candidate=retryAfterMs!==null&&Number.isFinite(retryAfterMs)&&retryAfterMs>=0?retryAfterMs:(tokenResetMs!==null&&Number.isFinite(tokenResetMs)&&tokenResetMs>=0?tokenResetMs:null);
 const chosenWaitMs=candidate==null?0:Math.min(Math.round(candidate),MAX_DEPENDENT_TOKEN_RESET_WAIT_MS);
 return freeze({previousTask,nextTask,remainingTokens,nextCompletionTokenBudget:budget,tokenHeadroomSufficient:false,resetTokens:text(rateLimitMetadata?.resetTokens)||null,chosenWaitMs,pacingReason:chosenWaitMs>0?'insufficient_token_headroom_for_dependent_call':'insufficient_token_headroom_reset_unknown'});
}

export function createLiveHigherOrderProfessionalSynthesisProvider({modelRunner=runGroqHigherOrderProfessionalSynthesisModel,diagnosticSink,executionDiagnosticSink,beforeCallPacing,now=()=>new Date().toISOString()}={}){
 let lastRun=null;
 const proposalProvider=async({contributors=[],locale='it'}={})=>{const input=buildHigherOrderProfessionalSynthesisModelInput({contributors,locale}),started=performance.now();const pacing=typeof beforeCallPacing==='function'?beforeCallPacing():null;const pacingWaitMs=Number.isFinite(Number(pacing?.chosenWaitMs??pacing?.waitMs))?Math.max(0,Math.min(Number(pacing?.chosenWaitMs??pacing?.waitMs),MAX_DEPENDENT_TOKEN_RESET_WAIT_MS)):0;if(pacing){diagnosticSink?.(freeze({boundary:'pd070l_live_second_order_proposal',stage:'dependent_call_pacing_decision',at:now(),previousTask:text(pacing?.previousTask)||null,nextTask:text(pacing?.nextTask)||'higherOrderProfessionalSynthesis',remainingTokens:Number.isFinite(Number(pacing?.remainingTokens))?Number(pacing.remainingTokens):null,nextCompletionTokenBudget:Number.isFinite(Number(pacing?.nextCompletionTokenBudget))?Number(pacing.nextCompletionTokenBudget):null,tokenHeadroomSufficient:pacing?.tokenHeadroomSufficient??null,resetTokens:text(pacing?.resetTokens)||null,chosenWaitMs:pacingWaitMs,pacingReason:text(pacing?.pacingReason||pacing?.reason)||null}));}if(pacingWaitMs>0){diagnosticSink?.(freeze({boundary:'pd070l_live_second_order_proposal',stage:'provider_aware_pacing',at:now(),waitMs:pacingWaitMs,reason:text(pacing?.pacingReason||pacing?.reason)||'provider_reset_metadata'}));await delay(pacingWaitMs);}diagnosticSink?.(freeze({boundary:'pd070l_live_second_order_proposal',stage:'model_call_start',at:now(),inputContributorCount:input.contributors.length}));try{const result=await modelRunner({systemPrompt:systemPrompt(locale),userPrompt:userPrompt(input),executionDiagnosticSink});const raw=arr(result?.structured?.structureProposals);const byRef=new Map(input.contributors.map(c=>[c.contributorRef,c]));const proposals=raw.map(p=>{const refs=unique(p?.contributorRefs),resolved=refs.map(r=>byRef.get(r)).filter(Boolean);return freeze({...p,compositionSemanticClass:text(p?.compositionSemanticClass)||'generic_descriptive_combination',contributorRefs:refs,independenceBasis:{professionalBasisRefs:unique(resolved.flatMap(x=>x.professionalBasisRefs))},persistence:'representation_only',targetInputs:[],providerAuthority:false});});lastRun={status:'ok',input,result,rawProposals:raw,proposals,elapsedMs:Math.round(performance.now()-started)};diagnosticSink?.(freeze({boundary:'pd070l_live_second_order_proposal',stage:'model_call_end',at:now(),elapsedMs:lastRun.elapsedMs,model:text(result.model),inputContributorCount:input.contributors.length,proposalCount:proposals.length}));return proposals;}catch(error){const failure=boundedFailure(error);lastRun={status:'failed',input,error,failure,rawProposals:[],proposals:[],elapsedMs:Math.round(performance.now()-started)};diagnosticSink?.(freeze({boundary:'pd070l_live_second_order_proposal',stage:'model_call_failed',at:now(),elapsedMs:lastRun.elapsedMs,inputContributorCount:input.contributors.length,fallbackReason:failure.failureKind,...failure}));return [];}};
 return freeze({proposalProvider,getLastRun:()=>lastRun});
}
export default createLiveHigherOrderProfessionalSynthesisProvider;
