import { performance } from 'node:perf_hooks';
import { runGroqGroundedRelationshipProposalModel } from '../infrastructure/groq/runGroqGroundedRelationshipProposalModel.js';
const arr=v=>Array.isArray(v)?v:[];const text=v=>typeof v==='string'?v.trim():'';const freeze=v=>{if(Array.isArray(v)){v.forEach(freeze);return Object.freeze(v)}if(v&&typeof v==='object'){Object.values(v).forEach(freeze);return Object.freeze(v)}return v};
function boundedMaterial(m){const materialRef=text(m?.materialRef);const raw=[...arr(m?.exactSupports),text(m?.summary),...arr(m?.facts),...arr(m?.sourceFaithfulExperienceExcerpts)].map(text).filter(Boolean);const unique=[...new Set(raw)].slice(0,8);return {materialRef,sourceId:text(m?.sourceId),episodeRef:text(m?.episodeRef)||null,summary:text(m?.summary),facts:arr(m?.facts).map(text).filter(Boolean).slice(0,8),supports:unique.map((exactText,index)=>({supportRef:`${materialRef}:support:${index+1}`,exactText})),semanticCeiling:m?.semanticCeiling?{...m.semanticCeiling}:null};}
export function buildGroundedRelationshipModelInput({materials=[],locale='it'}={}){return freeze({locale:text(locale)||'it',task:'grounded_descriptive_professional_relationship_proposal',materials:arr(materials).map(boundedMaterial).filter(x=>x.materialRef&&x.sourceId)});}
function systemPrompt(locale){return `You propose source-grounded descriptive professional relationships for IMAGO. Return only the required structured output. Work only from supplied materials and IDs. The model proposes; deterministic validators decide acceptance. Do not invent facts or IDs. Do not infer person capabilities, traits, personality, leadership, seniority, strengths, weaknesses, fit, readiness, employability or recommendations. Do not strengthen participation, responsibility, ownership, decision authority or result causality. Do not use target-relative reasoning or create a universal ontology. Descriptor wording must stay within its claimShape. For relationship hypotheses, the SUBJECT OF THE SYNTHESIS is the documented materials, situations, episodes, activities, phases or function configurations — not the person or the person's career/path. MATERIAL RELATIONSHIP IS NOT PERSON CONTINUITY: related situations, recurring documented configurations and cross-material relationships must not be converted into professional continuity, a stable person property, capability, strength, preference, leadership, seniority or career identity. Ordinary grounded descriptive material relationships must use continuityAssertion=none; professional_continuity is prohibited under this task and remains available in the contract only so deterministic validation can reject an over-strong proposal. RelationshipBasis must state why the documented materials are related; relationshipWording must express that bounded relation naturally and MUST NOT go semantically beyond relationshipBasis. Do not merely concatenate or restate separate facts: propose a meaningful bounded connection between independently documented materials when supported. Relationship wording and claimShape must be semantically consistent and produced together. Do not rely on later rewriting or sanitisation. Prefer few meaningful cross-material connections; omit unsupported hypotheses. Preserve uncertainty. Output relationship wording in ${locale==='en'?'English':'Italian'}.`}
function userPrompt(input){return `Analyse only this bounded authorised Representation material. Descriptor roles should prioritise situation_context, work_phase and involved_function. Ground each descriptor by selecting a supplied supports[].supportRef. You may echo its exactText, but never invent support identities. Relationship hypotheses must reference descriptor proposalRef values and connect at least two independent materials. Describe relationships BETWEEN the documented materials/situations/phases/configurations. For ordinary cross-material relatedness set claimShape.continuityAssertion to none. Do not turn recurrence or related operational phases into professional continuity of the person. Keep relationshipWording within relationshipBasis while still expressing a useful synthesis rather than two disconnected restatements.\n${JSON.stringify(input)}`;}
function safeReason(error){return text(error?.providerDiagnostic?.failureKind)||text(error?.message)||'provider_failure';}
export function createLiveGroundedRelationshipProposalProviders({modelRunner=runGroqGroundedRelationshipProposalModel,diagnosticSink,executionDiagnosticSink,now=()=>new Date().toISOString()}={}){
 let cacheKey=null,cache=null;
 async function obtain({materials=[],locale='it'}={}){const input=buildGroundedRelationshipModelInput({materials,locale});const key=JSON.stringify(input);if(cache&&cacheKey===key)return cache;const started=performance.now();diagnosticSink?.(freeze({boundary:'pd069l_live_proposal',stage:'model_call_start',at:now(),inputMaterialCount:input.materials.length}));try{const result=await modelRunner({systemPrompt:systemPrompt(locale),userPrompt:userPrompt(input),executionDiagnosticSink});const s=result.structured;cacheKey=key;cache={status:'ok',input,result,descriptorProposals:arr(s.descriptorProposals),relationshipHypotheses:arr(s.relationshipHypotheses)};diagnosticSink?.(freeze({boundary:'pd069l_live_proposal',stage:'model_call_end',at:now(),elapsedMs:Math.round(performance.now()-started),model:text(result.model),outputMode:text(result.outputMode),inputMaterialCount:input.materials.length,descriptorProposalCount:cache.descriptorProposals.length,relationshipHypothesisCount:cache.relationshipHypotheses.length}));return cache;}catch(error){cacheKey=key;cache={status:'failed',input,error,descriptorProposals:[],relationshipHypotheses:[]};const providerDiagnostic=error?.providerDiagnostic&&typeof error.providerDiagnostic==='object'?error.providerDiagnostic:{};diagnosticSink?.(freeze({boundary:'pd069l_live_proposal',stage:'model_call_failed',at:now(),elapsedMs:Math.round(performance.now()-started),inputMaterialCount:input.materials.length,fallbackReason:safeReason(error),httpStatus:Number.isFinite(Number(providerDiagnostic.status))?Number(providerDiagnostic.status):null,providerCode:text(providerDiagnostic.providerCode)||null,providerType:text(providerDiagnostic.providerType)||null,providerMessage:text(providerDiagnostic.providerMessage)||null,providerErrorMessage:text(providerDiagnostic.providerErrorMessage)||null,providerFailedGeneration:text(providerDiagnostic.providerFailedGeneration)||null,outputMode:text(providerDiagnostic.outputMode)||null,structuredOutput:providerDiagnostic.structuredOutput===true,attemptCount:Number.isFinite(Number(providerDiagnostic.httpAttemptsUsed))?Number(providerDiagnostic.httpAttemptsUsed):null}));return cache;}}
 const descriptorProposalProvider=async ({materials=[],locale='it'}={})=>{const c=await obtain({materials,locale});if(c.status!=='ok')return [];return c.descriptorProposals.map(p=>freeze({...p,provenance:{providerRef:`groq:${text(c.result.model)||'configured_model'}`,proposalRef:text(p.proposalRef)},persistence:'representation_only'}));};
 const relationshipHypothesisProvider=async ({descriptors=[],materials=[],locale='it'}={})=>{const c=await obtain({materials,locale});if(c.status!=='ok')return [];const acceptedByProposal=new Map(arr(descriptors).map(d=>[text(d?.provenance?.proposalRef),text(d?.descriptorId)]));return c.relationshipHypotheses.map(h=>freeze({descriptorRefs:arr(h.descriptorProposalRefs).map(r=>acceptedByProposal.get(text(r))||`missing:${text(r)}`),relationshipWording:text(h.relationshipWording),relationshipBasis:text(h.relationshipBasis),claimShape:h.claimShape,provenance:{providerRef:`groq:${text(c.result.model)||'configured_model'}`,proposalRef:text(h.proposalRef)},persistence:'representation_only'}));};
 return freeze({descriptorProposalProvider,relationshipHypothesisProvider,getLastRun:()=>cache});
}
export default createLiveGroundedRelationshipProposalProviders;
