import { createHash, randomBytes, scryptSync, createCipheriv, createDecipheriv } from 'node:crypto';
import { validatePrivateBetaProfessionalIdentityContinuityRecord } from './privateBetaProfessionalIdentityContinuity.js';
import { professionalSourceAssetBytes, professionalSourceAssetPublicMetadata, validateProfessionalSourceAsset, validateProfessionalSourceAssetCollection, PROFESSIONAL_SOURCE_ASSET_MAX_COUNT, PROFESSIONAL_SOURCE_ASSET_TOTAL_MAX_BYTES } from './privateBetaProfessionalSourceAssets.js';

export const IMAGO_PROFILE_BACKUP_FORMAT='imago_professional_profile_backup';
export const IMAGO_PROFILE_BACKUP_SCHEMA_VERSION=2;
export const IMAGO_PROFILE_BACKUP_CONTAINER_VERSION=2;
export const IMAGO_PROFILE_BACKUP_PROTECTED_CONTAINER_VERSION=3;
export const IMAGO_PROFILE_BACKUP_KDF='scrypt';
export const IMAGO_PROFILE_BACKUP_CIPHER='aes-256-gcm';
export const IMAGO_PROFILE_BACKUP_SCRYPT=Object.freeze({N:16384,r:8,p:1,keyLength:32,maxmem:64*1024*1024});
export const IMAGO_PROFILE_BACKUP_PASSWORD_MIN_LENGTH=8;
const PROTECTED_MAGIC=Buffer.from('IMAGO3\n','ascii');
export const IMAGO_PROFILE_BACKUP_MAX_BYTES=8_000_000;
export const IMAGO_PROFILE_BACKUP_MAX_ENTRIES=2+PROFESSIONAL_SOURCE_ASSET_MAX_COUNT;
const obj=v=>!!v&&typeof v==='object'&&!Array.isArray(v); const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const txt=v=>typeof v==='string'?v.trim():'';
const stable=v=>Array.isArray(v)?`[${v.map(stable).join(',')}]`:obj(v)?`{${Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')}}`:JSON.stringify(v);
const shaBytes=v=>createHash('sha256').update(v).digest('hex');const sha=v=>shaBytes(Buffer.from(stable(v),'utf8'));
function projectApplicationState(state={}){const out={};for(const k of ['careerPreferenceContext','opportunityUnderstanding','groundedApplicationPackage','applicationArtifacts'])if(state[k]!=null)out[k]=clone(state[k]);return out;}
function projectedProfile(record){return {
  continuityVersion:record.version,
  authorizedMaterials:clone(record.authorizedMaterials||{}),
  professionalSources:clone(record.professionalSources||[]),
  sourceAssets:(record.sourceAssets||[]).map(professionalSourceAssetPublicMetadata),
  reusableKnowledgeResults:clone(record.reusableKnowledgeResults||[]),
  knowledgeRefs:clone(record.knowledgeRefs||[]),
  representationSnapshots:clone(record.representationSnapshots||[]),
  currentRepresentationSnapshotRefs:clone(record.currentRepresentationSnapshotRefs||{}),
  applicationState:projectApplicationState(record.applicationState||{}),
  revision:Number(record.revision)||1,
  createdAt:txt(record.createdAt)||null,
  updatedAt:txt(record.updatedAt)||null
};}
function rejectUnsafe(v,path='backup'){if(typeof v==='string'){if(/(?:sk-|api[_-]?key|bearer\s+[a-z0-9._-]{12,})/i.test(v))throw new Error('PROFILE_BACKUP_SECRET_DETECTED');return;}if(Array.isArray(v)){v.forEach((x,i)=>rejectUnsafe(x,`${path}[${i}]`));return;}if(!obj(v))return;for(const [k,x] of Object.entries(v)){if(/(?:api.?key|secret|token|credential|password|filesystem.?path|local.?path)/i.test(k))throw new Error('PROFILE_BACKUP_SECRET_FIELD');rejectUnsafe(x,`${path}.${k}`);}}
function assetEntryName(asset){return `sources/${asset.assetId.replace(/[^a-zA-Z0-9:_-]/g,'_')}`;}
export function buildProfessionalProfileBackup({record,exportedAt=new Date().toISOString(),locale='it',buildVersion='private-beta'}={}){
  validatePrivateBetaProfessionalIdentityContinuityRecord(record);validateProfessionalSourceAssetCollection(record.sourceAssets||[],{professionalSources:record.professionalSources||[]});
  const profile=projectedProfile(record);rejectUnsafe(profile);
  const payload={profileIdentityMarker:sha({professionalIdentityRef:record.professionalIdentityRef,createdAt:record.createdAt}).slice(0,24),sourcePersonId:record.personRef.id,profile};
  const sourceAssetBytes={};for(const asset of record.sourceAssets||[])sourceAssetBytes[asset.assetId]=professionalSourceAssetBytes(asset);
  const assetManifest=profile.sourceAssets.map(asset=>Object.freeze({...asset,entry:assetEntryName(asset)}));
  const manifest={format:IMAGO_PROFILE_BACKUP_FORMAT,containerVersion:IMAGO_PROFILE_BACKUP_CONTAINER_VERSION,schemaVersion:IMAGO_PROFILE_BACKUP_SCHEMA_VERSION,exportedAt:txt(exportedAt),buildVersion:txt(buildVersion)||'private-beta',locale:locale==='en'?'en':'it',includedSections:Object.freeze(['authorised_source_material','original_source_assets','person_knowledge','professional_representation_resume_state','candidate_controlled_context','application_resume_state']),integrityAlgorithm:'sha256',profileEntry:'profile.json',profileSha256:sha(payload),sourceAssets:Object.freeze(assetManifest)};
  return Object.freeze({format:IMAGO_PROFILE_BACKUP_FORMAT,schemaVersion:IMAGO_PROFILE_BACKUP_SCHEMA_VERSION,containerVersion:IMAGO_PROFILE_BACKUP_CONTAINER_VERSION,manifest:Object.freeze(manifest),payload:Object.freeze(payload),integrity:Object.freeze({payloadSha256:manifest.profileSha256}),sourceAssetBytes:Object.freeze(sourceAssetBytes)});
}
function crc32(buf){let c=0xffffffff;for(const byte of buf){c^=byte;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function zipStore(files){if(files.length>IMAGO_PROFILE_BACKUP_MAX_ENTRIES)throw new Error('PROFILE_BACKUP_TOO_MANY_ENTRIES');const locals=[],centrals=[];let offset=0;for(const [name,dataValue] of files){const data=Buffer.isBuffer(dataValue)?dataValue:Buffer.from(String(dataValue),'utf8'),nameBuf=Buffer.from(name,'utf8'),crc=crc32(data),local=Buffer.alloc(30+nameBuf.length);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0x0800,6);local.writeUInt16LE(0,8);local.writeUInt32LE(crc,14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(nameBuf.length,26);nameBuf.copy(local,30);locals.push(local,data);const central=Buffer.alloc(46+nameBuf.length);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(0x0800,8);central.writeUInt16LE(0,10);central.writeUInt32LE(crc,16);central.writeUInt32LE(data.length,20);central.writeUInt32LE(data.length,24);central.writeUInt16LE(nameBuf.length,28);central.writeUInt32LE(offset,42);nameBuf.copy(central,46);centrals.push(central);offset+=local.length+data.length;}const centralStart=offset,centralSize=centrals.reduce((n,b)=>n+b.length,0),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(0,4);end.writeUInt16LE(0,6);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(centralSize,12);end.writeUInt32LE(centralStart,16);return Buffer.concat([...locals,...centrals,end]);}
function allowedEntryName(name){return name==='manifest.json'||name==='profile.json'||/^sources\/sourceAsset_[a-f0-9]{24}$/.test(name)||/^sources\/sourceAsset:[a-f0-9]{24}$/.test(name);}
function parseZipStore(buffer){if(!Buffer.isBuffer(buffer))buffer=Buffer.from(buffer);if(buffer.length>IMAGO_PROFILE_BACKUP_MAX_BYTES)throw new Error('PROFILE_BACKUP_TOO_LARGE');if(buffer.length<22)throw new Error('PROFILE_BACKUP_INVALID_FORMAT');let eocd=-1;for(let i=buffer.length-22;i>=Math.max(0,buffer.length-65557);i--){if(buffer.readUInt32LE(i)===0x06054b50){eocd=i;break;}}if(eocd<0)throw new Error('PROFILE_BACKUP_INVALID_FORMAT');const count=buffer.readUInt16LE(eocd+10),centralSize=buffer.readUInt32LE(eocd+12),centralOffset=buffer.readUInt32LE(eocd+16);if(count>IMAGO_PROFILE_BACKUP_MAX_ENTRIES||centralOffset+centralSize>eocd)throw new Error('PROFILE_BACKUP_INVALID_ARCHIVE');const out=new Map();let pos=centralOffset,total=0;for(let i=0;i<count;i++){if(pos+46>buffer.length||buffer.readUInt32LE(pos)!==0x02014b50)throw new Error('PROFILE_BACKUP_INVALID_ARCHIVE');const method=buffer.readUInt16LE(pos+10),crc=buffer.readUInt32LE(pos+16),compressed=buffer.readUInt32LE(pos+20),uncompressed=buffer.readUInt32LE(pos+24),nameLen=buffer.readUInt16LE(pos+28),extraLen=buffer.readUInt16LE(pos+30),commentLen=buffer.readUInt16LE(pos+32),localOffset=buffer.readUInt32LE(pos+42);const name=buffer.subarray(pos+46,pos+46+nameLen).toString('utf8');if(method!==0||compressed!==uncompressed)throw new Error('PROFILE_BACKUP_UNSAFE_COMPRESSION');if(!allowedEntryName(name)||name.includes('..')||name.startsWith('/')||name.includes('\\')||out.has(name))throw new Error('PROFILE_BACKUP_UNSAFE_ENTRY');if(localOffset+30>buffer.length||buffer.readUInt32LE(localOffset)!==0x04034b50)throw new Error('PROFILE_BACKUP_INVALID_ARCHIVE');const ln=buffer.readUInt16LE(localOffset+26),le=buffer.readUInt16LE(localOffset+28),start=localOffset+30+ln+le,end=start+compressed;if(end>buffer.length)throw new Error('PROFILE_BACKUP_INVALID_ARCHIVE');const data=buffer.subarray(start,end);if(crc32(data)!==crc)throw new Error('PROFILE_BACKUP_CORRUPTED');total+=uncompressed;if(total>IMAGO_PROFILE_BACKUP_MAX_BYTES)throw new Error('PROFILE_BACKUP_TOO_LARGE');out.set(name,Buffer.from(data));pos+=46+nameLen+extraLen+commentLen;}if(!out.has('manifest.json')||!out.has('profile.json'))throw new Error('PROFILE_BACKUP_INVALID_ARCHIVE');return out;}
export function serializeProfessionalProfileBackup(backup){validateProfessionalProfileBackup(backup);if(backup.schemaVersion===1){const raw=JSON.stringify(backup,null,2);if(Buffer.byteLength(raw,'utf8')>IMAGO_PROFILE_BACKUP_MAX_BYTES)throw new Error('PROFILE_BACKUP_TOO_LARGE');return raw;}const manifest=Buffer.from(JSON.stringify(backup.manifest,null,2),'utf8'),profile=Buffer.from(JSON.stringify(backup.payload,null,2),'utf8'),files=[['manifest.json',manifest],['profile.json',profile]];for(const meta of backup.manifest.sourceAssets||[]){const bytes=backup.sourceAssetBytes?.[meta.assetId];if(!Buffer.isBuffer(bytes))throw new Error('PROFILE_BACKUP_SOURCE_ASSET_MISSING');files.push([meta.entry,bytes]);}const zip=zipStore(files);if(zip.length>IMAGO_PROFILE_BACKUP_MAX_BYTES)throw new Error('PROFILE_BACKUP_TOO_LARGE');return zip;}

function protectedHeaderBytes(header){return Buffer.from(JSON.stringify(header),'utf8');}
function deriveBackupKey(password,salt){const pw=typeof password==='string'?password:'';if(pw.length<IMAGO_PROFILE_BACKUP_PASSWORD_MIN_LENGTH)throw new Error('PROFILE_BACKUP_PASSWORD_TOO_SHORT');return scryptSync(pw,salt,IMAGO_PROFILE_BACKUP_SCRYPT.keyLength,{N:IMAGO_PROFILE_BACKUP_SCRYPT.N,r:IMAGO_PROFILE_BACKUP_SCRYPT.r,p:IMAGO_PROFILE_BACKUP_SCRYPT.p,maxmem:IMAGO_PROFILE_BACKUP_SCRYPT.maxmem});}
export function isProtectedProfessionalProfileBackup(raw){const b=Buffer.isBuffer(raw)?raw:Buffer.from(raw||'');return b.length>=PROTECTED_MAGIC.length&&b.subarray(0,PROTECTED_MAGIC.length).equals(PROTECTED_MAGIC);}
export function serializeProtectedProfessionalProfileBackup(backup,{password}={}){const inner=serializeProfessionalProfileBackup(backup),salt=randomBytes(16),nonce=randomBytes(12),key=deriveBackupKey(password,salt);const header={format:IMAGO_PROFILE_BACKUP_FORMAT,containerVersion:IMAGO_PROFILE_BACKUP_PROTECTED_CONTAINER_VERSION,encrypted:true,kdf:IMAGO_PROFILE_BACKUP_KDF,kdfParameters:{N:IMAGO_PROFILE_BACKUP_SCRYPT.N,r:IMAGO_PROFILE_BACKUP_SCRYPT.r,p:IMAGO_PROFILE_BACKUP_SCRYPT.p,keyLength:IMAGO_PROFILE_BACKUP_SCRYPT.keyLength},salt:salt.toString('base64'),cipher:IMAGO_PROFILE_BACKUP_CIPHER,nonce:nonce.toString('base64'),ciphertextLength:inner.length,tagLength:16};const hb=protectedHeaderBytes(header);if(hb.length>4096)throw new Error('PROFILE_BACKUP_INVALID_SECURITY_HEADER');const cipher=createCipheriv(IMAGO_PROFILE_BACKUP_CIPHER,key,nonce,{authTagLength:16});cipher.setAAD(hb);const ciphertext=Buffer.concat([cipher.update(inner),cipher.final()]),tag=cipher.getAuthTag(),prefix=Buffer.alloc(PROTECTED_MAGIC.length+4);PROTECTED_MAGIC.copy(prefix,0);prefix.writeUInt32BE(hb.length,PROTECTED_MAGIC.length);const out=Buffer.concat([prefix,hb,ciphertext,tag]);if(out.length>IMAGO_PROFILE_BACKUP_MAX_BYTES+8192)throw new Error('PROFILE_BACKUP_TOO_LARGE');return out;}
function decryptProtectedProfessionalProfileBackup(raw,{password}={}){const bytes=Buffer.isBuffer(raw)?raw:Buffer.from(raw);if(!isProtectedProfessionalProfileBackup(bytes))throw new Error('PROFILE_BACKUP_INVALID_FORMAT');if(typeof password!=='string'||password.length===0)throw new Error('PROFILE_BACKUP_PASSWORD_REQUIRED');if(bytes.length<PROTECTED_MAGIC.length+4+16)throw new Error('PROFILE_BACKUP_AUTHENTICATION_FAILED');const headerLen=bytes.readUInt32BE(PROTECTED_MAGIC.length);if(headerLen<2||headerLen>4096)throw new Error('PROFILE_BACKUP_AUTHENTICATION_FAILED');const hs=PROTECTED_MAGIC.length+4,he=hs+headerLen;if(he+16>bytes.length)throw new Error('PROFILE_BACKUP_AUTHENTICATION_FAILED');const hb=bytes.subarray(hs,he);let header;try{header=JSON.parse(hb.toString('utf8'));}catch{throw new Error('PROFILE_BACKUP_AUTHENTICATION_FAILED');}if(header?.format!==IMAGO_PROFILE_BACKUP_FORMAT||header?.containerVersion!==3||header?.encrypted!==true||header?.kdf!==IMAGO_PROFILE_BACKUP_KDF||header?.cipher!==IMAGO_PROFILE_BACKUP_CIPHER)throw new Error('PROFILE_BACKUP_AUTHENTICATION_FAILED');const kp=header.kdfParameters||{};if(kp.N!==IMAGO_PROFILE_BACKUP_SCRYPT.N||kp.r!==IMAGO_PROFILE_BACKUP_SCRYPT.r||kp.p!==IMAGO_PROFILE_BACKUP_SCRYPT.p||kp.keyLength!==IMAGO_PROFILE_BACKUP_SCRYPT.keyLength||header.tagLength!==16)throw new Error('PROFILE_BACKUP_AUTHENTICATION_FAILED');let salt,nonce;try{salt=Buffer.from(header.salt,'base64');nonce=Buffer.from(header.nonce,'base64');}catch{throw new Error('PROFILE_BACKUP_AUTHENTICATION_FAILED');}if(salt.length!==16||nonce.length!==12)throw new Error('PROFILE_BACKUP_AUTHENTICATION_FAILED');const tag=bytes.subarray(bytes.length-16),ciphertext=bytes.subarray(he,bytes.length-16);if(ciphertext.length!==header.ciphertextLength||ciphertext.length>IMAGO_PROFILE_BACKUP_MAX_BYTES)throw new Error('PROFILE_BACKUP_AUTHENTICATION_FAILED');try{const key=deriveBackupKey(password,salt),decipher=createDecipheriv(IMAGO_PROFILE_BACKUP_CIPHER,key,nonce,{authTagLength:16});decipher.setAAD(hb);decipher.setAuthTag(tag);return {inner:Buffer.concat([decipher.update(ciphertext),decipher.final()]),security:{encrypted:true,containerVersion:3,kdf:IMAGO_PROFILE_BACKUP_KDF,cipher:IMAGO_PROFILE_BACKUP_CIPHER}};}catch(error){if(error?.message==='PROFILE_BACKUP_PASSWORD_TOO_SHORT')throw error;throw new Error('PROFILE_BACKUP_AUTHENTICATION_FAILED');}}
export function inspectProfessionalProfileBackupEnvelope(raw){const bytes=Buffer.isBuffer(raw)?raw:Buffer.from(raw||'');if(!isProtectedProfessionalProfileBackup(bytes))return Object.freeze({encrypted:false,containerVersion:bytes[0]===0x50&&bytes[1]===0x4b?2:1});if(bytes.length<PROTECTED_MAGIC.length+4)throw new Error('PROFILE_BACKUP_INVALID_FORMAT');const n=bytes.readUInt32BE(PROTECTED_MAGIC.length);if(n<2||n>4096||PROTECTED_MAGIC.length+4+n>bytes.length)throw new Error('PROFILE_BACKUP_INVALID_FORMAT');let h;try{h=JSON.parse(bytes.subarray(PROTECTED_MAGIC.length+4,PROTECTED_MAGIC.length+4+n).toString('utf8'));}catch{throw new Error('PROFILE_BACKUP_INVALID_FORMAT');}return Object.freeze({encrypted:true,containerVersion:h.containerVersion||3,kdf:h.kdf||null,cipher:h.cipher||null});}

function parseJsonV1(raw){let backup;try{backup=JSON.parse(Buffer.isBuffer(raw)?raw.toString('utf8'):String(raw));}catch{throw new Error('PROFILE_BACKUP_INVALID_FORMAT');}validateProfessionalProfileBackup(backup);return backup;}
export function parseProfessionalProfileBackup(raw,{password}={}){const bytes=Buffer.isBuffer(raw)?raw:Buffer.from(raw);if(bytes.length>IMAGO_PROFILE_BACKUP_MAX_BYTES+8192)throw new Error('PROFILE_BACKUP_TOO_LARGE');if(isProtectedProfessionalProfileBackup(bytes)){const decrypted=decryptProtectedProfessionalProfileBackup(bytes,{password});const backup=parseProfessionalProfileBackup(decrypted.inner);return Object.freeze({...backup,security:decrypted.security});}if(bytes.length>IMAGO_PROFILE_BACKUP_MAX_BYTES)throw new Error('PROFILE_BACKUP_TOO_LARGE');if(bytes[0]!==0x50||bytes[1]!==0x4b)return parseJsonV1(bytes);const entries=parseZipStore(bytes);let manifest,payload;try{manifest=JSON.parse(entries.get('manifest.json').toString('utf8'));payload=JSON.parse(entries.get('profile.json').toString('utf8'));}catch{throw new Error('PROFILE_BACKUP_INVALID_SCHEMA');}if(manifest?.schemaVersion>IMAGO_PROFILE_BACKUP_SCHEMA_VERSION)throw new Error('PROFILE_BACKUP_NEWER_VERSION');if(manifest?.schemaVersion!==2||manifest?.containerVersion!==2)throw new Error('PROFILE_BACKUP_UNSUPPORTED_VERSION');const sourceAssetBytes={};for(const meta of manifest.sourceAssets||[]){const data=entries.get(meta.entry);if(!data)throw new Error('PROFILE_BACKUP_SOURCE_ASSET_MISSING');sourceAssetBytes[meta.assetId]=data;}if(entries.size!==2+(manifest.sourceAssets||[]).length)throw new Error('PROFILE_BACKUP_UNSAFE_ENTRY');const backup={format:manifest.format,schemaVersion:manifest.schemaVersion,containerVersion:manifest.containerVersion,manifest,payload,integrity:{payloadSha256:manifest.profileSha256},sourceAssetBytes};validateProfessionalProfileBackup(backup);return backup;}
function validateV1(backup){if(!obj(backup)||backup.format!==IMAGO_PROFILE_BACKUP_FORMAT)throw new Error('PROFILE_BACKUP_INVALID_FORMAT');if(backup.schemaVersion>IMAGO_PROFILE_BACKUP_SCHEMA_VERSION)throw new Error('PROFILE_BACKUP_NEWER_VERSION');if(backup.schemaVersion!==1)throw new Error('PROFILE_BACKUP_UNSUPPORTED_VERSION');if(!obj(backup.manifest)||!obj(backup.payload)||!obj(backup.payload.profile)||!obj(backup.integrity))throw new Error('PROFILE_BACKUP_INVALID_SCHEMA');if(sha(backup.payload)!==txt(backup.integrity.payloadSha256))throw new Error('PROFILE_BACKUP_CORRUPTED');const p=backup.payload.profile;if(!obj(p.authorizedMaterials)||!Array.isArray(p.professionalSources)||!Array.isArray(p.reusableKnowledgeResults)||!Array.isArray(p.knowledgeRefs)||!obj(p.applicationState||{}))throw new Error('PROFILE_BACKUP_INVALID_SCHEMA');rejectUnsafe(backup);return true;}
export function validateProfessionalProfileBackup(backup){
 if(!obj(backup)||backup.format!==IMAGO_PROFILE_BACKUP_FORMAT)throw new Error('PROFILE_BACKUP_INVALID_FORMAT');if(backup.schemaVersion===1)return validateV1(backup);if(backup.schemaVersion>IMAGO_PROFILE_BACKUP_SCHEMA_VERSION)throw new Error('PROFILE_BACKUP_NEWER_VERSION');if(backup.schemaVersion!==2||backup.containerVersion!==2)throw new Error('PROFILE_BACKUP_UNSUPPORTED_VERSION');
 if(!obj(backup.manifest)||!obj(backup.payload)||!obj(backup.payload.profile)||!obj(backup.integrity)||backup.manifest.format!==IMAGO_PROFILE_BACKUP_FORMAT||backup.manifest.schemaVersion!==2||backup.manifest.containerVersion!==2)throw new Error('PROFILE_BACKUP_INVALID_SCHEMA');if(sha(backup.payload)!==txt(backup.integrity.payloadSha256)||sha(backup.payload)!==txt(backup.manifest.profileSha256))throw new Error('PROFILE_BACKUP_CORRUPTED');const p=backup.payload.profile;if(!obj(p.authorizedMaterials)||!Array.isArray(p.professionalSources)||!Array.isArray(p.sourceAssets)||!Array.isArray(p.reusableKnowledgeResults)||!Array.isArray(p.knowledgeRefs)||!obj(p.applicationState||{}))throw new Error('PROFILE_BACKUP_INVALID_SCHEMA');if(!Array.isArray(backup.manifest.sourceAssets)||backup.manifest.sourceAssets.length!==p.sourceAssets.length)throw new Error('PROFILE_BACKUP_INVALID_SCHEMA');let total=0;const seen=new Set();for(const meta of backup.manifest.sourceAssets){if(!obj(meta)||seen.has(meta.assetId)||!allowedEntryName(meta.entry))throw new Error('PROFILE_BACKUP_INVALID_SCHEMA');seen.add(meta.assetId);const pm=p.sourceAssets.find(x=>x.assetId===meta.assetId);if(!pm||stable(pm)!==stable(Object.fromEntries(Object.entries(meta).filter(([k])=>k!=='entry'))))throw new Error('PROFILE_BACKUP_INVALID_SCHEMA');const data=backup.sourceAssetBytes?.[meta.assetId];if(!Buffer.isBuffer(data)||data.length!==meta.byteSize||shaBytes(data)!==meta.sha256)throw new Error('PROFILE_BACKUP_CORRUPTED');validateProfessionalSourceAsset({...pm,contentBase64:data.toString('base64')},{professionalSourceRefs:p.professionalSources.map(x=>txt(x.id)).filter(Boolean)});total+=data.length;}if(total>PROFESSIONAL_SOURCE_ASSET_TOTAL_MAX_BYTES)throw new Error('PROFILE_BACKUP_TOO_LARGE');rejectUnsafe({manifest:backup.manifest,payload:backup.payload});return true;
}
function rebind(value,fromId,toId){if(Array.isArray(value))return value.map(x=>rebind(x,fromId,toId));if(!obj(value))return value;const out={};for(const [k,v] of Object.entries(value))out[k]=rebind(v,fromId,toId);if(out.type==='person'&&out.id===fromId)out.id=toId;return out;}
export function restoreProfessionalProfileBackup({backup,destinationPersonRef,now=new Date().toISOString()}={}){
 validateProfessionalProfileBackup(backup);if(!obj(destinationPersonRef)||destinationPersonRef.type!=='person'||!txt(destinationPersonRef.id))throw new Error('PROFILE_BACKUP_DESTINATION_PERSON_REQUIRED');
 const p=clone(backup.payload.profile),oldId=txt(backup.payload.sourcePersonId)||findPersonId(p.reusableKnowledgeResults)||null,reb=oldId&&oldId!==destinationPersonRef.id?rebind(p,oldId,destinationPersonRef.id):p;
 const sourceAssets=backup.schemaVersion===2?(reb.sourceAssets||[]).map(meta=>({...meta,contentBase64:backup.sourceAssetBytes[meta.assetId].toString('base64')})):[];
 const record={version:'1.0',type:'private_beta_professional_identity_continuity',professionalIdentityRef:`professionalIdentity:${destinationPersonRef.id}`,personRef:{type:'person',id:destinationPersonRef.id},owner:'person',authorizedMaterials:reb.authorizedMaterials,professionalSources:reb.professionalSources,sourceAssets,reusableKnowledgeResults:reb.reusableKnowledgeResults,knowledgeRefs:reb.knowledgeRefs,revision:Math.max(1,Number(reb.revision)||1),createdAt:reb.createdAt||txt(now),updatedAt:txt(now),lastEnrichedBySessionRef:null,representationSnapshots:reb.representationSnapshots||[],currentRepresentationSnapshotRefs:reb.currentRepresentationSnapshotRefs||{},applicationState:reb.applicationState||{},portableRestore:{imported:true,sourceSchemaVersion:backup.schemaVersion,restoredAt:txt(now)}};
 validatePrivateBetaProfessionalIdentityContinuityRecord(record,{personRef:destinationPersonRef});return Object.freeze(record);
}
function findPersonId(v){if(Array.isArray(v)){for(const x of v){const id=findPersonId(x);if(id)return id;}return null;}if(!obj(v))return null;if(v.type==='person'&&txt(v.id))return txt(v.id);for(const x of Object.values(v)){const id=findPersonId(x);if(id)return id;}return null;}
export function professionalProfileBackupFilename({record,at=new Date().toISOString()}={}){const iso=txt(at),d=iso.slice(0,10)||'backup',hm=(iso.slice(11,16)||'').replace(':','');return `IMAGO_backup_${d}${hm?'_'+hm:''}.imago`; }
