import { runFringeInterviewMVPSession } from './runFringeInterviewMVPSession.js';
import { advanceInterviewRuntime, collectInterviewReport, buildFinalCandidateReport } from '../interview/index.js';
import buildProReportV2 from '../report/buildProReportV2.js';
import { syncBetaRuntimeProgress, completeBetaRuntimeSession } from './betaRuntimeSessionIntegration.js';
import { assessBetaUserJourney } from './assessBetaUserJourney.js';
import { startPrivateBetaOnboarding, advancePrivateBetaOnboarding } from './privateBetaOnboarding.js';
import { createPrivateBetaConsent, decidePrivateBetaConsent, assertPrivateBetaDataUseAllowed } from './privateBetaPrivacyConsent.js';
import { createPrivateBetaFeedback, submitPrivateBetaFeedback, skipPrivateBetaFeedback } from './privateBetaFeedback.js';
import { runGroqParserModel } from '../parser/adapters/index.js';
import { buildRepresentationValueProofProjection } from './buildRepresentationValueProofProjection.js';
import { buildAcceptedRuntimeAnswerEvidenceStore } from './registerAcceptedRuntimeAnswerEvidence.js';
import { runAcceptedRuntimeAnswerKnowledgeVerticalSlice } from './runAcceptedRuntimeAnswerKnowledgeVerticalSlice.js';
import { buildPrivateBetaOperationalEvent, emitPrivateBetaOperationalEvent, recordPrivateBetaInterruption } from './privateBetaOperationalLogging.js';
const txt=v=>typeof v==='string'?v.trim():'';
const q=r=>{const s=r?.currentStep,p=s?.payload||{};return s?{stepType:s.stepType||'',phaseName:s.phaseName||'',question:txt(p.question||p.prompt||p.questionText||p.resolvedQuestionText||p.renderedQuestion||p.openingPrompt||p.closingPrompt||p.text||p.leadIn||p.openingScript||p.closingLeadIn||s.question||s.prompt||s.label)}:null;};
const qHistory=r=>{const s=r?.currentStep,p=s?.payload||{};if(!s)return null;const key=txt(p.questionKey||p.key||p.resolvedQuestionKey||p.structuredQuestionKey||p.familyKey||p.blockType||s.stepType);if(!key)return null;return Object.freeze({key,category:txt(p.category||p.familyKey||s.phaseName),signals:Array.isArray(p.expectedSignals)?p.expectedSignals.filter(x=>typeof x==='string'&&x.trim()).map(x=>x.trim()):[]});};
async function emit(st,eventType,boundary,outcome,errorCode=null){await emitPrivateBetaOperationalEvent(buildPrivateBetaOperationalEvent({eventId:`${st.sessionId}:${boundary}:${eventType}:${st.seq++}`,sessionId:st.sessionId,eventType,boundary,outcome,errorCode,now:st.now()}),st.sink);}
function onboarding(i){let s=startPrivateBetaOnboarding();for(const c of [i.identityAction==='recover'?'recover':'create',i.workingMode==='with_tutor'?'with_tutor':'independent','prepare_interview'])s=advancePrivateBetaOnboarding(s,c);return s;}
function fb(id,a,c,now){let f=createPrivateBetaFeedback(id,{now:now()});return a==='submit'?submitPrivateBetaFeedback(f,{experience:{clarity:'clear',usefulness:'useful',reportCredibility:'credible'},valueAndDifficulty:{mostValuablePart:'professional_impression',difficulty:'none'},futureIntent:{reuse:'yes',recommend:'yes'}},{comment:txt(c),now:now()}):skipPrivateBetaFeedback(f,{now:now()});}
function code(e){return /429|5\d\d|timeout|network|fetch failed/i.test(String(e?.message||''))?'SERVICE_UNAVAILABLE':'UNEXPECTED_ERROR';}
export async function prepareStagedPrivateBetaJourney({uiInput={},modelAdapter,operationalSink,now=()=>new Date().toISOString(),technicalDiagnosticSink,recentQuestionKeys=[],recentQuestionHistory=[],knowledgeSemanticAuthority=null,knowledgeSubjectRef=null}={}){
 const ob=onboarding(uiInput);let consent=createPrivateBetaConsent(ob,{now:now()});consent=decidePrivateBetaConsent(consent,uiInput.consentDecision,{now:now()});
 if(consent.status!=='accepted')return{publicResult:{status:'blocked',completed:false,phase:'privacy_consent',error:{code:'CONSENT_REFUSED'}},state:null};assertPrivateBetaDataUseAllowed(consent);
 const cvText=txt(uiInput.cvText),jdText=txt(uiInput.jdText),targetRole=txt(uiInput.targetRole);
 const baseAdapter=typeof modelAdapter==='function'?modelAdapter:({task,system,user})=>runGroqParserModel({task,system,user,temperature:0.2}).then(x=>x?.outputText||'');
 const adapter=async r=>{try{return await baseAdapter(r);}catch(e){if(typeof technicalDiagnosticSink==='function'){const m=String(e?.message||'');const failureKind=/429/.test(m)?'provider_rate_limit':/5\d\d/.test(m)?'provider_http_5xx':/timeout|timed out/i.test(m)?'provider_timeout':/fetch failed|network/i.test(m)?'provider_network':'provider_or_model_adapter_error';try{technicalDiagnosticSink(Object.freeze({boundary:'model_adapter',task:String(r?.task||'unknown'),failureKind}));}catch{}}throw e;}};
 try{const out=await runFringeInterviewMVPSession({cvText,jdText,targetRole,modelAdapter:adapter,answers:[],inputMode:'text',uiLocale:txt(uiInput.uiLocale)||'it',sessionLocale:txt(uiInput.sessionLocale)||txt(uiInput.uiLocale)||'it',inputSource:'manual',recentQuestionKeys,recentQuestionHistory});const session=out.fringeInterviewMVPSession;const state={sessionId:session.betaSession.sessionId,onboarding:ob,consent,session,modelAdapter:adapter,sink:operationalSink,now,seq:0,usedQuestionHistory:[],knowledgeSemanticAuthority,knowledgeSubjectRef};await emit(state,'session_started','beta_journey','started');return{publicResult:{status:'interview',completed:false,phase:'interview',sessionRef:state.sessionId,currentQuestion:q(session.interviewRuntime)},state};}catch(e){return{publicResult:{status:'blocked',completed:false,phase:'interview',error:{code:code(e)}},state:null};}
}
export async function answerStagedPrivateBetaJourney({state,answer,feedbackAction='skip',feedbackComment=''}={}){
 if(!state?.session?.interviewRuntime)throw new Error('PRIVATE_BETA_STAGED_SESSION_REQUIRED');const answerText=txt(answer);if(!answerText)return{publicResult:{status:'interview',completed:false,phase:'interview',sessionRef:state.sessionId,currentQuestion:q(state.session.interviewRuntime),error:{code:'ANSWER_REQUIRED'}},state};
 try{const answeredQuestion=qHistory(state.session.interviewRuntime);const advanced=await advanceInterviewRuntime({interviewSession:state.session.interviewSession,interviewRuntime:state.session.interviewRuntime,answerText,modelAdapter:state.modelAdapter});const runtime=advanced.interviewRuntime;if(answeredQuestion&&!state.usedQuestionHistory.some(x=>x.key===answeredQuestion.key))state.usedQuestionHistory.push(answeredQuestion);let betaSession=syncBetaRuntimeProgress(state.session.betaSession,{runtime,now:state.now});const imagoEvidenceStore=buildAcceptedRuntimeAnswerEvidenceStore({betaSessionId:state.sessionId,interviewSessionId:state.session?.interviewSession?.id||state.sessionId,answers:runtime?.runtimeState?.answers||[]});let runtimeKnowledge=null;
if(state.knowledgeSemanticAuthority&&state.knowledgeSubjectRef){
 const acceptedAnswers=runtime?.runtimeState?.answers||[];
 const latestAcceptedAnswer=acceptedAnswers[acceptedAnswers.length-1];
 if(latestAcceptedAnswer) runtimeKnowledge=runAcceptedRuntimeAnswerKnowledgeVerticalSlice({
  betaSessionId:state.sessionId,
  interviewSessionId:state.session?.interviewSession?.id||state.sessionId,
  acceptedAnswer:latestAcceptedAnswer,
  subjectRef:state.knowledgeSubjectRef,
  semanticAuthority:state.knowledgeSemanticAuthority,
  now:state.now()
 });
}
state.session={...state.session,interviewRuntime:runtime,betaSession,imagoEvidenceStore,runtimeKnowledge};if(!runtime?.runtimeState?.isCompleted)return{publicResult:{status:'interview',completed:false,phase:'interview',sessionRef:state.sessionId,currentQuestion:q(runtime)},state};
 const interviewReport=collectInterviewReport({interviewRuntime:runtime}).interviewReport;const finalCandidateReport=buildFinalCandidateReport({candidateProfile:state.session.parserResult.candidateProfile,roleProfile:state.session.parserResult.roleProfile,jobFitAnalysis:state.session.parserResult.jobFitAnalysis,interviewReport}).finalCandidateReport;const professionalPerceptionReport=buildProReportV2({candidate:state.session.parserResult.candidateProfile,role:state.session.parserResult.roleProfile,fit:state.session.parserResult.jobFitAnalysis,report:interviewReport,finalCandidateReport,runtimeAnswers:runtime?.runtimeState?.answers||[],openingPositioning:finalCandidateReport.openingPositioning,localeKey:finalCandidateReport.locale||'it',rawInput:{targetRole:state.session.rawInput?.targetRole||''}}).proReportV2;betaSession=completeBetaRuntimeSession(betaSession,{runtime,resultRef:{type:'final_candidate_report',id:`${state.sessionId}_final_candidate_report`},now:state.now});const representationValueProof=buildRepresentationValueProofProjection({professionalPerceptionReport,targetRole:state.session.rawInput?.targetRole||'',candidateProfile:state.session.parserResult.candidateProfile,jobFitAnalysis:state.session.parserResult.jobFitAnalysis});const completed={...state.session,interviewRuntime:runtime,interviewReport,finalCandidateReport,professionalPerceptionReport,representationValueProof,betaSession};completed.betaUserJourney=assessBetaUserJourney(completed);state.session=completed;return{publicResult:{status:'feedback',completed:false,phase:'feedback',sessionRef:state.sessionId,report:{available:true,professionalPerceptionReport,representationValueProof}},state};
 }catch(e){await emit(state,'application_error','beta_journey','failed',code(e));await recordPrivateBetaInterruption({eventId:`${state.sessionId}:beta_journey:session_interrupted:${state.seq++}`,sessionId:state.sessionId,boundary:'beta_journey',now:state.now(),sink:state.sink});return{publicResult:{status:'blocked',completed:false,phase:'interview',sessionRef:state.sessionId,error:{code:code(e)}},state};}
}

export async function finalizeStagedPrivateBetaJourney({state,feedbackAction='skip',feedbackComment=''}={}){ if(!state?.session?.interviewRuntime?.runtimeState?.isCompleted) throw new Error('PRIVATE_BETA_STAGED_INTERVIEW_NOT_COMPLETED'); const feedback=fb(state.sessionId,feedbackAction,feedbackComment,state.now); await emit(state,'session_completed','beta_journey','completed'); return {publicResult:{status:'completed_with_gap',completed:true,phase:'experience_closed',sessionRef:state.sessionId,report:{available:true,professionalPerceptionReport:state.session.professionalPerceptionReport,representationValueProof:state.session.representationValueProof},feedback,betaSession:state.session.betaSession},state}; }
