import { loadPrivateBetaUiMessages } from "../i18n/loadPrivateBetaUiMessages.js";
function escapeHtml(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");}
function reportBlock(m,result){if(!result?.report?.available)return "";const projection=result.report.representationValueProof;const claims=Array.isArray(projection?.claims)?projection.claims:[];if(claims.length){return `<section><h2>${escapeHtml(m.valueProofTitle)}</h2><p>${escapeHtml(m.valueProofIntro)}</p>${claims.map(c=>`<article class="value-proof-claim"><h3>${escapeHtml(c.claim)}</h3><details><summary>${escapeHtml(m.valueProofWhy)}</summary><p><strong>${escapeHtml(m.valueProofStatus)}:</strong> ${escapeHtml(m['valueProofStatus_'+c.epistemicStatus]||c.epistemicStatus)}</p>${c.supportingEvidence?.length?`<h4>${escapeHtml(m.valueProofEvidence)}</h4><ul>${c.supportingEvidence.map(e=>`<li>${escapeHtml(e.summary)}</li>`).join("")}</ul>`:""}${c.uncertainty?.length?`<h4>${escapeHtml(m.valueProofUncertain)}</h4><ul>${c.uncertainty.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul>`:""}${c.targetRelation?.summary?`<h4>${escapeHtml(m.valueProofTarget)}</h4><p>${escapeHtml(c.targetRelation.summary)}</p>`:""}</details></article>`).join("")}</section>`;}const p=result.report.professionalPerceptionReport?.professionalPerception?.perceptionV2||{};const messages=[p?.whoEmerges?.narrative,p?.credibilityAssets?.narrative,p?.targetDistance?.bridgeNarrative].filter(Boolean).slice(0,3);return `<section><h2>${escapeHtml(m.report)}</h2>${messages.map(x=>`<p>${escapeHtml(x)}</p>`).join("")}</section>`;}
export function renderPrivateBetaUiJourneyHtml({locale="it",result=null}={}){
 const m=loadPrivateBetaUiMessages(locale); const phase=result?.phase||"start"; let content="";
 if(phase==="interview"&&result?.currentQuestion){content=`<section><h2>${escapeHtml(m.interviewTitle)}</h2><small>${escapeHtml(m.interviewProgress)}</small><p id="runtime-question"><strong>${escapeHtml(m.questionLabel)}:</strong> ${escapeHtml(result.currentQuestion.question)}</p><form method="post" action="/private-beta/interview/answer"><input type="hidden" name="sessionRef" value="${escapeHtml(result.sessionRef)}"><label>${escapeHtml(m.answerLabel)}</label><textarea name="answer" rows="7" required></textarea><button type="submit">${escapeHtml(m.continueInterview)}</button></form></section>`;}
 else if(phase==="feedback"){content=`${reportBlock(m,result)}<section><h2>${escapeHtml(m.feedbackTitle)}</h2><form method="post" action="/private-beta/feedback"><input type="hidden" name="sessionRef" value="${escapeHtml(result.sessionRef)}"><label>${escapeHtml(m.feedbackAction)}</label><select name="feedbackAction"><option value="skip">${escapeHtml(m.feedbackSkip)}</option><option value="submit">${escapeHtml(m.feedbackSubmit)}</option></select><label>${escapeHtml(m.comment)}</label><textarea name="feedbackComment" rows="3"></textarea><button type="submit">${escapeHtml(m.next)}</button></form></section>`;}
 else if(result?.completed){content=`${reportBlock(m,result)}<section id="beta-result"><h2>${escapeHtml(m.resultTitle)}</h2><p>${escapeHtml(m.completed)}</p></section>`;}
 else {const err=result?.error?`<section id="beta-result"><p>${escapeHtml(m.safeError)}</p></section>`:"";content=`<form method="post" action="/private-beta/journey" id="private-beta-form"><section><h2>${escapeHtml(m.onboardingTitle)}</h2><label>${escapeHtml(m.identityLabel)}</label><select name="identityAction"><option value="create">${escapeHtml(m.identityCreate)}</option><option value="recover">${escapeHtml(m.identityRecover)}</option></select><label>${escapeHtml(m.modeLabel)}</label><select name="workingMode"><option value="independent">${escapeHtml(m.modeIndependent)}</option><option value="with_tutor">${escapeHtml(m.modeTutor)}</option></select><label>${escapeHtml(m.goalLabel)}</label><input value="${escapeHtml(m.goalInterview)}" disabled></section><section><h2>${escapeHtml(m.consentTitle)}</h2><select name="consentDecision" id="consentDecision"><option value="accept">${escapeHtml(m.consentAccept)}</option><option value="refuse">${escapeHtml(m.consentRefuse)}</option></select></section><section id="materialsSection"><h2>${escapeHtml(m.materialsTitle)}</h2><label>${escapeHtml(m.targetRole)}</label><input name="targetRole"><label>${escapeHtml(m.cv)}</label><textarea name="cvText" rows="8"></textarea><label>${escapeHtml(m.jd)}</label><textarea name="jdText" rows="6"></textarea></section><input type="hidden" name="feedbackAction" value="skip"><input type="hidden" name="uiLocale" value="${escapeHtml(locale)}"><input type="hidden" name="sessionLocale" value="${escapeHtml(locale)}"><button type="submit">${escapeHtml(m.prepareInterview)}</button></form>${err}<script>(()=>{const c=document.getElementById('consentDecision'),g=document.getElementById('materialsSection');function s(){const a=c.value==='accept';g.hidden=!a;g.querySelectorAll('input,textarea,select').forEach(f=>f.disabled=!a)}c.addEventListener('change',s);s()})();</script>`;}
 return `<!doctype html><html lang="${escapeHtml(locale)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(m.title)}</title><style>body{font-family:Arial,sans-serif;max-width:880px;margin:0 auto;padding:24px;background:#f5f7fb;color:#1f2937}section{background:white;border:1px solid #d9e1ea;border-radius:12px;padding:18px;margin:14px 0}label{display:block;font-weight:700;margin:10px 0 5px}input,textarea,select{width:100%;box-sizing:border-box;padding:10px;border:1px solid #b9c4d0;border-radius:8px}button{padding:11px 16px;font-weight:700}small{color:#596579}</style></head><body><h1>${escapeHtml(m.title)}</h1><p>${escapeHtml(m.intro)}</p>${content}</body></html>`;
}
export default renderPrivateBetaUiJourneyHtml;
