import { createProfessionalMaterialRelevanceRelation } from '../professionalMaterialRelevance.js';
const text=v=>typeof v==='string'?v.trim():'';
const arr=v=>Array.isArray(v)?v:[];
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const freeze=v=>Object.freeze(clone(v));
export const ROLE_REQUIREMENT_TYPES=Object.freeze(['responsibility','knowledge','capability','experience_exposure','credential_qualification','contextual_expectation']);
export const ROLE_REQUIREMENT_STRENGTHS=Object.freeze(['core_common','context_dependent']);
export const DIRECTION_RELATION_TYPES=Object.freeze(['supported_relevance','insufficiently_observed','material_contradiction']);
export const PEOPLE_REQUIREMENT_CLASSES=Object.freeze(['generic_people_coordination','formal_continuing_people_responsibility','unspecified']);
export const RESPONSIBILITY_FORMALITY=Object.freeze(['formal','informal_or_operational','unspecified']);
export const CONTINUITY_REQUIREMENTS=Object.freeze(['continuing','episodic','unspecified']);
const assert=(c,m)=>{if(!c)throw new Error(m);};
export function createRoleRequirement(x={}){assert(text(x.id),'ROLE_REQUIREMENT_ID_REQUIRED');assert(ROLE_REQUIREMENT_TYPES.includes(x.type),'ROLE_REQUIREMENT_TYPE_INVALID');assert(text(x.statement),'ROLE_REQUIREMENT_STATEMENT_REQUIRED');assert(ROLE_REQUIREMENT_STRENGTHS.includes(x.strength),'ROLE_REQUIREMENT_STRENGTH_INVALID');assert(arr(x.sourceSupport).length,'ROLE_REQUIREMENT_PROVENANCE_REQUIRED');for(const s of x.sourceSupport)assert(text(s.sourceRef)&&text(s.sourceClass)&&text(s.sourcePropositionRef)&&text(s.observedAt)&&text(s.supportRole),'ROLE_REQUIREMENT_SOURCE_SUPPORT_INVALID');const authority=x.requirementAuthority||null;if(authority){assert(PEOPLE_REQUIREMENT_CLASSES.includes(authority.requirementClass),'ROLE_REQUIREMENT_CLASS_INVALID');assert(RESPONSIBILITY_FORMALITY.includes(authority.responsibilityFormality),'ROLE_REQUIREMENT_FORMALITY_INVALID');assert(CONTINUITY_REQUIREMENTS.includes(authority.continuityRequirement),'ROLE_REQUIREMENT_CONTINUITY_INVALID');assert(text(authority.responsibilityScope)&&text(authority.authorityRef),'ROLE_REQUIREMENT_AUTHORITY_INVALID');assert(arr(authority.sourceBasisRefs).length,'ROLE_REQUIREMENT_AUTHORITY_PROVENANCE_REQUIRED');}return freeze({...x,material:Boolean(x.material),sourceSupport:arr(x.sourceSupport),limitations:arr(x.limitations),requirementAuthority:authority});}
export function createRoleCareerDirectionRepresentation(x={}){assert(text(x.id),'ROLE_REPRESENTATION_ID_REQUIRED');assert(x.type==='role_career_direction_representation','ROLE_REPRESENTATION_TYPE_INVALID');assert(text(x.roleIdentity?.canonicalLabel),'ROLE_IDENTITY_REQUIRED');assert(text(x.scope?.function),'ROLE_SCOPE_REQUIRED');assert(arr(x.requirements).length,'ROLE_REQUIREMENTS_REQUIRED');const requirements=x.requirements.map(createRoleRequirement);assert(text(x.version?.roleVersion)&&text(x.version?.recipeVersion)&&text(x.version?.materializedAt)&&text(x.version?.sourceStateRef),'ROLE_VERSION_REQUIRED');return freeze({...x,requirements,contextualVariants:arr(x.contextualVariants),sourceRefs:arr(x.sourceRefs),limitations:arr(x.limitations),metadata:x.metadata||{},extensions:x.extensions||{}});}
export function createDirectionSupportRelation(x={}){assert(text(x.id),'DIRECTION_RELATION_ID_REQUIRED');assert(text(x.personMeaningRef)&&text(x.roleRequirementRef),'DIRECTION_RELATION_REFS_REQUIRED');assert(DIRECTION_RELATION_TYPES.includes(x.relationType),'DIRECTION_RELATION_TYPE_INVALID');if(x.relationType==='supported_relevance'){const relation=createProfessionalMaterialRelevanceRelation({id:x.id,purpose:'professional_direction_explore',personMaterialRef:x.personMeaningRef,contextRef:x.contextRef||x.directionRef,externalRequirementRef:x.roleRequirementRef,relationType:x.relationType,explanationBasis:x.supportExplanation,provenance:{personSupport:x.provenance?.personSupport,externalSupport:arr(x.provenance?.roleSupport)},limitations:x.limitations,metadata:x.metadata});return freeze({...relation,personMeaningRef:x.personMeaningRef,roleRequirementRef:x.roleRequirementRef,supportExplanation:x.supportExplanation,provenance:{personSupport:relation.provenance.personSupport,externalSupport:relation.provenance.externalSupport,roleSupport:relation.provenance.externalSupport}});}return freeze({...x,limitations:arr(x.limitations),metadata:x.metadata||{}});}
export function createConditionToVerify(x={}){assert(text(x.id)&&text(x.roleRequirementRef),'DIRECTION_CONDITION_REQUIRED');assert(x.currentState==='insufficiently_observed','DIRECTION_CONDITION_STATE_INVALID');assert(text(x.reason)&&text(x.materialityBasis),'DIRECTION_CONDITION_MATERIALITY_REQUIRED');return freeze({...x,personStateRefs:arr(x.personStateRefs),limitations:arr(x.limitations)});}
export function createDirectionExplorationContext(x={}){return freeze({type:'direction_exploration_context',preferredThemes:arr(x.preferredThemes),avoidedConditions:arr(x.avoidedConditions),geographyConstraints:arr(x.geographyConstraints),mobilityConstraints:arr(x.mobilityConstraints),workContextPreferences:arr(x.workContextPreferences),explicitDirectionRequests:arr(x.explicitDirectionRequests),uncertainties:arr(x.uncertainties),preferenceState:['declared','uncertain','no_preference'].includes(x.preferenceState)?x.preferenceState:null});}
export function createDirectionPreferenceBasis(x={}){assert(text(x.id)&&text(x.preferenceRef)&&text(x.roleRepresentationRef),'DIRECTION_PREFERENCE_BASIS_REQUIRED');assert(['preferred_theme','explicit_direction_request'].includes(x.influenceType),'DIRECTION_PREFERENCE_INFLUENCE_INVALID');return freeze({...x,candidateDeclared:true,limitations:arr(x.limitations)});}
export function createCareerDirectionHypothesis(x={}){assert(x.type==='career_direction_hypothesis','CAREER_DIRECTION_TYPE_INVALID');assert(x.purpose==='professional_direction_explore','CAREER_DIRECTION_PURPOSE_INVALID');for(const k of ['id','directionRef','roleRepresentationRef','professionalRepresentationRef','whyWorthExploring','roleVersion','recipeVersion','evaluatedAt'])assert(text(x[k]),`CAREER_DIRECTION_${k.toUpperCase()}_REQUIRED`);assert(arr(x.supportBasis).some(r=>r?.relationType==='supported_relevance')||arr(x.preferenceBasis).length,'CAREER_DIRECTION_EXPLORATION_BASIS_REQUIRED');for(const forbidden of ['readinessScore','fitScore','recommendedRank'])assert(!(forbidden in x),'CAREER_DIRECTION_SCORE_FORBIDDEN');return freeze({...x,supportBasis:arr(x.supportBasis),preferenceBasis:arr(x.preferenceBasis),conditionsToVerify:arr(x.conditionsToVerify),insufficientlyObserved:arr(x.insufficientlyObserved),materialContradictions:arr(x.materialContradictions),assumptions:arr(x.assumptions),limitations:arr(x.limitations),metadata:x.metadata||{},extensions:x.extensions||{}});}
