import { createCareerDirectionHypothesis,createConditionToVerify,createDirectionExplorationContext,createDirectionSupportRelation,createDirectionPreferenceBasis } from './contracts.js';
import { CURATED_ROLE_REPRESENTATIONS } from './roleFixtures.js';
import { buildCareerDirectionRequirementSupportProjection } from './requirementSupportAuthority.js';
import { deriveTemporalRequirementSupport,aggregateTemporalRequirementSupport } from './temporalRequirementSupportAuthority.js';
const arr=v=>Array.isArray(v)?v:[];const text=v=>typeof v==='string'?v.trim():'';
export const CAREER_DIRECTION_EVALUATION_RECIPE=Object.freeze({id:'career_direction_minimal_evaluation',version:'1.3'});
export const DIRECTION_MAPPING_POLICY=Object.freeze([
 {personKind:'documented_cross_functional_coordination_recurrence',roleRequirementSemanticKey:'cross_functional_coordination',relationType:'supported_relevance'},
 {personKind:'bounded_decision_accountability',roleFamilyRef:'operations_management',roleRequirementSemanticKey:'broader_operational_decision_context',relationType:'supported_relevance'},
 {personKind:'formal_role_continuity',roleFamilyRef:'industrial_production_management',roleRequirementSemanticKey:'manufacturing_production_continuity',relationType:'supported_relevance'},
 {personKind:'bounded_measurable_outcome_contribution',roleFamilyRef:'industrial_production_management',roleRequirementSemanticKey:'production_performance_scope',relationType:'supported_relevance'},
 {personKind:'bounded_continuing_people_responsibility',roleRequirementSemanticKey:'people_responsibility',relationType:'supported_relevance'},
 {personKind:'bounded_resource_budget_responsibility',roleRequirementSemanticKey:'budget_resource_scope',relationType:'supported_relevance'},
 {personKind:'bounded_production_planning_scheduling_responsibility',roleRequirementSemanticKey:'production_planning_resource_scope',relationType:'supported_relevance'}
]);
export const DIRECTION_PREFERENCE_EXPLORATION_POLICY=Object.freeze([
 {preferenceType:'preferred_theme',preferenceValue:'people_coordination',roleFamilyRefs:['operations_management','industrial_production_management']},
 {preferenceType:'preferred_theme',preferenceValue:'operations_coordination',roleFamilyRefs:['operations_management']},
 {preferenceType:'preferred_theme',preferenceValue:'production_operations',roleFamilyRefs:['industrial_production_management']}
]);
function preferenceBases(role,context){
 if(context.preferenceState==='no_preference')return [];
 const out=[];
 for(const theme of arr(context.preferredThemes))for(const policy of DIRECTION_PREFERENCE_EXPLORATION_POLICY){if(policy.preferenceType==='preferred_theme'&&policy.preferenceValue===theme&&policy.roleFamilyRefs.includes(role.roleIdentity.familyRef))out.push(createDirectionPreferenceBasis({id:`directionPreference:${role.id}:preferred_theme:${theme}`,preferenceRef:`careerPreference:preferredTheme:${theme}`,roleRepresentationRef:role.id,influenceType:'preferred_theme',preferenceValue:theme,explanationKey:theme,limitations:['Candidate preference guides exploration only; it is not professional support, fit, readiness, or capability evidence.']}));}
 const requested=arr(context.explicitDirectionRequests).map(x=>text(x).toLowerCase());
 const roleKeys=[role.id,role.roleIdentity.familyRef,role.roleIdentity.canonicalLabel,...arr(role.roleIdentity.aliases)].map(x=>text(x).toLowerCase());
 for(const request of requested)if(roleKeys.includes(request))out.push(createDirectionPreferenceBasis({id:`directionPreference:${role.id}:explicit_direction_request:${request.replace(/[^a-z0-9]+/g,'_')}`,preferenceRef:`careerPreference:explicitDirectionRequest:${request}`,roleRepresentationRef:role.id,influenceType:'explicit_direction_request',preferenceValue:request,explanationKey:'explicit_direction_request',limitations:['Candidate-requested exploration does not establish professional support, fit, readiness, or capability.']}));
 return [...new Map(out.map(x=>[x.id,x])).values()];
}

function personMeanings(representation){
 const pm=representation?.professionalMeaning||{},out=[];
 for(const [i,p] of arr(pm.supportedPatterns).entries())out.push({ref:`professionalMeaning:supportedPattern:${i}:${p.kind}`,kind:p.kind,value:p,displayKind:p.kind});
 const ps=pm.professionalSynthesis||{};
 if(ps.hasDocumentedRoleContinuity)out.push({ref:'professionalMeaning:professionalSynthesis:formal_role_continuity',kind:'formal_role_continuity',value:{currentRole:ps.currentRole,previousRoles:arr(ps.previousRoles),domains:arr(ps.domains)},displayKind:'formal_role_continuity'});
 for(const [i,k] of arr(pm.knowledgeContribution).entries()){const primary=k?.primaryProfessionalMeaning;if(primary?.kind)out.push({ref:`professionalMeaning:knowledgeContribution:${i}:${primary.kind}`,kind:primary.kind,value:primary,displayKind:primary.kind});}
 return out;
}
function roleSourceSummary(req){return req.sourceSupport.map(s=>({sourceRef:s.sourceRef,sourceClass:s.sourceClass,sourcePropositionRef:s.sourcePropositionRef,observedAt:s.observedAt,scope:s.scope,independenceGroupRef:s.independenceGroupRef||null,displayName:s.displayName||null,publisher:s.publisher||null,sourceTitle:s.sourceTitle||null,url:s.url||null}));}
function existingSupportRobustness(meaning){if(meaning?.kind==='documented_cross_functional_coordination_recurrence'&&new Set(arr(meaning?.value?.episodeRefs).filter(Boolean)).size>=2)return 'INDEPENDENT_RECURRENT_BASIS';return 'SINGLE_GROUNDED_BASIS';}
function supportExplanation(kind){return ({documented_cross_functional_coordination_recurrence:'recurring_cross_functional_coordination',bounded_decision_accountability:'bounded_decision_accountability',formal_role_continuity:'industrialization_to_production_role_continuity',bounded_measurable_outcome_contribution:'bounded_measurable_outcome_contribution',bounded_continuing_people_responsibility:'bounded_continuing_people_responsibility',bounded_resource_budget_responsibility:'bounded_resource_budget_responsibility',bounded_production_planning_scheduling_responsibility:'bounded_production_planning_scheduling_responsibility'})[kind]||kind;}
function distinctiveMeaning(role,relations){const kinds=new Set(relations.map(r=>r.metadata?.personMeaningKind));if(role.roleIdentity.familyRef==='operations_management'&&kinds.has('bounded_decision_accountability'))return 'broader_operational_coordination_and_decision_contexts';if(role.roleIdentity.familyRef==='industrial_production_management'&&kinds.has('formal_role_continuity'))return kinds.has('bounded_measurable_outcome_contribution')?'manufacturing_role_continuity_and_production_results':'manufacturing_role_continuity';return 'recurring_cross_functional_coordination';}
function conditionReason(req){if(req.semanticKey==='people_responsibility')return 'people_responsibility_scope';if(req.semanticKey==='production_planning_resource_scope')return 'production_planning_scope';if(req.semanticKey==='budget_resource_scope')return 'broader_resource_budget_scope';return `role_requirement_scope:${req.semanticKey}`;}
function collectSourceRefs(value,out=new Set()){if(Array.isArray(value)){for(const x of value)collectSourceRefs(x,out);return out;}if(value&&typeof value==='object'){for(const [k,v] of Object.entries(value)){if((k==='sourceRef'||k==='sourceId')&&typeof v==='string'&&v.trim())out.add(v.trim().replace(/^source:/,''));else if(k==='sourceRefs'&&Array.isArray(v))for(const x of v)if(typeof x==='string'&&x.trim())out.add(x.trim().replace(/^source:/,''));else collectSourceRefs(v,out);} }return out;}
function inferredSupportRoleRefs(relation,exposures){const refs=collectSourceRefs(relation?.provenance);return arr(exposures).filter(e=>arr(e?.provenance?.sourceRefs).some(s=>refs.has(String(s).replace(/^source:/,'')))).map(e=>e.roleRef);}
export function evaluateCareerDirections({professionalRepresentation,professionalRepresentationRef,roles=CURATED_ROLE_REPRESENTATIONS,explorationContext={},requirementSupportProposals=[],sustainedRoleExposures=[],requirementSupportRoleRefs={},now='2026-09-10T00:00:00.000Z'}={}){
 const context=createDirectionExplorationContext(explorationContext),meanings=personMeanings(professionalRepresentation),out=[];
 for(const role of roles){const relations=[];const richProjection=buildCareerDirectionRequirementSupportProjection({professionalMeaning:professionalRepresentation?.professionalMeaning||{},role,proposals:requirementSupportProposals});for(const mapping of DIRECTION_MAPPING_POLICY){if(mapping.roleFamilyRef&&mapping.roleFamilyRef!==role.roleIdentity.familyRef)continue;const meaning=meanings.find(x=>x.kind===mapping.personKind);const req=role.requirements.find(r=>r.semanticKey===mapping.roleRequirementSemanticKey);if(meaning&&req&&req.material)relations.push(createDirectionSupportRelation({id:`directionRelation:${role.id}:${meaning.kind}:${req.id}`,directionRef:role.id,contextRef:role.id,personMeaningRef:meaning.ref,roleRequirementRef:req.id,relationType:mapping.relationType,supportExplanation:supportExplanation(meaning.kind),provenance:{personSupport:meaning.value,roleSupport:roleSourceSummary(req)},limitations:['This relation establishes bounded professional relevance only; it does not establish overall role fit, readiness, or stable capability.'],metadata:{personMeaningKind:meaning.kind,roleRequirementSemanticKey:req.semanticKey,supportRobustnessClass:existingSupportRobustness(meaning)}}));}
  for(const aggregate of richProjection.aggregates){const req=role.requirements.find(r=>r.id===aggregate.targetRequirementRef);if(!req)continue;const existingIndex=relations.findIndex(r=>r.roleRequirementRef===req.id);if(existingIndex>=0){const existing=relations[existingIndex];relations[existingIndex]=Object.freeze({...existing,provenance:Object.freeze({...existing.provenance,richRequirementSupport:Object.freeze({relations:aggregate.relations})}),metadata:Object.freeze({...existing.metadata,requirementSupportAggregate:aggregate})});continue;}relations.push(createDirectionSupportRelation({id:`directionRelation:${role.id}:rich:${req.id}`,directionRef:role.id,contextRef:role.id,personMeaningRef:`requirementSupport:${aggregate.acceptedContributorRefs.join('|')}`,roleRequirementRef:req.id,relationType:'supported_relevance',supportExplanation:'rich_authorised_requirement_support',provenance:{personSupport:{requirementSupportRelations:aggregate.relations},roleSupport:roleSourceSummary(req)},limitations:['Target-relative documented support only; it does not establish fit, readiness, capability strength, or Person truth.'],metadata:{personMeaningKind:'rich_authorised_requirement_support',roleRequirementSemanticKey:req.semanticKey,requirementSupportAggregate:aggregate}}));}
  const preferences=preferenceBases(role,context);
  if(!relations.some(x=>x.relationType==='supported_relevance')&&!preferences.length)continue;
  const supportedReqs=new Set(relations.map(x=>x.roleRequirementRef)),conditions=[];
  for(const req of role.requirements.filter(r=>r.material&&role.metadata.evaluationRequirementRefs.includes(r.id)&&!supportedReqs.has(r.id)).slice(0,2))conditions.push(createConditionToVerify({id:`directionCondition:${role.id}:${req.id}`,roleRequirementRef:req.id,reason:conditionReason(req),currentState:'insufficiently_observed',materialityBasis:`${req.strength}:curated_evaluation_set`,personStateRefs:[professionalRepresentationRef],limitations:['Insufficient observation does not mean the capability or responsibility is absent.']}));
  const temporalRequirementSupport={};for(const req of role.requirements){const priority=arr(role?.extensions?.targetRequirementPriorities).find(p=>p.targetRequirementRef===req.id);if(!priority)continue;const existing=relations.find(r=>r.roleRequirementRef===req.id)||null;const temporal=arr(sustainedRoleExposures).map(exposure=>deriveTemporalRequirementSupport({targetDirectionRef:role.id,targetRequirementRef:req.id,roleExposure:exposure,occupationalPriority:priority,existingRequirementSupport:existing,supportRoleRefs:[...new Set([...arr(requirementSupportRoleRefs?.[req.id]),...inferredSupportRoleRefs(existing,sustainedRoleExposures)])]})).filter(x=>x?.accepted);const aggregate=aggregateTemporalRequirementSupport(temporal);if(aggregate)temporalRequirementSupport[req.id]=aggregate;}
  const meaningKey=relations.length?distinctiveMeaning(role,relations):'candidate_requested_exploration';
  out.push(createCareerDirectionHypothesis({id:`careerDirection:${role.id}:${professionalRepresentationRef}:${CAREER_DIRECTION_EVALUATION_RECIPE.version}`,type:'career_direction_hypothesis',purpose:'professional_direction_explore',directionRef:role.id,roleRepresentationRef:role.id,professionalRepresentationRef,supportBasis:relations,preferenceBasis:preferences,whyWorthExploring:meaningKey,conditionsToVerify:conditions,insufficientlyObserved:conditions.map(c=>c.roleRequirementRef),materialContradictions:[],userContext:context,assumptions:['Evaluation is limited to the curated role scope and current Professional Representation.'],limitations:['Worth exploring is not fit, readiness, recommendation, or predicted success.',...role.limitations],provenance:{personSide:relations.map(r=>r.personMeaningRef),preferenceSide:preferences.map(r=>r.preferenceRef),roleSide:relations.map(r=>r.roleRequirementRef)},roleVersion:role.version.roleVersion,recipeVersion:CAREER_DIRECTION_EVALUATION_RECIPE.version,evaluatedAt:now,metadata:{roleLabel:role.roleIdentity.canonicalLabel,roleFamilyRef:role.roleIdentity.familyRef,roleScope:role.scope,distinctiveMeaningKey:meaningKey,personSupportKinds:relations.map(r=>r.metadata?.personMeaningKind),preferenceInfluences:preferences.map(r=>({influenceType:r.influenceType,preferenceValue:r.preferenceValue,preferenceRef:r.preferenceRef})),roleRequirementSources:Object.fromEntries(role.requirements.map(r=>[r.id,roleSourceSummary(r)])),roleRequirementSemanticKeys:Object.fromEntries(role.requirements.map(r=>[r.id,r.semanticKey])),roleRequirementStatements:Object.fromEntries(role.requirements.map(r=>[r.id,r.statement])),targetRequirementPriorities:role.extensions?.targetRequirementPriorities||[],requirementSupportProjection:{relations:richProjection.relations,rejections:richProjection.rejections,aggregates:richProjection.aggregates},temporalRequirementSupport,roleRequirementAuthorities:Object.fromEntries(role.requirements.map(r=>[r.id,r.requirementAuthority||{requirementRef:r.id,roleRequirementSemanticKey:r.semanticKey,requirementClass:'unspecified',responsibilityFormality:'unspecified',continuityRequirement:'unspecified',responsibilityScope:'unspecified',authorityRef:'target_requirement_authority:unspecified:pd072d:v1',sourceBasisRefs:roleSourceSummary(r).map(s=>s.sourceRef),limitations:['No bounded formal-people-responsibility classification is authorized for this requirement.']}]))},extensions:{}}));
 }
 return Object.freeze({type:'career_direction_evaluation',purpose:'professional_direction_explore',professionalRepresentationRef,context,hypotheses:Object.freeze(out)});
}
