import { performance } from 'node:perf_hooks';
import { createHash } from 'node:crypto';
import { runGroqCareerDirectionRequirementSupportProposalModel } from '../../infrastructure/groq/runGroqCareerDirectionRequirementSupportProposalModel.js';
import { buildCareerDirectionRequirementSupportContributorInventory, buildCareerDirectionRequirementSupportProjection } from './requirementSupportAuthority.js';
const arr=v=>Array.isArray(v)?v:[];const text=v=>typeof v==='string'?v.trim():'';const freeze=v=>{if(Array.isArray(v)){v.forEach(freeze);return Object.freeze(v)}if(v&&typeof v==='object'){Object.values(v).forEach(freeze);return Object.freeze(v)}return v};
const cache=new Map();
function boundedContributor(c){const v=c.value||{};return {contributorType:c.contributorType,contributorRef:c.contributorRef,claimShape:v.claimShape||null,relationshipWording:text(v.relationshipWording)||null,relationshipBasis:text(v.relationshipBasis)||null,structureWording:text(v.structureWording)||null,compositionBasis:text(v.compositionBasis)||null,semanticProtection:arr(c.semanticProtection),professionalBasisRefs:arr(c.professionalBasisRefs),materialRefs:arr(c.materialRefs),sourceRefs:arr(c.sourceRefs)};}
function boundedRequirement(role,req){return {targetDirectionRef:role.id,targetRequirementRef:req.id,semanticKey:req.semanticKey,meaning:text(req.statement)};}
export function buildCareerDirectionRequirementSupportProposalInput({professionalRepresentation,roles=[]}={}){const pm=professionalRepresentation?.professionalMeaning||{};const contributors=buildCareerDirectionRequirementSupportContributorInventory(pm).filter(c=>['grounded_descriptive_professional_relationship','higher_order_descriptive_professional_structure'].includes(c.contributorType)).map(boundedContributor);const requirements=arr(roles).flatMap(role=>arr(role.requirements).filter(r=>r?.material).map(r=>boundedRequirement(role,r)));return freeze({task:'career_direction_requirement_support_relevance_proposal',contributors,requirements});}
function fingerprint(input){return createHash('sha256').update(JSON.stringify(input)).digest('hex');}
function systemPrompt(){return `You propose bounded target relevance relations for IMAGO Career Direction. Return zero or more proposals only from supplied contributorRef, targetDirectionRef and targetRequirementRef identities. The model is proposal-only; deterministic application validators decide acceptance. Do not infer Person truth, capability, competency, fit, readiness, employability, personality, strength, weakness or probability of success. Do not strengthen agency, responsibility, ownership, decision authority or causality. Do not map by lexical similarity alone. A proposal is appropriate only when the supplied bounded contributor semantics directly support the exact atomic target requirement without exceeding its semantic ceiling. Empty proposals are valid and preferred to uncertain mapping. Never invent IDs.`;}
function userPrompt(input){return `Propose only bounded relevance relations supported by these structured accepted contributors and explicit target requirements. relationBasis must briefly state the bounded semantic relation, not a Candidate evaluation.\n${JSON.stringify(input)}`;}
function rejectionCategories(projection){const counts={};for(const r of arr(projection?.rejections))for(const e of arr(r.errors))counts[e]=(counts[e]||0)+1;return counts;}
export async function proposeLiveCareerDirectionRequirementSupport({professionalRepresentation,roles=[],modelRunner=runGroqCareerDirectionRequirementSupportProposalModel,diagnosticSink,executionDiagnosticSink,now=()=>new Date().toISOString()}={}){
 const input=buildCareerDirectionRequirementSupportProposalInput({professionalRepresentation,roles});const key=fingerprint(input);const prior=cache.get(key);if(prior){diagnosticSink?.(freeze({...prior.diagnostic,at:now(),reused:true,providerAttempted:false}));return freeze({...prior,reused:true});}
 if(!input.contributors.length||!input.requirements.length){const out=freeze({proposals:[],reused:false,diagnostic:{boundary:'pd079l_live_requirement_support_proposal',providerAttempted:false,provider:null,model:null,elapsedMs:0,proposalCount:0,acceptedCount:0,rejectedCount:0,rejectionCategories:{},reused:false,affectedTargetRequirementSemanticKeys:[],resultingRobustnessClasses:[]}});cache.set(key,out);diagnosticSink?.(freeze({...out.diagnostic,at:now()}));return out;}
 const started=performance.now();try{const result=await modelRunner({systemPrompt:systemPrompt(),userPrompt:userPrompt(input),executionDiagnosticSink});const byRef=new Map(input.contributors.map(c=>[c.contributorRef,c]));const raw=arr(result?.structured?.proposals);const proposals=raw.map((p,i)=>{const c=byRef.get(text(p.contributorRef));return {contributorType:c?.contributorType||'unknown',contributorRef:text(p.contributorRef),targetDirectionRef:text(p.targetDirectionRef),targetRequirementRef:text(p.targetRequirementRef),relationBasis:text(p.relationBasis),provenance:{providerRef:`groq:${text(result.model)||'configured_model'}`,proposalRef:`pd079l:${key.slice(0,12)}:${i+1}`}};});
 const projections=arr(roles).map(role=>buildCareerDirectionRequirementSupportProjection({professionalMeaning:professionalRepresentation?.professionalMeaning||{},role,proposals}));const accepted=projections.flatMap(x=>x.relations),rejected=projections.flatMap(x=>x.rejections);const affected=[...new Set(accepted.map(x=>x.targetRequirementSemanticKey))],robustness=[...new Set(accepted.map(x=>x.robustnessClass))];const diagnostic=freeze({boundary:'pd079l_live_requirement_support_proposal',providerAttempted:true,provider:'groq',model:text(result.model),elapsedMs:Math.round(performance.now()-started),proposalCount:proposals.length,acceptedCount:accepted.length,rejectedCount:rejected.length,rejectionCategories:rejectionCategories({rejections:rejected}),reused:false,affectedTargetRequirementSemanticKeys:affected,resultingRobustnessClasses:robustness});const out=freeze({proposals,reused:false,diagnostic});cache.set(key,out);diagnosticSink?.(freeze({...diagnostic,at:now()}));return out;
 }catch(error){const diagnostic=freeze({boundary:'pd079l_live_requirement_support_proposal',providerAttempted:true,provider:'groq',model:text(error?.providerDiagnostic?.model)||null,elapsedMs:Math.round(performance.now()-started),proposalCount:0,acceptedCount:0,rejectedCount:0,rejectionCategories:{provider_failure:1},reused:false,affectedTargetRequirementSemanticKeys:[],resultingRobustnessClasses:[],failureKind:text(error?.providerDiagnostic?.failureKind)||text(error?.message)||'provider_failure'});diagnosticSink?.(freeze({...diagnostic,at:now()}));return freeze({proposals:[],reused:false,degraded:true,diagnostic});}
}
export function clearCareerDirectionRequirementSupportProposalCache(){cache.clear();}
