import { createRoleCareerDirectionRepresentation } from './contracts.js';
import { buildTargetRequirementPriorities } from './targetRequirementPriorityAuthority.js';
const observedAt='2026-09-10';
const sources=Object.freeze({
 onetOps:{sourceRef:'roleSource:onet:11-1021.00:2026',sourceClass:'reference_authority',observedAt,scope:'US occupational reference; generalized operations management',independenceGroupRef:'onet-11-1021',displayName:'O*NET — General and Operations Managers',publisher:'O*NET',sourceTitle:'General and Operations Managers (11-1021.00)',url:'https://www.onetonline.org/link/summary/11-1021.00'},
 onetProd:{sourceRef:'roleSource:onet:11-3051.00:2026',sourceClass:'reference_authority',observedAt,scope:'US occupational reference; industrial production management',independenceGroupRef:'onet-11-3051',displayName:'O*NET — Industrial Production Managers',publisher:'O*NET',sourceTitle:'Industrial Production Managers (11-3051.00)',url:'https://www.onetonline.org/link/summary/11-3051.00'},
 blsProd:{sourceRef:'roleSource:bls:industrial-production-managers:2026',sourceClass:'reference_authority',observedAt,scope:'US manufacturing occupational outlook',independenceGroupRef:'bls-ooh-industrial-production-managers',displayName:'U.S. Bureau of Labor Statistics — Industrial Production Managers',publisher:'U.S. Bureau of Labor Statistics',sourceTitle:'Industrial Production Managers — Occupational Outlook Handbook',url:'https://www.bls.gov/ooh/management/industrial-production-managers.htm'}
});
const support=(s,prop,role)=>[{...s,sourcePropositionRef:prop,supportRole:role}];
const req=(id,type,statement,strength,material,ss,limitations=[],requirementAuthority=null)=>({id,type,statement,strength,material,semanticKey:id.includes('cross_functional')?'cross_functional_coordination':id.includes('broader_operational_decision')?'broader_operational_decision_context':id.includes('manufacturing_continuity')?'manufacturing_production_continuity':id.includes('production_performance')?'production_performance_scope':id.includes('people')?'people_responsibility':id.includes('budget_schedule')?'production_planning_resource_scope':'budget_resource_scope',sourceSupport:ss,independenceState:ss.length>1?'corroborated_independent':'single_source',scope:'manufacturing/industrial',limitations,requirementAuthority});
const formalPeopleAuthority=(requirementRef,sourceBasisRefs)=>({requirementRef,roleRequirementSemanticKey:'people_responsibility',requirementClass:'formal_continuing_people_responsibility',responsibilityFormality:'formal',continuityRequirement:'continuing',responsibilityScope:'role_ongoing_staff_responsibility',authorityRef:'target_requirement_authority:formal_continuing_people_responsibility:pd072d:v1',sourceBasisRefs,limitations:['Target-requirement classification only; does not establish Candidate fit, readiness, gap, or capability.']});
export const CURATED_ROLE_SOURCES=sources;
const withTargetPriorities=role=>createRoleCareerDirectionRepresentation({...role,extensions:{...(role.extensions||{}),targetRequirementPriorities:buildTargetRequirementPriorities(role)}});
export const CURATED_ROLE_REPRESENTATIONS=Object.freeze([
 withTargetPriorities(createRoleCareerDirectionRepresentation({id:'roleDirection:operations_manager_manufacturing:v1',type:'role_career_direction_representation',roleIdentity:{canonicalLabel:'Operations Manager',aliases:['Operations General Manager'],familyRef:'operations_management'},scope:{function:'operations',industry:'manufacturing/industrial',seniorityBand:'management',geography:'reference sources: United States'},requirements:[
  req('operations_manager.cross_functional_operational_coordination','responsibility','Coordinate operations and activities across departments or functions.','core_common',true,support(sources.onetOps,'Tasks include directing/coordinating business or department activities and coordinating with other department managers.','supports_core_requirement')),
  req('operations_manager.broader_operational_decision_context','contextual_expectation','Operate across multiple business or departmental activities and decision contexts rather than within one narrow production task.','context_dependent',true,support(sources.onetOps,'Tasks include directing/coordinating business or department activities, planning use of resources, and coordinating with other department managers.','supports_distinctive_direction_meaning')),
  req('operations_manager.people_responsibility','responsibility','Carry material responsibility for assigning, supervising, selecting, training, or evaluating staff.','core_common',true,support(sources.onetOps,'Tasks include assigning duties and personnel functions such as selection, training, or evaluation.','creates_material_condition'),[],formalPeopleAuthority('operations_manager.people_responsibility',[sources.onetOps.sourceRef])),
  req('operations_manager.budget_operational_resources','responsibility','Coordinate financial or budget activity and use of operational resources.','core_common',true,support(sources.onetOps,'Tasks include coordinating budget activity and planning use of materials and human resources.','creates_material_condition'))
 ],contextualVariants:[{kind:'manufacturing_context',note:'General Operations Manager reference is broader than manufacturing; this fixture is intentionally scoped to industrial exploration.'}],sourceRefs:[sources.onetOps.sourceRef],provenance:{curation:'repository_curated_multi_source_role_fixture',observedAt},version:{roleVersion:'1.0',recipeVersion:'pdir04-role-fixture-1.0',materializedAt:observedAt,sourceStateRef:'roleSourceState:operations_manager:2026-09-10'},limitations:['General Operations Manager is a broad occupational family; employer-specific scope may differ.'],metadata:{evaluationRequirementRefs:['operations_manager.cross_functional_operational_coordination','operations_manager.broader_operational_decision_context','operations_manager.people_responsibility','operations_manager.budget_operational_resources']},extensions:{}})),
 withTargetPriorities(createRoleCareerDirectionRepresentation({id:'roleDirection:industrial_production_manager:v1',type:'role_career_direction_representation',roleIdentity:{canonicalLabel:'Industrial Production Manager',aliases:['Production Manager','Manufacturing Manager'],familyRef:'industrial_production_management'},scope:{function:'production_operations',industry:'manufacturing/industrial',seniorityBand:'management',geography:'reference sources: United States'},requirements:[
  req('industrial_production_manager.cross_functional_operational_coordination','responsibility','Coordinate production operations and work with technical, administrative, supplier, or other functions to resolve operational issues.','core_common',true,[...support(sources.onetProd,'Direct/coordinate industrial production activities and confer with technical or administrative staff on production problems.','supports_core_requirement'),...support(sources.blsProd,'Coordinate production activities and communicate/work with suppliers and other departments.','supports_core_requirement')]),
  req('industrial_production_manager.manufacturing_continuity','experience_exposure','Bring related manufacturing or production experience into responsibility for industrial production operations.','context_dependent',true,[...support(sources.onetProd,'Industrial Production Managers direct and coordinate resources needed for manufacturing operations.','supports_distinctive_direction_meaning'),...support(sources.blsProd,'Industrial production managers typically need several years of related work experience in manufacturing or production.','supports_distinctive_direction_meaning')]),
  req('industrial_production_manager.production_performance_scope','responsibility','Monitor and improve production performance, quality, efficiency, or output within manufacturing operations.','context_dependent',true,[...support(sources.onetProd,'Production-management work includes monitoring production and resolving production problems.','supports_distinctive_direction_meaning'),...support(sources.blsProd,'Managers analyze production data and identify ways to improve efficiency and productivity.','supports_distinctive_direction_meaning')]),
  req('industrial_production_manager.people_responsibility','responsibility','Carry ongoing staffing, supervision, training, or evaluation responsibility in production.','core_common',true,[...support(sources.onetProd,'Production-management tasks include staffing decisions and personnel responsibility.','creates_material_condition'),...support(sources.blsProd,'Typical duties include hiring, training, evaluating workers and leading staff.','creates_material_condition')],[],formalPeopleAuthority('industrial_production_manager.people_responsibility',[sources.onetProd.sourceRef,sources.blsProd.sourceRef])),
  req('industrial_production_manager.budget_schedule_scope','responsibility','Make production scheduling/resource decisions within budget, quality, and quantity constraints.','core_common',true,[...support(sources.onetProd,'Review production orders for staffing/work decisions considering budget and time constraints.','creates_material_condition'),...support(sources.blsProd,'Keep production on schedule and within budget; assess production needs against budget.','creates_material_condition')])
 ],contextualVariants:[],sourceRefs:[sources.onetProd.sourceRef,sources.blsProd.sourceRef],provenance:{curation:'repository_curated_multi_source_role_fixture',observedAt},version:{roleVersion:'1.0',recipeVersion:'pdir04-role-fixture-1.0',materializedAt:observedAt,sourceStateRef:'roleSourceState:industrial_production_manager:2026-09-10'},limitations:['Occupational reference is US-scoped; company size and plant scope materially vary.'],metadata:{evaluationRequirementRefs:['industrial_production_manager.cross_functional_operational_coordination','industrial_production_manager.manufacturing_continuity','industrial_production_manager.production_performance_scope','industrial_production_manager.people_responsibility','industrial_production_manager.budget_schedule_scope']},extensions:{}}))
]);
