const arr=v=>Array.isArray(v)?v:[];const text=v=>typeof v==='string'?v.trim():'';const freeze=v=>Object.freeze(JSON.parse(JSON.stringify(v)));
export const SUSTAINED_ROLE_MIN_MONTHS=12;
export const TEMPORAL_SUPPORT_CLASSES=Object.freeze({EPISODIC_OR_UNESTABLISHED:'EPISODIC_OR_UNESTABLISHED',SUSTAINED_ROLE_CONTEXT:'SUSTAINED_ROLE_CONTEXT',SUSTAINED_REQUIREMENT_SUPPORT:'SUSTAINED_REQUIREMENT_SUPPORT',CROSS_ROLE_SUSTAINED_RECURRENT_SUPPORT:'CROSS_ROLE_SUSTAINED_RECURRENT_SUPPORT'});
function monthIndex(d){return d.getUTCFullYear()*12+d.getUTCMonth();}
function parseMonth(value){const s=text(value);if(!/^\d{4}-(0[1-9]|1[0-2])(?:-\d{2})?$/.test(s))return null;const d=new Date(`${s.length===7?s+'-01':s}T00:00:00Z`);return Number.isNaN(d.valueOf())?null:d;}
export function deriveSustainedRoleExposure({roleRef,formalRole,organisationRef=null,startDate,endDate=null,startYear=null,endYear=null,current=false,datePrecision='month',rawDateExpression=null,provenance={},now='2026-09-30'}={}){
 if(!text(roleRef)||!text(formalRole))return freeze({accepted:false,rejectionCategory:'role_identity_missing'});
 let durationMonths=null,minimumDurationMonths=null,maximumDurationMonths=null,boundedInterval=null;
 if(datePrecision==='year'&&Number.isInteger(Number(startYear))){const sy=Number(startYear),nowDate=parseMonth(now),ey=current?(nowDate?.getUTCFullYear()):Number(endYear);if(!Number.isInteger(ey)||ey<sy)return freeze({accepted:false,rejectionCategory:'insufficient_date_precision'});const latestStart=sy*12+11,earliestStart=sy*12,earliestEnd=current?monthIndex(nowDate):ey*12,latestEnd=current?monthIndex(nowDate):ey*12+11;minimumDurationMonths=Math.max(1,earliestEnd-latestStart+1);maximumDurationMonths=Math.max(1,latestEnd-earliestStart+1);durationMonths=minimumDurationMonths;boundedInterval={startYear:sy,endYear:current?null:ey,current:Boolean(current),minimumDurationMonths,maximumDurationMonths};}
 else {const start=parseMonth(startDate),end=current?parseMonth(now):parseMonth(endDate);if(!start||!end||end<start||!['month','day'].includes(datePrecision))return freeze({accepted:false,rejectionCategory:'insufficient_date_precision'});durationMonths=Math.max(1,monthIndex(end)-monthIndex(start)+(datePrecision==='month'?1:0));minimumDurationMonths=maximumDurationMonths=durationMonths;}
 return freeze({type:'sustained_role_exposure',roleRef,formalRole,organisationRef,startDate:startDate||null,endDate:current?null:(endDate||null),startYear:startYear||null,endYear:current?null:(endYear||null),current:Boolean(current),durationMonths,durationPrecision:datePrecision,minimumDurationMonths,maximumDurationMonths,boundedInterval,rawDateExpression,roleContinuityState:minimumDurationMonths>=SUSTAINED_ROLE_MIN_MONTHS?'sustained':'episodic',derivedOnly:true,provenance,limitations:['Role duration establishes occupational exposure only; it does not establish competence, performance, employer approval, or execution of every occupational task.']});
}
export function deriveSustainedRoleExposuresFromRoleHistory(roleHistory=[],now='2026-09-30'){return arr(roleHistory).map(r=>{const c=r?.chronology;if(!c||c.accepted===false)return null;return deriveSustainedRoleExposure({roleRef:r.roleRef,formalRole:r.role,organisationRef:r.organisationRef||null,startDate:c.startDate,endDate:c.endDate,startYear:c.startYear,endYear:c.endYear,current:c.current,datePrecision:c.precision,rawDateExpression:c.rawDateExpression,provenance:{sourceRefs:c.sourceRefs||[r.sourceId],derivationMethod:c.derivationMethod},now});}).filter(x=>x?.type);}
function corePriority(priority){return priority?.accepted===true&&arr(priority.descriptors).some(d=>d?.rawPriorityRelation?.taskType==='Core');}
export function deriveTemporalRequirementSupport({targetDirectionRef,targetRequirementRef,roleExposure,occupationalPriority,existingRequirementSupport=null,supportRoleRefs=[]}={}){
 if(!roleExposure?.type||!text(targetRequirementRef)||!text(targetDirectionRef))return freeze({accepted:false,rejectionCategory:'input_identity_missing'});
 if(!corePriority(occupationalPriority))return freeze({accepted:false,rejectionCategory:'exact_core_priority_required'});
 if(roleExposure.roleContinuityState!=='sustained')return freeze({accepted:true,type:'temporal_requirement_support',targetDirectionRef,targetRequirementRef,sustainedRoleExposureRef:roleExposure.roleRef,occupationalPriorityRef:targetRequirementRef,existingRequirementSupportRef:null,temporalSupportClass:TEMPORAL_SUPPORT_CLASSES.EPISODIC_OR_UNESTABLISHED,provenance:{durationMonths:roleExposure.durationMonths},limitations:['No sustained temporal basis is established.']});
 const direct=Boolean(existingRequirementSupport)&&arr(supportRoleRefs).includes(roleExposure.roleRef);
 return freeze({accepted:true,type:'temporal_requirement_support',targetDirectionRef,targetRequirementRef,sustainedRoleExposureRef:roleExposure.roleRef,occupationalPriorityRef:targetRequirementRef,existingRequirementSupportRef:direct?(existingRequirementSupport.id||existingRequirementSupport.targetRequirementRef||targetRequirementRef):null,temporalSupportClass:direct?TEMPORAL_SUPPORT_CLASSES.SUSTAINED_REQUIREMENT_SUPPORT:TEMPORAL_SUPPORT_CLASSES.SUSTAINED_ROLE_CONTEXT,provenance:{durationMonths:roleExposure.durationMonths,roleRef:roleExposure.roleRef,priorityDescriptors:arr(occupationalPriority.descriptors).map(d=>d.descriptorIdentity)},limitations:[direct?'Temporal depth augments an existing requirement-specific support relation without changing its semantic ceiling.':'Sustained role occupancy provides contextual role support only; requirement-specific professional support remains unestablished.']});
}
export function aggregateTemporalRequirementSupport(relations=[]){const accepted=arr(relations).filter(x=>x?.accepted);if(!accepted.length)return null;const direct=accepted.filter(x=>x.temporalSupportClass===TEMPORAL_SUPPORT_CLASSES.SUSTAINED_REQUIREMENT_SUPPORT);const independentRoles=new Set(direct.map(x=>x.sustainedRoleExposureRef));const temporalSupportClass=independentRoles.size>=2?TEMPORAL_SUPPORT_CLASSES.CROSS_ROLE_SUSTAINED_RECURRENT_SUPPORT:(direct[0]?.temporalSupportClass||accepted.find(x=>x.temporalSupportClass===TEMPORAL_SUPPORT_CLASSES.SUSTAINED_ROLE_CONTEXT)?.temporalSupportClass||TEMPORAL_SUPPORT_CLASSES.EPISODIC_OR_UNESTABLISHED);return freeze({temporalSupportClass,roleExposureRefs:[...new Set(accepted.map(x=>x.sustainedRoleExposureRef))],relations:accepted,limitations:['Temporal depth remains separate from PD-079 structural robustness and Candidate capability.']});}
export function buildTemporalRequirementSupportDiagnostics({requirementRef,priority,exposures=[],relations=[]}={}){return freeze({requirementRef,onetPriority:priority?.descriptors?.map(d=>({taskId:d.descriptorIdentity?.taskId,taskType:d.rawPriorityRelation?.taskType,importance:d.rawImportanceRating?.displayValue??null}))||[],documentedRoleExposure:arr(exposures).map(x=>({roleRef:x.roleRef,durationMonths:x.durationMonths,state:x.roleContinuityState})),existingPd079Support:arr(relations).some(x=>x.existingRequirementSupportRef),temporal:aggregateTemporalRequirementSupport(relations)});}
